### ISSUE TITLE
Some direct memory accesses lack bounds-checks

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1007]
The `Allocation` APIs should generally be avoided as they are low-level building blocks and don't do bounds or alignment checks themselves. I [did an audit](https://github.com/rust-lang/miri/pull/1006) and noticed some uses crept in recently that are not properly checked:

* [x] `getcwd`
* [ ] `read`
* [ ] `write`

This can lead to ICEs. When these are fixed, a test should be added.

Cc @christianpoveda @oli-obk 

It would be even better if we could stop exposing `Memory::get` and `Memory::get_mut` from `librustc_mir`... once these issues are fixed and the current wave of PRs is in (I suggested to @christianpoveda to add a `write_bytes` API anyway), we could try to make a concerted effort to remove the remaining uses in Miri.

**Comment by oli-obk** [comment]
So is the goal to make these methods private? Or rename to `get_internal` or sth?

**Comment by RalfJung** [comment]
Making them private would be great.
Renaming them could be a good idea nevertheless.

**Comment by christianpoveda** [comment]
I can do a PR with the changes after https://github.com/rust-lang/rust/pull/65621 lands

**Comment by RalfJung** [comment]
The `getcwd` one should actually be taken care of in https://github.com/rust-lang/miri/pull/993.

**Comment by christianpoveda** [comment]
Hahaha yes i know about that one :P. I was talking about `read` and `write`.
