### ISSUE TITLE
Implement file system access for Windows

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1013]
On Unix systems Miri can read and write as well as create and delete files, but not on Windows.

This would also allow us to get rid of the "TERM" env var hack (added in https://github.com/rust-lang/miri/pull/1225).

**Comment by christianpoveda** [comment]
I can provide some instructions if anyone wants to tackle this issue.

**Comment by JOE1994** [comment]
I've started working on this issue, and will try to submit a PR soon 😃


> I can provide some instructions if anyone wants to tackle this issue.

I'll ask questions if I get stuck on the way. Thank you 👍

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/miri/issues/1537.
