### ISSUE TITLE
Miri evaluation errors show up with error code E0080

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/miri#1035]
When running MIRI on [a Rust program](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=333669a9c68690eebac2b394f840dd78), I was a bit puzzled with the output error message with the [error code E0080](https://doc.rust-lang.org/error-index.html#E0080) as the code seemed irrelevant to the error that MIRI catched.

`error[E0080]: Miri evaluation error: trying to reborrow for SharedReadWrite, but parent tag <1368> does not have an appropriate item in the borrow stack`

After running MIRI on [another Rust program](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=db30519a97cd1f6dab8d184ed2d773ab) did I begin to think that maybe all MIRI evaluation errors are printed out with the same rustc error code **E0080.**

(Assuming all MIRI evaluation errors are printed out with code **E0080**) 
To prevent unnecessary confusion, maybe it would be nice to either
1.  create a new Rustc error code dedicated for MIRI evaluation errors **OR**
2.  add an additional explanation to the `rustc --explain E0080` message,  mentioning that **E0080** can also be relevant to MIRI evaluation errors.

**Comment by RalfJung** [comment]
> all MIRI evaluation errors are printed out with the same rustc error code E0080.

Lol, I had never even noticed this.^^
@oli-obk is there something we can do about this? Ideally we'd not have an error code, or have an error code dedicated to Miri.

**Comment by oli-obk** [comment]
We can remove the error code entirely. There's no point to miri having a specific error code.

**Comment by RalfJung** [comment]
The problem is that we are currently calling [this method](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc/mir/interpret/error.rs.html#181-183):
```rust
pub fn struct_error<'tcx>(tcx: TyCtxtAt<'tcx>, msg: &str) -> DiagnosticBuilder<'tcx> {
    struct_span_err!(tcx.sess, tcx.span, E0080, "{}", msg)
}
```

It's a one-liner, so we could inline it to change the error code, but what would we do do not have an error code?

**Comment by bjorn3** [comment]
https://doc.rust-lang.org/nightly/nightly-rustc/rustc/session/struct.Session.html#method.struct_span_err

**Comment by JOE1994** [comment]
Macro [struct_span_err!](https://doc.rust-lang.org/nightly/nightly-rustc/src/syntax/diagnostics/macros.rs.html#88) makes a call to [`fn struct_span_err_with_code`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/session/struct.Session.html#method.struct_span_err_with_code).
Under the **miri/src** directory, the only file that contains a call to the [`fn struct_error`](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc/mir/interpret/error.rs.html#181) is **miri/src/eval.rs**.
