### ISSUE TITLE
support inline asm

### ISSUE THREAD

**Issue by dvc94ch** [rust-lang/miri#1045]
Useful to run tests for unsafe code with miri

**Comment by bjorn3** [comment]
https://internals.rust-lang.org/t/should-we-ever-stabilize-inline-assembly/11211/125

https://github.com/CraneStation/cranelift/issues/444#issuecomment-531574394

tl;dr: inline asm is hard.

**Comment by dvc94ch** [comment]
llvm already supports asm and jit. Wouldn't telling llvm to jit the inline asm somehow work? That shouldn't require the inline asm to be stabilized or reimplementing it in cranelift.

**Comment by bjorn3** [comment]
> Wouldn't telling llvm to jit the inline asm somehow work? That shouldn't require the inline asm to be stabilized or reimplementing it in cranelift.

For miri: that would require FFI support in miri.

For cg_clif (my cranelift based **c**odegen **b**ackend): cg_clif doesnt have any dependency on LLVM, which I want to keep that way.

**Comment by dvc94ch** [comment]
I see, so it's a duplicate of #11. Thanks.
