### ISSUE TITLE
ICE: validity checks should have excluded dangling/unaligned pointer

### ISSUE THREAD

**Issue by CAD97** [rust-lang/miri#1050]
[repro repo](https://github.com/CAD97/thin-dst/tree/952f712a02658224ea4f7a01e98e9e6b93e3cc2c)

I'm unable to minimize this further; any attempt at further minification made the ICE go away. Running `cargo miri test` against the commit linked produces the ICE message:

> thread 'rustc' panicked at 'validity checks should have excluded dangling/unaligned pointer: InterpErrorInfo { kind: Memory access failed: pointer must be in-bounds at offset 24, but is outside bounds of allocation 25410 which has size 16, backtrace: None }', src\libcore\result.rs:1165:5

I'm running on windows-mingw, so my backtrace isn't of much use. (It's pretty much just all `_clzsi2`.)

(Note that I'm not asking for help finding the unsoundness in the linked code.)

One interesting observation that may help narrow down the issue:

For the test exercising the ICE-causing dangling pointer

```rust
fn node() {
    let a = ThinArc::<usize, u8>::new(1, vec![]);
    ThinBox::new(1, vec![a]);
}
```

changing the first line to create a `ThinBox` instead causes the ICE (and dangling deref?) to go away.

**Comment by RalfJung** [comment]
Here's the 1-file version, I also replaced polyfill by `alloc::layout`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6b993d79a2ec5fc0eb521100bfc328bc. This still ICEs.

I'll need to run this locally with tracing to say more. But I am quite startled by `repr_c_3`, are you really wrapping that entire function in `unsafe` to avoid 0-initializing 24 bytes?!?

**Comment by CAD97** [comment]
> I am quite startled by `repr_c_3`

It's because I copied over the const generic version. Definitely should replace that with a `[0; 3]`, though. (This is in-progress code.)

**Comment by CAD97** [comment]
Just to record it: the main issue in the linked code is that `<*mut Erased>::offset` is a nop because `Erased` has size 0. I was treating it as if `*mut Erased` were `*mut u8`.

**Comment by RalfJung** [comment]
The core of the backtrace is
```
  15: core::result::unwrap_failed
             at src/libcore/result.rs:1165
  16: core::result::Result<T,E>::expect
             at /rustc/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/libcore/result.rs:960
  17: miri::stacked_borrows::EvalContextPrivExt::reborrow
             at src/stacked_borrows.rs:536
  18: miri::stacked_borrows::EvalContextPrivExt::retag_reference
             at src/stacked_borrows.rs:599
  19: miri::stacked_borrows::EvalContextExt::retag
             at src/stacked_borrows.rs:641
  20: <miri::machine::Evaluator as rustc_mir::interpret::machine::Machine>::retag
             at src/machine.rs:341
  21: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::statement
             at /rustc/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/librustc_mir/interpret/step.rs:114
  22: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::step
             at /rustc/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/librustc_mir/interpret/step.rs:61
  23: rustc_mir::interpret::step::<impl rustc_mir::interpret::eval_context::InterpCx<M>>::run
             at /rustc/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/librustc_mir/interpret/step.rs:40
  24: miri::eval::eval_main::{{closure}}
             at src/eval.rs:190
  25: miri::eval::eval_main
             at src/eval.rs:189
```

That's this line:

https://github.com/rust-lang/miri/blob/09b0a8a813d178233aff88d521ff0aa672ff6dbe/src/stacked_borrows.rs#L536

So somehow we are reborrowing a dangling pointer... odd.

This is the last MIR it executed:
```
[INFO  rustc_mir::interpret::eval_context] CONTINUING(13) std::boxed::Box::<ThinData<usize, u8>>::from_raw
[INFO  rustc_mir::interpret::step] // bb1
[INFO  rustc_mir::interpret::step] StorageDead(_3)
[INFO  rustc_mir::interpret::step] (_0.0: std::ptr::Unique<T>) = move _2
[INFO  rustc_mir::interpret::step] Retag(_0)
```
That's somewhere inside `<impl std::convert::From<ThinBox<usize, u8>> for std::boxed::Box<ThinData<usize, u8>>>::from`. We have a dangling `Box` here it seems.

**Comment by RalfJung** [comment]
Minimal reproducer:
```rust
fn main() { unsafe {
    let ptr = Box::into_raw(Box::new(0u16));
    Box::from_raw(ptr as *mut u32);
} }
```
