### ISSUE TITLE
Merge PR and bors CI configurations

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/miri#1051]
Currently, this repository appears to be using Travis CI to automatically test PR commits, and Appveyor to test `r+`'d PRs. There are only four jobs in total, and PRs to this repository are very infrequent compared to `rust-lang/rustc`. Would it be possible to run the same CI checks for both PR commits and for accepted PRs?

**Comment by RalfJung** [comment]
We use Travis *and* AppVeyor for bors (`r+` testing). AppVeyor shares a single parallel job with *all other rust-lang projects*. We definitely do not want to run AppVeyor on PRs where each time someone pushes we take away 30min from that single runner.

IOW, the setup is similar to rustc: in the PR we only test some things; after `r+` we test all the things. Only very rarely do these platform differences matter, and we can also use `bors try` if we think that might be the case (or just `r+` and rely on bors gating).

**Comment by Aaron1011** [comment]
Ah, I wasn't aware that there was a shared job pool.
