### ISSUE TITLE
Unwinding panics have wrong exit code

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1064]
When a `panic=unwind` program panics in regular `rustc`, it has exit code 101. When it panics in Miri, it has exit code 0. That seems wrong, the exit code shouldn't indicate success.

@Aaron1011 why idea where the disparity might come from?

**Comment by Aaron1011** [comment]
It looks like we don't currently inspect the return value of the `start` lang item - we only handle explicit calls to `std::process::exit`
