### ISSUE TITLE
Throwing a panic via core::panic reports memory leak

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1071]
When a `#[should_panic]` test throws via `core::panic!` instead of (the default) `std::panic!`, we have a memory leak:
```
Alloc 23790: 00 00 00 00 00 00 00 00 0d 00 00 00 00 00 00 00 35 00 00 00 05 00 00 00 (24 bytes, alignment 8) (stack)
             └───────(23789)───────┘ 
Alloc 23789: 74 65 73 74 73 2f 74 65 73 74 2e 72 73 (13 bytes, alignment 1) (Static)
```
The 2nd allocation is the string `tests/test.rs` and 0x35 is 53, the line with the panic statement; this looks like some kind of panic information struct.

The interesting question is, why does a *stack* allocation not get freed?

Cc @Aaron1011

**Comment by RalfJung** [comment]
This can easily be reproduced by adjusting our `catch_panic` test to use `core::panic!`.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/miri/pull/1073 contains some commented-out tests for this.

**Comment by oli-obk** [comment]
If we create a stack allocation without putting it into a frame's locals list, it will get leaked

**Comment by RalfJung** [comment]
The offending allocation is created here:

**Comment by RalfJung** [comment]
The offending allocation is created here:

https://github.com/rust-lang/rust/blob/4752c05af4a5f392de026f9ae1877eae030be359/src/librustc_mir/interpret/intrinsics/caller_location.rs#L31

**Comment by bjorn3** [comment]
That should be treated like a const, right?

**Comment by RalfJung** [comment]
Not sure what you mean? Ideally it should probably be interned but I am not sure what the best way is to achieve that.

**Comment by bjorn3** [comment]
I mean it should be treated like `const LOC_AT_THIS_POS: &'static Location = ...`.

**Comment by RalfJung** [comment]
Yeah that would be achieved by interning the result.

I went with https://github.com/rust-lang/rust/pull/66844 instead as that seemed simpler; I was not sure how to best achieve interning here.
