### ISSUE TITLE
Running diverging closure coerced to fn ptr fails: "invalid use of NULL pointer"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1075]
The following code fails to run in Miri:
```rust
fn main() {
    let f: fn() -> ! = || std::process::exit(0);  
    f();
}
```
The error is
```
error: Miri evaluation error: invalid use of NULL pointer
   --> /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/ops/function.rs:227:5
    |
227 |     extern "rust-call" fn call_once(self, args: Args) -> Self::Output;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri evaluation error: invalid use of NULL pointer
    |
note: inside call to `<[closure@src/main.rs:2:24: 2:48] as std::ops::FnOnce<()>>::call_once - shim` at src/main.rs:3:5
   --> src/main.rs:3:5
    |
3   |     f();
    |     ^^^
```
I am not entirely sure what is happening; it looks like this has something to do with the shim that is used to coerce non-capturing closures to function pointers.

Cc @eddyb @oli-obk

**Comment by eddyb** [comment]
Does it have to be `-> !`? I can't think why that could affect the outcome.

**Comment by RalfJung** [comment]
I don't understand it either, but replacing `!` by `()` in the example fixes it.

**Comment by RalfJung** [comment]
There is something weird about the coercion of diverging closures anyway, see https://github.com/rust-lang/rust/issues/66738.

**Comment by RalfJung** [comment]
Looks like the exception comes from here

https://github.com/rust-lang/rust/blob/04e69e4f4234beb4f12cc76dcc53e2cc4247a9be/src/librustc_mir/interpret/terminator.rs#L80

and then probably

https://github.com/rust-lang/rust/blob/04e69e4f4234beb4f12cc76dcc53e2cc4247a9be/src/librustc_mir/interpret/place.rs#L667

So, we have a function call with a return place, but that return place is actually the *callers* return place, and the caller diverges. This is okay because the callee also diverges, but we error out when just creating that return place.
