### ISSUE TITLE
Problems with instalation miri: cargo no such subcommand: `miri`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/miri#1120]
I'm trying to install `miri` using guide from `README`, however for some reason cargo doesn't see `miri` command...
```
% rustup override set nightly-2019-12-15                                                                                   
info: using existing install for 'nightly-2019-12-15-x86_64-unknown-linux-gnu'
info: override toolchain for '/home/waffle/projects/ub_in_array_iterator' set to 'nightly-2019-12-15-x86_64-unknown-linux-gnu'

  nightly-2019-12-15-x86_64-unknown-linux-gnu unchanged - rustc 1.41.0-nightly (c8ea4ace9 2019-12-14)

% rustup component add miri                                                                                                
info: downloading component 'miri'
info: installing component 'miri'
% cargo miri run                                                                                                            
error: no such subcommand: `miri`

	Did you mean `fix`?
```
What am I doing wrong?

**Comment by oli-obk** [comment]
Maybe your rustup is very old. Try `rustup self update`

**Comment by WaffleLapkin** [comment]
I'd installed `rustup` using package manager (`pacman`, Arch Linux), so it won't update self:
```
% rustup self update
error: self-update is disabled for this build of rustup
error: you should probably use your system package manager to update rustup
```

But updating with `pacman` didn't help either.

My rustup version:
```% rustup --version                                                                                                         
rustup 1.20.2 (2019-10-16)
```

**Comment by bjorn3** [comment]
https://www.archlinux.org/packages/community/x86_64/rustup/

> Provides: cargo,   cargo-nightly,   rust,   rustfmt,   rust-nightly

The `rustup` package doesn't provide `cargo-miri`. I think creating a symlink called `cargo-miri` to `/usr/bin/rustup` somewhere in your path will fix this.

**Comment by RalfJung** [comment]
`rustup` [*does* provide `cargo-miri`](https://github.com/rust-lang/rustup/blob/ec6d1afcbe0fe2f0f52fb7b856f9672ebf87b177/src/lib.rs#L15). Looks like ana rch packaging bug?

**Comment by bjorn3** [comment]
The package manually creates all symlinks: https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/rustup#n31

**Comment by RalfJung** [comment]
Yeah definitely an Arch bug then. Can someone report this there?

**Comment by GoldsteinE** [comment]
Reported: https://bugs.archlinux.org/index.php?do=details&action=details.addvote&task_id=64972

**Comment by RalfJung** [comment]
Thanks. Closing as forwarded-to-downstream then.
