### ISSUE TITLE
Stacked borrow implementation of miri may mistreat statics since they aren't places anymore

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#1122]
cc @spastorino @RalfJung 

The way we represent statics and promoteds in MIR changed from them being an explicit place to them just being a constant that is a reference to the static (https://github.com/rust-lang/rust/pull/67000). Since this was supported before anyway, we remove the special case of statics being referencable both via a `Place` and via a constant.

This change may have broken how stacked borrows process references to statics. We should run miri on a few examples and see whether the borrows assigned change in a significant way.

related discussion on zulip: https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/promoteds.20are.20not.20places

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/67000 has landed, and from all I can see Stacked Borrows for globals behaves exactly as it should. The miri engine uses `tag_global_base_ptr` to determine the tag when directly accessing a global; if there were untagged accesses to such globals we would notice (as in https://github.com/rust-lang/rust/pull/70479).

So, closing this as everything seems just fine.
