### ISSUE TITLE
Build Miri's libstd with debug assertions

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1126]
It would be good to build Miri's libstd with debug assertions -- the performance is already horrible anyway, and this way we get better testing.

**Comment by bjorn3** [comment]
At https://github.com/rust-lang/rust/blob/625375400cdd172877e81c3ce44ce68f2011af2d/src/libcore/intrinsics.rs#L1417, there is a function which is used in several debug assertions to test the alignment and non-nullness of pointers. This function uses an ptr-int cast followed by a modulo to check for the alignment. I think this should be changed to [`align_offset`](https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/libcore/ptr/mod.rs#L1056) to prevent the address to be considered leaking and thus unnecessarily growing `memory_extra.intptrcast.int_to_ptr_map`.

**Comment by RalfJung** [comment]
My long-term plan is anyway for the base address in `int_to_ptr_map` to be allocated eagerly instead of lazily, so I am not much concerned about growing that map.

Also, `align_offset` cannot be used to test the rel alignment, precisely because it does not take `int_to_ptr_map` into account.
