### ISSUE TITLE
Refactor `shim` module by platform

### ISSUE THREAD

**Issue by christianpoveda** [rust-lang/miri#1161]
Right now we are checking the platform in some shims to avoid calling them in the incorrect platform. Ffor example, `stat` and its cousins are used only on `macos` and calling them on other `unix`-like platforms should be forbidden because they have a different behavior there.

I'd like to refactor the `shim` module and the `find_foreign_function` function to dispatch the shims based on the platform eagerly instead of doing it independently for each shim.

PD: I'm wondering, is it possible that someone writes some rust code that calls a foreign function on another platform by accident? like writing a small `macos` program that calls a foreign `statx` function and miri will dispatch it to our `statx` shim.

**Comment by RalfJung** [comment]
> like writing a small macos program that calls a foreign statx function and miri will dispatch it to our statx shim.

That is possible and whatever Miri does in that case is very wrong. But it seems unlikely that this might happen, which is why I don't consider this a big problem.

But I agree that in principle, the foreign-function dispatch should be platform-specific. Though I expect Linux and macOS to share quite a few shims, with them both being Unix platforms. (This is similar to how they share plenty of code in `libstd/sys`.)

**Comment by christianpoveda** [comment]
> > like writing a small macos program that calls a foreign statx function and miri will dispatch it to our statx shim.
> 
> That is possible and whatever Miri does in that case is very wrong. But it seems unlikely that this might happen, which is why I don't consider this a big problem.

Yes I also think that this is super uncommon.

> But I agree that in principle, the foreign-function dispatch should be platform-specific. Though I expect Linux and macOS to share quite a few shims, with them both being Unix platforms. (This is similar to how they share plenty of code in `libstd/sys`.)

I haven't thought a lot about the structure of this refactor but I think we could have a `unix` module and reexport the common shims in `macos` and `linux`.

I also think that this would produce cleaner shim implementations. Right now `fs.rs` has a bunch of methods that some of them are shims, other are helper functions and so.

**Comment by RalfJung** [comment]
> I also think that this would produce cleaner shim implementations. Right now fs.rs has a bunch of methods that some of them are shims, other are helper functions and so and all of them are under the same trait implementation.

Not sure how changing that to only make shims `pub` has anything to do with the rest of this proposal. Also, the linux and macos shims share some code and types there, I don't think those should be moved too far apart.

In terms of structure, I think the part I like least right now is that big `enum` in `foreign_items.rs`. I feel like that should be split by platform and/or topic, somehow.

**Comment by christianpoveda** [comment]
> In terms of structure, I think the part I like least right now is that big `enum` in `foreign_items.rs`. I feel like that should be split by platform and/or topic, somehow. But other than that I think `find_foreign_function` is fine, not sure what you planned to change there?

Sorry I got confused, I meant `emulate_foreign_item` instead of `find_foreign_function`. I think that the function should only match the target platform and then there should be a platform specific `emulate_foreign_item` in its own file/module. In case a shim is the same for more than one platform I'd import it in each platform's module.

> Not sure how changing that to only make shims pub has anything to do with the rest of this proposal. Also, the linux and macos shims share some code and types there, I don't think those should be moved too far apart.

I don't know if it makes sense to separate the shims implementation from its interface but I think it would make easier to identify the core functionality from the little details of each shim, like `stat/statx` where we have the `FileMetadata` with several methods that are used by `stat` and `statx`. I think this could be done to the `fs/env` shims to keep them as generic as possible and even be able to reuse the code for the three platforms. Instead of having `open` as both the function that opens a new file and adds its file descriptor/handle and the shim at the same time.

I think I'd structure it as follows:
```
shims/
    foreign_items.rs
    foreign_items/
        windows.rs
        windows/
            fs.rs
            time.rs
            env.rs
            ... 
        macos.rs
        macos/
            fs.rs
            time.rs
            env.rs
            ...
        linux.rs
        linux/
            fs.rs
            time.rs
            env.rs
            ...
    helpers/
        fs.rs
        time.rs
        env.rs
        ...
```
so inside `helpers` we'd have stripped down versions of `FileMetadata`, `EnvVars`, `TlsData`, etc. In `<platform>.rs` we have the platform specific dispatch ala `emulate_foreign_item` and inside `platform/` we have the specific functions for each shim. For example, `statx` should be inside `shims/linux/fs.rs` and `stat` inside `shims/macos/fs.rs`.

**Comment by RalfJung** [comment]
> Sorry I got confused, I meant emulate_foreign_item instead of find_foreign_function. I think that the function should only match the target platform and then there should be a platform specific emulate_foreign_item in its own file/module. In case a shim is the same for more than one platform I'd import it in each platform's module.

I think we should permit for platforms that are very similar, the way macOS and Linux are. So this should be more tree-shaped: first distinguish windows and POSIX early, then on the POSIX side handle the POSIX common things, and if none of them matches dispatch to the Linux/macOS-specific handlers.

> For example, statx should be inside shims/foreign_items/linux/fs.rs and stat inside shims/foreign_items/macos/fs.rs

What I don't like about this is how this splits the code handling `FileMetadata` across modules all over the module tree. This requires making things public that ought to be private to that module.

For this reason, I think for shims that are interesting enough to warrant a "domain module" (like `fs,rs` or `env.rs` or `tls.rs`), that module should keep as much private as it can and thus contain the code for all targets it supports.

**Comment by RalfJung** [comment]
> Sorry I got confused, I meant emulate_foreign_item instead of find_foreign_function. I think that the function should only match the target platform and then there should be a platform specific emulate_foreign_item in its own file/module. In case a shim is the same for more than one platform I'd import it in each platform's module.

I think we should permit for platforms that are very similar, the way macOS and Linux are. So this should be more tree-shaped: first distinguish windows and POSIX early, then on the POSIX side handle the POSIX common things, and if none of them matches dispatch to the Linux/macOS-specific handlers.

> For example, statx should be inside shims/foreign_items/linux/fs.rs and stat inside shims/foreign_items/macos/fs.rs

What I don't like about this is how this splits the code handling `FileMetadata` across modules all over the module tree. This requires making things public that ought to be private to that module.

For this reason, I think for shims that are interesting enough to warrant a "domain module" (like `fs,rs` or `env.rs` or `tls.rs`), that module should keep as much private as it can and thus contain the code for all targets it supports.

**Comment by christianpoveda** [comment]
> I think we should permit for platforms that are very similar, the way macOS and Linux are. So this should be more tree-shaped: first distinguish windows and POSIX early, then on the POSIX side handle the POSIX common things, and if none of them matches dispatch to the Linux/macOS-specific handlers.

This sounds good to me.

> What I don't like about this is how this splits the code handling `FileMetadata` across modules all over the module tree. This requires making things public that ought to be private to that module.
> 
> For this reason, I think for shims that are interesting enough to warrant a "domain module" (like `fs,rs` or `env.rs` or `tls.rs`), that module should keep as much private as it can and thus contain the code for all targets it supports.

So you'd rather have `statx` and `stat` living under the same `fs` module and only make the distinction at the dispatch level, am I right?

**Comment by RalfJung** [comment]
> So you'd rather have statx and stat living under the same fs module and only make the distinction at the dispatch level, am I right?

Yes.
*Within* the `fs` module, it might make sense to do some further organization if it grows too big. For now, I think it is enough to sort the methods in that file ("generic", "Linux", "macOS") and separate these groups clearly by comments.

**Comment by christianpoveda** [comment]
Ok then I'll start working on it, we'll have something like this:
```
shims/
    foreign_items.rs
    foreign_items/
        windows.rs
        posix.rs
        posix/
            linux.rs
            macos.rs
    fs.rs
    time.rs
    env.rs
    tls.rs
```

**Comment by RalfJung** [comment]
Yes, I like that basic structure. :)
