### ISSUE TITLE
Confusing false positives and negatives calling `mmap`

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/miri#1181]
The call to `libc::mmap` evaluates precisely to its first argument. In many cases, this signals a successful return and thus a valid pointer. Such a pointer is likely to be 'dangling' for all other uses in MIRI but it doesn't need to be. This can be very confusing when MIRI failure occurs at a *later* point although the actual failure was already the `mmap` call, especially when the pointer is *not* considered dangling the errors can get obscure.

```rust
extern crate libc;

fn main() {
    // Invent an address.
    let addr = 0x8_0000_0000 as *mut libc::c_void;
    let ptr = unsafe {
        libc::mmap(
            addr,
            32,
            libc::PROT_READ | libc::PROT_WRITE,
            libc::MAP_ANON | libc::MAP_PRIVATE | libc::MAP_FIXED,
            -1,
            0,
        )
    };
    // Should pass exactly on success due to MAP_FIXED
    assert!(ptr == addr, "Mmap failed");
    unsafe {
        // MIRI fails here.
        (ptr as *mut usize).write(0x42);
    }
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7dafcaad70fd8d1fc134d944d9edf9ce)

**Comment by RalfJung** [comment]
Yeah, what we do with `mmap` is quite gross. Really it should just return as "not supported" immediately, but we need to somehow make [this](https://github.com/rust-lang/rust/blob/183e893aaae581bd0ab499ba56b6c5e118557dc7/src/libstd/sys/unix/stack_overflow.rs#L130) call work out. I suppose we could check that the pointer is NULL? Or we would go even further and make sure the caller is in libstd, to make sure user code doesn't run into this.
