### ISSUE TITLE
Abort in "assert_*" intrinsics

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1222]
[These three intrinsics](https://github.com/rust-lang/miri/blob/704228d0bb65227c82a8b44ab819485912b44007/src/shims/intrinsics.rs#L447-L449) should, IMO, abort instead of panic. The main reason we make them panic in rustc is that we want a good backtrace, and doing that from codegen is hard. But causing a panic is easy thanks to libcore having panic support, and std hooking into it.

But in Miri, we can show great backtraces on abort! So, there is no reason to use panics IMO. So I propose that we extend this with an abort message:
https://github.com/rust-lang/miri/blob/704228d0bb65227c82a8b44ab819485912b44007/src/eval.rs#L56
and then cause an abort from the intrinsic.

@elichai that they would look into this.

**Comment by eddyb** [comment]
Might make more sense to name the intrinsics e.g `assert_inhabited` instead of `panic_if_uninhabited`.
That would also make aborting instead of panicking in miri less odd-looking.

**Comment by elichai** [comment]
Had a medical procedure, so sadly I'll only be able to work on it in a few days

**Comment by RalfJung** [comment]
No worries, this is not urgent at all. :)

**Comment by elichai** [comment]
How should I modify these tests to capture the aborts?
Should I make a separate `.rs` file for each? :/ 
Should I write the code into a new `.rs` file, and compile+run it in a new process? something else?

(maybe I can "patch" the abort function so I can catch it? but it might defeat the purpose)

**Comment by RalfJung** [comment]
Just remove these things from the `catch` test. And then add one or two new `compile-fail` tests instead. See [here for an example](https://github.com/rust-lang/miri/blob/ff2e799e360f8552dc5d70fa03ccf2f76b74485f/tests/compile-fail/double_panic.rs) of another test that aborts.
