### ISSUE TITLE
Write Windows batch script version of 'miri' script?

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/miri#1229]
With my Windows PC, I've been running the `miri` bash script by running 
*ex.* `sh miri run tests/run-pass/env.rs`.

It's been working because I had `Git for Windows` installed (which comes with `bash.exe` & `sh.exe`)
and I had the `sh.exe` added in my **Path**.

Running `cargo miri` works in Windows, but the `miri` bash script itself does not work out-of-the-box in Windows. The current method I'm using is more of a workaround, rather than proper support for Windows developers. 

I think it'd be nice to have a batch script version of `miri` script that Windows users can use out-of-the-box, without workarounds.

p.s. if there is already proper support for Windows users to run the `miri` script, please let me know 😉

**Comment by RalfJung** [comment]
I should preface that I have not done any development on Windows for at least 15 years, so I have no idea at all what is considered a normal development environment on that platform.^^

That said, if there is a way to use the shell script we have, that seems like the best option to me. That shell script is maintained as Miri changes, and it is used by our CI, so it should just always work. Sharing code across platforms is better than re-writing things for each platform. Currently, Windows CI (via AppVeyor) does not use it; if you could help use it there that would be great. :D

I suspect most devs will have git installed on their Windows box so your method will work for them?

That said, if you want to submit *and maintain* a Windows variant of that script, I'll happily review those patches. I just want to avoid having an outdated Windows-only script in the repository that nobody in the Miri team can fix or test.

**Comment by eddyb** [comment]
Why is there a *script*? Rust executables are far more portable.
Anyway, if you wanted a Windows equivalent, you'd probably use PowerShell.
"Batch files" are woefully outdated and underpowered.

**Comment by RalfJung** [comment]
@eddyb well [go read it yourself](https://github.com/rust-lang/miri/blob/master/miri) if you want to know what it does. ;)

Note that the rustup distribution contains no script. The script is just for development. It handles building the Miri sysroot (usually done by cargo-miri, but during development you often want to to worectly with the miri driver), working around https://github.com/rust-lang/rust/issues/58343, things like that.

**Comment by eddyb** [comment]
> @eddyb well go read it yourself  if you want to know what it does. ;)

I have, it looks like the kind of thing a Rust project would write in Rust :P.

> Note that the rustup distribution contains no script.

Okay so this isn't as bad as it could be.

**Comment by RalfJung** [comment]
> it looks like the kind of thing a Rust project would write in Rust :P.

Fair. ;) I'm somehow still reaching for shell/Python first for such things...

It's not entirely trivial though, since this sets flags for the build it would have to at least be an entirely separate crate from the main thing. And workspaces always seemed too complicated for me...^^

**Comment by eddyb** [comment]
> And workspaces always seemed too complicated for me...^^

Every cargo package is at most one lib crate and any number of bin crates, so you wouldn't need a workspace probably - or wait, whoops, do you mean it'd need to be a separate package?

**Comment by RalfJung** [comment]
> do you mean it'd need to be a separate package?

Yes. In particular it should have an independent set of dependencies. After all this sets RUSTFLAGS for the main compilation.

Now, moving to a workspace would also help with https://github.com/rust-lang/miri/issues/418, but still... so far I couldn't be bothered.^^

**Comment by JOE1994** [comment]
> That said, if there is a way to use the shell script we have, that seems like the best option to me. That shell script is maintained as Miri changes, and it is used by our CI, so it should just always work. Sharing code across platforms is better than re-writing things for each platform. 

I agree with your point :smiley_cat: 

I've just learned that [*the Windows Build environment of Travis CI* also uses **Git Bash** to run builds](https://docs.travis-ci.com/user/reference/windows/#git-bash).
I guess there isn't much motivation to write and maintain a separate batch script.

Adding a single line `- windows` to `.travis.yml` should probably suffice to make Travis CI test the build in its Windows Build environment. 
https://github.com/rust-lang/miri/blob/acdddc78bc738786e3992377a0d1378c071d8579/.travis.yml#L10-L12

Thank you for your feedback! I'm closing the issue now :sweat_smile:

**Comment by RalfJung** [comment]
We've experimented with using Travis for Windows CI in the past and it didn't really work. Maybe it got better since then.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/miri/pull/1407, we are now using `bash miri` for our Windows CI, and it actually Just Works (TM). So this should also be an option for developing on Windows (AFAIK a bash comes with git, so I assume most developers will have one).
