### ISSUE TITLE
Use clippy to avoid unchecked casts and arithmetic

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1236]
@oli-obk [writes](https://github.com/rust-lang/miri/pull/1235#issuecomment-600176700)

> There's a clippy lint for this if we want to make sure we don't add more of these in the future: https://rust-lang.github.io/rust-clippy/master/index.html#integer_arithmetic

AFAIK there is also one for casts, right?

Is there a good way to also subject the miri engine in `librustc_mir/interpret` to these checks?

**Comment by oli-obk** [comment]
There's a whole group of cast lints.

Unfortunately we aren't quite at the stage where we can run clippy lints on rustc. Though @matthiaskrgr has been doing this, and it may actually work well nowadays.

**Comment by matthiaskrgr** [comment]
Yes, one can get it to work but it is very fragile and I am currently waiting on clippy being updated :)
https://github.com/matthiaskrgr/rust/commits/fix_xpy_clippy

**Comment by oli-obk** [comment]
The minimal bar would be to add it to our CI like with rustfmt. https://github.com/rust-lang/miri/pull/2091 updates miri to be clean with clippy

**Comment by RalfJung** [comment]
We now have clippy on CI. So we can resolve this issue by adding
```rust
#![warn(
    clippy::cast_sign_loss,
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_lossless
)]
```
and fixing the warnings.

This doesn't help for the code in the rustc repo though.
