### ISSUE TITLE
Readme.md - should list what miri doesn't support

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/miri#1289]
The readme.md states:

> When compiling code via cargo miri, the miri config flag is set. You can use this to ignore test cases that will fail under Miri because they do things Miri does not support:

However, there doesn't seem to be a list of what miri does not support? It would be good to have this list on the readme for when people need to reference it. :) 

Thanks!

**Comment by RalfJung** [comment]
I'm afraid that list is infinite, as it contains every single FFI function except for the few that are explicitly implemented.

Also, the README says the following, very far up in the first section, below an introduction that says "Miri [...] cannot run all programs":

> Miri runs the program as a platform-independent interpreter, so the program has no access to most platform-specific APIs or FFI. A few APIs have been implemented (such as printing to stdout) but most have not: for example, Miri currently does not support concurrency, or SIMD, or networking.

I honestly cannot think of anything else we could say in the README. Do you have concrete suggestions?

**Comment by RalfJung** [comment]
Also note that when your program does something that Miri does not support, Miri will quite explicitly tell you:
```
error: unsupported operation: can't call foreign function: mach_timebase_info
   --> /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/time.rs:239:13
    |
239 |             mach_timebase_info(&mut info);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function: mach_timebase_info
    |
    = help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
    = note: inside call to `std::sys::unix::time::inner::info` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/sys/unix/time.rs:156:24
    = note: inside call to `std::sys::unix::time::inner::Instant::checked_sub_instant` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/time.rs:263:9
note: inside call to `std::time::Instant::duration_since` at tests/run-pass/time.rs:25:20
   --> tests/run-pass/time.rs:25:20
    |
25  |         let diff = now2.duration_since(now1);
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: inside call to `main` at /home/r/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/rt.rs:67:34
```
If you don't get such an error, you are good. :)

**Comment by Firstyear** [comment]
Maybe that's what the readme needs? To say "if there is something unsupported you will get an error like this"? Basically what you just said here would help people to understand that the unsupported list is infinite and you just have to try it and find out. :)

Thanks for your patience!

**Comment by Firstyear** [comment]
https://github.com/rust-lang/miri/pull/1293
Open a PR for this :)
