### ISSUE TITLE
Confused by build instructions concealing the actual build step

### ISSUE THREAD

**Issue by ssomers** [rust-lang/miri#1306]
Preparations are very well explained in CONTRIBUTING.md, but I had a hard time figuring out how to build miri:
- "Testing the Miri driver" doesn't mention it builds too (at least I think now that it also builds)
- "Building Miri with a locally built rustc" suggests you need to build something, but doesn't mention how to build. You set stuff up and then proceed with "working with the Miri driver."
- There's a Cargo.toml, so perhaps aspiring Rusticians are assumed to just `cargo build` away, but now I don't think that's the way.

**Comment by RalfJung** [comment]
Thanks for the feedback!

> "Testing the Miri driver" doesn't mention it builds too (at least I think now that it also builds)

Yes it does (in analogy with `cargo run`).

I think your questions are answered by `./miri help`, but it is probably worth mentioning this in the docs as well.
