### ISSUE TITLE
Add option to flag uninitialized integers as UB

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1340]
The reference currently states that this code is UB, but Miri deliberately accepts it:
```rust
fn main() {
    let _val = unsafe { std::mem::MaybeUninit::<usize>::uninit().assume_init() };
}
```
The reason we accept it is that the lang-team is not sure if we really want this to be UB (also see https://github.com/rust-lang/unsafe-code-guidelines/issues/71), so the conservative choice for the reference is to make it UB for now, but in Miri I fear this might lead to too many errors that people could consider false positives (even though by the letter of the reference they are true positives).

Still it could be interesting to see how much code (that Miri can run) actually fails when considering uninitialized integers UB, so having a flag in Miri to enable stricter checking would be interesting.

**Comment by oli-obk** [comment]
Maybe this is something where we could just emit a warning (silenceable of course) by default?

**Comment by RalfJung** [comment]
Yeah that also sounds good... but then we have three levels, allow/warn/deny, so it really seems like we should use the lint system.^^

That will also be much harder though, I imagined just having a machine hook that affects whether validation checks integers for being initialized (instead of doing that based on whether we are in "const mode").

**Comment by oli-obk** [comment]
seems good, too. If we make it configurable in miri via the command line, users can turn it off if it bothers them (or we start with opt-in)

**Comment by DrMeepster** [comment]
Looks like [this](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_mir/interpret/validity.rs.html#551-552) is the place where the check would go

**Comment by RalfJung** [comment]
Yes that is correct.

**Comment by RalfJung** [comment]
While at it we should probably also mark ptr-to-int transmutes as UB (Cc https://github.com/rust-lang/unsafe-code-guidelines/issues/286)

**Comment by camelid** [comment]
I started working on this, but when I try to use my locally-built rustc with Miri, I get a strange error:

```
error[E0463]: can't find crate for `rustc_apfloat`
  --> src/lib.rs:10:1
   |
10 | extern crate rustc_apfloat;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

For more information about this error, try `rustc --explain E0463`.
```

When I built rustc, it said that it built `rustc_apfloat`, so I'm not sure what's going on. What should I do to fix this?

**Comment by oli-obk** [comment]
I don't know how to work with a locally built miri except by doing ./x.py test src/tools/miri

It may be that we just don't properly support going the rustup toolchain link route

**Comment by RalfJung** [comment]
@camelid have you follow the instructions at https://github.com/rust-lang/miri/blob/master/CONTRIBUTING.md#building-miri-with-a-locally-built-rustc ? Those are what I used for locally built rustc and they always worked for me.

**Comment by RalfJung** [comment]
Hm, actually I am always using stage 2, not stage 1. But you are the one who changed the instructions to recommend stage 1 instead of stage 2... are you saying that does not work any more? Should we revert https://github.com/rust-lang/miri/commit/bb59980b2da10437ce1ee4d53bdb3feb1f4a9c5f?

**Comment by camelid** [comment]
> Hm, actually I am always using stage 2, not stage 1. But you are the one who changed the instructions to recommend stage 1 instead of stage 2... are you saying that does not work any more? Should we revert [bb59980](https://github.com/rust-lang/miri/commit/bb59980b2da10437ce1ee4d53bdb3feb1f4a9c5f)?

Yes, I'm almost done with a stage2 build to see if that fixes it. If that works, I was planning to also suggest we revert that commit :)

**Comment by camelid** [comment]
Indeed, that fixed it.

**Comment by camelid** [comment]
> are you saying that does not work any more?

I'm not sure; I wonder if I had already built a full stage2 when I was testing it for that PR.

**Comment by RalfJung** [comment]
The good news is that the Rust libcore/liballoc test suites pass even with this flag. :)

**Comment by DrMeepster** [comment]
That doesn't sound correct to me, I know at least `std::io::copy` and `std::io::Read::read_to_end` create slices of uninit u8s.

**Comment by bjorn3** [comment]
This options doesn't check behind references AFAIK, so it doesn't catch slices of uninit u8s.

**Comment by RalfJung** [comment]
Yeah -- (a) I am not sure if we are hitting those codepaths (we are not running the std test suite, only core and alloc), and (b) validity is not checked recursively through references (see https://github.com/rust-lang/unsafe-code-guidelines/issues/77).
