### ISSUE TITLE
Leak checker doesn't see through AtomicPtr

### ISSUE THREAD

**Issue by vorner** [rust-lang/miri#1350]
Hello

I had miri report a leak in my code and after searching for it for a while, I believe it is a false positive. I've created a reproducer which should demonstrate it. The allocated memory is still reachable through the AtomicPtr, but miri doesn't see it.

```rust
use std::sync::atomic::{AtomicPtr, Ordering};
use std::ptr;

static X: AtomicPtr<usize> = AtomicPtr::new(ptr::null_mut());

fn main() {
    X.store(Box::into_raw(Box::new(42usize)), Ordering::Relaxed);
}
```

I think it might be somewhat similar to #1318 (I suspect the AtomicPtr might be considered usize internally).

**Comment by bjorn3** [comment]
> I think it might be somewhat similar to #1318 (I suspect the AtomicPtr might be considered usize internally).

Yes. https://github.com/rust-lang/rust/pull/70765 will fix this if it lands.

**Comment by RalfJung** [comment]
> Yes. rust-lang/rust#70765 will fix this if it lands.

Yeah... but it seems unlike that that will land, honestly. :/

> I think it might be somewhat similar to #1318 (I suspect the AtomicPtr might be considered usize internally).

Indeed, I'll close this as a duplicate -- I see no good reason to track this separately.
