### ISSUE TITLE
Miri has exit code 0 on typeck failure

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1352]
When Miri fails to typeck a program (so that interpretation cannot even start), for some reason it exits with exit code 0. When Miri detects a problem with the program it exist with code 1 as expected.  

I have no idea...

**Comment by oli-obk** [comment]
I think it's because we abort compilation after the analysis phase and just report the interpreted program's exit code

**Comment by RalfJung** [comment]
Well, we do use the exit code given to us by `catch_fatal_errors`:

https://github.com/rust-lang/miri/blob/52f5d202bdcfe8986f0615845f8d1647ab8a2c6a/src/bin/miri.rs#L263

**Comment by RalfJung** [comment]
Also, we don't even get to `after_analysis` in case of a rustc error. So whatever we do there cannot make a difference.

**Comment by oli-obk** [comment]
Oh, I misunderstood, I thought you were talking about typeck-errors on query invocations.

This seems like a driver engine issue to me
