### ISSUE TITLE
Skip interactive prompts if `CI` environment variable is set

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/miri#1357]
This is a consistent variable that various CI environments define for the purpose of tooling to change its defaults to make more sense in a noninteractive context.

- https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
- https://help.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables
- https://www.appveyor.com/docs/environment-variables/

The readme calls out that `cargo miri setup` avoids the prompts but it shouldn't be necessary; CI should be able to go directly to `cargo miri test`.

**Comment by RalfJung** [comment]
So you are basically saying that if `env::var_os("CI").is_some()`, we should skip prompts? That makes sense. I didn't know such a general env var existed. Thanks for bringing this up!
