### ISSUE TITLE
Strange libstd rebuilds

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1410]
After doing `./miri install`, alternating between the following commands rebuilds libstd each time:
```
./miri run tests/run-pass/hello.rs
cargo miri setup
```
That is rather strange, I do not know why it thinks the build cache is outdated.

In particular this happens on CI, where we first run `./miri test`, and then later when we get to the `cargo miri` tests we run `cargo miri setup`, causing an unnecessary rebuild.

**Comment by bjorn3** [comment]
You may be able to find the reason cargo thinks it has to rebuild libstd by using `CARGO_LOG=trace`.
