### ISSUE TITLE
stdin cannot be read

### ISSUE THREAD

**Issue by koivunej** [rust-lang/miri#1434]
I tried to run my stdin reading program yesterday with miri 0.1.0 (10419b3 2020-05-11) and rustc 1.45.0-nightly (a74d1862d 2020-05-14) but upon reading the stdin `Ok(0)` seems to be always returned at least on Linux.

Example:

```
use std::io::Read;

fn main() {
    let mut bytes = [0u8; 8192];
    let total = std::io::stdin().lock().read(&mut bytes[..]).unwrap();
    println!("{}", total);
}
```

With stable `echo foo | cargo run` prints 4.
With miri `echo foo | cargo +nightly miri run -- -Zmiri-disable-isolation` prints 0. Same for reading in a loop.

Looking at `src/shims/foreign_items/posix.rs` and `src/shims/fs.rs` I can't at least see any relevant TODO's or other notes which would suggest this should not work.

Could this be because `src/bin/cargo-miri.rs` launches a subprocess and somehow the stdin does not get inherited?

**Comment by RalfJung** [comment]
Reading from stdin is indeed not implemented. So what I would have expected is that it returns an error, saying that the FD does not exist...

**Comment by RalfJung** [comment]
Yeah we are definitely returning -1 from that one. But somehow libstd swallows the error?

**Comment by RalfJung** [comment]
Yeah libstd contains explicit code to translate "ebadf" errors for stdin/stdout/stderr into 0 reads -- probably to work in environments where the handle is for some reason not available. (This is the `Maybe` wrapper defined in `io/stdio.rs`.)

**Comment by koivunej** [comment]
Ok good that I filed this issue then, I had misunderstood and was hoping this could be an E-easy issue I could snipe :) I'll update when I've looked more on how this could be implemented.

**Comment by RalfJung** [comment]
Hm, I'd still call this easy but yeah it requires digging into the shims code a bit more. ;) Probably it is time to handle FDs 0-2 in `shims/fs.rs` instead of having that code separately.

And what you said about cargo wrapping Miri causing problems might still be true, but we'll only know after the driver can handle stdin.^^

**Comment by RalfJung** [comment]
I improved the error message in https://github.com/rust-lang/miri/pull/1435.

**Comment by samrat** [comment]
I am interested in picking this issue up.

@RalfJung Just to clarify, we want to start supporting `read`s on stdin, right?

**Comment by RalfJung** [comment]
@samrat yes. The starting point for that would be here:

https://github.com/rust-lang/miri/blob/b334004607f1cfb5754d9b0a007114748f272444/src/shims/foreign_items/posix.rs#L69

**Comment by samrat** [comment]
Oh, I just realized that @koivunej had mentioned that he was interested in picking this up-- didn't mean to step on their toes like this.

@koivunej Assuming you're still interested in the issue, please it away! I look forward to checking out the solution you come up with :)

**Comment by koivunej** [comment]
@samrat I don't expect to have time until the weekend so you can go ahead. Given the starting point [linked above](https://github.com/rust-lang/miri/issues/1434#issuecomment-633974515) I'd guess reading should be implemented similar to stdout and stderr writing few lines below.

> I look forward to checking out the solution you come up with :)

Likewise :)

**Comment by RalfJung** [comment]
> I'd guess reading should be implemented similar to stdout and stderr writing few lines below.

Yes I think that would be a good start.
Longer-term, I'd like to move the handling of "special" FDs to `shims/fs.rs` together with the other FDs, with some kind of abstraction for "either a normal FD or stdout/stdin/stderr" -- then we could even support `dup` or `close` on the "special" FDs. But that does not have to happen in the same PR.
