### ISSUE TITLE
ICE around validation of `bool` and `char`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1467]
@niluxv found an ICE around validation of uninitialized `char`. [Here's a self-contained example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d140693dd8cde352915b3140841b2c93); this embeds linked-hash-map. It would be nice to minimize this further.

The actual ICE [occurs here](https://github.com/contain-rs/linked-hash-map/blob/f1ee0d032368e4912af9d4620bd0ec3857838f2e/src/lib.rs#L114) and it is unclear why, because uninitialized `char` usually work fine.

**Comment by niluxv** [comment]
I used [this example (playground link)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=4e6b3f018fa09f96d066d35294ef74e7). It only includes the code from `linked-hash-map` that is required for the example to compile.

**Comment by RalfJung** [comment]
Actually, even this ICEs:
```rust
fn main() {
    let _b: bool = unsafe { std::mem::MaybeUninit::uninit().assume_init() };
}
```
Something is very odd...

**Comment by niluxv** [comment]
Actually a call to `drop`ing a `LinkedHashMap` is enough: [playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=6c8a17ddc28189e0b7188296e1876d92).

**Comment by RalfJung** [comment]
I'll need to do a full rustc bootstrap to get more debugging information, right now nothing makes any sense.^^ This will take a while.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/74059 should fix this.
