### ISSUE TITLE
De-duplicate read/write code for stdin/out and other FDs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1486]
Currently, FDs 0-2 are handled separated from all other FDs, leading to some code duplication. We should instead extend `posix/fs.rs` to handle FDs a bit more generally, and make 0-2 more like normal FDs.

@samrat you expressed some interest in working on this; is that information still current?

**Comment by samrat** [comment]
@RalfJung Yes, I am still interested in working on this.

**Comment by RalfJung** [comment]
@samrat great. :)

What I was imagining is to adjust this:

https://github.com/rust-lang/miri/blob/91b58c93c5ab18969e7bdce3bf3e110c9b150d4b/src/shims/posix/fs.rs#L27

Basically, instead of mapping file descriptors to `FileHandle`, we'd have a `trait FileDescriptor` and we'd use a `BTreeMap<i32, Box<dyn FileDescriptor>>`. The trait would have all the operations we need on file descriptors, and we'd implement it not only for `FileHandle` but also have something like
```rust
struct Stdin;
struct Stdout;
struct Stderr;
```
and implement the trait for those as well.

I think to stage this it would make sense to first just to the work of defining such a trait, implementing it for `FileHandle` and changing the rest of `fs.rs` appropriately, but without actually incorporating stdin/stdout/stderr. That can then happen in a separate follow-up PR.

@samrat does this make sense?

**Comment by samrat** [comment]
Thanks! The approach makes sense. I'll try to break down the changes into separate PRs like you've suggested.

IIUC, this will involve changes in all syscalls which use `FileHandler` and not just `read` & `write`. Is that correct? Did you have anything in mind to stage these changes as well?

**Comment by RalfJung** [comment]
Long-term, it would be nice if `dup` etc also worked for stdin/stdout/stderr.

Short-term, a transition strategy could be to have a method `as_file_handle(self) -> InterpResult<'tcx, FileHandle>` in the trait, which throws an "unsupported" error for non-FileHandle-FDs.
