### ISSUE TITLE
When do thread-local dtors execute relative to thread blocked on "join"?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1488]
I just realized that currently, Miri unblocks threads joining on some other thread *before* running the TLS dtors of that thread. That seems odd to me, is that really the right semantics?

Cc @vakaras

**Comment by RalfJung** [comment]
[This example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3fbd464eb9da84c0541cf4ec42427165) shows that probably we should run dtors before waking up threads that join.

**Comment by vakaras** [comment]
Good point. I somehow have not though about this.
