### ISSUE TITLE
`env::current_dir()` is not updated for non-root packages in a workspace

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/miri#1514]
`cargo test` and `cargo bench` [update the working directory](https://github.com/rust-lang/cargo/blob/67075be62607d14d84ef858017e15f177b4b346d/src/cargo/core/compiler/compilation.rs#L309) when running the test binary. For example, if you have a `foo` sub-package in its own `foo` directory, then `cargo test -p foo` updates the working directory to `./foo` when running its tests.

`cargo miri test -p foo -- -Zmiri-disable-isolation` does not update the working directory, so it's still `.` rather than `./foo`. This breaks tests that rely on accessing files for test data.

**Comment by RalfJung** [comment]
I am actually surprised that anything happened with workspaces -- see https://github.com/rust-lang/miri/issues/1001, they are currently not really supported.
