### ISSUE TITLE
Cargo env vars aren't set

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/miri#1515]
Cargo's docs specify [various env vars](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) that [are passed](https://github.com/rust-lang/cargo/blob/67075be62607d14d84ef858017e15f177b4b346d/src/cargo/core/compiler/compilation.rs#L278-L308) to binaries run with `cargo run/test/bench`. `cargo miri` does not currently pass them, so this fails under miri:

```rust
fn main() {
    println!("{}", std::env::var("CARGO_PKG_NAME").unwrap());
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c7c4b8a1a1dde5bc7090b2ca60a560f5))

**Comment by bjorn3** [comment]
You need to pass `-Zmiri-disable-isolation` to miri. For example `cargo miri run -- -Zmiri-disable-isolation`. Otherwise everything from env var access to filesystem access is disabled.

**Comment by alecmocatta** [comment]
Sorry, I thought I'd repro'd this with `-Zmiri-disable-isolation` but I was mistaken. Closing!

**Comment by RalfJung** [comment]
@alecmocatta  Also you should be able to use `env!` I think, which is evaluated at build-time rather than at run-time. That's advisable anyway as it will mean that this works even if you distribute the binary and run it outside `cargo`. (For tests that seems unlikely, for the main binaries more likely.)

**Comment by alecmocatta** [comment]
Thanks @RalfJung! I bumped into this when I changed `env::current_dir()` to `PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").unwrap())` to workaround #1514. `env!` could plausibly be outdated whereas `env::var_os` is in theory guaranteed to be correct. Regardless, looking forward to removing once #1540 lands!

**Comment by RalfJung** [comment]
Not sure what you mean by "outdated"? The file should be rebuilt if the env var changes (that used to not happen but was fixed recently I think).

**Comment by alecmocatta** [comment]
e.g. on moving the manifest directory, but now I think about it you're probably right that would trigger a rebuild on the next `cargo test` invocation.

**Comment by alecmocatta** [comment]
Actually I've just confirmed that moving the manifest directory **does not** trigger a rebuild, thus `env!` and `env::var` can disagree. This seems dubious behaviour to me, I'll file an issue rust-lang/rust.

**Comment by alecmocatta** [comment]
https://github.com/rust-lang/rust/issues/76511
