### ISSUE TITLE
Feature Request: flag to disable "inbounds" check on inbounds pointer arithmetic

### ISSUE THREAD

**Issue by YoshikiTakashima** [rust-lang/miri#1519]
Hello.

Is it possible for Miri to delay pointer bounds check until time of dereferencing? I think this will cut down on "false positive" cases.

After using Miri for some time, I've realized that there are some quite a few low level parsing/memory manipulation libraries (encoding_rs for example) that does some something like this:

Increment pointer without dereferencing => check bounds => if pointer is in bounds, do some dereferencing operations.

Currently, Miri quits with an error the moment the pointer goes out of bounds. In theory, we should be able to maintain soundness so long as we don't dereference the pointer outside of known memory ranges. In practice, you'll need to carry some bounds information regarding the offset from which this pointer is formed, which may be practical or not.

If this isn't possible, please let me know.

Thanks
~Yoshi

**Comment by bjorn3** [comment]
> Increment pointer without dereferencing => check bounds => if pointer is in bounds, do some dereferencing operations.

It should already be valid to have a pointer 1 element out of bounds.

**Comment by RalfJung** [comment]
As far as I know, Miri has no false positives on bounds checks. Delaying the bounds check would be wrong.

Do you have a concrete example, ideally a small one, for a program that you think is valid but which Miri complains about?

**Comment by YoshikiTakashima** [comment]
Unfortunately, I don't have a very short example, but here is a case I saw recently with encoding_rs.

src/ascii.rs lines 189~273
```
        pub unsafe fn $name(
            src: *const $src_unit,
            dst: *mut $dst_unit,
            len: usize,
        ) -> Option<($src_unit, usize)> {
            let mut offset = 0usize;
            // This loop is only broken out of as a `goto` forward
            loop {
                let mut until_alignment = {
                    // ...other comments
                    if ::std::mem::size_of::<$src_unit>() < ::std::mem::size_of::<$dst_unit>() {
                        // ascii_to_basic_latin
                        let src_until_alignment = (ALU_ALIGNMENT
                            - ((src as usize) & ALU_ALIGNMENT_MASK))
                            & ALU_ALIGNMENT_MASK;
                        if (dst.add(src_until_alignment) as usize) & ALU_ALIGNMENT_MASK != 0 { //miri stops
                            break;
                        }
                        src_until_alignment
                    } else {
                        // basic_latin_to_ascii
                        let dst_until_alignment = (ALU_ALIGNMENT
                            - ((dst as usize) & ALU_ALIGNMENT_MASK))
                            & ALU_ALIGNMENT_MASK;
                        if (src.add(dst_until_alignment) as usize) & ALU_ALIGNMENT_MASK != 0 {
                            break;
                        }
                        dst_until_alignment
                    }
                };
...
```

And Miri stops on `dst.add(src_until_alignment)` when `dst` goes out of bounds. I ran the same code with rust-san and it does not flag any issues, so I think it avoided dereferencing the pointer after it went out of bounds.

If you want to replicate it, you can clone encoding_rs and run miri inside it. It should be the first error that gets flagged.

**Comment by bjorn3** [comment]
https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.add

> Both the starting and resulting pointer must be either in bounds or one byte past the end of the same allocated object. Note that in Rust, every (stack-allocated) variable is considered a separate allocated object.

You must use `wrapping_add` instead to prevent UB.

**Comment by YoshikiTakashima** [comment]
Hi @RalfJung.

You're right about it being unsound. I was thinking of other, looser semantic models, not Rust.

Thank you for the information. I will take a look.

**Comment by YoshikiTakashima** [comment]
After nearly a year of using Miri, I no longer see much of a use for this particular feature. 

If anybody wants it, you can reopen.
