### ISSUE TITLE
Implement missing shims for Windows

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1537]
Here we track shims that Miri currently only implements for Linux and macOS targets, but not for Windows.

If you run into this, try `cargo miri test --target x86_64-unknown-linux-gnu`. This works even on a Windows host (without installing anything extra) and interprets programs on a well-supported Linux target.

* [ ] File system access (https://github.com/rust-lang/miri/issues/3482)
* [x] Threading
* [x] `std::thread::sleep`
* [x] `std::sync`
* [ ] Console functions (https://github.com/rust-lang/miri/issues/2652)

**Comment by jmerdich** [comment]
Also add RNG to the list (rand's default initial seed comes from the OS via `BCryptGenRandom`).

**Comment by RalfJung** [comment]
We do test that `getrandom` works on Windows, why isn't `rand` using that? For this to work we implement `SystemFunction036` which is the actual name of `RtlGenRandom`. I thought supporting `getrandom` would be enough to cover RNG initialization.

**Comment by RalfJung** [comment]
In fact we even test this through `rand`:

https://github.com/rust-lang/miri/blob/2cdd1744b896e8129322229f253f95fd7ad491f1/test-cargo-miri/tests/test.rs#L28

@jmerdich ` SmallRng::from_entropy()` and `rand::thread_rng()` both work on Windows, so I cannot reproduce the problem you are describing.

**Comment by RalfJung** [comment]
Ah, looks like newer versions of `getrandom` changed which function they are using.

**Comment by RalfJung** [comment]
@jmerdich thanks for the notification, https://github.com/rust-lang/miri/pull/1755 should fix this. :)

**Comment by jmerdich** [comment]
@RalfJung thanks for the amazingly prompt fix! I got set up to contribute something for this and was surprised to find it already done! :D

**Comment by RalfJung** [comment]
Ah, sorry for that.^^

Fixing `std::thread::sleep` should be rather easy, if you are looking for something small to get started with. :)

**Comment by RalfJung** [comment]
That's great! I don't know a lot about the Windows File IO APIs, so I can't tell if it makes more sense to share code with Unix or to have a completely different implementation. But either way you can use the Unix version as a template. There's even a testcase already, `tests/run-pass/fs.rs`, that you just need to enable on Windows.

Yeah we don't have all the rustc tooling, but just leaving a comment is enough. :)

**Comment by mbyt** [comment]
Miri is great project, thanks!

I am trying to use miri on a regression test on windows, which uses `fs::read_to_string`. When doing so, I get an error
```
can't call foreign function `CreateFileW` on OS `windows`
```
To my understanding from this issue is that file system access is still not implemented for windows (it was added for Unix platforms 2019 in #923.

Is there a workaround for reading a regression reference in windows, such that miri does not complain (unfortunately I cannot use `include_str!` as it takes a string literal as argument)?

**Comment by RalfJung** [comment]
@mbyt you can run Miri with `--target x86_64-unknown-linux-gnu`. This works on Windows without WSL and without installing anything extra. Miri can then use its Linux support for file system access to emulate what the program does, and it should largely work for accessing Windows file systems as well. Please report an issue (a new issue) if it does not.

**Comment by RalfJung** [comment]
Since most of the small things are done now, I'll close this issue in favor of one that is specifically about file system access: https://github.com/rust-lang/miri/issues/3482.
