### ISSUE TITLE
Miri can't find crate after toolchain update

### ISSUE THREAD

**Issue by vertexclique** [rust-lang/miri#1567]
So our project was using toolchain version `nightly-2020-06-10` with miri like:
```
rustup component add miri rustfmt
cargo miri setup
cargo clean
cargo miri test
```
after updating toolchain to `nightly-2020-09-28` same build continuously fails with:
```
error[E0463]: can't find crate for `array_tool`
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/jsonpath_lib-0.2.5/src/lib.rs:125:1
    |
125 | extern crate array_tool;
    | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
```
Though, in the previous toolchain version that Miri has been shipped, this wasn't an issue. Any idea what might be going wrong?

P.S. We've changed the flag passing to MIRIFLAGS with `MIRIFLAGS="-Zmiri-disable-isolation"`.

**Comment by RalfJung** [comment]
That is strange, it seems we're doing something wrong in our cargo wrapper.

Do you have an example project you could point me to that reproduces the problem?

**Comment by RalfJung** [comment]
@vertexclique I'm afraid without a way to reproduce the problem or some further details there is not much I can do here -- since this works with many other crates, there must be something specific to your setup that is causing this.

Can you share the output of `cargo miri test -v` (after a `cargo clean`)?

**Comment by vertexclique** [comment]
@RalfJung You can find the MCVE here: https://github.com/vertexclique/miri-mcve

**Comment by oli-obk** [comment]
the only thing I'm seeing that could be relevant here just from looking at the source is that `jsonpath_lib` has a `crate-type = ["cdylib", "rlib"]` in its `Cargo.toml`

**Comment by RalfJung** [comment]
Yeah, rustc was trying and failing to build an rlib/cdylib for this. Turns out we can just skip that build, nobody needs it anyway.
