### ISSUE TITLE
Test libstd backtrace type

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1578]
@Aaron1011 added support for capturing backtraces in Miri, but so far we only test directly using the Miri API for that. Once actually using the libstd types works, we should test those as well.

@Aaron1011 what is the status of that?

**Comment by Aaron1011** [comment]
I think we need to bump thebacktrace-rs submodule in libstd.

**Comment by Aaron1011** [comment]
This is being done in https://github.com/rust-lang/rust/pull/77731
