### ISSUE TITLE
Allow blessing test stdout/stderr

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/miri#1588]
Currently, I need to update the captured stdout/stderr for each test individually whenever it changes. It would be nice to have a `./miri test --bless` mode, which would work like `./x.py test --bless`

**Comment by RalfJung** [comment]
Yeah, that would definitely be nice. Unfortunately I have no idea what would be a good way to do this.

I am also not sure if it is worth sinking more effort into our `compiletest`-based infrastructure (the non-rustc version of that crate is barely maintained) or if we can use https://github.com/dtolnay/trybuild instead.

**Comment by oli-obk** [comment]
Another alternative is to use `assert_cmd` like in https://github.com/davidbarsky/tracing-tree/pull/21/files (if `trybuild` doesn't give us the control we ened)

**Comment by saethlin** [comment]
@RalfJung I think this is done now?
