### ISSUE TITLE
No notification for cronjobs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1591]
The GHA cronjob [just failed](https://github.com/rust-lang/miri/runs/1291115625?check_suite_focus=true) but I did not get an email about this. That's not good.

@lzutao how can we ensure that cronjob failures lead to notifications for maintainers?

**Comment by RalfJung** [comment]
I have

> Notifications for workflow runs on repositories set up with GitHub Actions. 

Set to "email", "Send notifications for failed workflows only". But that does not seem to help.

Maybe @pietroalbini has an idea.

**Comment by pietroalbini** [comment]
Hmm, I'm not sure why, as I don't use email notifications for workflows myself.

**Comment by lzutao** [comment]
I see you commented on <https://github.community/t/no-email-notification-on-schedule-cron-job-failure/119638/4>.
Do you want to use that work around ? I could try to set it up for you.

**Comment by RalfJung** [comment]
I have enabled web notifications now to see if that makes a difference.

>  Do you want to use that work around ? I could try to set it up for you.

Which mail service would you use? Does Rust run a mailserver we could use for this?
The obvious alternative is to set up Travis again, which does not require such complicated setup to get mail notifications...

**Comment by bjorn3** [comment]
I enabled both web and email notifications for failed github actions runs. I haven't ever had a problem with it. Maybe it has to do something with miri being part of an organization, while cg_clif is part of my user. I haven't ever got a notification for rust-analyzer either. I am a triage team member and I am watching the main rust-analyzer repo.

**Comment by RalfJung** [comment]
> I enabled both web and email notifications for failed github actions runs. I haven't ever had a problem with it. 

Just to be sure, this includes getting notifications for failed cronjobs?

**Comment by bjorn3** [comment]
Yes, I get a notification for a failed pr labeler cronjob on my wasmtime fork every so often. https://github.com/bjorn3/wasmtime/actions?query=is%3Afailure

**Comment by RalfJung** [comment]
We now get these notifications via Zulip.
