### ISSUE TITLE
Miri fails when some rustflags are set in .cargo/config

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/miri#1654]
My .cargo/config contains the lines:

```
[build]
rustflags = ["-C target-cpu=native"]
``` 

However this causes miri to fail.

```
cargo miri test
warning: unused manifest key: package.repostiory
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/886b45ce-98b2-4d79-9069-c9ff25bc0232/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri rustc - --crate-name ___ --print=file-names '-C target-cpu=native' '-C target-cpu=native' --target x86_64-unknown-linux-gnu --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit code: 1)
  --- stderr
  error: unknown codegen option: ` target-cpu`

```

I think miri should probably be able to work with these flags when set.

**Comment by bjorn3** [comment]
I am pretty sure you need to set rustflags to either `["-C", "target-cpu=native"]` (two args) or `["-Ctarget-cpu=native"]` (no space). You are currently trying to set the ` target-cpu` option. Note the leading space.

**Comment by RalfJung** [comment]
Does regular `cargo test` work? The error seems to originate from rust, and indeed there seems to be a spurious space here:
```
  error: unknown codegen option: ` target-cpu`
                                  ^
```

**Comment by Firstyear** [comment]
Regular cargo test was working when I had it on "-C target-cpu=...", I think it was when I went to the [""] format that I had some issues. Anyway, I think this may not be an issue sorry for the noise.
