### ISSUE TITLE
Cannot compile a crate with a `crate-type = ["rlib"]` dependency

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/miri#1691]
See https://github.com/danielhenrymantilla/rust-uninit/pull/4

### Steps to reproduce the problem

Have a crate with a `crate-type = ["rlib"]` dependency (that gets used):

```bash
cd $(mktemp -d)

cargo init --lib --name foo

cargo new --lib bar && echo 'bar = { path = "bar" }' >> Cargo.toml

cat >>bar/Cargo.toml<<\#\ END
[lib]
crate-type = ["rlib"]
# END

echo 'use ::bar;' >> src/lib.rs

cargo miri test
```

The last command fails with:

```text
error: extern location for bar does not exist: /private/var/folders/m_/347zzk7j6nz08tt6z3tnd3z00000gn/T/tmp.c7NSx84d/target/x86_64-apple-darwin/debug/deps/libbar-03d28c0dc71f4bad.rmeta
 --> src/lib.rs:8:7
  |
8 | use ::bar;
  |       ^^^
```

  - When I tried to debug this with a `-vv` flag, the copy-pasted compilation invocation of crate `bar` yielded no compilation artifacts (mainly, no `.rmeta` file).

### Host context

  - As you can see from the error message, this, at least, happens on the `x86_64-apple-darwin` platform; ~~will try to test this on Linux now~~ Same for `x86_64-unknown-linux-gnu`.

  - ```text
    cargo -V
    cargo 1.51.0-nightly (783bc43c6 2021-01-20)
    ```

**Comment by RalfJung** [comment]
This sounds similar to https://github.com/rust-lang/miri/issues/1567 (which got fixed) and https://github.com/rust-lang/miri/issues/1627 (for which we failed to get a reproducible example).

**Comment by hyd-dev** [comment]
If I [remove](https://github.com/rust-lang/miri/commit/a6fc3a7a9e08c989862f360ed59f5c6bb62b7253) `rlib` in https://github.com/rust-lang/miri/blob/e09dce0f43993faf03cc46ac365b6a46287f90e7/cargo-miri/bin.rs#L599-L607, this issue disappears.

Actually I don't understand why `rlib` is there. [The documentation](https://doc.rust-lang.org/nightly/rustc/command-line-arguments.html#--crate-type-a-list-of-types-of-crates-for-the-compiler-to-emit) says it's the current default of `lib`:
> `lib` — Generates a library kind preferred by the compiler, currently defaults to `rlib`.

Maybe that's an oversight from #1577?

**Comment by RalfJung** [comment]
Maybe? The tricky bit about touching that code is that we have no test for it...
We now have a little workspace for `test-cargo-miri`, maybe we can have a `crate-type = ["cdylib", "rlib"]` crate in there? I'll try to craft a test.

**Comment by RalfJung** [comment]
Okay, with https://github.com/rust-lang/miri/pull/1708 we have a test. If you can make it so that test still passes, I'm okay. ;)

In a quick local test, you are right -- looks like we can remove `rlib` from that `match`.
