### ISSUE TITLE
fast mode and tracing mode

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#17]
Original post: add tail-call optimization

> `<scott> a call that branches to the return block on success could be TCO'd`

---

Things to add in super fast mode:
- JIT compilation of MIR

Things to add in fast mode:
- tail-call optimization

Things to add in trace mode:
- type information of Allocations
- taint analysis
- memory leak analysis

**Comment by solson** [comment]
@eddyb pointed out on IRC that this would destroy stack traces.

I think we should have a debug/release mode concept for Miri as well. (@eddyb called it fast mode and tracking mode.)

**Comment by eddyb** [comment]
Well, what I mean is that you can run both in succession: if you rarely expect failures, and it's measurably faster not to track debug information, you can re-run on failure to get stack traces, taint analysis and other goodies.
That is, for deterministic use. But one interesting thing is that you can have a third mode: recording only non-determinism (i.e. I/O). Like rr, but specialized to whatever miri will support.

**Comment by solson** [comment]
@eddyb Interesting idea. Determinism allows for some neat features.

**Comment by RalfJung** [comment]
@oli-obk is this still a useful ticket to keep open?

**Comment by oli-obk** [comment]
I think the taint analysis and leak analysis would still be helpful. Leak analysis is pretty easy, we just need to make `allocate` take a `Span` and put that `Span` into the `Allocation` extra data.

Taint analysis seems harder, since you would have to find a way to store the tag information in integers and other `Immediate` values.

**Comment by oli-obk** [comment]
With all the perf projects that @saethlin come up with and carried through, and all the reproducability issues we have with rerunning, I think we can just close this and keep focussing on finding other ways to speed up miri.
