### ISSUE TITLE
Load weak dll imports on Windows

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/miri#1707]
On Windows, some syscalls (e.g. `WakeOnAddress`) are loaded from an `.CRT$XCU` section, which doesn't get executed on Miri.

See https://github.com/rust-lang/rust/pull/81478#issuecomment-770378432

This means the standard library falls back to not using those, which is okay for now, but is a problem when implementing `WakeOnAddress`, as that mechanism falls back to another dynamic dll import which will also not have been loaded in miri.

**Comment by RalfJung** [comment]
So basically, https://github.com/rust-lang/miri/issues/450 will be mandatory on Windows for things like `WakeOnAddress`?

**Comment by m-ou-se** [comment]
With the current implementation in `std`, yes. But there's big plans for changes that area: https://github.com/rust-lang/rust/pull/81478#issuecomment-770037764

**Comment by m-ou-se** [comment]
I suppose we could also add some `#[cfg(miri)]` in `std` to load these differently in miri?

**Comment by RalfJung** [comment]
Yeah, that would be one option.

Implementing these sections also shouldn't be terribly hard -- we just need some way to iterate over all `static` that are declared to live in that section, and then run those function pointers. It's just a bit annoying to get the code flow right here (I think this needs to be a new "stage" or so in our scheduler).

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/95775 makes weak dll imports on Windows "work" in Miri via a hack. Still, that's enough to close this issue I think.  We have https://github.com/rust-lang/miri/issues/450 for "properly" implementing this.
