### ISSUE TITLE
Implement atomic_min/max

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1718]
In https://github.com/rust-lang/rust/pull/82391 I had to disable some tests because Miri does not support atomic_min/max.

In https://github.com/rust-lang/miri/pull/1653, an attempt was made to implement those intrinsics. The general approach looks good but see that PR for some of the remaining issues that need to be solved before landing this (also, there'll be lots of conflicts due to https://github.com/rust-lang/miri/pull/1716).

**Comment by henryboisdequin** [comment]
I'm interested in working on this.

**Comment by RalfJung** [comment]
Awesome. :) If you have any questions, please just ask!
