### ISSUE TITLE
"dep-bin-cargo-miri-test" is only created on the second `cargo miri run`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1724]
To reproduce, run `rm target -rf && cargo miri run -- "" && cargo miri run -- ""` in the `test-cargo-miri` directory:
```
   Compiling byteorder v1.3.4
   Compiling cargo-miri-test v0.1.0 (/home/r/src/rust/miri/test-cargo-miri)
   Compiling issue_1691 v0.1.0 (/home/r/src/rust/miri/test-cargo-miri/issue-1691)
   Compiling cdylib v0.1.0 (/home/r/src/rust/miri/test-cargo-miri/cdylib)
   Compiling issue_1705 v0.1.0 (/home/r/src/rust/miri/test-cargo-miri/issue-1705)
   Compiling issue_1567 v0.1.0 (/home/r/src/rust/miri/test-cargo-miri/issue-1567)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
     Running `/home/r/.cargo/bin/cargo-miri target/x86_64-unknown-linux-gnu/debug/cargo-miri-test ''`
0x01020304
main

   Compiling cargo-miri-test v0.1.0 (/home/r/src/rust/miri/test-cargo-miri)
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `/home/r/.cargo/bin/cargo-miri target/x86_64-unknown-linux-gnu/debug/cargo-miri-test ''`
0x01020304
main

```
Notice how in the second run, it is still doing `Compiling cargo-miri-test`. If we do a third run, it does not do this any more.

Running with `CARGO_LOG=cargo::core::compiler::fingerprint=trace` shows that cargo is missing a file called `dep-bin-cargo-miri-test`, which (as of right now on my platform) it expects in `target/x86_64-unknown-linux-gnu/debug/.fingerprint/cargo-miri-test-44bcc890eaab31dc`. After the first run, that folder contains
```
bin-cargo-miri-test  bin-cargo-miri-test.json  invoked.timestamp
```
Only after the second run does it also contain the expected `dep-bin-cargo-miri-test`.

This is not a terribly big deal since the `Compiling` step for a binary that Miri will run does literally nothing, but it's still strange noise in the log, and it would be good to figure out what is going on.

@ehuss could you give some guidance, in particular about who is supposed to create that file and why it might only happen on the second attempt here?

**Comment by RalfJung** [comment]
Ah, I think I understand what is happening. I found a comment in cargo:
```
//! After `rustc` exits successfully, Cargo will read the dep info file and
//! translate it into a binary format that is stored in the fingerprint
//! directory (`translate_dep_info`). The mtime of the fingerprint dep-info
//! file itself is used as the reference for comparing the source files to
//! determine if any of the source files have been modified (see below for
//! more detail). Note that Cargo parses the special `# env-var:...` comments in
//! dep-info files to learn about environment variables that the rustc compile
//! depends on. Cargo then later uses this to trigger a recompile if a
//! referenced env var changes (even if the source didn't change).
```
What happens is that the `.d` file has not actually been created yet when cargo "built" the binary; it will only be created when the binary is actually run. On the second `cargo miri run`, the `.d` file exists from the previous run and now cargo finds it and translates it to its binary format.

I see two paths forward:
* Do nothing. The rebuild is harmless in the sense that no work is repeated.
* When cargo "builds" the binary, run rustc with `--emit=dep-info`. That would create the required `.d` file. I am not sure how using *just* `dep-info` is supported and how expensive it is.

**Comment by hyd-dev** [comment]
> I am not sure if emitting _just_ `dep-info` is supported and how expensive it is.

It's supported:
```bash
$ $(rustup which miri) --emit=dep-info -o /dev/stdout - <<<'macro_rules! empty { () => (include_bytes!("/dev/null")) } const _: &[u8] = empty!();'
/dev/stdout: /dev/null

/dev/null:
```
But unfortunately looks like it has to expand macros, which could be slow.

**Comment by hyd-dev** [comment]
I'm wondering if creating a stub `.d` file just like `.rlib`s and `.so`s works, Cargo will run the final "binary" anyway.

**Comment by RalfJung** [comment]
Hm... a step that doesn't do anything arguably has no dependencies, so yeah that could work.^^
