### ISSUE TITLE
Question: Undefined Behavior: trying to reborrow for Unique...

### ISSUE THREAD

**Issue by neyo8826** [rust-lang/miri#1747]
I am trying to get 2 mutable elements of a slice.
The first function gives me `Undefined Behavior: trying to reborrow for Unique at alloc1423+0x4, but parent tag <2887> does not have an appropriate item in the borrow stack`
The second one runs perfectly.
Is this really UB? Please help!

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=49ff1fa3759a26924f217bb5417f972f
```rust
fn index_twice_bad<T>(slc: &mut [T], a: usize, b: usize) -> Option<(&mut T, &mut T)> {
    if a == b || std::cmp::max(a, b) >= slc.len() {
        None
    } else {
        unsafe {
            let ar = &mut *(slc.get_unchecked_mut(a) as *mut _);
            let br = &mut *(slc.get_unchecked_mut(b) as *mut _);
            Some((ar, br))
        }
    }
}
fn index_twice_good<T>(slc: &mut [T], a: usize, b: usize) -> Option<(&mut T, &mut T)> {
    if a == b || std::cmp::max(a, b) >= slc.len() {
        None
    } else {
        unsafe {
            let ptr = slc.as_mut_ptr();
            let ar = &mut *ptr.offset(a as isize);
            let br = &mut *ptr.offset(b as isize);
            Some((ar, br))
        }
    }
}
```

**Comment by bjorn3** [comment]
Yes. In the first case `slc` gets reborrowed each time before calling `get_unchecked_mut`. The second reborrow invalidates all references and pointers derived from the first reborrow.

**Comment by neyo8826** [comment]
Thank you
