### ISSUE TITLE
undefined symbol: miri_resolve_frame

### ISSUE THREAD

**Issue by kellerkindt** [rust-lang/miri#1760]
I just installed* miri and wanted to try it before adding a stage to the github actions.
But executing `cargo +nightly miri test` on [asn1rs](https://github.com/kellerkindt/asn1rs/) throws the following error:

```bash
error: /tmp/cargo-target/debug/deps/libasn1rs_macros-398599e648a8b772.so: undefined symbol: miri_resolve_frame
 --> asn1rs/src/lib.rs:5:1
  |
5 | pub extern crate asn1rs_macros as macros;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `asn1rs`

To learn more, run the command again with --verbose.
```
```bash
$ cargo +nightly miri test --version
miri 0.1.0 (12dac5c 2021-03-17)
```

*like that
```bash
$ rustup +nightly component add miri
$ cargo +nightly miri test
I will run `"/home/...../.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo" "install" "xargo"` to install a recent enough xargo. Proceed? [Y/n] y
    Updating crates.io index
  Downloaded xargo v0.3.22
...
```

**Comment by RalfJung** [comment]
Okay that is strange, something is trying to actually *build* code with `cfg(miri)` -- which cannot work as Miri provides some `extern` symbols that do not actually exist. Thanks for the report! I won't have time to dig into this before the week-end though.

@hyd-dev any idea what might be going on?

**Comment by hyd-dev** [comment]
Is `miri` passing `--cfg=miri` unconditionally?
https://github.com/rust-lang/miri/blob/7b2e325728e800664e55a7b91bac8b8b8378ab74/src/bin/miri.rs#L156
I can't find an `if` excluding "host" crates, so it seems like all build scripts and `proc-macro` crates are indeed always *built* with `cfg(miri)`.

Also, I can confirm `cfg(miri)` is set for build scripts and `proc-macro` crates by adding `#[cfg(miri)]` gated `compile_error!` to `test-cargo-miri/build.rs` and `test-cargo-miri/subcrate/src/lib.rs`.

**Comment by RalfJung** [comment]
Hm... yeah that's probably bad.^^ `MIRI_DEFAULT_ARGS` should probably only be set when building "for Miri", not when building for a proc-macro or `build.rs`.

**Comment by hyd-dev** [comment]
Adding an `if` above that `args.splice()` line that checks `--target` works: the "undefined symbol" error goes away.
<details>
<summary>FYI there's an "unsupported operation" error now</summary>

```
test cover_asn_to_rust_macro ... error: unsupported operation: `getcwd` not available when isolation is enabled
   --> /home/hyd-dev/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:140:17
    |
140 |             if !libc::getcwd(ptr, buf.capacity()).is_null() {
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `getcwd` not available when isolation is enabled
    |
    = help: pass the flag `-Zmiri-disable-isolation` to disable isolation
            
    = note: inside `std::sys::unix::os::getcwd` at /home/hyd-dev/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/unix/os.rs:140:17
    = note: inside `std::env::current_dir` at /home/hyd-dev/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/env.rs:47:5
note: inside `cover_asn_to_rust_macro` at tests/proc_macro_coverage_hack.rs:18:24
   --> tests/proc_macro_coverage_hack.rs:18:24
    |
18  |         let mut path = env::current_dir().unwrap();
    |                        ^^^^^^^^^^^^^^^^^^
note: inside closure at tests/proc_macro_coverage_hack.rs:14:1
   --> tests/proc_macro_coverage_hack.rs:14:1
    |
14  | / fn cover_asn_to_rust_macro() {
15  | |     walk_dir({
16  | |         // This code doesn't check much. Instead, it does macro expan...
17  | |         // tarpaulin measure code coverage for the macro.
...   |
21  | |     });
22  | | }
    | |_^
    = note: inside `<[closure@tests/proc_macro_coverage_hack.rs:14:1: 22:2] as std::ops::FnOnce<()>>::call_once - shim` at /home/hyd-dev/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
...
```
</details>

Preparing a PR now... 🚧
