### ISSUE TITLE
miri doesn't catch a violation of `&mut [u8]`'s validity invariants

### ISSUE THREAD

**Issue by anp** [rust-lang/miri#1762]
I *think* miri should fail on https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a79f547a85d6d09e52756c2da3c121f4 because it produces an invalid `&mut [u8]` on line 11 (see [context] for reference interpretation).

Should it be an error to produce a `&mut [u8]` that references uninit bytes?

[context]: https://github.com/gyscos/zstd-rs/issues/111#issuecomment-815090135

**Comment by anp** [comment]
I missed this bit from the README: "In particular, Miri does currently not check that integers/floats are initialized or that references point to valid data."

**Comment by RalfJung** [comment]
For the int/float part, https://github.com/rust-lang/miri/issues/1340 tracks adding an option to check that.

But for references, I don't currently have plans to implement that -- it would be prohibitively expensive. Moreover I am anyway lobbying for relaxing that UB rule. ;)

**Comment by anp** [comment]
Makes sense. I'm assuming it would still be prohibitive to treat slices differently than "thin" references.

I'd be interested to see a path for relaxing that rule, the ergonomics of single-write-only buffer usage is pretty rough. I have no idea what that'll look like, but you've got an eager audience :D.

**Comment by RalfJung** [comment]
> I'd be interested to see a path for relaxing that rule,

The discussion is at https://github.com/rust-lang/unsafe-code-guidelines/issues/77. ;)
To summarize, I think we should change the description of invalid references from
> A reference or Box<T> that is dangling, unaligned, or points to an invalid value.

to

> A reference or Box<T> that is dangling, unaligned, or points to an uninhabited type (i.e., a type with no valid value).
