### ISSUE TITLE
Bad error message on deallocation when the size is wrong

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1767]
This code is wrong because `ptr` has type `*mut u8` so the deallocation happens at the wrong size:
```rust
#![feature(allocator_api, slice_ptr_get)]

use std::alloc::{Allocator, Layout, System};

fn main() { unsafe {
    let ptr = System.allocate(Layout::new::<i32>()).unwrap().as_mut_ptr();
    ptr.write(5);
    let x = Box::from_raw_in(ptr, System);
    drop(x);
} }
```
However, the error message does not make this very clear:
```
error: Undefined Behavior: no item granting write access for deallocation to tag <2885> at alloc1396+0x1 found in borrow stack
  --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/alloc.rs:42:9
   |
42 |         libc::free(ptr as *mut libc::c_void)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no item granting write access for deallocation to tag <2885> at alloc1396+0x1 found in borrow stack
   |
   = help: this indicates a potential bug in the program: it performed an invalid operation, but the rules it violated are still experimental
   = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
```
it is true that the pointer provenance also makes this wrong, but maybe we could check the allocation size first and give the more clear error message.

**Comment by RalfJung** [comment]
Actually, we can't really give a better error than this -- `free` does not take a size parameter that could be used for a check!

**Comment by MikailBag** [comment]
What if Miri provided its own `std::alloc::System` implementation? That way it could verify allocation sizes better.

**Comment by RalfJung** [comment]
We don't really have infrastructure to do that -- and also it is somewhat questionable since `System` is *guaranteed* to use the system allocator, so you can e.g. use `libc::malloc` directly to allocate and later use `System` to free.

Miri *does* provide its own implementation for `Global` and checks everything precisely there.
