### ISSUE TITLE
Investigate `measureme` intergration

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/miri#1782]
The rust compiler uses [measureme](https://github.com/rust-lang/measureme) to profile query execution times. I think it would be relatively straightforward to integrate this into Miri to allow profiling the underlying program being executed. For example, we could generate a measureme 'event' when we start executing a MIR body, allowing us to generate a 'callstack' of functions that consume a large amount of execution time under Miri. This could be useful in tracking down issues like https://github.com/rust-lang/miri/issues/1780, where Miri is spending a large amount of time executing some particular part of the program.

Integrating this with Miri's virtual threads could be tricky, so we could limit this to the single-threaded case at first.

**Comment by RalfJung** [comment]
Does measureme have support for "multiple independent stacks"? This sounds like something that would also come up e.g. with concurrent execution of queries.

**Comment by bjorn3** [comment]
Measureme supports multiple threads. It doesn't natively support indicating that a thread is currently not scheduled, but you could add an event for that beginning when the thread stops running and stopping once it gets scheduled again.

**Comment by Aaron1011** [comment]
This was implemented in https://github.com/rust-lang/miri/pull/1791. We still night want to investigate some form of splint, to prevent the generated profiler output from becoming enormous on long runs.

**Comment by RalfJung** [comment]
What's a "splint"?

**Comment by Aaron1011** [comment]
That was supposed to say 'sampling' - I have no idea how autocorrect ended up with 'splint' :laug

**Comment by RalfJung** [comment]
Okay. So do you want to keep the issue open for that? The issue title and description don't match, so a new issue might be better. Or we could update those.

**Comment by RalfJung** [comment]
Closing this for now as "fixed by https://github.com/rust-lang/miri/pull/1791", if you think more could be done here please open a new issue that describes the details. :)
