### ISSUE TITLE
Possibly a bug in the stacked borrow checker of Miri

### ISSUE THREAD

**Issue by Medowhill** [rust-lang/miri#1796]
Hi.

```rust
struct A(u32);

fn main() {
    let a = A(0);
    let mut b = Box::new(a);
    let p = &*b as *const A;
    &mut *b;
    unsafe { &*p };
    std::mem::forget(b);
}
```

When I run the above code with Miri, it generates the following error:

```
error: Undefined Behavior: trying to reborrow for Unique at alloc1446, but parent tag <3014> does not have an appropriate item in the borrow stack
 --> src/main.rs:9:22
  |
9 |     std::mem::forget(b);
  |                      ^ trying to reborrow for Unique at alloc1446, but parent tag <3014> does not have an appropriate item in the borrow stack
```

which seems weird because passing `b` to `forget` should not cause any problems.

On the other hand, if I use `&mut` instead of `Box:new`, Miri generates an error for `&*p`, which seems correct because `&mut *b` invalidates `p`.

```rust
struct A(u32);

fn main() {
    let mut a = A(0);
    let b = &mut a;
    let p = &*b as *const A;
    &mut *b;
    unsafe { &*p };
    std::mem::forget(b);
}
```
```
error: Undefined Behavior: trying to reborrow for SharedReadOnly at alloc1428, but parent tag <untagged> does not have an appropriate item in the borrow stack
 --> src/main.rs:8:14
  |
8 |     unsafe { &*p };
  |              ^^^ trying to reborrow for SharedReadOnly at alloc1428, but parent tag <untagged> does not have an appropriate item in the borrow stack
```

When I add the `-Zmiri-track-raw-pointers` flag, Miri works properly (blaming `&*p`) on both programs.

I'm wondering whether this behavior of Miri is intended or not.

Thank you.

**Comment by RalfJung** [comment]
> which seems weird because passing b to forget should not cause any problems.

`forget` is a function like any other. So this is expected: passing a pointer to a function "uses" the pointer, and `forget` is a function.

This is why the docs explicitly [recommend using `ManuallyDrop`](https://doc.rust-lang.org/nightly/std/mem/fn.forget.html#relationship-with-manuallydrop) instead of `forget`.

**Comment by RalfJung** [comment]
> When I add the -Zmiri-track-raw-pointers flag, Miri works properly (blaming &*p) on both programs.

Yeah, on the first program Miri "confuses" the raw ptr `p` with some raw ptr internal to the `Box` implementation, and hence it puts the blame in the wrong place. This is exactly the kind of thing `-Zmiri-track-raw-pointers` treats differently, so this is expected.

**Comment by Medowhill** [comment]
Oh, I see. Thanks a lot for the quick response.

**Comment by RalfJung** [comment]
Sure, thanks for using Miri and reporting potential problems. :)
