### ISSUE TITLE
`extern crate std;` in a `#![no_std]` crate confuses Miri unless it's in the root module

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/miri#1821]
This program:
```rs
#![no_std]

fn main() {
    extern crate std;
}
```
Causes this error in Miri ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=81a82dcc0740bd324db6c6ffd1fe97d3)):
```
error: unsupported operation: can't call foreign function: signal
   --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/mod.rs:119:17
    |
119 |         assert!(signal(libc::SIGPIPE, libc::SIG_IGN) != libc::SIG_ERR);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function: signal
    |
    = help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
            
    = note: inside `main::std::sys::unix::init::reset_sigpipe` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/mod.rs:119:17
    = note: inside `main::std::sys::unix::init` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/mod.rs:62:5
    = note: inside `main::std::sys_common::rt::init` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/rt.rs:16:9
    = note: inside `main::std::rt::lang_start_internal` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:32:14
    = note: inside `main::std::rt::lang_start::<()>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
```

But the program runs fine if [`extern crate std;` is in the root module](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3b92981a84bfe92a3c8ce916db46b5a0) or [the crate is not `#![no_std]`](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6b04b979a68a49ad51fdc59232c35c15).

I encountered this issue when I was trying to access `std` by using `extern crate std;` in a `#[test]` of a `#![no_std]` crate.

I guess that this is because the stack frame is `main::std::...` in this case, while this code (cc #1263) only checks for `std::...`:
https://github.com/rust-lang/miri/blob/453affaaa1762a065d2857970b8333017211208c/src/shims/posix/foreign_items.rs#L504

**Comment by RalfJung** [comment]
> I guess that this is because the stack frame is main::std::... in this case, while this code (cc #1263) only checks for std::...:

Yes, I am pretty sure that's it.
How common is it to have `extern crate` not at the root module...?

**Comment by oli-obk** [comment]
> How common is it to have `extern crate` not at the root module...?

serde does this a lot
