### ISSUE TITLE
Support `#[start]`

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/miri#1825]
The [`start` feature](https://github.com/rust-lang/rust/issues/29633) allows to mark a function as the entry point and override the `start` lang item. It's currently [not supported in Miri](https://github.com/rust-lang/miri/pull/1823#discussion_r646066770):
```
error: internal compiler error: src/tools/miri/src/eval.rs:110:9: main function must not take any arguments

thread 'rustc' panicked at 'Box<Any>', compiler/rustc_errors/src/lib.rs:1007:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (c79419af0 2021-06-04) running on x86_64-unknown-linux-gnu
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b867b78dd787c573bdfb44c88fa856dc
https://github.com/rust-lang/miri/blob/ef998308805748289e46bce394a5d539b12b0118/src/eval.rs#L110

**Comment by RalfJung** [comment]
Interesting, so `#[start]` *must* have 2 arguments even though the start lang-item defined inside std has 0 arguments.
```
error[E0308]: `#[start]` function has wrong type
 --> src/main.rs:4:1
  |
4 | fn start() -> isize {
  | ^^^^^^^^^^^^^^^^^^^ incorrect number of function parameters
  |
  = note: expected fn pointer `fn(isize, *const *const u8) -> _`
             found fn pointer `fn() -> _`
```

**Comment by hyd-dev** [comment]
> the start lang-item defined inside std has 0 arguments

It's not the `start` lang item, but the `main` function, I think. The `start` lang item takes 3 arguments:
https://github.com/rust-lang/miri/blob/ef998308805748289e46bce394a5d539b12b0118/src/eval.rs#L195-L199

**Comment by RalfJung** [comment]
Ah, right. And then we pass a pointer to the main function. That one must indeed have no arguments or else the call you are citing above will not even be well-typed.
