### ISSUE TITLE
`#[no_mangle]` on associated functions

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/miri#1837]
This program works with `rustc`, but not in Miri ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=46fc298b46ff44093c45cab9fddb6650)):
```rs
struct AssocFn;

impl AssocFn {
    #[no_mangle]
    fn foo() {}
}

fn main() {
    extern "Rust" {
        fn foo();
    }
    AssocFn::foo();
    unsafe { foo() }
}
```

(And unlike [`#[no_mangle]` on normal functions](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=789b3f283ee6126f53939429103ed98d), if `AsocFn::foo` is not used *directly*, it also does not work with `rustc`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f1244afcdd26e2a28445f6e82ca46b50.)

cc https://github.com/rust-lang/miri/pull/1833#discussion_r651636695

**Comment by RalfJung** [comment]
> (And unlike #[no_mangle] on normal functions, if AsocFn::foo is not used directly, it also does not work with rustc: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f1244afcdd26e2a28445f6e82ca46b50.)

That sounds like a rustc bug?

**Comment by hyd-dev** [comment]
rust-lang/rust#76211 looks related. I have a [patch](https://github.com/rust-lang/rust/commit/ec30b12c19bb49f15c67038163ccbb592ecca7b7) that fixes my playground example above and non-public associated functions in `rlib` crates for rustc. I haven't tested it for Miri and the rustc issue yet.
