### ISSUE TITLE
doctests in libcore sometimes use wrong external crate

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1852]
Under some circumstances, Miri [goes all crazy on libcore doctests](https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/Cron.20Job.20Failure.202021-07-15): it seems to load two distinct copies of libcore and then hell breaks loose.

Specifically, this seems to be triggered when the code contains a variable that does not exist -- rustc will try to make szggestions for names to use, which can trigger loading external crates, which might be what is happening here.

**Comment by hyd-dev** [comment]
I think this issue belongs to https://github.com/rust-lang/miri-test-libstd. `cargo test` without Miri fails with same errors in that repository and all other libcore tests passed. It's caused by the `miri-test-libstd`-specific `core_miri_test` crate which is effectively another libcore.

**Comment by RalfJung** [comment]
Ah I see, thanks. I can't transfer issues there so I'll do that by hand.

**Comment by RalfJung** [comment]
Moved to https://github.com/rust-lang/miri-test-libstd/issues/4
