### ISSUE TITLE
[Low Priority Question] How to get Miri working with `-Zprofile` Flag?

### ISSUE THREAD

**Issue by YoshikiTakashima** [rust-lang/miri#1869]
Hi.

I have a niche use case that requires compiling and running a few
million test cases. I'm looking for ways to reduce the compile time
while running both coverage analysis (currently `grcov`) and miri.

I ultimately figured out that I can run `cargo test` with `-Zprofile`
and `cargo miri test` in an "normal" environment without having to run
`cargo clean` between the 2 commands. This saves significant amount of
time, and makes our project feasible.

However, my original plan was to:
1. Modify Miri at
   https://github.com/rust-lang/miri/blob/master/src/bin/miri.rs#L82-L91
   so that the compilation will continue after interpretation and
   write out interpretation results into a file (latter not
   implemented yet).

   ```rust
   if let Some(return_code) = miri::eval_main(tcx, entry_def_id, config) {
                // std::process::exit(
                //     i32::try_from(return_code).expect("Return value was too large!"),
                // );
            }
        });

        // compiler.session().abort_if_errors();

        Compilation::Continue
   ```
2. Run the modified Miri (`cargo miri test`) with the `grcov` flags given in:
   https://github.com/mozilla/grcov#example-how-to-generate-gcda-files-for-a-rust-project
   ```bash
   export CARGO_INCREMENTAL=0
   export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
   export RUSTDOCFLAGS="-Cpanic=abort"
   ```
3. Run the instrumented binary to gather coverage **without compiling
   twice.**
4. Gather both coverage and Miri interpretation result.

The original plan fails while compiling the target library:
```bash
error[E0463]: can't find crate for `profiler_builtins`
  |
  = note: the compiler may have been built without the profiler runtime

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I'm curious as to what is causing this failure?

While it is not a critical issue for us, the original plan is still
preferable as cuts the compile time, our largest bottleneck, in
half.

I understand this is a very odd use case, so I don't mind if you
prioritize other issues over this one.

**Comment by bjorn3** [comment]
> I'm curious as to what is causing this failure?

Miri needs to compile a separate sysroot to get MIR for all functions. This sysroot is probably compiled without profiler support.

> Run the instrumented binary to gather coverage without compiling twice.

Miri and regular execution require separately compiled programs. They use different sysroots and compilation options. You can use `CARGO_TARGET_DIR` to set a separate target dir for miri and regular execution, removing the need to clear anything (not that `cargo clean` should be necessary anyway I think), but you will need to compile once for regular execution and once for miri unless you avoid the `cargo miri` wrapper and manually compile a sysroot suitable for both miri and regular execution.

**Comment by YoshikiTakashima** [comment]
I also agree that `cargo clean` is not necessary. Even without
`CARGO_TARGET_DIR` Miri seems to generate a separate target directory
by default.

As of now, `cfg(miri)` and Windows targets are not in scope. We are
only targeting 64bit Linux and we don't generate any test cases with
`cfg(miri)`.

Thank you for the suggestions! They make sense to me as `cargo-miri
--print sysroot` does contain profiler libraries, but the
`~/.cache/miri/HOST/` does not. I'll give them a try.

**Comment by RalfJung** [comment]
> As of now, cfg(miri) and Windows targets are not in scope. We are
only targeting 64bit Linux and we don't generate any test cases with
cfg(miri).

What I am saying is that there are `cfg(miri)` in the standard library and other crates (e.g. hashbrown). The Miri sysroot is build with `cfg(miri)`. If you want to use a single build (and hence a single sysroot) you thus will end up building a regular binary with `cfg(miri)`, which is an entirely untested and unsupported configuration.

> `cargo-miri --print sysroot`

`cargo-miri --print sysroot` does not really make much sense as a command... (and it shows an ICE for me). Maybe you mean `miri --print sysroot`, but that is just the default rustc sysroot which is unsuited for Miri. `cargo miri` sets an appropriate sysroot when invoking `miri`.

**Comment by YoshikiTakashima** [comment]
Thanks for the clarification; I agree that would not be avoidable.

> `cargo-miri --print sysroot`

is a typo. I meant `cargo-miri rustc --print sysroot`. This prints out the same thing as 

> `miri --print sysroot`

**Comment by RalfJung** [comment]
This is not very actionable on our side, so I am going to close the issue. There currently are no plans to officially support using the Miri sysroot for building a real executable. If concrete questions come up about how Miri's sysroot handling works, feel free to reopen, open a new issue, or ask on Zulip!
