### ISSUE TITLE
OOM when testing gimli with miri

### ISSUE THREAD

**Issue by philipc** [rust-lang/miri#1906]
When testing [gimli](https://github.com/gimli-rs/gimli/):
```
$ rustc +nightly  --version
rustc 1.58.0-nightly (db062de72 2021-11-01)
$ cargo +nightly miri --version
miri 0.1.0 (9c18177 2021-10-26
$ cd gimli && cargo +nightly miri test test_advance
```
I get an OOM:
```
Nov 02 15:16:47 fedora earlyoom[782]: mem avail:    55 of 15859 MiB ( 0.35%), swap free:  575 of 8191 MiB ( 7.03%)
Nov 02 15:16:47 fedora earlyoom[782]: low memory! at or below SIGTERM limits: mem  2.52%, swap 10.00%
Nov 02 15:16:48 fedora earlyoom[782]: sending SIGTERM to process 17322 uid 1000 "miri": badness 1159, VmRSS 12042 MiB
Nov 02 15:16:48 fedora earlyoom[782]: process exited after 0.1 seconds
```
I'm not sure if this kind of problem is expected for some tests.

**Comment by RalfJung** [comment]
Yeah, Miri can use up tons of RAM. Cc https://github.com/rust-lang/miri/issues/1367

Does `MIRIFLAGS="-Zmiri-disable-stacked-borrows"` help? That will of course mean Miri can no longer detect aliasing violations. You could also try figuring out which test is being run to use up all that RAM, and try reducing the iteration count or data size for that test.

**Comment by philipc** [comment]
`MIRIFLAGS="-Zmiri-disable-stacked-borrows"` does help, but instead I'll use `#[cfg_attr(miri, ignore)]`, since I don't particularly need to run this test under miri. Thanks!
