### ISSUE TITLE
cargo-miri does not support target wasm32-unknown-unknown

### ISSUE THREAD

**Issue by dvc94ch** [rust-lang/miri#1916]
this works very nicely: `cargo +nightly miri test --target mips64-unknown-linux-gnuabi64` however `wasm32-unknown-unknown` doesn't.

```sh
cargo +nightly miri test --target wasm32-unknown-unknown
   Compiling anyhow v1.0.45
   Compiling rust-ffi v0.1.0 (/home/dvc/rust-ffi)
    Finished test [unoptimized + debuginfo] target(s) in 0.82s
     Running unittests (target/miri/wasm32-unknown-unknown/debug/deps/rust_ffi-4a0413132da28d8a.wasm)
fatal error: `cargo-miri` called with unexpected first argument `/home/dvc/rust-ffi/target/miri/wasm32-unknown-unknown/debug/deps/rust_ffi-4a0413132da28d8a.wasm`; please only invoke this binary through `cargo miri`
error: test failed, to rerun pass '--lib'
```

**Comment by bjorn3** [comment]
I think we need to do the same as for windows `.exe` for wasm `.wasm` at https://github.com/rust-lang/miri/blob/b258eb3c27a87320c35860dc233a656838f65003/cargo-miri/bin.rs#L708-L710

**Comment by RalfJung** [comment]
Yeah I honestly have no ideas which targets work and which do not, it's kind of a case-by-case thing.^^

This issue is probably similar to https://github.com/rust-lang/miri/issues/1867.

**Comment by RalfJung** [comment]
I know basically nothing about wasm targets and wouldn't even know what to test, so I marked this as "help-wanted".

**Comment by workingjubilee** [comment]
If it is acceptable to add a dependency, Miri could simply include the `wasmtime` crate as an embedding and simply execute the wasm file directly from Rust, like so:

https://docs.wasmtime.dev/lang-rust.html

**Comment by RalfJung** [comment]
That's not really what Miri is expected to do, though -- it should *interpret* the code, not run it like nirmal. Running it in wasmtime will not run all of the extra checks Miri is doing to detect UB.

**Comment by workingjubilee** [comment]
Ah, no idea then~!

**Comment by RalfJung** [comment]
This should be fixed by https://github.com/rust-lang/miri/pull/2685.
