### ISSUE TITLE
Shl/Shr should throw UB on too large shift

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#1920]
The LLVM docs for `shl` say

>  If op2 is (statically or dynamically) equal to or larger than the number of bits in op1, this instruction returns a poison value.

However, the CTFE/Miri implementation of shl/shr currently just [truncates the shift amount](https://github.com/rust-lang/rust/blob/c5fc2609f0f81698616734e22adee9b9ed67f729/compiler/rustc_const_eval/src/interpret/operator.rs#L133). In rustc-generated MIR this can never happen since there always is a check being emitted, but we should still make sure to implement all UB checks for this operation correctly -- and the `simd_shl` intrinsic also exposes direct access to this operation, making it possible to trigger this UB. (I plan to add tests for this.)

I just hope we didn't miss any other MIR operations which compile ti LLVM arithmetic operations that can produce poison/undef/UB... (we do check for div-by-zero, of course). Cc @rust-lang/wg-llvm

**Comment by nagisa** [comment]
To my knowledge `Div`, `Rem` and the two shifts are the only MIR-native operations that have validity invariants. We also have `unchecked` methods for various operations, including those same shifts which expose these invariants to the users.

**Comment by bjorn3** [comment]
> In rustc-generated MIR this can never happen since there always is a check being emitted

It can with `-Zforce-overflow=checks=no`. The shift amounts need to be truncated in that case: https://github.com/rust-lang/rust/blob/22c2d9ddbf356bcdb718e88ca6ee3665e1e42690/src/test/ui/mir/mir_overflow_off.rs#L2

**Comment by RalfJung** [comment]
> We also have unchecked methods for various operations, including those same shifts which expose these invariants to the users.

Miri currently implements those by executing the MIR operation and then raising UB if an overflow is indicated.
For div and rem, AFAIK the unchecked intrinsics have a different validity invariant than the MIR-native operations: unchecked_div also makes overflow UB, such as in `int_min / -1`.

> It can with -Zforce-overflow=checks=no. The shift amounts need to be truncated in that case

I assume truncation is happening as explicit MIR operation then (like the div-by-zero checks) -- or do the codegen backends implicitly insert truncation?

**Comment by bjorn3** [comment]
> I assume truncation is happening as explicit MIR operation then (like the div-by-zero checks) -- or do the codegen backends implicitly insert truncation?

It is implicitly added.

```rust
pub fn foo(shift_amount: u8) -> bool {
    if 1 << shift_amount != 2_u8 {
        return false;
    }
    if 2 >> shift_amount != 1_u8 {
        return false;
    }
    true
}
```
gives the following MIR with `-Zforce-overflow-checks=no`:

```rust
fn foo(_1: u8) -> bool {
    debug shift_amount => _1;            // in scope 0 at /app/example.rs:1:12: 1:24
    let mut _0: bool;                    // return place in scope 0 at /app/example.rs:1:33: 1:37
    let mut _2: u8;                      // in scope 0 at /app/example.rs:2:8: 2:25
    let mut _3: u8;                      // in scope 0 at /app/example.rs:2:13: 2:25
    let mut _4: u8;                      // in scope 0 at /app/example.rs:5:8: 5:25
    let mut _5: u8;                      // in scope 0 at /app/example.rs:5:13: 5:25

    bb0: {
        _3 = _1;                         // scope 0 at /app/example.rs:2:13: 2:25
        _2 = Shl(const 1_u8, move _3);   // scope 0 at /app/example.rs:2:8: 2:25
        switchInt(move _2) -> [2_u8: bb2, otherwise: bb1]; // scope 0 at /app/example.rs:2:8: 2:33
    }

    bb1: {
        _0 = const false;                // scope 0 at /app/example.rs:3:16: 3:21
        goto -> bb5;                     // scope 0 at no-location
    }

    bb2: {
        _5 = _1;                         // scope 0 at /app/example.rs:5:13: 5:25
        _4 = Shr(const 2_u8, move _5);   // scope 0 at /app/example.rs:5:8: 5:25
        switchInt(move _4) -> [1_u8: bb4, otherwise: bb3]; // scope 0 at /app/example.rs:5:8: 5:33
    }

    bb3: {
        _0 = const false;                // scope 0 at /app/example.rs:6:16: 6:21
        goto -> bb5;                     // scope 0 at no-location
    }

    bb4: {
        _0 = const true;                 // scope 0 at /app/example.rs:8:5: 8:9
        goto -> bb5;                     // scope 0 at /app/example.rs:9:2: 9:2
    }

    bb5: {
        return;                          // scope 0 at /app/example.rs:9:2: 9:2
    }
}
```

The reason I know about this test in the first place is because it used to fail with cg_clif due to incorrectly implementing this truncating behavior.

**Comment by RalfJung** [comment]
So from that it seems like Miri is doing the right thing already -- but I can't find the code in the LLVM backend that does this truncation. [Here](https://github.com/rust-lang/rust/blob/a3b9405ae7bb6ab4e8103b414e75c44598a10fd2/compiler/rustc_codegen_llvm/src/builder.rs#L268) it looks like it is just constructing a single `Shl` for the MIR binop.

**Comment by bjorn3** [comment]
The masking is done in cg_ssa: https://github.com/rust-lang/rust/blob/a3b9405ae7bb6ab4e8103b414e75c44598a10fd2/compiler/rustc_codegen_ssa/src/common.rs#L131-L158

**Comment by RalfJung** [comment]
Ah, there it is, thanks! I will add a comment in the Miri/CTFE code explaining this.

I assume the simd shift intrinsics directly use the underlying LLVM operation though, and thus do *not* implicitly truncate and *do* require a UB check here... so our SIMD operations are inconsistent with our MIR operations. :/

**Comment by bjorn3** [comment]
Indeed. It directly exposes the LLVM operation.

```rust
#![feature(platform_intrinsics, repr_simd)]

extern "platform-intrinsic" {
    fn simd_shl<T>(a: T, amount: T) -> T;
}

#[repr(simd)]
#[derive(Copy, Clone)]
pub struct u8x8([u8; 8]);

pub fn foo(a: u8x8) -> u8x8 {
    unsafe {
        simd_shl(a, a)
    }
}
```

```llvm
define void @_ZN7example3foo17he8b5d79f940e09f4E(<8 x i8>* noalias nocapture sret(<8 x i8>) dereferenceable(8) %0, <8 x i8>* noalias nocapture dereferenceable(8) %a) unnamed_addr #0 !dbg !6 {
  %_2 = load <8 x i8>, <8 x i8>* %a, align 8, !dbg !10
  %_3 = load <8 x i8>, <8 x i8>* %a, align 8, !dbg !11
  %1 = shl <8 x i8> %_2, %_3, !dbg !12
  store <8 x i8> %1, <8 x i8>* %0, align 8, !dbg !12
  br label %bb1, !dbg !12

bb1:                                              ; preds = %start
  ret void, !dbg !13
}
```

**Comment by RalfJung** [comment]
Okay, that is good to know. Cc @workingjubilee this might be interesting to know for the SIMD folks, though I am not sure if you want to change anything here -- the SIMD shift intrinsics are not consistent with the MIR shift primitives. This will require extra care in a Miri implementation of those intrinsics, and could also be potentially confusing for other codegen backends.

AFAIK shifts are the only MIR primitive that does not directly correspond to an LLVM primitive, so I hope this is the only SIMD vs MIR inconsistency.

**Comment by oli-obk** [comment]
Since all backends need to do the truncation, how about we make it explicit in MIR and stop doing it in the backends?

**Comment by RalfJung** [comment]
So basically, we'd make too large shifts UB in the MIR -- seems fine to me, if someone wants to push through that change.

**Comment by bjorn3** [comment]
In Cranelift ishl/ushr/sshr are specified as masking themself. (Cranelift tries to avoid UB as much as possible.) Adding the masking at MIR level would result in two maskings for cg_clif.

**Comment by oli-obk** [comment]
OK then let's proceed with masking in the backends

**Comment by RalfJung** [comment]
That could also be handled by an optimization in cranelift though.

No strong opinion here, but it would be nice to make the MIR binops and intrinsics consistent (and that seems to be true for any backend that plans to implement simd_shl/shr).

**Comment by bjorn3** [comment]
> No strong opinion here, but it would be nice to make the MIR binops and SIMD intrinsics consistent

I agree.

**Comment by RalfJung** [comment]
I was talking about making the 'primitive operations' that Miri/codegen see consistent -- so we have two options:
- Make the SIMD intrinsic also well-defined for too large shifts. This would require a vectored version of the truncation that the LLVM backend currently performs -- not sure if that is a good idea, though maybe given that there already is a bounds check before the intrinsic is invoked, this will not be usable in high-throughput SIMD code anyway?
- Make the MIR binop UB for too large shifts. This would require MIR building to explicitly perform truncation, leading to redundant truncation in cranelift -- not sure how good the cranelift optimizer is at removing the double-truncation.

**Comment by workingjubilee** [comment]
To be honest, I regard all the compilers, including LLVM, as a bit silly here, because the assembly instructions in question tend to have a simple semantic of "if the arg is too big, then just set or clear all bits according to the existing semantics". This would be roughly equivalent to

```rust
fn $shift_op(self, rhs: U) -> T {
    let shift = cmp::max(mem::size_of<T> * 8 -1), rhs as _);
    $shift_impl(self, shift)
}
```

With the vectorized version simply doing that on a per-lane basis.

This may not actually be true on all machines LLVM targets, of course, so maybe LLVM shouldn't change that, but I have looked at **several** copies of this instruction on several different modern architectures, and just like Rust's other operators compile to, and matches the semantics of, a "just lower it to `add reg0, reg1, reg2`, don't worry too hard about optimizing it in isel", I don't quite see why Rust's shl, ashr, and lshr don't do the same.

**Comment by workingjubilee** [comment]
Ah, so there's encodings for both that and a formally saturating shift (so `1 << BITS` will set all, I think) for Neon, but x86 does masking for the scalar shift, but on PowerPC the vector shifts also mask, now that I actually look. I see, I see, that **would** make things more vexing to lower without UB or something indeed.

**Comment by workingjubilee** [comment]
Anyways, now that I have finished being distracted by assembly manuals:

> Make the SIMD intrinsic also well-defined for too large shifts. This would require a vectored version of the truncation that the LLVM backend currently performs -- not sure if that is a good idea, though **maybe given that there already is a bounds check before the intrinsic is invoked**, this will not be usable in high-throughput SIMD code anyway?

As far as the fact that there is a bounds check in the existing version of our implementation, I would not assume that this is considered a desirable feature by us. We have a few bounds checks in our current implementation simply because we did not yet find another route, because we are still at some edges negotiating our semantics, and because we do not want users to find interesting ways to discover UB while we hammer out such details.

For most operators, we have been implementing assuming an "always wrapping" semantic: No overflow checks. This also mirrors the behavior of most intrinsics users may be familiar with. So, in a way, that's a vote "for" Cranelift's interpretation, but at the same time it's not clear what we would most like do for the shift operators due to the varying machine behavior.

**Comment by RalfJung** [comment]
> For most operators, we have been implementing assuming an "always wrapping" semantic: No overflow checks. This also mirrors the behavior of most intrinsics users may be familiar with. So, in a way, that's a vote "for" Cranelift's interpretation, but at the same time it's not clear what we would most like do for the shift operators due to the varying machine behavior.

Also, machine behavior does not matter all that much when what we are concerned with is generating LLVM IR.

> simd_and is pretty efficient tho' on most arches, so it's not like I am going to lose sleep.

So you are saying, changing the LLVM backend to lower the `simd_shl` intrinsic into an LLVM SIMD `and` for masking followed by `shl` for the actual shift would be reasonable (and then you could remove the panic from the `core::simd` wrapper)?

That would also work well from a consistency perspective -- and it might be better for `core::arch`'s shl to be panic-free, since presumably its arithmetic operations are also panic-free (except for division and rem, of course).

**Comment by workingjubilee** [comment]
> Also, machine behavior does not matter all that much when what we are concerned with is generating LLVM IR.

Well yes, but when at least one of the (virtual) machine implementers is in the conversation, discussing the implementation felt relevant, so I decided to embarrass myself by misremembering exactly how many architectures implement vector `shl`/`shr` with an inherently mostly-unwrapped mechanism. :^)

> So you are saying, changing the LLVM backend to lower the simd_shl intrinsic into an LLVM SIMD and for masking followed by shl for the actual shift would be reasonable (and then you could remove the panic from the core::simd wrapper)?

Prooobably. I am not sure if using an appropriate `and` mask would have consensus, but at the moment I think it's on the table as an option, especially if @bjorn3 thinks that would help Cranelift in lowering. I will bring it up, as I was considering revising the wrapper to use `simd_and` (and thereby drop the panic) anyways.

At the moment, `std::arch` links directly against the "architecture intrinsics" for AVX512.

**Comment by RalfJung** [comment]
I opened https://github.com/rust-lang/rust/issues/91237 for discussing the inconsistency -- this is no longer just a Miri issue.
