### ISSUE TITLE
Cargo miri failes to build why am i getting this error?

### ISSUE THREAD

**Issue by jayhill365** [rust-lang/miri#1948]
<img width="1007" alt="Screen Shot 2021-12-21 at 6 22 34 PM" src="https://user-images.githubusercontent.com/19259608/147024217-fedf89a8-942e-44c3-9447-390309b0fc75.png">

**Comment by jayhill365** [comment]
<img width="832" alt="Screen Shot 2021-12-21 at 6 29 03 PM" src="https://user-images.githubusercontent.com/19259608/147024949-7dbc11c2-08cd-473e-8340-ce95dd189856.png">


^^^^ after running ./miri build

**Comment by jayhill365** [comment]
<img width="269" alt="Screen Shot 2021-12-21 at 6 31 59 PM" src="https://user-images.githubusercontent.com/19259608/147025156-8dd11319-53f3-4187-a8f9-6757ae681f1f.png">
^^^^^^^^ ./miri check produces above
<img width="151" alt="Screen Shot 2021-12-21 at 6 32 40 PM" src="https://user-images.githubusercontent.com/19259608/147025219-5ae9532b-b9d8-41a5-8160-0b168bb7ba0e.png">
<img width="1308" alt="Screen Shot 2021-12-21 at 6 33 10 PM" src="https://user-images.githubusercontent.com/19259608/147025269-21017044-85dd-442d-aa07-330c4a21b39c.png">
<img width="826" alt="Screen Shot 2021-12-21 at 6 33 34 PM" src="https://user-images.githubusercontent.com/19259608/147025309-8a892a42-cdc4-44c0-a736-41e76ab22ab6.png">

**Comment by bjorn3** [comment]
Please follow the instructions at https://github.com/rust-lang/miri/blob/master/CONTRIBUTING.md#preparing-the-build-environment Miri can't be compiled on stable. Also if you only want to use miri rather than develop it, you can add the miri component to the nightly toolchain. `rustup component add miri --toolchain nightly` and then `cargo +nightly miri`.

**Comment by jayhill365** [comment]
Hey @ralfJung thanks for responding here 

after runnung rustup component add miri --toolchain nightly I receive 
<img width="261" alt="Screen Shot 2021-12-22 at 3 00 05 PM" src="https://user-images.githubusercontent.com/19259608/147164470-08fbe4f7-8b9b-4037-9887-06042a98305a.png">
and then cargo +nightly miri setup produces 

<img width="457" alt="Screen Shot 2021-12-22 at 3 02 38 PM" src="https://user-images.githubusercontent.com/19259608/147164585-b75d1b08-b02f-45bf-af5d-59ad9df2f5d6.png">

Seems to be working, so far I will update this thread and follow the instructions above to see if this fixes my issue.

**Comment by jayhill365** [comment]
Also i'm very interested in learning and developing miri as well 👍
