### ISSUE TITLE
Find a way to test MIR code that rustc won't emit

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#196]
It would be nice to be able to test miri against known-bad MIR code -- like, code that uses `StorageLive`/`StorageDead` incorrectly, just to make sure that miri catches such errors. Some more examples will come come up with the stuff about unsafe code guidelines that I'm working on.

It seems that we need something like a MIR parser for this, though?

**Comment by eddyb** [comment]
One way you could do this is use valid Rust syntax and have an AST-to-MIR transform (maybe use HIR to get types that you can use `rustc_typeck::astconv` on).

**Comment by oli-obk** [comment]
We now have `#[custom_mir]`, so there's no need to keep this issue open
