### ISSUE TITLE
Rename Posix → Unix

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2012]
In Miri, we use the term "POSIX" to refer to the functionality shared between Linux and macOS (and soon, Android: https://github.com/rust-lang/miri/pull/2011). I used that term because those files started essentially as an implementation of a small part of the POSIX API.

However, in the Rust standard library, the term used for grouping those platforms is "Unix", and there also is `target_family = "unix"`. So I think it would make to rename "posix" to "unix" in the Miri codebase. This should be an easy change. However, it should wait until #2011 lands to reduce merge conflicts.

**Comment by InfRandomness** [comment]
I am willing to do this, I'll make a draft PR that can be merged after #2011 landed

**Comment by RalfJung** [comment]
No rustbot in this repo, but we can track this by hand. :)  Thanks for chiming in!

#2011 is still a draft; @landaire know best whether it makes sense to wait for that or whether we can go ahead and let them deal with the merge conflicts as they arise.

**Comment by landaire** [comment]
I apologize for the delay on #2011. I've been busier than expected recently... I can deal with merge conflicts as they come.

**Comment by InfRandomness** [comment]
> I apologize for the delay on #2011. I've been busier than expected recently... I can deal with merge conflicts as they come.

No worries 😉
