### ISSUE TITLE
ratelimit_meter 5.0.0 tests fail under Miri but pass normally (due to a clock problem?)

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#2034]
Under Miri, I see this
```
test expiration ... FAILED

failures:

---- expiration stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `["foo"]`,
 right: `[]`', tests/keyed.rs:57:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is the failing assertion: https://github.com/antifuchs/ratelimit_meter/blob/9a5e443a6f0ea9df8972b3bb00f24a729a3ecf2a/tests/keyed.rs#L61

This crate is UB under Stacked Borrows with raw pointer tracking, but I don't think that's relevant. My extra debug assertions PR for can't coax a crash out of it, so I don't think there is anything terribly obviously wrong here.

What I can tell is that there is a lot of clock access on the scene. This might be revealing a clock bug in Miri.

I have not attempted to minimize this. It should probably be minimized.

**Comment by bjorn3** [comment]
Try running with `MIRIFLAGS="-Zmiri-disable-isolation"`. Without this flag the clock will probably always return the same value.

**Comment by saethlin** [comment]
The clock isn't accessible at all in Miri by default. The flag is required to run the test in question.

**Comment by RalfJung** [comment]
My guess would be that Miri is so extremely slow that things go wrong somewhere...

**Comment by saethlin** [comment]
Oh wow I think you're right. The test has a comment about "2 seconds plus change" which seems to permit an extra 100 ms of timing lag in the implementation. If I increase that to 220 ms, the test passes. ARGH
