### ISSUE TITLE
cargo-miri does not support .json target files

### ISSUE THREAD

**Issue by budde25** [rust-lang/miri#2053]
rustc 1.61.0-nightly (76d770ac2 2022-04-02)
When I run `cargo miri test` with a custom target I get an error

If I run `cargo miri test --target ./x86_64-os.json` I get
```
error: target path "./x86_64-os.json" is not a valid file

Caused by:
  No such file or directory (os error 2)
fatal error: failed to run xargo
```
same error if I try this`cargo miri test --target x86_64-os.json`

then I tried a fully qualified path `cargo miri test --target /home/budd/Code/os/x86_64-os.json`
and it said 
```
error: Xargo doesn't support files as an argument to --target. Use `--target foo` instead of `--target foo.json`.
note: run with `RUST_BACKTRACE=1` for a backtrace
fatal error: failed to run xargo
```
finally I tried without the .json as `cargo miri test --target /home/budd/Code/os/x86_64-os` and got a panic
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', src/tools/cargo/src/cargo/core/compiler/fingerprint.rs:1290:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: `"/home/budd/.rustup/toolchains/nightly-2022-04-03-x86_64-unknown-linux-gnu/bin/cargo" "check" "--release" "--manifest-path" "/tmp/xargo.buKrTnrXV4hZ/Cargo.toml" "--target" "/home/budd/Code/os/x86_64-os" "-p" "std"` failed with exit code: Some(101)
note: run with `RUST_BACKTRACE=1` for a backtrace
fatal error: failed to run xargo
```

If custom target files are not supported by miri I think the error should be more clear, especially the first one that just said file not valid.
Also this target works perfectly fine without miri.

the x86_64-os.json is bellow.
```json
{
  "llvm-target": "x86_64-unknown-none-gnu",
  "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
  "arch": "x86_64",
  "target-endian": "little",
  "target-pointer-width": "64",
  "target-c-int-width": "32",
  "os": "none",
  "executables": true,
  "linker-flavor": "ld.lld",
  "linker": "rust-lld",
  "panic-strategy": "abort",
  "disable-redzone": true,
  "features": "-mmx,-sse,+soft-float",
  "pre-link-args": {
    "ld.lld": [
      "--script=src/arch/x86_64/linker.ld"
    ]
  }
}
```

**Comment by RalfJung** [comment]
I know basically nothing about custom target JSON files so I *guess* they are not supported, probably?

But it looks like they are unsupported by xargo and hence by extension also unsupported by Miri. A better error would indeed be nice; I am not sure what the best way would be to detect that situation though since the cargo-miri wrapper that invokes xargo doesn't know anything about targets.

**Comment by bjorn3** [comment]
Try passing the absolute path to the json file.

**Comment by RalfJung** [comment]
We could probably look for a `.json` suffix here:

https://github.com/rust-lang/miri/blob/fb01df538e30cf63bdcbadad61828940ca8ec578/cargo-miri/bin.rs#L432

> Try passing the absolute path to the json file.

They did that, `/home/budd/Code/os/x86_64-os.json` did not work either.

**Comment by berkus** [comment]
Why does miri use xargo, instead of say, `-Z build-std`?

**Comment by RalfJung** [comment]
1. Miri's use of xargo predates `-Z build-std`.
2. Miri needs to build a *sysroot* that is usable for a range of crates, not just a stdlib for a particular crate. This has some subtle differences, in particular around unwinding: a sysroot contains *both* panic_abort and panic_unwind, but `-Z build-std` will only build one of them.

If someone can figure out how to build reusable sysroots with `-Z build-std`, I'd be happy for Miri to drop its dependency on xargo.

**Comment by RalfJung** [comment]
Status update: we are not using xargo any more, we are using https://github.com/RalfJung/rustc-build-sysroot. However that does not support target json files either. so this is probably blocked on https://github.com/RalfJung/rustc-build-sysroot/issues/4.
