### ISSUE TITLE
forcable cargo miri setup

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/miri#2085]
if I update my nightly and try to run `cargo miri setup` to get the latest std, miri refuses to do anything because `WARNING: MIRI_SYSROOT already set, not doing anything.`.

`MIRI_SYSROOT` is part of my `~/zsh.rc` so I don't have to set it manually every time :smile: 

in order to work around I have to
```
unset MIRI_SYSROOT
cargo miri setup
```
It would be handy to have some kind of `cargo miri setup --force` command which works even if `MIRI_SYSROOT` is present. :upside_down_face:

**Comment by RalfJung** [comment]
Hm, the reasoning for this is that if you set MIRI_SYSROOT then you are using some other way to prepare the sysroot and the automatism shouldn't mess with that.

We also cannot really build the sysroot into whatever location you gave, we always put it in a default place if we build it in `cargo miri setup`. So things would behave really weird if we just kept building -- we'd either ignore the env var (so why did you even set it) or ignore the newly built sysroot (so why would we even build it).

May I ask why you have to ever set that env var? I work on Miri a lot and I have not set this variable for *years*.

**Comment by RalfJung** [comment]
I have clarified the README to say that MIRI_SYSROOT should only be set if you do not want to use the automatically created sysroot. That means `cargo miri setup` + setting MIRI_SYSROOT as a combination doesn't make sense: the first says to auto-create a sysroot, but the latter says you don't want to use the auto-created sysroot.

So, my inclination is to close this as not-a-bug, but I'd still like to hear from @matthiaskrgr about why you have set this env var in the first place.

**Comment by matthiaskrgr** [comment]
Ah I see that this works without having MIRI_SYSROOT set manually :)
(I had that set up a couple of years ago probably) great!
