### ISSUE TITLE
Invalid alignment to posix_memalign is documented as an error condition not a precondition

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#2099]
POSIX says:
> The posix_memalign() function shall fail if:
[EINVAL]
The value of the alignment parameter is not a power of two multiple of sizeof(void *).
[ENOMEM]
There is insufficient memory available with the requested alignment.

and POSIX further says this:
> The ERRORS section on each reference page specifies which error conditions shall be detected by all implementations (shall fail") and which may be optionally detected by an implementation (may fail"). If no error condition is detected, the action requested shall be successful. If an error condition is detected, the action requested may have been partially performed, unless otherwise stated.

(encountered running `cargo miri test` in `aligned_alloc==0.1.3`)

**Comment by RalfJung** [comment]
Ah, we should then probably replace the `throw_ub` by returning gracefully with an error code. Good catch!

**Comment by saethlin** [comment]
AddressSanitizer has the same behavior which is making me doubt this reading of POSIX. Did Miri inherit this behavior from ASan?

**Comment by RalfJung** [comment]
> Did Miri inherit this behavior from ASan?

No, I just didn't read the docs and used the same checks as our other allocation functions. :shrug: 

The docs seem pretty clear. Has this been reported to the ASan devs?

**Comment by 5225225** [comment]
I'm working on this btw. Will get a PR up in a bit, just writing the tests.
