### ISSUE TITLE
WinApi SYSTEM_INFO `dwPageSize` always returning 0

### ISSUE THREAD

**Issue by V0ldek** [rust-lang/miri#2136]
This is a rather weird issue I reported first in the [`page_size`](https://github.com/Elzair/page_size_rs/issues/7) crate. When running Miri with any of the Tier 1 Windows targets the crate reports page size 0, which is a fatal error for my use, where I want to allocate aligned to the page boundary.

This is witnessed most easily by [the GitHub Action run](https://github.com/V0ldek/aligners/runs/6526456428?check_suite_focus=true). My code panics when the page size is not a power of two, so in this case it crashes with:

```bash
thread 'main' panicked at 'detected page size 0 that is not a power of two, this is unsupported', src/alignment.rs:111:21
```

The page size query works perfectly well for Unix targets.

## Replication

This can be confirmed by referencing `page_size` and asking for it like this:

```rust
fn main() {
    println!("Page size: {}", page_size::get());
}
```
and running Miri:

```bash
cargo +nightly miri run --target x86_64-pc-windows-gnu
```

resulting in:

```plain
> Page size: 0
```

Whereas running it without Miri gives the correct result (on my PC it's 4KB):

```bash
cargo run
```
```plain
> Page size: 4096
```

If it matters, the host OS seems to not affect this, the issue is the same running the command both from Unix and Windows.

**Comment by RalfJung** [comment]
Miri's Windows support is a big hack, barely enough to get our own test suite to pass. Windows is effectively at best a Tier 2 target in Miri. (Not that we have a formal target policy.)

Basically, I don't have a lot of time to spend on Windows support in Miri myself. But help with the Windows support would certainly be appreciated. :D

This is probably caused by some code in [this file](https://github.com/rust-lang/miri/blob/master/src/shims/windows/foreign_items.rs), though I do not know which function is responsible.

**Comment by V0ldek** [comment]
That would certainly be this code:

https://github.com/rust-lang/miri/blob/b96610b3de5bc9fd346d90700ba881aca8d503f0/src/shims/windows/foreign_items.rs#L112-L126

If I read it correctly, it fills the entire SYSTEM_INFO structure with zeroes and then sets a few selected fields to actual values.

**Comment by V0ldek** [comment]
Hah, but the `page_size` crate just calls the WinApi SYSTEM_INFO :D

https://github.com/Elzair/page_size_rs/blob/290f3da944d0f1c86612172ec84958a9dbf910ac/src/lib.rs#L162-L170

**Comment by RalfJung** [comment]
Okay, this should be easy to fix then. :)
If someone wants to work on this, let me know and I can provide more details if needed.

**Comment by V0ldek** [comment]
I don't see why that'd make it easy, doesn't that mean we couldn't use `page_size` for this?

- `page_size` calls WinApi `GetSystemInfo`, which with Miri resolves to the code you linked before
- Miri would call `page_size` to get the response
- `page_size` calls WinApi `GetSystemInfo`, which with Miri resolves to the same code as before...

**Comment by bjorn3** [comment]
Miri would call page_size as native dependency rather than as interpeted code which means that GetSystemInfo ends up as native system call rather than in the miri shim.

**Comment by V0ldek** [comment]
@bjorn3 

Okay, so I just don't know how Miri works 😅 

I'd happily work on this then, it'd allow me to test my crate on more platforms with Miri.

**Comment by V0ldek** [comment]
@RalfJung 

Actually, I can ask more focused questions.

1. How would I test this change when implemented?
2. Looking at the code for num_cpus I've stumbled upon this:

https://github.com/rust-lang/miri/blob/b96610b3de5bc9fd346d90700ba881aca8d503f0/src/machine.rs#L34-L38

I see that these constants are also used in posix shim to set some variables. Should we also do justice to this FIXME and switch this to the actual underlying page size?

**Comment by RalfJung** [comment]
> I don't see why that'd make it easy, doesn't that mean we couldn't use page_size for this?

Sorry, what I meant is call page_size in a test inside Miri to ensure that we are implementing whatever APIs it needs on the platforms we support.

> Miri would call page_size as native dependency rather than as interpeted code which means that GetSystemInfo ends up as native system call rather than in the miri shim.

Actually I was thinking Miri would just hard-code 4096 as the pagesize, as it does on Unix.

> Should we also do justice to this FIXME and switch this to the actual underlying page size?

Right, we may want to do that, but then we should do it on all platforms.
However, I am also not 100% convinced it is the right thing to do -- this would be leaking some "host" information into the target, which is not right. Miri is supposed to emulate an arbitrary target, not something host-specific -- at least without `-Zmiri-disable-isolation`.

So for now I think it should just also use PAGE_SIZE on windows. Basically you would adjust [this code](https://github.com/rust-lang/miri/blob/b96610b3de5bc9fd346d90700ba881aca8d503f0/src/shims/windows/foreign_items.rs#L112-L126) to also fill out the page size field.

**Comment by V0ldek** [comment]
Got it. I need guidance on how to test it, though, where would I put the `page_size` dep and test?

**Comment by RalfJung** [comment]
You can add it as a dep in test-cargo-miri/Cargo.toml, and then add a test in test-cargo-miri/tests/test.rs

**Comment by V0ldek** [comment]
There's one thing I don't understand at all.

The layout of [`winapi::um::sysinfoapi::SYSTEM_INFO`](https://docs.rs/winapi/0.3.9/winapi/um/sysinfoapi/struct.SYSTEM_INFO.html) is this (comments added to mark the field names):

```rust
layout: TyAndLayout { 
    ty: winapi::um::sysinfoapi::SYSTEM_INFO,
    layout: Layout { 
        fields: Arbitrary { 
            offsets: [
                Size(0 bytes),  // 0, u                           : SYSTEM_INFO_u
                Size(4 bytes),  // 1, dwPageSize                  : DWORD
                Size(8 bytes),  // 2, lpMinimumApplicationAddress : LPVOID
                Size(16 bytes), // 3, lpMaximumApplicationAddress : LPVOID
                Size(24 bytes), // 4, dwActiveProcessorMask       : DWORD_PTR
                Size(32 bytes), // 5, dwNumberOfProcessors        : DWORD
                Size(36 bytes), // 6, dwProcessorType             : DWORD
                Size(40 bytes), // 7, dwAllocationGranularity     : DWORD
                Size(44 bytes), // 8, wProcessorLevel             : WORD
                Size(46 bytes)],// 9, wProcessorRevision          : WORD
                memory_index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
            }, 
            variants: Single { index: 0 },
            abi: Aggregate { sized: true },
            largest_niche: None,
            align: AbiAndPrefAlign { 
                abi: Align(8 bytes),
                pref: Align(8 bytes) 
            }, 
            size: Size(48 bytes) 
        } 
    } 
}
```

So number of processors is the 5th field. But the existing code writes to the 6th:

https://github.com/rust-lang/miri/blob/b96610b3de5bc9fd346d90700ba881aca8d503f0/src/shims/windows/foreign_items.rs#L122-L126

From this, the page size field must be either the 1st field (as in the layout) or the 2nd field (4 fields before `dwProcessorType` if that is the 6th). But none of these work:

## 2nd

If I write:
```rust
let page_size = this.mplace_field(&system_info, 2)?;
this.write_scalar(Scalar::from_int(PAGE_SIZE, dword_size), &page_size.into())?;
```
then `page_size` does not work and fails with:

```plain
error: Undefined Behavior: scalar size mismatch: expected 8 bytes but got 4 bytes instead
   --> /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.2/src/lib.rs:166:13
    |
166 |             GetSystemInfo(&mut info as LPSYSTEM_INFO);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ scalar size mismatch: expected 8 bytes but got 4 bytes instead
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information

    = note: inside `page_size::windows::get` at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.2/src/lib.rs:166:13
    = note: inside closure at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.2/src/lib.rs:127:39
    = note: inside closure at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/once.rs:276:41
    = note: inside `std::sync::Once::call_inner` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/once.rs:434:21
    = note: inside `std::sync::Once::call_once::<[closure@page_size::get_helper::{closure#0}]>` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sync/once.rs:276:9
    = note: inside `page_size::get_helper` at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.2/src/lib.rs:127:9
    = note: inside `page_size::get` at /home/mat/.cargo/registry/src/github.com-1ecc6299db9ec823/page_size-0.4.2/src/lib.rs:53:5
note: inside `main` at src/main.rs:2:31
   --> src/main.rs:2:31
    |
2   |     println!("Page size: {}", page_size::get());
    |                               ^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error
```

## 1st

If I write:

```rust
let page_size = this.mplace_field(&system_info, 2)?;
this.write_scalar(Scalar::from_int(PAGE_SIZE, dword_size), &page_size.into())?;
```
then `page_size` _does_ work and correctly returns 4096. But miri's test suite fails!

```plain
$ MIRI_TEST_TARGET="x86_64-pc-windows-gnu" ./run-test.py

## Running `cargo miri` tests for target x86_64-pc-windows-gnu
A libstd for Miri is now available in `/home/mat/.cache/miri`.
Testing `cargo miri run` (no isolation)...
Testing `cargo miri run` (no rebuild)...
Testing `cargo miri run` (with arguments and target)...
Testing `cargo miri r` (subcrate, no isolation)...
Testing `cargo miri run` (custom target dir)...
Testing `cargo miri test`...
Test stdout or stderr did not match reference!
--- BEGIN test stdout ---
--- END test stdout ---
--- BEGIN test stderr ---
error: Undefined Behavior: scalar size mismatch: expected 2 bytes but got 4 bytes instead
   --> /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/windows/thread.rs:104:9
    |
104 |         c::GetSystemInfo(&mut sysinfo);
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ scalar size mismatch: expected 2 bytes but got 4 bytes instead
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information

    = note: inside `std::sys::windows::thread::available_parallelism` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/sys/windows/thread.rs:104:9
    = note: inside `std::thread::available_parallelism` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/std/src/thread/mod.rs:1609:5
    = note: inside `test::test::helpers::concurrency::get_concurrency` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/test/src/helpers/concurrency.rs:12:9
    = note: inside `<fn() -> usize {test::test::helpers::concurrency::get_concurrency} as std::ops::FnOnce<()>>::call_once - shim(fn() -> usize {test::test::helpers::concurrency::get_concurrency})` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/ops/function.rs:248:5
    = note: inside `std::option::Option::<usize>::unwrap_or_else::<fn() -> usize {test::test::helpers::concurrency::get_concurrency}>` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/option.rs:805:21
    = note: inside `test::test::run_tests_console` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/test/src/console.rs:269:28
    = note: inside `test::test::test_main` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/test/src/lib.rs:114:15
    = note: inside `test::test::test_main_static` at /home/mat/.rustup/toolchains/miri/lib/rustlib/src/rust/library/test/src/lib.rs:133:5
    = note: inside `main`

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

error: test failed, to rerun pass '--bin cargo-miri-test'
--- END test stderr ---

TEST FAIL: exit code was 1
```

I tried digging into this but I found nothing apart from confusion.

**Comment by RalfJung** [comment]
FWIW, that existing code is unnecessarily roundabout -- this would be better written as
```rust
                let num_cpus = this.mplace_field(&system_info, 6)?;
                this.write_scalar(Scalar::from_u32(NUM_CPUS), &num_cpus.into())?;
```
and changing the type of NUM_CPUS to be `u32`.
I also noticed an `as` cast a few lines above... this is really old code.^^ We usually try to avoid `as` casts.

---

Regarding your problem, maybe there is something odd with the type signature used by num_cpus? You can find it [here](https://github.com/seanmonstar/num_cpus/blob/5f1b03332000b4c4274b5bd35fac516049ff1c6b/src/lib.rs#L206), and `dwNumberOfProcessors` is field number 6 (counting from 0).

If you want you can adjust the code to not use the caller signature at all, and instead hard-code offsets and types. That will be a bit more work though. `MPlaceTy` has an `offset` method you can use to go to a field at a certain offset, but you will have to provide the layout of the field. `this.machine.layouts` contains a couple common ones, so `this.machine.layouts.u32` (or is DWORD signed? then `i32`) should do it.

**Comment by V0ldek** [comment]
I think that is the crux of the issue. I don't know where the layout in the `foreign_items` code comes from, but

- `page_size` uses the layout from [`winapi::um::sysinfoapi::SYSTEM_INFO`](https://docs.rs/winapi/0.3.9/winapi/um/sysinfoapi/struct.SYSTEM_INFO.html), so when called from there `page_size` is indeed field number 1, so that works.
- but `num_cpus` uses [the linked layout](https://github.com/seanmonstar/num_cpus/blob/5f1b03332000b4c4274b5bd35fac516049ff1c6b/src/lib.rs#L206), where the first field is inlined into the structure and actually takes 2 fields. So there writing to 6th field is actually `dwNumberOfProcessors`, but when I write to field number 1 that means the `wReserved` `WORD`-type field and it all goes to hell.

I think that can be detected though. Maybe the solution would be to check whether the first field is of size 4 or size 2 and offset according to that? In the first case use field 1 for page size and 5 for num cpus, in the latter use fields 2 and 6, respectively?

**Comment by RalfJung** [comment]
The layout in foreign_itens comes from the declaration of the call site that we are currently emulating.

Checking field counts sounds rather fragile. I think it is better to ignore the layout and hard-code the offsets.

**Comment by V0ldek** [comment]
The checking field counts approach led to simpler code, but I reimplemented it by explicitly using `offset`, and it still works 🥳

**Comment by V0ldek** [comment]
I implemented dynamically calculating the offsets of all fields in SYSTEM_INFO, since the concrete values depend on target's pointer size. With that adding values to other fields in that structure should be relatively straightforward. And now it indeed works (🥳).
