### ISSUE TITLE
Filtering tests does not work any more

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2155]
`./miri test foo` used to only run the tests that have "foo" in their name (including the folder name, i.e. "fail" matches all compile-fail/foo.rs tests). That doesn't work any more.
I use this quite a lot when testing so would be nice to get it back. :)

Cc @oli-obk

**Comment by oli-obk** [comment]
Oh yea, I knew this was lost but forgot to add it to the list

**Comment by RalfJung** [comment]
Once this is fixed we should also enable running tests with optimized MIR again, filtered for "tests/pass" and "tests/panic".
