### ISSUE TITLE
Error patterns do not seem to work?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2156]
I edited an error pattern to make it not match the output and the tests still pass...
```diff
--- a/tests/compile-fail/validity/dangling_ref1.rs
+++ b/tests/compile-fail/validity/dangling_ref1.rs
@@ -3,5 +3,5 @@
 use std::mem;
 
 fn main() {
-    let _x: &i32 = unsafe { mem::transmute(16usize) }; //~ ERROR encountered a dangling reference (address $HEX is unallocated)
+    let _x: &i32 = unsafe { mem::transmute(16usize) }; //~ ERROR encountered a dangling reference (address $HEX is unallocateds)
 }
```
Cc @oli-obk this seems rather critical^^

**Comment by RalfJung** [comment]
This might be due to the space after the `~`? We should probably allow that.

But even then it should have caught the problem that there is no error pattern in this file.

**Comment by oli-obk** [comment]
Hmm odd. I'll start adding those unit tests I wanted to add
