### ISSUE TITLE
Integers and pointers sometimes incorrectly preserve provenance on typed copies

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2182]
Miri currently does not properly implement what happens to provenance during a typed copy:
- When doing a copy at integer type, provenance should be stripped. Instead, we will currently complain during validation that provenance on an integer is UB.
- When doing a copy at pointer type, if the provenance is not the same for all bytes of a pointer, it should be stripped. Instead, we will currently just preserve it.

The best way I see to solve this is to make validation mutating, so that during validation we can adjust integer and pointer values following these rules. Mutating validation is also needed for https://github.com/rust-lang/miri/issues/845.

**Comment by a-b-c-1-2-3** [comment]
Seems like testcase #1 currently passes but I didn't dig too deep to see why/since when; maybe this issue is worth updating for anyone coming to work on it in the future?

**Comment by RalfJung** [comment]
Ah right that got fixed by https://github.com/rust-lang/rust/pull/104054.
