### ISSUE TITLE
Print out both accesses involved in a data race

### ISSUE THREAD

**Issue by cbeuw** [rust-lang/miri#2205]
Currently Miri throws a UB on the access that ultimately causes a data race, which is always the later one. It is not clear where the other access involved in the data race is in the source file.
```
error: Undefined Behavior: Data race detected between Write on Thread(id = 0, name = "main") and Write on Thread(id = 1) at alloc1 (current vector clock = VClock([5]), conflicting timestamp = VClock([0, 8]))
  --> src/lib.rs:21:18
   |
21 |         unsafe { V = 2 }
   |                  ^^^^^ Data race detected between Write on Thread(id = 0, name = "main") and Write on Thread(id = 1) at alloc1 (current vector clock = VClock([5]), conflicting timestamp = VClock([0, 8]))
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
           
   = note: inside `tests::data_race` at src/lib.rs:21:18
```
Both [TSan](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual#usage) and [Go's race detector](https://go.dev/doc/articles/race_detector#Report_Format) print out the line numbers of both accesses involved in the data race, we'd like to do the same.

It shouldn't be too hard to implement, we just need to augment `VTimestamp` with the current `Span` from `MiriEvalContext::cur_span()`
https://github.com/rust-lang/miri/blob/aca3b3a645e6d0295e9f1829c37af811a6de5251/src/vector_clock.rs#L45

**Comment by RalfJung** [comment]
Stacked Borrows recently got some support for showing extra spans thanks to @saethlin; we probably want to reuse that -- in particular it doesn't use `cur_span` but tries to find a span "in the local crate".

Also, augmenting *every* timestamp might be a bit too expensive in terms of performance?

**Comment by saethlin** [comment]
I don't know that augmenting every timestamp would be too slow. TSan manages to report backtraces in a debug build for these races, and those backtraces are not small and we're only trying to report one measly span. If someone is interested in doing this, it's probably worth giving the naïve approach a shot. If it's too slow I already have some ideas.

**Comment by cbeuw** [comment]
Is there a way to get a backtrace in Miri, and how expensive would this be? Only showing one span is probably not too helpful

**Comment by saethlin** [comment]
`ecx.generate_stacktrace()`, or you may be interested in looking over this: https://github.com/rust-lang/miri/blob/dcaa7a7221b3b25a1ad6cdb30d30739e0ea4d331/src/helpers.rs#L825-L860

**Comment by cbeuw** [comment]
@saethlin Thanks, that looks handy.

> we just need to augment VTimestamp with the current Span from

I realised what I said wouldn't work, because

https://github.com/rust-lang/miri/blob/dcaa7a7221b3b25a1ad6cdb30d30739e0ea4d331/src/concurrency/data_race.rs#L32-L36

On a data race, we know the offending timestamp, but that could cover multiple spans so we won't be able to pinpoint a line

**Comment by ibraheemdev** [comment]
I was trying to debug a data race in https://github.com/ibraheemdev/seize and had it narrowed down to a simple test case with two threads. I wanted to see the order in which miri was interleaving the threads to narrow down the bug, but adding debug statements added extra synchronization that fixed the data race ;) I ended up having to use a thread-unsafe `println` shim to see the order without breaking it:

```rust
pub fn println(x: String) {
    unsafe {
        let mut f = std::fs::File::from_raw_fd(1);
        f.write_all(x.as_bytes()).unwrap();
        std::mem::forget(f);
    }
}
```

And I did manage to find the missing synchronization edge, but it would be nice if this was easier.

**Comment by saethlin** [comment]
> but that could cover multiple spans so we won't be able to pinpoint a line

We could give each timestamp a start and end span. I wonder how many times when we report a diagnostic the start and end span would be the same.
