### ISSUE TITLE
Miri fails to run in presence of `RUSTC` environment variable

### ISSUE THREAD

**Issue by CraftSpider** [rust-lang/miri#2238]
Currently, if the `RUSTC` environment variable is set, miri errors out with 'failed to run `rustc` to learn about target-specific information'. This appears to be because, in `cargo-miri`, the arg 'rustc' is being checked for exactly, but with `RUSTC` set, it may actually be set to any binary.
https://github.com/rust-lang/miri/blob/fa4e77c9fda4fde7f100ec79fc7233e7e1d532ce/cargo-miri/bin.rs#L1112

I found this out due to the Jetbrains rust plugin failing to run miri, as it unconditionally sets the `RUSTC` environment variable. I'm not sure the best solution. Looking for a path ending in `rustc` would make an okay patch, but to truly fix the issue, there would need to be a way to distinguish any particular path from being a `rustc` executable vs a JSON file (for `phase_runner`). A possible way to do that is to just attempt to execute the provided path?

**Comment by RalfJung** [comment]
Is it even meaningful to set RUSTC when using Miri? What would you expect that to do?

**Comment by CraftSpider** [comment]
Personally I'd expect miri to work the same whether it's set or not, though the actual value probably isn't useful to miri itself. I could raise this as an issue with the jetbrains plugin, but I also feel that having `RUSTC` set to a valid rustc binary shouldn't lead to failures in cargo commands, even if the command doesn't actually care about the value.

If you don't agree, I'll raise the issue with them instead, and see if they can special-case `cargo miri`.

**Comment by RalfJung** [comment]
We could make `cargo-miri` remove the `RUSTC` env var if it is set. That should "fix" your problem, unless you expected the env var to actually do something, so I don't know if it is a reasonable approach. Maybe we should at least print a warning?

(I do not have a clear idea for the use-cases where one would even set that env var.)

**Comment by RalfJung** [comment]
This `file "C:\\Users\\runet\\.cargo\\bin\\rustc.exe" contains outdated or invalid JSON` error looks similar to https://github.com/rust-lang/miri/issues/2233. Do you have any way to reproduce this that does not require IntelliJ?

**Comment by RalfJung** [comment]
Ah, I can reproduce this with `RUSTC=$(which rustc) cargo +miri miri run`. This is very odd:
```
Caused by:
  process didn't exit successfully: `/home/r/.cargo/bin/cargo-miri /home/r/.cargo/bin/rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  fatal error: file "/home/r/.cargo/bin/rustc" contains outdated or invalid JSON; try `cargo clean`
```
Looks like cargo is acting really strangely when both RUSTC and RUSTC_WRAPPER are set?
