### ISSUE TITLE
False positive leak if using `slice::fill`

### ISSUE THREAD

**Issue by ZetaNumbers** [rust-lang/miri#2260]
I don't exactly know if it is *false* positive, but it does look like it really is.

Fell free to run miri in the playground:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=df6fb386304d71a6b211f06060cd1a30

This is still an issue on latest accessible nightly too.

**Comment by bjorn3** [comment]
```rust
        for (i, v) in slice.iter().enumerate() {
            let foo = [Foo(i as i32)];
            assert_eq!(v, &foo);
            std::mem::forget(foo);
        }
```

The `std::mem::forget(foo)` here seems to cause this. It shouldn't though I think.

**Comment by oli-obk** [comment]
This is expected, as `slice::fill` uses `clone_from` for all but the last element. `Vec::clone_from` does not deallocate the memory of the overwritten `Vec`.

**Comment by ZetaNumbers** [comment]
Moved to https://github.com/rust-lang/rust/issues/98425 due to valgrind
