### ISSUE TITLE
cargo miri: can't disable colors

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/miri#2277]
It seems that since the last miri sync, stdout/stderr is printed with colors unconditionally?

This broke a bunch of icemaker regexes which fetch UB/ICEs from miri stdout and produced a couple of funny diffs:
````
-    "error_reason": "error: Undefined Behavior: type validation failed at .value: encountered uninitialized raw pointer",
+    "error_reason": "\u001b[0m   \u001b[0m\u001b[0m\u001b[1m\u001b[38;5;12m= \u001b[0m\u001b[0m\u001b[1mhelp\u001b[0m\u001b[0m: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior\u001b[0m",
````

I tried to disable colors but not even `cargo --color=never miri run  --color=never` does work.

**Comment by RalfJung** [comment]
How does `cargo` forward `--color=never` to rustc? I would hope it stops passing `diagnostic-rendered-ansi`...

**Comment by RalfJung** [comment]
Oh no. Cargo seems to always pass `--json=diagnostic-rendered-ansi,artifacts,future-incompat`, even with `--color=never`. Does cargo then itself strip the ANSI from the JSON before putting it to the terminal...?

It looks like there is no way for the rustc driver to tell whether the user wanted output with or without colors? Cc @ehuss

**Comment by ehuss** [comment]
For caching purposes, cargo strips out the ANSI when color is disabled.
