### ISSUE TITLE
libtest output is not colored

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2292]
`cargo miri test` output is not colored the same way `cargo test` is: the output that is generated inside Miri (the libtest runner) uses no colors. I think this is probably because of the hack where we remove the `TERM` environment variable even with isolation disabled -- that makes libtest think that the terminal does not support color so it falls back to no colors. (EDIT: looks like I am wrong, see below.)

We remove the `TERM` variable because having it makes libtest startup *super slow* (that was https://github.com/rust-lang/miri/issues/1702). Maybe we need another work-around for this problem, like adding a `cfg(miri)` somewhere to skip the slow code -- or actually making Miri less slow on that code.^^

@saethlin this is the bug you mentioned in one of your PRs; it has nothing to do with `--color=always` (other than, even with `--color=always`, libtest still uses no color unless `TERM` indicates that the terminal supports color).

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/miri/pull/2293 we can use  `MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-env-forward=TERM" cargo miri test` to test what happens when `TERM` is properly forwarded... and strangely there are still no colors. Hm...

**Comment by RalfJung** [comment]
Ah, got it -- in addition to forwarding `TERM`, we *also* need to adjust our [`isatty` shim](https://github.com/rust-lang/miri/blob/73a1a27a450c0a7c0bfcab258230bb3165d9c05c/src/shims/unix/foreign_items.rs#L416), which currently just says nothing is a TTY.

I am not sure what the best solution is here, given the multi-second wait triggered by forwarding `TERM`.

**Comment by saethlin** [comment]
Is it sufficient to just lie about whether we are a TTY? I was honestly thinking of hacking up something like that for myself to induce colors to appear.

**Comment by RalfJung** [comment]
As I said, we need *both* `TERM` and the `isatty` change.

**Comment by saethlin** [comment]
Argh I was reading your phrasing in the most desperately optimistic way possible.

terminfo files are a mess, and I really wonder how much portability this is actually providing for libtest. Are people actually running `cargo test` or `cargo miri test` on a terminal that only supports 8-bit colors? That would be shocking. I wonder if whoever is in charge of this code would be okay with us just bypassing the parsing with a `#[cfg(miri)]` and selecting some terminfo that we think is reasonable everywhere that Cargo/Miri can run.

**Comment by RalfJung** [comment]
Yeah they might be. However, is always forcing isatty even what we want? Playground was not happy last time we did that...

**Comment by saethlin** [comment]
I was thinking of a flag so the user could pick, but it would be better to have the shim work correctly.

**Comment by RalfJung** [comment]
If the host is also Unix (or maybe only for Linux), we could forward to libc. That will help at least in some cases?

**Comment by saethlin** [comment]
https://crates.io/crates/atty

**Comment by RalfJung** [comment]
Hm, not sure how I feel about adding external dependencies. We are quite conservative about that here. OTOH that sounds like exactly the API we want and it is even cross-platform...

But anyway it seems like there are two orthogonal steps here:
- make whatever code in libtest parses the TERM stuff just skip all that under `cfg(miri)` and assume a reasonably modern terminal, but still honor `isatty`
- do something more clever with Miri's `isatty` shim

**Comment by RalfJung** [comment]
> Everyone goes through this crate https://crates.io/crates/atty

Alternatively we could copy [this file](https://github.com/rust-lang/rust/blob/2c31b45ae878b821975c4ebd94cc1e49f6073fd0/library/test/src/helpers/isatty.rs) which is tiny.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/miri/pull/2349, the following now produces colored output:
```
MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-env-forward=TERM" cargo miri test
```
However it also takes forever to start, due to the terminfo parsing.
(And I feel like that has gotten slower recently? It used to take maybe 2-10s, now it is on the order of 30-60s... @saethlin there might be a benchmark hiding here that got worse recently)

**Comment by RalfJung** [comment]
(never mind I was running a Miri with debug assertions^^)
