### ISSUE TITLE
ui_test: blessing should also delete stderr files when stderr is empty

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2310]
The title pretty much says it all.

**Comment by oli-obk** [comment]
we already do this. I think the issue is more like what happens when you rename a test file or remove a revision. In that case there's no link from the test file to the output, so we don't know to remove it.

**Comment by RalfJung** [comment]
Didn't you say the [leftover stderr file in one PR](https://github.com/rust-lang/miri/pull/2282#discussion_r910983808) was due to that? Or was there a rename involved there as well?

**Comment by oli-obk** [comment]
that may have been mostly confusion on my side. After all, CI did catch it, so we must've already been doing something right, and testing locally I can't reproduce any issues...
