### ISSUE TITLE
Chaos ensues when cargo miri is run concurrently

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2340]
Two instances of cargo miri running concurrently can lead to the following fun situation:
- A creates and fills the Xargo.toml.
- B empties the Xargo toml.
- A runs xargo.
- (B fills the Xargo.toml but now it's too late.)

Then we end up building a no-std systroot. *oops*
We need to either do the Xargo.toml writing atomically via `rename` or so and hope that xargo itself is fine with the concurrency, or (probably better) have some kind of file system locking.

Thanks to @matthiaskrgr for reporting this.

**Comment by RalfJung** [comment]
- Cargo has its own file locking in [this file](https://github.com/rust-lang/cargo/blob/6963df3b941e2b72d9ca34efeaf0664108d7decd/src/cargo/util/flock.rs).
- xargo seems to have a copy of it [here](https://github.com/japaric/xargo/blob/5d21834e6b63d11e4ac36982832af92c4c00ad4a/src/flock.rs).

So I guess we could just have another copy in Miri to resolve this? :joy: 

Maybe going with an atomic rename is the better strategy after all...

**Comment by RalfJung** [comment]
Uh, no, I have specifically edited the comment to *not* indicate that this should be closed...

**Comment by RalfJung** [comment]
@matthiaskrgr the latest nightly has a Miri with this fix. Could you give that a try?

**Comment by matthiaskrgr** [comment]
running miri in parallel since two hours now and i did not run into problems yet :)

**Comment by RalfJung** [comment]
Awesome. :) Going to close this as fixed then.
