### ISSUE TITLE
Setup triagebot?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2358]
It would be nice to get at least the `@rustbot ready`/`@rustbot author` commands to work in this repo.
@Mark-Simulacrum any hints for what we have to do for that? Do we just have to add that toml file (probably basically empty, except for `[shortcuts]`), or is there anything else to be done?

**Comment by Mark-Simulacrum** [comment]
Almost, you also need to ping me to enable it. Consider me pinged :)

See some docs here - https://github.com/rust-lang/triagebot/wiki/Enabling-triagebot

**Comment by RalfJung** [comment]
All right, seems to be working -- thanks @Mark-Simulacrum :)
