### ISSUE TITLE
Miri misses UB in place expressions when there are "_" patterns

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2360]
~~The following example should both be UB, but Miri finds neither of it:~~ (this got fixed by https://github.com/rust-lang/rust/pull/104844)
```rust
fn main() {
    let ptr = 32 as *const u8;
    unsafe { let _ = *ptr; }
}
```
~~This is blocked on https://github.com/rust-lang/rust/issues/99180.~~

Here's another variant: (that is not fixed yet, will be fixed by https://github.com/rust-lang/rust/pull/103208)

```rust
fn main() {
    let ptr = 32 as *const u8;
    unsafe {
        match *ptr { _ => {} }
    }
}
```

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/102256 preserves these place expressions in MIR, which is a step towards fixing this.

@JakobDegen 
> We currently spec FakeRead as being a semantic nop; we could make an exception for the ForWildcard case, but it might be cleaner to have a new StatementKind::PlaceComputation or something like that

Would anything go wrong if we spec'ed them *all* to be evaluating the place expression and then discarding it (i.e., not actually doing a read, never producing a value)?

**Comment by JakobDegen** [comment]
Can't be sure without trying, but I experimented for a bit and wasn't able to come up with any problems.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/103208 landed. Due to https://github.com/rust-lang/reference/pull/1387, the original example is not UB any more, but similar things are, so this will be fixed after adding a test.
