### ISSUE TITLE
Installing locally built miri

### ISSUE THREAD

**Issue by fakedrake** [rust-lang/miri#2366]
I wanted to modify `cargo miri` a bit to print the borrow stack of the problematic address when throwing an error. I found the code and modified it, I even tried the [contributing](https://github.com/rust-lang/miri/blob/master/CONTRIBUTING.md) which seems to suggest to run `./miri install`. However `cargo miri` doesn't work when I try to test my unsafe-heavy crate with it:

```
unsafe-heavy-crate/ $ cargo miri test
I will run `"rustup" "component" "add" "rust-src"` to install the `rust-src` component for the selected toolchain. Proceed? [Y/n] 
info: component 'rust-src' is up to date
fatal error: given Rust source directory `lib/rustlib/src/rust/library` does not exist.    
```

I am clearly doing something wrong but I don't know what to do?

**Comment by fakedrake** [comment]
#2233 had information relevant to my problem as it turns out

**Comment by RalfJung** [comment]
The docs also say

> Make sure you use the same toolchain when calling cargo miri that you used when installing Miri!

I assume that is what went wrong here?

> had information relevant to my problem

For the sake of other's having the same problem, it'd be great if you could explain what you did to resolve the problem. :)

**Comment by fakedrake** [comment]
So the `+miri` part of `cargo +miri miri test` was what I was missing. It was probably a problem with my `$PATH`.

**Comment by RalfJung** [comment]
Yeah, that is what the docs are referring to when they say to use the same toolchain. Maybe we should make that more explicit...
