### ISSUE TITLE
RA causes regular unnecessary rebuilds

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2406]
Some time recently, I started getting a lot of unnecessary rebuilds : `./miri run` and `./miri test` would start by building libc, even though I had just recently completed a full build so there is no need to re-build all the dependencies.

Here is a reproducer:
- Close vscode, `rm -rf target`
- `./miri build`
- `./miri check`
- `./miri build` does nothing, finishes immediately (as it should)
- start vscode, wait until RA is done with all its indexing etc
- close vscode
- `./miri build` now does a rebuild!

It's not a full rebuild, but some crates to get rebuilt:
```
$ ./miri build
   Compiling libc v0.2.112
   Compiling memchr v2.4.1
   Compiling log v0.4.14
   Compiling aho-corasick v0.7.18
   Compiling getrandom v0.2.3
   Compiling parking_lot_core v0.8.5
   Compiling atty v0.2.14
   Compiling memmap2 v0.2.3
   Compiling perf-event-open-sys v1.0.1
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.11.2
   Compiling rand_chacha v0.3.1
   Compiling measureme v10.1.0
   Compiling regex v1.5.5
   Compiling rand v0.8.4
   Compiling env_logger v0.9.0
   Compiling miri v0.1.0 (/home/r/src/rust/miri)
    Finished dev [optimized + debuginfo] target(s) in 25.60s
   Compiling dirs-sys v0.3.6
   Compiling directories v3.0.2
   Compiling cargo-miri v0.1.0 (/home/r/src/rust/miri/cargo-miri)
    Finished dev [optimized + debuginfo] target(s) in 2.05s
```
This is rather annoying. Something RA does (potentially in combination with the somewhat special setup in the Miri repo) seems to destroy the build cache. This also never stops, each time I restart vscode, the next `./miri build` does a bunch of work it should not have to do.

Here are my vscode settings:
```json
{
    "rust-analyzer.rustc.source": "discover",
    "rust-analyzer.linkedProjects": [
        "./Cargo.toml",
        "./cargo-miri/Cargo.toml"
    ],
    "rust-analyzer.checkOnSave.overrideCommand": [
        "./miri",
        "check",
        "--message-format=json"
    ],
    "rust-analyzer.buildScripts.overrideCommand": [
        "./miri",
        "check",
        "--message-format=json",
    ],
    "rust-analyzer.rustfmt.extraArgs": [
        "+nightly"
    ],
}
```

**Comment by RalfJung** [comment]
Adding this to my workspace config fixes the issue:
```
    "rust-analyzer.cargo.buildScripts.enable": false,
    "rust-analyzer.procMacro.enable": false,
```
So it seems to have something to do with the build script / proc macro support of RA. @fee1-dead any idea what might be happening here?

**Comment by oli-obk** [comment]
I think the proc macro support is broken on nightly right now

**Comment by RalfJung** [comment]
I think it might have to do with this hack where RA sets RUSTC_WRAPPER or RUSTC or so to speed up the build -- which however means that some build scripts, like that of libc, are being re-run, since they depend on those env vars.

**Comment by fee1-dead** [comment]
Try setting `cargo.buildScripts.useRustcWrapper` to false.

**Comment by RalfJung** [comment]
I can't find such a setting in the UI; is this the right JSON snippet?
```json
    "rust-analyzer.cargo.buildScripts.useRustcWrapper": false,
```

**Comment by fee1-dead** [comment]
I think so. Does that help?

**Comment by RalfJung** [comment]
No, it still rebuilds `libc` when I start vscode, wait until RA is fully loaded (which takes forever with proc macro support turned on), and then do `./miri build` again.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/rust-analyzer/issues/13011.
