### ISSUE TITLE
setting rustc-wrapper in ~/.cargo/config break miri

### ISSUE THREAD

**Issue by youknowone** [rust-lang/miri#2429]
```
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `~/.cargo/bin/sccache ~/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo-miri - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 2)
  --- stderr
  sccache: error: failed to execute compile
  sccache: caused by: Compiler not supported: "error: Unrecognized option: \'E\'\n\n"
error: `"~/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo" "check" "--release" "--manifest-path" "/var/folders/yf/dvzgtwmx7bsfgfc2d6mcldvh0000gn/T/xargo.4Al3EAsEZ1Oj/Cargo.toml" "--target" "x86_64-apple-darwin" "-p" "std"` failed with exit code: Some(101)
fatal error: failed to run xargo
```

**Comment by RalfJung** [comment]
That sounds like a problem with your specific rustc-wrapper and a sysroot build? If it just executed the binary it was asked to execute, everything would work fine...

**Comment by RalfJung** [comment]
We explicitly unset the RUSTC_WRAPPER env var during the sysroot build to avoid potential problems like this.

@ehuss is there a way to unset config.toml settings via the environment?

**Comment by youknowone** [comment]
Thank you! Setting RUSTC_WRAPPER looks helpful to prevent toggling option everytime.

I was using a common sccache local storage setup working fine with plain rustc.
Maybe other sccache users experience similar problems:
https://github.com/rust-lang/miri/issues/1421#issuecomment-761587559

**Comment by RalfJung** [comment]
@youknowone could you try setting `RUSTC_WRAPPER` to the empty value (and keep the global config.toml option)? From my testing it looks like that disables wrapping in cargo.

**Comment by ehuss** [comment]
Hm, looks like setting `RUSTC_WRAPPER` to an empty string will unset it. We should probably add that to the documentation. There isn't a general mechanism for unsetting config values, though.

**Comment by RalfJung** [comment]
Okay, thanks. Well I guess we'll have to handle this on a case-by-case basis, as people discover global config options that cause trouble for cargo-miri. At least for rustc-wrapper we have a plan. :)

**Comment by youknowone** [comment]
setting both `.cargo/config` and `RUSTC_WRAPPER=""` made miri using cargo global config.

**Comment by RalfJung** [comment]
@youknowone what do you mean, it is still not working? In my tests, I can set rustc-wrapper to a nonsense value in `config.toml`, and if I also have `RUSTC_WRAPPER=""` the build still works.

**Comment by youknowone** [comment]
I exactly did the same trial and getting the same error:
```
$ RUSTC_WRAPPER="" MIRIFLAGS='-Zmiri-ignore-leaks' cargo +nightly miri test
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `~/.cargo/bin/sccache ~/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo-miri - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 2)
  --- stderr
  sccache: error: failed to execute compile
  sccache: caused by: Compiler not supported: "error: Unrecognized option: \'E\'\n\n"
fatal error: failed to run xargo
```

**Comment by RalfJung** [comment]
Okay that is odd. I am seeing the same thing, but when I programmatically make the env var empty inside cargo-miri (as in https://github.com/rust-lang/miri/pull/2430), that helps...

**Comment by RalfJung** [comment]
Oh yeah of course, `cargo-miri` *removes* RUSTC_WRAPPER from the environment. :facepalm:
