### ISSUE TITLE
MIRI_LOG=trace stopped working

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2502]
Something changed in the log crate at some point, and now e.g. `MIRI_LOG=miri::tls=trace` does not work any more. It says:
```
warning: some trace filter directives would enable traces that are disabled statically
 | `miri::tls=trace` would enable the TRACE level for the `miri::tls` target
 = note: the static max level is `info`
 = help: to enable DEBUG logging, remove the `max_level_info` feature
```
This is somewhat annoying; it used to be that debug builds have a max level of `trace` and release builds of `info`, which was exactly what we wanted. I am not sure how to replicate the original behavior.

**Comment by RalfJung** [comment]
Oh, turns out my actual mistake was that I should have used `MIRI_LOG=miri::shims::tls=trace`. The error does not originate from the log crate used by Miri, it originates from somewhere in rustc.

**Comment by oli-obk** [comment]
uh... is this because we also forward to RUSTC_LOG? Or is it actually not working

**Comment by RalfJung** [comment]
Yeah we forward to RUSTC_LOG and so rustc also sees the `miri::` filters. We would have to parse the directive ourselves if we wanted to not forward `miri::...`.
