### ISSUE TITLE
-Zmiri-report-progress does not keep reporting for infinite loops

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2522]
Try running this
```rust
fn main() {
  loop {}
}
```
with `-Zmiri-report-progress`. It reports progress exactly once:
```rust
note: tracking was triggered
 --> loop.rs:2:3
  |
2 |   loop {}
  |   ^^^^^^^ progress report: current operation being executed is here
  |
  = note: inside `main` at loop.rs:2:3
```
and then stops showing any messages.

My guess is that there is some diagnostic deduplication in rustc. We usually want that but not here. Can we disable the deduplication for a single diagnostic? If not we have to be creative, like include some kind of counter in the message to make them not exact duplicates.

**Comment by bjorn3** [comment]
Indeed. Rustc deduplicates diagnostics unless `-Zdeduplicate-diagnostics` is enabled. Deduplication is based on hashing the `Diagnostic`. It doesn't seem like you can disable it on a per-diagnostic basis.
