### ISSUE TITLE
Document and simplify Miri subtree syncing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2569]
The Miri [subtree sync docs](https://github.com/rust-lang/miri/blob/master/CONTRIBUTING.md#fetching-the-latest-changes-from-the-rustc-repo) are not complete yet (the part for moving changes from Miri to the rustc repo is missing). Also it'd be great if syncing from rustc to Miri would not require spawning an entire docker container. :D

Meanwhile, [these steps](https://github.com/rust-lang/miri/pull/2561/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R311) seem to work fine for Miri-to-rustc syncs.

**Comment by oli-obk** [comment]
yea, I don't know if we want to keep using git subtree for miri to rustc syncs, but since I am currently unable to do the sync in that direction with `josh` (see https://github.com/josh-project/josh/issues/950), I'm going to check if that works without causing duplicate commits on the rustc side

**Comment by oli-obk** [comment]
Or worst case: every sync duplicates all commits since the miri subtree creation

**Comment by RalfJung** [comment]
After trying it, using docker actually doesn't seem so bad.

But the instructions are incomplete -- if one wants to also update the rust-version file (which is crucial), then one first needs to do a local merge of the new josh branch into master (I assume `git merge josh/master` should work but the route I went was more complicated), and then make a commit with the rust-version bump. `josh/master` contains only the josh part of the history, not all the local Miri history.

**Comment by RalfJung** [comment]
> Or worst case: every sync duplicates all commits since the miri subtree creation, including already duplicated commits

Yeah using git-subtree for the 'backwards' merge (Miri to rustc) doesn't seem to recognize the josh commits (which I guess is not surprising) so the rustc commits get duplicated. :/
I wanted to get the 'no more xargo' shipped soon, this is bad timing.^^

We could use a simple copy approach for this direction? Having the Miri history in the rustc repo does not seem necessary (and we didn't have that with submodules either).

**Comment by oli-obk** [comment]
Seems fine to me. Effectively do a `git subtree pull` and then squash the entire PR

**Comment by RalfJung** [comment]
What's missing from the docs is how to exit that docker container... it entirely ignores Ctrl-C... :(

> At that point, we can also rebase the sync from rustc to miri and thus eliminating the merge commits without losing the others.

I don't understand what you mean by that.

**Comment by oli-obk** [comment]
> What's missing from the docs is how to exit that docker container... it entirely ignores Ctrl-C... :(
> I did `sudo killall josh-proxy` for now but I doubt that is the right way ;)

yea, I ended up using `docker stop`, but that didn't do it cleanly either I think?

> I don't understand what you mean by that.

Basically if we only use josh in the rustc->miri direction to preserve history, we don't need to care about the commits josh built, as long as we preserve the history in a way that works for us. So if you rebase the sync PR over miri/master, that should eliminate all merge commits and only leave the content-commits. This would be a problem if we used josh for the miri->rustc sync, but if we use squashing for that direction, we don't need to care.

**Comment by RalfJung** [comment]
> Basically if we only use josh in the rustc->miri direction to preserve history, we don't need to care about the commits josh built, as long as we preserve the history in a way that works for us. So if you rebase the sync PR over miri/master, that should eliminate all merge commits and only leave the content-commits. This would be a problem if we used josh for the miri->rustc sync, but if we use squashing for that direction, we don't need to care.

Won't that screw up the state for the *next* josh sync?

**Comment by RalfJung** [comment]
Also no that rebase doesn't work. Those jush syncs have a *wild* git history and `git rebase` seems to have no idea which commits to pick up.^^

**Comment by RalfJung** [comment]
Or maybe I screwed up something else? A 2nd attempt at rebasing works better.

**Comment by RalfJung** [comment]
FWIW here's what I tried for the Miri to rustc side:
```
(cd src/tools && rm -rf miri && git clone https://github.com/rust-lang/miri && rm -rf miri/.git && git add miri)
```
Seems to work well, but https://github.com/rust-lang/miri/pull/2574 needs to land first to actually make this work (for issues unrelated to the syncing process).

**Comment by oli-obk** [comment]
😆 I would have tried `git subtree pull --squash`, but that works, too

**Comment by RalfJung** [comment]
Lol, I didn't know that's a thing, but if we can avoid `git subtree` that seems like a plus ;)

**Comment by RalfJung** [comment]
For the record, here's the latest version of my sync instructions

### Fetching the latest changes from the rustc repo

Run the josh proxy locally (in another terminal)

```
docker run -it -p 8000:8000 -e JOSH_REMOTE=https://github.com JOSH_EXTRA_OPTS=--no-background -v josh-vol:/data/git joshproject/josh-proxy:latest
```

And then integrate the recent changes and update the `rust-version` file

```
git checkout master
git pull
git fetch http://localhost:8000/rust-lang/rust.git:/src/tools/miri.git master # takes ca 5-10 min the first time
git merge FETCH_HEAD -m "merge rustc history"
./rustup-toolchain HEAD && ./miri fmt
git commit -am "rustup"
```

Now push to your own miri fork and open a PR with it.
You can stop the josh proxy with Ctrl-C.

**Comment by RalfJung** [comment]
I think the instructions are as good as they are going to get, for now.
