### ISSUE TITLE
MIRI requires synchronization for deallocation of "empty" Arc

### ISSUE THREAD

**Issue by sbarral** [rust-lang/miri#2588]
MIRI complains with `Data race detected between Read on thread <unnamed> and Atomic Store on thread main` with this code of an empty `Arc` pointer:

```rust
struct EmptyArc {
    inner: *const AtomicUsize,
}
impl EmptyArc {
    fn new() -> Self {
        Self {
            inner: Box::into_raw(Box::new(AtomicUsize::new(1))),
        }
    }
}
impl Clone for EmptyArc {
    fn clone(&self) -> Self {
        unsafe { (*self.inner).fetch_add(1, Ordering::Relaxed) };

        Self { inner: self.inner }
    }
}
impl Drop for EmptyArc {
    fn drop(&mut self) {
        unsafe {
            // MIRI detects a data race with Relaxed ordering here, but not with AcqRel.
            let prev_count = (*self.inner).fetch_sub(1, Ordering::Relaxed);
            if prev_count == 1 {
                let _ = Box::from_raw(self.inner as *mut AtomicUsize);
            }
        }
    }
}
unsafe impl Send for EmptyArc {}

fn main() {
    let foo1 = EmptyArc::new();
    let foo2 = foo1.clone();

    let th = thread::spawn(move || drop(foo1));
    drop(foo2);

    th.join().unwrap();
}

```

When the `fetch_sub` uses `AcqRel` instead of `Relaxed` (or `Release` + conditional `Acquire` fence), then all is good.

This behavior would be expected for an actual `Arc` that contains data that may be modified, but here I cannot see what memory operations would make a `Release`/`Acquire` synchronization necessary.

**Comment by RalfJung** [comment]
Could you please show the error that Miri prints?

**Comment by sbarral** [comment]
> Could you please show the error that Miri prints?

Here it goes:
```
error: Undefined Behavior: Data race detected between Deallocate on thread `<unnamed>` and Atomic Store on thread `main` at alloc1513
   --> /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:113:14
    |
113 |     unsafe { __rust_dealloc(ptr, layout.size(), layout.align()) }
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Data race detected between Deallocate on thread `<unnamed>` and Atomic Store on thread `main` at alloc1513
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE:
    = note: inside `std::alloc::dealloc` at /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:113:14
    = note: inside `<std::alloc::Global as std::alloc::Allocator>::deallocate` at /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:250:22
    = note: inside `alloc::alloc::box_free::<std::sync::atomic::AtomicUsize, std::alloc::Global>` at /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/alloc.rs:348:9
    = note: inside `std::ptr::drop_in_place::<std::boxed::Box<std::sync::atomic::AtomicUsize>> - shim(Some(std::boxed::Box<std::sync::atomic::AtomicUsize>))` at /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:487:1
note: inside `<EmptyArc as std::ops::Drop>::drop` at src/main.rs:26:70
   --> src/main.rs:26:70
    |
26  |                 let _ = Box::from_raw(self.inner as *mut AtomicUsize);
    |                                                                      ^
    = note: inside `std::ptr::drop_in_place::<EmptyArc> - shim(Some(EmptyArc))` at /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:487:1
    = note: inside `std::mem::drop::<EmptyArc>` at /home/sbarral/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:988:24
note: inside closure at src/main.rs:37:36
   --> src/main.rs:37:36
    |
37  |     let th = thread::spawn(move || drop(foo1));
    |                                    ^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error
```

**Comment by RalfJung** [comment]
So what's wrong with that error? The deallocation is indeed not synchronized -- deallocation is like a non-atomic write. So there is a race between a non-atomic write and an atomic write, and that is UB.

**Comment by RalfJung** [comment]
Essentially, in terms of data races, your implicit `drop(Box::from_raw(self.inner as *mut AtomicUsize))` is the same as a
```rust
let mut b = Box::from_raw(self.inner as *mut AtomicUsize);
*b.get_mut() = 0;
drop(b);
```

**Comment by sbarral** [comment]
The reason I don't expect it as necessary is that (1) the RMWs provide a total order, (2) the memory allocation was made on the main thread so is visible to both thread and (3) the deallocation is sequenced before the `fetch_sub`, so basically there is no possible concurrent modification of memory (well, at least that's what I'd expect...).

**Comment by RalfJung** [comment]
Do you agree that [this variant](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e9e0500988c5286fabcfd6203d6b48b8) indeed is UB due to a data race? That one is pretty clear: the non-atomic write at the `get_mut()` has no happens-before edge with the `fetch_sub` in the concurrent thread that also `drop`s.

And then deallocations act like non-atomic writes, which is why your original code is also racy.

> the deallocation is sequenced before after the fetch_sub

It's not. `Relaxed` does not induce an ordering on other operations, not even when used with an RMW.

**Comment by RalfJung** [comment]
No, I am pretty sure that is not the case. The total per-location order on RMWs is *not* includes in happens-before. Happens-before is the union of program-order and sync-with.

**Comment by sbarral** [comment]
I see that `ThreadSanitizer` complains in the same way as MIRI so I am clearly in the wrong here.

I will close the issue then, thank you for your patience!

**Comment by RalfJung** [comment]
Btw, those sequenced-before rules are for *sequential* code. They are related to "sequence points", and the fact that `x++ + x++` is UB in C. The rules for concurrent code are separate. https://en.cppreference.com/w/cpp/atomic/memory_order has more details on that (but is not a great learning resource).

**Comment by sbarral** [comment]
Yes, sequenced-before is only relevant for the same thread, that part was in fact clear to me. The section "Sequenced-before" in the link you provided actually defines it in terms of the evaluation order and points to the very link I provided earlier.

As you correctly pointed out earlier, my mistake was rather to assume that the total order provided by the RMWs could by itself ensure that, once the reference count is decreased from 2 to 1, then the thread that performed that operation would not be considered to be accessing that memory concurrently. Which seemed intuitive to me, but the C++ memory model is of course all but intuitive so I have only myself to blame for relying on intuition :-)

**Comment by RalfJung** [comment]
I wish I understood the model well enough to explain to you why the model is the way it is, but alas, I do not. ;) It would probably break some desirable optimizations, such as reordering `Relaxed` operations on different locations across each other.
