### ISSUE TITLE
Support synchronization primitives on Windows

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2628]
Thanks to @DrMeepster we now do support basic concurrency and atomics on Windows (https://github.com/rust-lang/miri/pull/2231). However, we do not support all of the standard library concurrency primitives. Based on my testing:
- [x] Mutex
- [x] RwLock
- [x] Condvar
- [x] thread parking

The fact that we don't support thread parking (which is needed by `std::sync::mpsc`) unfortunately blocks https://github.com/rust-lang/rust/pull/103681.

**Comment by RalfJung** [comment]
@DrMeepster if I recall, you actually had a first implementation of at least thread parking. Is that code still available somewhere?

**Comment by RalfJung** [comment]
Looks like the code still exists [here](https://github.com/rust-lang/miri/commits/556ff34b47eb3e402eb10e58c1a86219052e5958), in particular in https://github.com/rust-lang/miri/commit/2cd61e6fa52d9eac25b4acd93663d34975bd05bb.

**Comment by RalfJung** [comment]
Thread parking is implemented now, Condvars are still missing.

**Comment by DrMeepster** [comment]
Opened #2638 for condvars
