### ISSUE TITLE
scoped threads vs thread leaks

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2629]
The standard library scoped threads do not use the OS facilities for joining threads, but instead they implement join logic with their own synchronization primitives. (This seems to help with cleaning up thread resources ASAP rather than keeping them around until the scope finishes and all threads are joined.)

Unfortunately this can show up in Miri as a thread leak, if a thread gets scheduled away just after the custom join logic is done, and then the main thread finishes.

For now, a possible work-around is to use `-Zmiri-ignore-leaks`. But of course it'd be nice to find a better solution. Maybe, after the main thread is done, instead of halting execution immediately we could yield that thread N times (for some suitable N), thus giving other threads a chance to finish?

**Comment by oli-obk** [comment]
As an immediate step we should probably add a test for it ^^

The "leaked" threads don't have anything interesting to finish doing, so maybe we could have the scoped cleanup logic mark them as leakable or just join them under cfg(miri)

**Comment by RalfJung** [comment]
Yeah I considered just adding this to the standard library somewhere after `main` returns:
```rust
if cfg!(miri) {
  for _ in 0..100 { thread::yield_now(); }
}
```
But honestly that seemed a bit too hacky.^^ Seems better to do this on the interpreter side.

**Comment by oli-obk** [comment]
No I meant... actually join the threads in scoped thread code instead of just cleaning up their resources and letting them run to completion.

**Comment by RalfJung** [comment]
That would be a much bigger and more annoying set of `cfg(miri)`.

**Comment by RalfJung** [comment]
Yes it's a tight window. I definitely saw this happen, which is how I even noticed, but don't remember the exact code. But a test will always risk false negatives here.

**Comment by RalfJung** [comment]
For example, this code
```rust
use std::thread;

fn main() {
let mut a = vec![1, 2, 3];
let mut x = 0;

thread::scope(|s| {
    s.spawn(|| {
        println!("hello from the first scoped thread");
        // We can borrow `a` here.
        dbg!(&a);
    });
    s.spawn(|| {
        println!("hello from the second scoped thread");
        // We can even mutably borrow `x` here,
        // because no other threads are using it.
        x += a[0] + a[2];
    });
});
}
```
reproduces the problem with seed 26.

**Comment by saethlin** [comment]
Is there any particular reason to believe that "yield to all other threads on thread exit" isn't something we should/can do in the interpreter instead?

**Comment by RalfJung** [comment]
That's exactly what I suggested in the OP. :)
