### ISSUE TITLE
review all early aborts

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#263]
We might have some ordering issues, where an early abort hides UB or produces the wrong error.

**Comment by RalfJung** [comment]
In terms of "wrong error", often it is just not clear what the right error is when multiple error conditions apply -- like deallocating a pointer with the wrong size *and* alignment (and maybe even non-0 offset from the allocation base).

**Comment by RalfJung** [comment]
Things have been refactored several times since this issue was opened, is there still something actionable about this issue? I think we are now checking the alignment properly for all zero-sized accesses, and that was the main concern here if I recall correctly.
