### ISSUE TITLE
Unexpected alignment of `repr(packed)` struct containing a DST

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/miri#2632]
Example code ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c67354309342a10aead9574ec0a90ff0))

```rust
#![feature(layout_for_ptr, ptr_metadata)]
use std::{mem, ptr};

#[repr(C, packed)]
struct A {
    f: u32,
}

#[repr(C, packed)]
struct B {
    f: [u32],
}

fn main() {
    let a = A { f: 0 };
    dbg!(mem::align_of_val(&a));

    let storage = [0u8; 4];
    let b: *const B = ptr::from_raw_parts(storage.as_ptr().cast(), 1);

    dbg!(unsafe { mem::align_of_val_raw(b) });
}
```

Running this outside of Miri gives the output I would expect; values of `A` and `B` both have an alignment of 1:
```
[src/main.rs:16] mem::align_of_val(&a) = 1
[src/main.rs:21] unsafe { mem::align_of_val_raw(b) } = 1
```

But when running under Miri, I get this instead:
```
[src/main.rs:16] mem::align_of_val(&a) = 1
[src/main.rs:21] unsafe { mem::align_of_val_raw(b) } = 4
```

I would have expected the alignment of `B` to be 1 since it is `repr(packed)`. https://doc.rust-lang.org/nomicon/other-reprs.html#reprpacked says "repr(packed) forces Rust to strip any padding, and only align the type to a byte", and doesn't mention an exception for DSTs.

**Comment by RalfJung** [comment]
Good catch! This indeed seems wrong.

Miri's logic for this is [here](https://github.com/rust-lang/rust/blob/fd59d44f5880fea109fe68e31fab2486cd686fc6/compiler/rustc_const_eval/src/interpret/eval_context.rs#L570). And it seems like that subtly differs from the [codegen logic](https://github.com/rust-lang/rust/blob/50f6a9ed87e47c7a8ff6aefcde01a33821e80e20/compiler/rustc_codegen_ssa/src/glue.rs#L11). The cranelift one is [here](https://github.com/rust-lang/rust/blob/e54a13f18bf2873f12d556fb05bb60f2a7f75bfa/compiler/rustc_codegen_cranelift/src/unsize.rs#L190) and it *does* contain a [special case for packed types](https://github.com/rust-lang/rust/blob/e54a13f18bf2873f12d556fb05bb60f2a7f75bfa/compiler/rustc_codegen_cranelift/src/unsize.rs#L236-L241). Cc @bjorn3 

Looks like we really would want some way to share this code between all the backends and Miri...
