### ISSUE TITLE
Incorrect sign of zero on float `%`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2649]
The following program works fine at runtime but panics in Miri:
```rust
fn f(one: f64) -> f64 {
    (-1.0) % one
}

fn main() {
    let black_box_one = (std::env::args().len()) as f64;
    let result_rt = f(black_box_one);
    assert!(result_rt.is_sign_negative());
}
```
This is basically the Miri version of https://github.com/rust-lang/rust/issues/102403, leading to incorrect execution. It's similar to https://github.com/rust-lang/rust/issues/100233 (likely an apfloat porting bug) but a lot harder to work around...

**Comment by saethlin** [comment]
The program here doesn't panic anymore, and the linked issues are closed as completed by https://github.com/rust-lang/rust/pull/113843 so I think we're probably fixed too?

**Comment by RalfJung** [comment]
Ah, good point! This can be closed with a test: https://github.com/rust-lang/miri/pull/3094.
