### ISSUE TITLE
Miri warns about int2ptr when Stacked Borrows is disabled

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#2651]
In response to a suggestion from @RalfJung, I tried running the tests for `bitvec` with `-Zmiri-disable-stacked-borrows`, only to be greeted with a bunch of warnings about int2ptr. It seems to me like those are just noise with that flag applied?

**Comment by RalfJung** [comment]
Provenance is very much a thing even without Stacked Borrows, so the warning is definitely deliberate.

**Comment by saethlin** [comment]
Sure provenance exists, but in a world without Stacked Borrows, is there any downside from the perspective of Miri's analysis to doing ptr-int-ptr roundtrips? I thought the point of those warnings were to indicate that if the user wants to tighten up the results they get from Miri, those are the places to work. But with Stacked Borrows disabled, are there any approximate operations?

**Comment by saethlin** [comment]
I am upset that I didn't already know this. 😂

**Comment by RalfJung** [comment]
If you have ideas for better documenting/communicating this, I am all ears. :D
