### ISSUE TITLE
Using a mutable reference and shared read-write pointers (Cell references) at the same time is not caught

### ISSUE THREAD

**Issue by nandesu-utils** [rust-lang/miri#2692]
This is based on [`as_cell`](https://rust-lang.github.io/rfcs/1789-as-cell.html) feature that introduces opt-in temporary interior mutability via referencing using reference to a `Cell`.

For summary, the deal is that the default standard library interface to create such `Cell`ed references makes sure that you are not able to reuse the original mutable reference again. However if you would use unsafe code directly you basically keep that mutable reference and you are also able to use `Cell` references (pointers underneath) along leading to supposedly undefined behavior relatively to stacked borrows due to using a borrow that is not on top of the stack. I am not sure which one though.

Maybe `from_mut` method in the standard library explicitly creates a reborrow through lifetime parameter therefore example code does not make a reborrow at all so the problem is simply about aliasing rules. If these are not the reasons, *feel free to point that out to remove my misleading commentary.*

Happens on `miri 0.1.0 (8681d4c 2022-11-25)` and `miri 0.1.0 (a28f3c8 2022-11-20)`.

Rust permalinks:

* https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=fa1942088b465debeeaee74559791647
* https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=aed6c79d046c4e56941901bc3843b3e7

**Comment by RalfJung** [comment]
If I understood correctly, you are only reading from the mutable reference. So I think this is deliberate -- mutable references allow writes to pointers derived from them, and don't kill derived pointers on reads.

In fact under the model @Vanille-N is currently working on, this code would be fine even if you added some writes to `a`. Basically when you are turning `a` into a raw pointer, under that model you are allowed arbitrary aliasing between this mutable reference and *that particular raw pointer*, and then the `UnsafeCell` inherits all that.

**Comment by nandesu-utils** [comment]
> If I understood correctly, you are only reading from the mutable reference. So I think this is deliberate -- mutable references allow writes to pointers derived from them, and don't kill derived pointers on reads.

Doesn't this somehow represent `noalias` behavior in LLVM as in [reference](https://llvm.org/docs/LangRef.html#parameter-attributes)? Information about such topics is pretty scattered and it's pretty hard to make a picture that captures every language specifics. So, citating:

> `noalias`
>
> This indicates that memory locations accessed via pointer values [based](https://llvm.org/docs/LangRef.html#pointeraliasing) on the argument or return value are not also accessed, during the execution of the function, via pointer values not based on the argument or return value.

That is, being based on is a synonym to being derived from.

And also:

> In fact under the model @Vanille-N is currently working on, this code would be fine even if you added some writes to `a`. Basically when you are turning `a` into a raw pointer, under that model you are allowed arbitrary aliasing between this mutable reference and _that particular raw pointer_, and then the `UnsafeCell` inherits all that.

Basically what caught my eye was using both means of accessing memory at the same time while having an exclusive reference to the data in the first place. Is there some consistent explanation on how it *currently* works, maybe in unsafe-core-guidelines or internals/users forum? Perhaps I have read badly and this was thoroughly explained in stacked borrows articles.

**Comment by RalfJung** [comment]
> Doesn't this somehow represent noalias behavior in LLVM as in [reference](https://llvm.org/docs/LangRef.html#parameter-attributes)? Information about such topics is pretty scattered and it's pretty hard to make a picture that captures every language specifics. So, citing:

Yes I think what Miri does matches what the LLVM docs say. Do you see a contradiction?

It is explicitly okay in LLVM to derive `q` from `p` (where `p: noalias`), and then use both pointers in an interleaved way.

**Comment by RalfJung** [comment]
> Basically what caught my eye was using both means of accessing memory at the same time while having an exclusive reference to the data in the first place. Is there some consistent explanation on how it currently works, maybe in unsafe-core-guidelines or internals/users forum? Perhaps I have read badly and this was thoroughly explained in stacked borrows articles.

What Miri currently does follows the 'Stacked Borrows' model, which is described [here](https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md). This is all WIP.

**Comment by nandesu-utils** [comment]
Thank you very much, after I re-read the stacked borrows reference everything has become more clear to me. Looking forward to the new model!

I was kind of oblivious (sorry!) of the internals but now I don't think I have any remaining questions.

**Comment by RalfJung** [comment]
No worries, I know this stuff is complicated, and we haven't spent a lot of effort on docs yet. We're still in the model finding phase.
