### ISSUE TITLE
Purpose of `basic_block_count` variable.

### ISSUE THREAD

**Issue by yunji-yunji** [rust-lang/miri#2706]
I found `basic_block_count` variable in your codes, which raised a few questions:

1. What is the original purpose of `basic_block_count`?
I guess it can be used to calculate line coverage (block coverage).
I wonder if this variable in MIRI code is for the same purpose as I'm thinking.

2. Does MIRI interpreter also record other coverage information such as function and branch coverage?
If not, why? I was curious about this because I only found `basic_block_count` variables.

**Comment by saethlin** [comment]
It is much easier to have conversations about speculative ideas on the Zulip: https://rust-lang.zulipchat.com/#narrow/stream/269128-miri

`basic_block_count` is for `-Zmiri-report-progress`, which is a very simple mechanism to get Miri to tell you what code it is executing. Some programs are 100 to 1000 times slower in Miri, so this is useful when Miri seems like it is running forever on what you thought was a pretty quick program or test.

Miri does not record any coverage information. This has sort of been discussed before: https://rust-lang.zulipchat.com/#narrow/stream/269128-miri/topic/miri.20coverage

> If not, why?

Like so many things, nobody has built it yet.

**Comment by RalfJung** [comment]
I'm going to close this since the question in the issue title has been answered. Feel free to open a feature request issue about adding coverage information. :)

**Comment by yunji-yunji** [comment]
Got it. Thank you so much for your answer!
