### ISSUE TITLE
uninitialized bytes in a local variable are not caught

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/miri#2732]
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=85cc29b9605e4cbf37a44ef1d5d3aa7a)

```rust
use std::ptr::copy_nonoverlapping;

#[derive(Debug, PartialEq)]
#[repr(C)]
struct Foo {
    x: u8,
    // uninitialized padding goes here
    y: u16,
}

fn main() {
    let foo = Foo { x: 1, y: 2 };

    // Copy the bytes of foo to a buffer, including the uninitialized padding byte.
    let mut buf = [0u8; 4];
    unsafe {
        copy_nonoverlapping(&foo as *const Foo as *const u8, buf.as_mut_ptr(), 4);
    }

    // Copy the buffer back to foo2. This passes Miri.
    let mut foo2 = Foo { x: 0, y: 0 };
    unsafe {
        copy_nonoverlapping(buf.as_ptr(), &mut foo2 as *mut Foo as *mut u8, 4);
    }
    assert_eq!(foo, foo2);

    // Uncommenting any of the following lines fails Miri.
    // drop(buf);
    // buf = buf;
    // buf[1];
}
```

This is similar to https://github.com/rust-lang/miri/issues/2518 (uninitialized value behind a reference), except here the uninitialized value is in a local variable.

Is it expected that Miri doesn't currently trigger on this code? Any thoughts about whether this is likely to be UB in the future?

**Comment by saethlin** [comment]
The type of `buf` does not matter.

Writing this code is a very bad idea, but it isn't UB. Miri is correctly quiet here. The docs for `copy_nonoverlapping` say this:

> The copy is “untyped” in the sense that data may be uninitialized or otherwise violate the requirements of T. The initialization state is preserved exactly.

And in this code, I think Ralf would say you didn't "use" `buf`. Though _precisely_ what "use" means, I'm not exactly sure, though I think the terminology generally provides the right intuition. The Reference uses similar language around "producing a value" and explains a bit more precisely:

> Producing an invalid value, even in private fields and locals. "Producing" a value happens any time a value is assigned to or read from a place, passed to a function/primitive operation or returned from a function/primitive operation.

And you do none of those things to `buf`, so Miri is silent.

**Comment by RalfJung** [comment]
This question is not entirely settled, see https://github.com/rust-lang/unsafe-code-guidelines/issues/84. However making code like yours UB will require a lot of extra complexity and the benefit of that is unclear.

**Comment by oconnor663** [comment]
Good to know!
