### ISSUE TITLE
Add test ensuring that drop terminator of no-drop type is a NOP

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2737]
In https://github.com/rust-lang/rust/pull/103957 we realized that Miri's treatment of Drop terminators subtly differed from that of the codegen backends. That got fixed, but we don't have a test for that. Not sure if a test is even possible, but we custom_mir it might be?

Cc @JakobDegen

**Comment by JakobDegen** [comment]
It will be once I add storage statements at least. Will do so then
