### ISSUE TITLE
Miri does not support target x86_64-unknown-uefi

### ISSUE THREAD

**Issue by jyn514** [rust-lang/miri#2740]
I am not quite sure what's going on here, but @oli-obk thinks it's a bug in miri itself, unrelated to cargo or the standard library.
```
$ env MIRI_NO_STD=1 cargo miri test --target=x86_64-unknown-uefi
fatal error: file "/home/jyn/.local/lib/cargo/target/miri/x86_64-unknown-uefi/debug/deps/example-d7b0fa77a56c0a56.efi" not found or `cargo-miri` invoked incorrectly; please only invoke this binary through `cargo miri`
error: test failed, to rerun pass `--lib`

Caused by:
  process didn't exit successfully: `/home/jyn/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo-miri runner /home/jyn/.local/lib/cargo/target/miri/x86_64-unknown-uefi/debug/deps/example-d7b0fa77a56c0a56.efi --quiet` (exit status: 1)
```

**Comment by jyn514** [comment]
The source code for this is https://stackoverflow.com/questions/68455964/how-can-i-execute-tests-in-a-crate-that-gets-developed-for-a-non-default-target (with the failing import removed)

**Comment by bjorn3** [comment]
This will need to be extended to include `elf` I think: https://github.com/rust-lang/miri/blob/4f051a6df22174897cbd22775f84b7c9e3cb99b6/cargo-miri/src/phases.rs#L284-L287

**Comment by RalfJung** [comment]
Yeah Miri simply does not support this target currently.

Is there a way cargo-miri can figure out the binary file name extension for a target, without us having to maintain a list of all of them?

**Comment by jyn514** [comment]
I am confused why miri needs to know the extension in the first place? Does cargo not pass the output file name to you?

**Comment by bjorn3** [comment]
> Is there a way cargo-miri can figure out the binary file name extension for a target, without us having to maintain a list of all of them?

`echo | rustc --print file-names --crate-type bin --target ... --crate-name ____ -` is what cargo uses.

**Comment by RalfJung** [comment]
> Does cargo not pass the output file name to you?

Nope.

> echo | rustc --print file-names --crate-type bin --target ... --crate-name ____ - is what cargo uses.

Ah, that should work for Miri as well then.
