### ISSUE TITLE
miri does not report UB for reference to uninitialized value

### ISSUE THREAD

**Issue by gftea** [rust-lang/miri#2795]
run MIRI on below [rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=63dcb32f3a6244e11bb769b46683784f), it does not report undefined behavior for the codes reference to unitialized value
```rust
// example from rust-std docs
let m = MaybeUninit::<UnsafeCell<i32>>::uninit();
unsafe { UnsafeCell::raw_get(m.as_ptr()).write(5); }
let uc = unsafe { m.assume_init() };

assert_eq!(uc.into_inner(), 5);

// reference to unitiailized value due to `&*m.as_ptr()`
let m = MaybeUninit::<UnsafeCell<i32>>::uninit();
unsafe { UnsafeCell::get(&*m.as_ptr()).write(5); }
let uc = unsafe { m.assume_init() };

assert_eq!(uc.into_inner(), 5);
```

**Comment by bjorn3** [comment]
cc https://github.com/rust-lang/unsafe-code-guidelines/issues/386

**Comment by saethlin** [comment]
See https://github.com/rust-lang/miri/issues/2518#issuecomment-1232995305

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang/miri/issues/2518 -- this is a deliberate decision, for now. Though maybe we should keep one issue open to make it easier to find? Not sure.

**Comment by RalfJung** [comment]
Sounds good, let's close this one then.

Thanks for reporting a potential problem, @gftea.
