### ISSUE TITLE
is it UB or not if using cell's underlying data raw ptr after cell is moved

### ISSUE THREAD

**Issue by gftea** [rust-lang/miri#2796]
[rust playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b877bf8bc9e1ab773e2cc98e0c739319)

I am a bit confused about the "Cell::as_ptr()", user can escape the compiler check, and may still use the raw pointer after the cell is moved.

```rust
#[derive(Debug)]
struct Inner(isize);

impl Drop for Inner {
    fn drop(&mut self) {
        println!("drop inner {:?}", self as *const _);
    }
}

let m = Cell::new(Inner(0));
let m_ptr = m.as_ptr();

println!("before move: {:?}", m.as_ptr());

let h = thread::spawn(move || {
    // the `m` cell underlying data has different address after move
    println!("after move: {:?}", m.as_ptr());
    // `m` drop
});

// we can still read/write the original address after moving `m`
// should it be UB? 
// if yes, miri does not report it
// If not, what does the address really means?
unsafe {println!("m_ptr: {:?}, value: {:?}",  m_ptr, *m_ptr)};


```

**Comment by oli-obk** [comment]
Yea. We don't invalidate memory on move. Though maybe we should invalidate borrows to moved out memory?

**Comment by saethlin** [comment]
This is https://github.com/rust-lang/unsafe-code-guidelines/issues/188

**Comment by RalfJung** [comment]
So the answer to "is this UB" is - maybe. It hasn't been decided yet, and it is not clear how to best make Miri detect these csses.

@oli-obk, that would be possible (thougj not easy) with stacked borrows but with the plans we have for raw pointers in tree borrows it becomes a lot harder at best.

**Comment by RalfJung** [comment]
This is a UCG / t-opsem question, not a Miri question, so closing in favor of https://github.com/rust-lang/unsafe-code-guidelines/issues/188.
