### ISSUE TITLE
running miri in release mode should disable debug assertions

### ISSUE THREAD

**Issue by lukas-code** [rust-lang/miri#2797]
### Code

```rust
fn main() {
    debug_assert!(false);
}
```

This currently passes with `cargo run --release`, but panics with `cargo miri run --release`.

Since debug assertions can actually change the behavior of a program, I think it would be useful to allow running miri with debug assertions disabled.

**Comment by RalfJung** [comment]
This is currently a deliberate choice -- unfortunately undocumented. We should definitely at least fix that part. The reasoning is that Miri is anyway so slow that the benefit from the extra sanity checks outweighs the costs. OTOH I do agree that it can be confusing. I think we definitely want to keep overflow checks enabled (their cost in Miri is definitely negligible and this can find real bugs), I am less sure about regular debug assertions (which can actually be quite expensive).

You can force debug assertions to be disabled with `-Cdebug-assertions=off`

**Comment by saethlin** [comment]
So are you advocating for Miri not setting any values here? What do you think about this consideration: https://github.com/rust-lang/miri/issues/2497

**Comment by LegionMammal978** [comment]
I'm fine with Miri setting whatever it wants for `std`, `core`, etc.; it's always taken special incantations to fiddle with their `RUSTFLAGS`, and their behavior is unlikely to change much between them (unless the standard library is what is being debugged). What I'm more concerned about is the `RUSTFLAGS` of the user crate being compiled, since changes to the profile can sometimes have far more important effects to their behavior and control flow.

**Comment by RalfJung** [comment]
> I just ran into this today when writing a reproducer for a reachable unreachable_unchecked() in cipher (https://github.com/RustCrypto/traits/issues/1275). To be defensive, the crate precedes the unreachable_unchecked() with a debug_assert!(false). I've also seen a few other crates, e.g., parking_lot, that switch between unreachable!() and unreachable_unchecked() based on cfg!(debug_assertions).

There's no problem here though, is there? Reaching the `unreachable` will still be reported.

> Soundness can often be sensitive to the particular profile settings. I've seen some crates which are unsound only when overflow_checks are disabled, 

With overflow checks enabled, those crates then raise panics, which are still clearly pointing out there is a bug.

>  It can easily make these edge cases very confusing to debug when Miri's behavior differs from the compiler's default behavior, given the same profile settings in Cargo.toml.

Yeah that is fair, I can see how this can be baffling when it comes unexpected. So it's about trading off the extra test coverage from having debug assertions and overflow checks enabled in more cases, against this element of surprise.

**Comment by RalfJung** [comment]
> Obviously, --release can't make Miri go any faster

That might seem obvious to you but I don't think it is obvious in general. `cargo miri run` roughly means "please find some bugs" and one could reasonably expect that if Miri finds out-of-bounds accesses it can also find overflows, no matter the flags being passed later.

Anyway I explained my rationale above and that I think this is a trade-off.  I am not dead set on the current behavior, but it's also not entirely clear to me that we want to change anything (except for the docs). I wonder what @saethlin and @oli-obk think.

**Comment by LegionMammal978** [comment]
> `cargo miri run` roughly means "please find some bugs"

I suppose that's where we differ. To me, "please find some ordinary bugs" is `cargo run`: that will already find everying that would be caught by debug assertions or overflow checks. I'd only use `cargo miri run` when I'm doing something tricky with atomics, raw pointers, etc., and I specifically want to find unexpected UB that `cargo run` doesn't catch. I suppose that might change in the future, if Miri gains more options for simulating programs under different environments, but in the meantime I just can't really see it as a generic "bug-finding" tool separate from its focus on UB.

**Comment by RalfJung** [comment]
> I have definitely seen users try passing that flag before when they realize Miri is too slow, in the hopes that Miri will still look for UB while also applying optimizations.

I assume they didn't realize that applying optimizations means missing some UB? We certainly can't stop passing `-Zmir-opt-level=0`...

**Comment by saethlin** [comment]
> I assume they didn't realize that applying optimizations means missing some UB?

Yes, I think it is likely that they did not think through that, and that is why a sentence or two of warning could be the right thing here. At least in my experience, tools like ASan and UBsan are often used with optimizations and tend to find just as many bugs with optimizations on and off.

**Comment by RalfJung** [comment]
FWIW Miri could totally run with optimizations and would still find at least as many bugs as ASan and UBSan. But I don't think we want to do that.
