### ISSUE TITLE
Why does `cargo miri test` run sequentially on a single thread?

### ISSUE THREAD

**Issue by Voultapher** [rust-lang/miri#2805]
Unless I'm doing something wrong, why is the miri test runner not running the tests in parallel? I have a project that would greatly benefit from this.

**Comment by bjorn3** [comment]
When using `cargo miri test` the test harness is interpreted by miri itself. Miri can't run multiple interpreted threads at the same time. It has to switch between them inside the same OS thread. The fast majority of rustc can't be accessed from multiple threads and every MIR statement and terminator miri evaluates calls back into these non-thread safe parts of rustc several times. There is a project ongoing to allow rustc to work with multiple threads, but even then various data structures of miri itself likely don't like accesses from multiple threads at the same time.

**Comment by Voultapher** [comment]
Because if I have to wait 2+ seconds per test, forking will certainly be worth it.

**Comment by bjorn3** [comment]
Maybe a wrapper around `cargo miri test` could be written which lists all tests and then spawns a couple of `cargo miri test` processes with each the test list filtered such that they all execute equal parts of the test suite?

**Comment by Voultapher** [comment]
Wow that's exactly what I was looking for 5min -> 25 seconds.

**Comment by RalfJung** [comment]
Could be worth adding a section on nextest to our readme?

**Comment by saethlin** [comment]
https://github.com/rust-lang/miri/pull/2811
