### ISSUE TITLE
Leaking a heap allocation of pointer results in confusing output

### ISSUE THREAD

**Issue by nonl4331** [rust-lang/miri#2812]
Take the code:
```rust
let local = 0usize;
let leak_this = Box::new(&local as *const usize);
Box::into_raw(leak_this);
```
Running `cargo miri run` produces the following output:
```
The following memory was leaked: alloc1673 (Rust heap, size: 8, align: 8) {
    ╾0x28970[a1657]<3157>─╼                         │ ╾──────╼
}
alloc1657 (deallocated)
```
It is not immediately clear why alloc1657 is shown or the relation between alloc1673 and alloc1657. If alloc1657 were not deallocated it would be possible to interpret alloc1657 as leaked memory.
One suggestion would be to explicitly mention that the leaked memory contains alloc1657 and expand a1657 to alloc1657 for clarity.
```
The following memory was leaked: alloc1673 (Rust heap, size: 8, align: 8) {
    ╾0x28970[alloc1657]<3157>─╼                         │ ╾──────╼
}
alloc1673 contains a pointer: alloc1657 (deallocated)
```

**Comment by saethlin** [comment]
(my comment is directed at everyone else, not OP)

The fact that the leak report also says `a1657` instead of `alloc1657` also doesn't help with the confusing newcomer experience.

But more importantly: Why are we even mentioning that `alloc1657` is deallocated? The program has exited, so allocations can only be deallocated or leaked. If an allocation is leaked, it should be part of the leak report.

**Comment by oli-obk** [comment]
Hmm... I thought it to be strictly better to tell the user about all the things their leaked alloc references, but it was definitely not based on any data

**Comment by saethlin** [comment]
This is not the first time I've seen a newcomer just be bewildered by the amount of text that gets written to the screen and just ignore most of it. It is of course possible to puzzle through this report, but the fact that it has so much information and dense notation and a lot of these IDs I think causes people to skim over it way too often.

It wouldn't hurt to link people to something like a glossary or the rustc error index.

But in this case specifically, I think unless we can explain how a user would use the
```
alloc1657 (deallocated)
```
to debug their leak, not outputting that sounds like a better option.

**Comment by oli-obk** [comment]
In that case, maybe we should change the `Allocation` printing logic (in rustc_interpret), too?

```
The following memory was leaked: alloc1673 (Rust heap, size: 8, align: 8) {
    ╾0x28970[dangling]─╼                         │ ╾──────╼
}
```

**Comment by saethlin** [comment]
I think Miri prints `0xaddr[noalloc]` in that case. We should try to be consistent, so whatever the terminology we should try to reuse the code.

**Comment by RalfJung** [comment]
> One suggestion would be to explicitly mention that the leaked memory contains alloc1657 and expand a1657 to alloc1657 for clarity.

FWIW, what happens here is that `0x28970[alloc1657]<3157>` is too wide to fit into the space that 8 bytes take in the memory dump, so `alloc` gets shortened to `a` such that the alignment of bytes is preserved in the output.
