### ISSUE TITLE
can't call foreign function `__libc_current_sigrtmin`

### ISSUE THREAD

**Issue by dead-claudia** [rust-lang/miri#2832]
`__libc_current_sigrtmax` is present (and so I can use `libc::SIGRTMAX()` without issue), but not `__libc_current_sigrtmin` for some reason (preventing me from using `libc::SIGRTMIN()`).

I could easily shim this to 35 for practical testing purposes (kernel starts at 32, glibc reserves 3 for its threading library), but it'd be nice to not have to hack that in.

**Comment by RalfJung** [comment]
Yeah that should be easy to add in Miri.
