### ISSUE TITLE
Clean up support for "aligning the backing store of allocations"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2836]
In https://github.com/rust-lang/rust/pull/108022 I raised some concerns post-landing. Let's track here that these need to be resolved, or else we should remove the interface again. In its current form it is at the very least insufficiently documented; more likely the trait needs to be adjusted.

Cc @CraftSpider

**Comment by CraftSpider** [comment]
I'm tied whether to respond here or on the original comments - I'll respond there, but copy them over here if you would rather all discussion have one spot.

**Comment by RalfJung** [comment]
I'm fine with discussing in that PR, this issue is to make sure we don't forget creating a new PR that resolves the problems. :)
