### ISSUE TITLE
Should Miri report MIR validation failures?

### ISSUE THREAD

**Issue by cbeuw** [rust-lang/miri#2840]
`rustc` contains a MIR [validation pass](https://github.com/rust-lang/rust/blob/9be9b5e09ad834e2ba9f2571ca17059e18f89b71/compiler/rustc_const_eval/src/transform/validate.rs) which detects ill-formed MIR. Currently Miri does not report MIR validation failures, but should it?

For instance, in runtime MIR, [`Deref` must the the first projection](https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/mir/syntax/enum.AnalysisPhase.html#variant.PostCleanup) if one exists. This code (https://github.com/rust-lang/rust/issues/110228) performs a dereference after a field projection, so it fails MIR validation, but Miri runs this without any complaint
```rust
#![feature(custom_mir, core_intrinsics)]
extern crate core;
use core::intrinsics::mir::*;
#[custom_mir(dialect = "runtime", phase = "optimized")]
pub fn fn0() {
    mir! {
        let x: i32;
        let tuple: (*mut i32,);
        {
            tuple.0 = core::ptr::addr_of_mut!(x);
            *(tuple.0) = 1;
            Return()
        }
    }
}
pub fn main() {
    fn0();
}
```

**Comment by RalfJung** [comment]
I am not entirely sure why that validation pass is skipped in Miri. @oli-obk is this some accident in MIR pass management?

**Comment by matthiaskrgr** [comment]
I had a look since I already have a rustc+miri with debug assertions laying around and I didn't see anything interesting :thinking: 

`MIRIFLAGS="-Zvalidate-mir"  RUSTFLAGS="-Zvalidate-mir"  ~/.cargo/bin/cargo  +local-debug-assertions miri run`

````
Preparing a sysroot for Miri (target: x86_64-unknown-linux-gnu)... done
WARNING: Ignoring `RUSTC_WRAPPER` environment variable, Miri does not support wrapping.
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `/home/matthias/.rustup/toolchains/local-debug-assertions/bin/cargo-miri runner target/miri/x86_64-unknown-linux-gnu/debug/miritest`
````

**Comment by RalfJung** [comment]
If I try this with today's Miri, I do get the expected ICE.
