### ISSUE TITLE
Is this self reference unsafe?

### ISSUE THREAD

**Issue by joshua-maros** [rust-lang/miri#2844]
I am having troubles understanding what MIRI is tripping over in the following code:

```rust
struct Thing {
    reff: &'static i32,
    data: AliasableBox<i32>,
}

#[test]
fn check() {
    let data = 0;
    let data = AliasableBox::from_unique(Box::new(data));
    let reff: &'static i32 = unsafe { &*(AliasableBox::as_ref(&data) as *const _) };
    let thing = Thing { reff, data };
    drop(thing);
}
```

(I have legitimate reasons to use `'static` instead of a pointer, summary being that this is part of auto-generated code that is designed to work with arbitrary user types that store their own references.)

<details>
<summary>It produces the following error:</summary> 

```
test ok_tests::check ... error: Undefined Behavior: not granting access to tag <200288> because that would remove [SharedReadOnly for <200335>] which is strongly protected because it is an argument of call 55307
    --> /home/josh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1014:9
     |
1014 |         Box(unsafe { Unique::new_unchecked(raw) }, alloc)
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not granting access to tag <200288> because that would remove [SharedReadOnly for <200335>] which is strongly protected because it is an argument of call 55307
     |
     = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
     = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <200288> was created by a SharedReadWrite retag at offsets [0x0..0x4]
    --> examples/src/ok_tests.rs:92:16
     |
92   |     let data = AliasableBox::from_unique(Box::new(data));
     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: <200335> is this argument
    --> examples/src/ok_tests.rs:95:5
     |
95   |     drop(thing);
     |     ^^^^^^^^^^^
     = note: BACKTRACE (of the first span):
     = note: inside `alloc::boxed::Box::<i32>::from_raw_in` at /home/josh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:1014:9: 1014:58
     = note: inside `alloc::boxed::Box::<i32>::from_raw` at /home/josh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/boxed.rs:958:18: 958:48
     = note: inside `ouroboros::macro_help::AliasableBox::<i32>::reclaim_as_unique_box` at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/aliasable-0.1.3/src/boxed.rs:57:9: 57:45
     = note: inside `<ouroboros::macro_help::AliasableBox<i32> as core::ops::Drop>::drop` at /home/josh/.cargo/registry/src/github.com-1ecc6299db9ec823/aliasable-0.1.3/src/boxed.rs:72:26: 72:54
     = note: inside `core::ptr::drop_in_place::<ouroboros::macro_help::AliasableBox<i32>> - shim(Some(ouroboros::macro_help::AliasableBox<i32>))` at /home/josh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1: 490:56
     = note: inside `core::ptr::drop_in_place::<ok_tests::Thing> - shim(Some(ok_tests::Thing))` at /home/josh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:490:1: 490:56
     = note: inside `core::mem::drop::<ok_tests::Thing>` at /home/josh/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:979:24: 979:25
note: inside `ok_tests::check`
    --> examples/src/ok_tests.rs:95:5
     |
95   |     drop(thing);
     |     ^^^^^^^^^^^
note: inside closure
    --> examples/src/ok_tests.rs:90:12
     |
89   | #[test]
     | ------- in this procedural macro expansion
90   | fn check() {
     |            ^
     = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
```
</details>

However, it does not error if I write out what I understand the original code to be doing:
```rust
#[test]
fn check() {
    let data = 0;
    let data = AliasableBox::from_unique(Box::new(data));
    let reff: &'static i32 = unsafe { &*(AliasableBox::as_ref(&data) as *const _) };
    drop(reff);
    drop(data);
}
```

Is there something I am overlooking that happens when introducing the struct or is MIRI being too eager here?

**Comment by saethlin** [comment]
> Is there something I am overlooking that happens when introducing the struct or is MIRI being too eager here?

Miri is correctly checking Stacked Borrows.

Stacked Borrows has two concepts which are interacting here to confuse you; protectors (which are introduced when a reference is passed as an argument, to model `dereferenceable`) and field retagging, where reference members of structs passed by value are treated as if they are all independent arguments too. This might sound a bit odd at first, but it ensure that you don't lose any optimizations by wrapping a reference in a struct (and possibly many references in a struct).

So in the UB example, when you call `drop` the reference member is treated as a reference argument which must be valid when the function returns.

Field retagging is a big problem for `ouroboros`. Miri supports 3 variants: `none`, `scalar`, and `all`. `scalar` models how rustc applies the LLVM pointer attributes through newtypes. But there's a zero-cost-abstraction argument that we should apply them through larger structs too. If you pass `-Zmiri-retag-fields=all`, the `ouroboros` test suite fails. I think you are being saved by something right now which just barely pushes `BoxAndRef` into not falling into the rustc Scalar ABI. Otherwise, your tests would fail by default.

**Comment by joshua-maros** [comment]
I appreciate the help, but I am still a bit confused. I understand you to be saying that the code in the first example is equivalent in terms of safety to:

```rust
fn drop_wrapper(reff: &'static i32, data: AliasableBox<i32>) {
    drop(reff);
    drop(data);
}

#[test]
fn check() {
    let data = 0;
    let data = AliasableBox::from_unique(Box::new(data));
    let reff: &'static i32 = unsafe { &*(AliasableBox::as_ref(&data) as *const _) };
    drop_wrapper(reff, data);
}
```

Which MIRI gives a similar error. But then why is it fine to have an invalid `'static` reference *inside* a function when it's not valid to have it as an argument *to* a function? Why must the argument remain valid but the variable does not need to, even though neither of them are used again after they become invalid?

I thought it might have something to do with code reordering, that the compiler might move `drop(reff)` to after `drop(data)` if it thinks `reff` is `'static`, but the same could be said about the body of the second example, which MIRI allows.

**Comment by saethlin** [comment]
> But then why is it fine to have an invalid 'static reference inside a function when it's not valid to have it as an argument to a function?

Quite simply, because for a long time rustc has promised LLVM that references when passed to a function are valid for the entire function, by putting `dereferenceable` on such reference arguments (along with newtype wrappers around references).

**Comment by joshua-maros** [comment]
I see, thanks for the help!
