### ISSUE TITLE
separate static from local allocations

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#285]
Leaving this here so it doesn't get lost:

We should separate the `AllocId` generation for locals and globals. One can count from `0` upwards, the other from `u64::max_value()` downwards. This allows us to reuse the `AllocId`s across evaluations without erasing the globals (which shouldn't change in CTFE-mode anyway). This allows us to use a `Vec` for globals instead of requiring the `HashMap` which will have lots of holes after a few executions. @eddyb notes that this is necessary for interning the allocations under the `'tcx` lifetime.

miri still contains code related to mutable statics, as a first step that has to be moved into the machine.

**Comment by RalfJung** [comment]
So the concern is that currently, if we do this, we will have many holes in the HashMap? That should not be a problem though, should it? HashMaps should be able to deal with that.

**Comment by oli-obk** [comment]
I think the problem is with interning in rustc. @eddyb?

**Comment by eddyb** [comment]
Yes, rustc requires monotonicity (cache/intern-append-only) for global state so no locals can end up in `TyCtxt` but we need globals somewhere in there to use them from the typesystem.

**Comment by oli-obk** [comment]
We could still use a HashMap on the TyCtxt end and keep our current AllocId scheme, right? As long as we never intern a local

**Comment by eddyb** [comment]
Yeah but we usually do that with references which gives us free deduplication. Having non-sequential IDs would be messy *but I suppose* it could work if the actual index inside is private and there's a method to "allocate" the next ID.

**Comment by oli-obk** [comment]
So, since we can't modify statics after they are in the `TyCtxt`, this also means statics always need to be backed by an allocation, since $someone might want to take the address of one of them, and we can't move from `ByVal` to `ByRef` after the fact. The alternative would be not caching `ByVal` globals, but that sounds prone to errors.

**Comment by eddyb** [comment]
@oli-obk `static` should be rare so making them all memory seems fine to me.
`const` is copied *anyway* at each use site.

**Comment by oli-obk** [comment]
Ha. Making them always backed by an allocation found a bug. We used to accept reading the wrong type from a static if it was a primitive. E.g. reading a `u64` when it's just a `u32`. The moment we have allocations this is nicely checked by `Memory`. I should benchmark whether scrapping the value optimization for locals has no effect on performance. This could make everything much cleaner.

**Comment by eddyb** [comment]
As long as they're removed between distinct evaluation runs for globals and whatnot (i.e. local memory is transient and not reachable from `TyCtxt`) then memory-only would probably work fine.

**Comment by RalfJung** [comment]
@oli-obk is this still planned? I remember talking about some proposals that you eventually discarded.

**Comment by oli-obk** [comment]
There are a lot of issues (e.g. interning allocations would need to convert local ids to new global ids) with this scheme and few advantages, so I'm going to scraop it.
