### ISSUE TITLE
The test suite does not print the flags used any more

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2886]
The output for the ui tests we run looks like this now
```
       Running tests/compiletest.rs (target/debug/deps/compiletest-775c57fcf04dec4e)
  ## Running ui tests in tests/pass against miri for x86_64-unknown-linux-gnu
  tests/pass/adjacent-allocs.rs (stack) ... ok
  tests/pass/adjacent-allocs.rs (tree) ... ok
```
With compiletest, it used to be the case that we also print the flags used somewhere. That is quite useful to figure out whether this is the regular run or the "mir-opt-level=4 run".

**Comment by oli-obk** [comment]
Whoops, I knew about that. I will re-add that message
