### ISSUE TITLE
Clarify in data race errors when a Read or Write is actually from the aliasing model

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#2921]
Since https://github.com/rust-lang/miri/issues/2648 it is possible to have a data race reported which points at code and says it does a Read or a Write, when there is actually no memory access in said code. The fact that a reborrow can even be relevant for data races is on itself surprising, and if a user is not already familiar with the fact that the aliasing model and data race models interact, these diagnostics can look like a bug.

See https://github.com/rust-lang/miri/issues/2920 for an example of a surprised user.

**Comment by RalfJung** [comment]
The same applies to Tree Borrows.

**Comment by RalfJung** [comment]
Fixed by https://github.com/rust-lang/miri/pull/3385
