### ISSUE TITLE
A shared reference to `static mut` stored in another static can be used mutably

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/miri#2937]
```rust
struct Foo(*mut i32);
unsafe impl Sync for Foo {}

static mut FOO: i32 = 0;
static PTR: Foo = Foo(unsafe { &FOO as *const i32 as *mut i32 });

fn main() {
    unsafe {
        let _r = &mut *PTR.0;
    }
}
```

[Does not report any error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=374a5a5f7511d905ade7e65213e7f4c6), even though it definitely contains UB because [a similar code does report](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7ad5ecc1b368b51ac41c48b9338c2fa6):
```rust
static mut FOO: i32 = 0;

fn main() {
    unsafe {
        let p = &FOO as *const i32 as *mut i32;
        let _r = &mut *p;
    }
}
```

This may be because of #121.

**Comment by RalfJung** [comment]
This is because we don't have an aliasing model at compile time, so nothing is remembering that this pointer originates from a shared reference.

We also haven't made a decision on whether aliasing rules even apply at the boundary between compiletime and runtime. They are not super useful here I think since everything is global... But that is a UCG question.

**Comment by isaacthefallenapple** [comment]
@RalfJung Does that imply this isn't UB? Or just unspecified? Chiming in because this originated from [my question on SO](https://stackoverflow.com/questions/76515592/is-t-as-const-t-as-mut-t-sound-for-static-mut-items).

**Comment by RalfJung** [comment]
It is deep in undecided/unspecified territory. So please don't do it. :)

**Comment by RalfJung** [comment]
I have opened https://github.com/rust-lang/unsafe-code-guidelines/issues/424 to track this question from a specification side. Thanks for bringing this to my attention!

There's nothing to be done on the Miri side here currently, so I will close this issue.
