### ISSUE TITLE
Erroneous "error: Undefined Behavior"?

### ISSUE THREAD

**Issue by EricLBuehler** [rust-lang/miri#2961]
Hello everyone,

I have been using Miri to debug one of my projects (https://github.com/EricLBuehler/trc) in which I am trying to implement new_cyclic. 

However, I ran into what I believe to be an erroneous UB error. I have attached a shortended example below. Note: It will not compile, and the version on Github is not the latest. However, is there anything wrong you can see at a glance? I tried to make it as close as possible to the Arc implementation: https://doc.rust-lang.org/src/alloc/sync.rs.html#431

My testing indicates that the read of `weakcount` through `init_ptr` is where the UB error is raised - not the one through `shareddata` directly.

Note: weakcount being initialized to 0 is okay.

```rust
pub fn new_cyclic<F>(data_fn: F) -> Self
    where
        F: FnOnce(&Weak<T>) -> T,
    {
        let shareddata: NonNull<_> = Box::leak(Box::new(SharedTrcInternal {
            atomicref: AtomicUsize::new(0),
            weakcount: AtomicUsize::new(0),
            data: std::mem::MaybeUninit::<T>::uninit(),
        }))
        .into();

        let weak_d = unsafe { shareddata.as_ref() }
            .weakcount
            .load(std::sync::atomic::Ordering::Relaxed);
        println!("{weak_d}");

        let init_ptr: NonNull<SharedTrcInternal<T>> = shareddata.cast();

        let weak_d = unsafe { init_ptr.as_ref() }
            .weakcount
            .load(std::sync::atomic::Ordering::Relaxed);
        println!("{weak_d}");

        let weak: Weak<T> = Weak { data: init_ptr };

        let data = data_fn(&weak);
...
}

```

Thank you for help!

**Comment by RalfJung** [comment]
Please share more details, in particular the exact error message you are getting.

**Comment by EricLBuehler** [comment]
---- src/trc.rs - trc::Trc<T>::new_cyclic (line 390) stdout ----
Test executable failed (exit status: 1).

stdout:
0

stderr:
error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory
   --> /home/ericbuehler/trc/src/trc.rs:417:22
    |
417 |           let weak_d = unsafe { init_ptr.as_ref() }
    |  ______________________^
418 | |             .weakcount
419 | |             .load(std::sync::atomic::Ordering::Relaxed);
    | |_______________________________________________________^ using uninitialized data, but this operation requires initialized memory
    |
    = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
    = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
    = note: BACKTRACE:
    = note: inside `trc::Trc::<main::_doctest_main_src_trc_rs_390_0::T>::new_cyclic::<[closure@src/trc.rs:10:27: 10:30]>` at /home/ericbuehler/trc/src/trc.rs:417:22: 419:56
note: inside `main::_doctest_main_src_trc_rs_390_0`
   --> src/trc.rs:397:11
    |
10  | let trc = Trc::new_cyclic(|x| T(x.clone()));
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `main`
   --> src/trc.rs:398:3
    |
11  | } _doctest_main_src_trc_rs_390_0() }
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

**Comment by RalfJung** [comment]
Hard to say without a runnable example. The `cast()` is suspicious though -- doesn't `shareddata` already have type `NonNull<SharedTrcInternal<T>>`?

**Comment by RalfJung** [comment]
Ah, looks like it has type `NonNull<SharedTrcInternal<MaybeUninit<T>>>`. There is no guarantee that these two types are laid out the same way, so `weakcount` might be at a different offset.

To actually see them at different offsets is surprising though. Are you setting `-Zrandomize-layout`?

You probably want to make `SharedTrcInternal` `#[repr(C)]` if you are doing layout shenanigans like this.

**Comment by EricLBuehler** [comment]
The full Miri invocation was `cargo +nightly miri test`. Adding repr(C) fixed it!
