### ISSUE TITLE
Should `./miri run` set a default edition?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#2999]
`./miri run` fails on a bunch of our test files since they require a newer edition. Maybe we should add `--edition 2021` or so to the flags (matching the edition used for our tests)? This does mean users cannot set an edition themselves any more, but that should rarely be required. (And we could also inhibit this flag if we see a user-passed `--edition`.)

**Comment by saethlin** [comment]
Having to specify the latest edition is really annoying; we should probably default to the latest. That's what the playground and godbolt do.

**Comment by oli-obk** [comment]
We could do that at the miri level if we wanted to. We don't have to follow rustc's CLI exactly

**Comment by RalfJung** [comment]
I think I'd rather keep the miri binary matching rustc.

**Comment by RalfJung** [comment]
With the changes in https://github.com/rust-lang/rust/pull/118692, more files will stop working with the 2015 edition.

I think we can just start with a single heuristic: if we don't find `--edition` in the flags, we add `--edition 2021`.

I wish rustc would just use the last flag when there are multiple `--edition`; currently it errors which makes this rather non-compositional...
