### ISSUE TITLE
Report UB instead of ICEing when SIMD operands have incompatible size

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#3076]
In a lot of our SIMD intrinsics, we assert that operands which must be equal size are equal size. Such a situation can arise because of an implementation mistake which would justify an ICE, but they can also arise if someone tries to declare their own LLVM intrinsics and gets it wrong. For example:
```rust
#![feature(link_llvm_intrinsics, simd_ffi)]
#[allow(improper_ctypes)]
use std::arch::x86_64::*;

extern "C" {
    #[link_name = "llvm.x86.sse2.sqrt.pd"]
    fn oof(x: __m128d) -> __m256d;
}

fn main() {
    unsafe {
        oof(_mm_set_pd(0.0, 0.0));
    };
}
```

This should report UB instead of ICEing.

**Comment by RalfJung** [comment]
We generally ICE when intrinsics are used the wrong way. I don't think we should make an exception for SIMD intrinsics.

`link_llvm_intrinsics` sounds like a feature on par with `feature(intrinsics)`: if you use it wrong, don't expect the compiler to give nice error messages.

**Comment by saethlin** [comment]
Hm. My concern is that we attach this text to an ICE:
```
error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/miri/issues/new
```
Which is not appropriate if the ICE is actually user error.

**Comment by RalfJung** [comment]
Yeah, that text is wrong when intrinsics are involved (and possibly with other internal features as well), see e.g. [this example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=b575ec82ea8304fd93c96abdc6d49612).

I'm fairly sure it's also possible to ICE rustc by misusing intrinsics, so this is not really a Miri issue.

**Comment by RalfJung** [comment]
Here's a [rustc ICE](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=87d587e98265e688b0cb4b48b3c15eff) that's not-a-bug due to being related to intrinsics.

We should clarify the message printed on an ICE (but getting access to enough state to figure out if any internal feature was enabled might be tricky). But that's a rustc issue, not a Miri issue.

**Comment by RalfJung** [comment]
This now prints
```
warning: the feature `link_llvm_intrinsics` is internal to the compiler or standard library
 --> src/main.rs:1:12
  |
1 | #![feature(link_llvm_intrinsics, simd_ffi)]
  |            ^^^^^^^^^^^^^^^^^^^^
  |
  = note: using it is strongly discouraged
  = note: using it is strongly discouraged
  = note: `#[warn(internal_features)]` on by default
```

FWIW with a regular rustc build it doesn't even ICE, it hits an LLVM assertion. So I don't think there is anything else we want to do in the Miri side here.

https://github.com/rust-lang/rust/issues/116217 tracks the ICE message.

**Comment by saethlin** [comment]
Thanks! I agree that making this an internal feature is a good improvement.
