### ISSUE TITLE
Is a stacked borrows error in iced-x86 a problem?

### ISSUE THREAD

**Issue by LunNova** [rust-lang/miri#3082]
Is the stacked borrows `error: Undefined Behavior: trying to retag from <2907067> for SharedReadOnly permission at alloc355283[0x1], but that tag does not exist in the borrow stack for this location` error described in more detail at https://github.com/icedland/iced/issues/455 due to a bug in iced-x86?

**Comment by saethlin** [comment]
It's nice to hear about people using Miri on iced, I've used that crate as a stress test.

I think you are asking about https://github.com/rust-lang/unsafe-code-guidelines/issues/134 or https://github.com/rust-lang/unsafe-code-guidelines/issues/256 (those issues are about the same situation but have slightly different discussion).

The fact that Stacked Borrows does not accommodate the &Header pattern is generally accepted as a problem with the model. There is an alternative model available in Miri via `MIRIFLAGS=-Zmiri-tree-borrows` which permits the &Header pattern but it is still somewhat under-construction, https://github.com/rust-lang/miri/pull/3067 for example.

I would have more confidence in my code being well-behaved if it is accepted by Stacked Borrows. But if you can get Miri to execute more of your code by turning on Tree Borrows instead, that's a good practical option.

**Comment by LunNova** [comment]
Closing as your answer explains why it failed and it looks like there's existing in progress work. Thanks for the help!
