### ISSUE TITLE
Is mutating value behind a shared reference undefined behavior?

### ISSUE THREAD

**Issue by StevenJiang1110** [rust-lang/miri#3151]
A simple example is
```rust
let v = vec![0u8, 1, 2, 3, 4, 5];
// Creates a slice on vector
let slice = &v;
unsafe {
     // Mutates the value via raw pointer
     let ptr = v.as_ptr() as *mut u8;
     *ptr = 100;
}
// Ensure slice is still alive.
assert_eq!(slice[0], 100);
```
I run `cargo miri test` and miri does not report error. Is this an undefined behavior? Or miri does not cover such case?

**Comment by RalfJung** [comment]
`slice` has type `&Vec`. You are not mutating the Vec itself, you are mutating data that is one pointer indirection away. The aliasing models implemented by Miri only enforce reference requirements at the top level, not recursively behind other references. For the case of Vec, there isn't even an inner reference there, just a raw pointer.

The way `as_ptr` happens to be implemented currently, it also doesn't generate immutability requirements. This can change any time though.

So the code is highly questionable, and definitely has library UB (it breaks the API contract of `Vec`). However, under the models we are currently considering, it does not have language UB, which is the only UB Miri can detect. So the compiler currently won't do funny optimizations on your code, but future versions of the standard library might change `as_ptr` in a way that the compiler *will* then do funny optimizations on your code. Miri can only check your code against the current version of the libraries you are using, not against all possible future versions.

**Comment by StevenJiang1110** [comment]
Thanks a lot. I used to think UB only contains UAF, DF, etc. But I don't know how to define this kinds of UB. Now I learned that code breaks library API contract is also UB.

**Comment by RalfJung** [comment]
There are two kinds of UB: language UB is a violation of your contract with the compiler, that's for things like UAF and DF but also reference aliasing violations. Library UB is a violation of your contract with the libraries you are using, such as using as_ptr in ways that its documentation does not allow.

Miri can unfortunately only detect language UB.
