### ISSUE TITLE
MIRI does not respect operators precedence

### ISSUE THREAD

**Issue by tower120** [rust-lang/miri#3156]
```rust
const S1: bool = true;
const S2: bool = true;
let s3: bool = MaybeUninit()::uninit().assume_init();
if S1 | S2 | s3{
    // this triggers MIRI, since it tries to access s3
}

if S1| S2{
    // This is OK.
} else if s3{
}
```

**Comment by RalfJung** [comment]
There's no bug here that I can see. `|` is not the same as `||`.

**Comment by tower120** [comment]
Aren't they the same for bools?

**Comment by tower120** [comment]
Yes you're right. Sorry for false alarm.

**Comment by RalfJung** [comment]
Your UB is already in this line
```rust
let s3: bool = MaybeUninit()::uninit().assume_init();
```
Here you call `assume_init` even though you didn't init anything.

Nothing after that matters.

**Comment by tower120** [comment]
It virtually does not exists (never-ever touched, not for read, not for write) under certain static/compile -time condition.
I want that due to lack of template/generics specialization in RUST. (ideally, it would not exists)

**Comment by RalfJung** [comment]
That makes no difference at all. If you write the code, and that function is execute, then the value exists, that's all that matters.

Quoting https://doc.rust-lang.org/reference/behavior-considered-undefined.html, it is UB when you do the following:
> Producing an invalid value, even in private fields and locals. 

Here's a whole blog post explaining why that kind of code has to be UB in an optimizing compiler: https://www.ralfj.de/blog/2020/07/15/unused-data.html.

**Comment by tower120** [comment]
I see, thank you.
