### ISSUE TITLE
Does not run with Winit 0.28.7 on Windows

### ISSUE THREAD

**Issue by stefnotch** [rust-lang/miri#3157]
I downloaded [a project that uses Winit](https://github.com/ash-rs/ash/tree/master/examples), and when starting it using Miri, I get the following error message

```
     Running `C:\Users\Stefnotch\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo-miri.exe runner C:\Users\Stefnotch\Downloads\ash-master\target\miri\x86_64-pc-windows-msvc\debug\texture.exe`
error: unsupported operation: can't call foreign function `GetCurrentThreadId` on OS `windows`
   --> C:\Users\Stefnotch\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:191:34
    |
191 |         let thread_id = unsafe { GetCurrentThreadId() };
    |                                  ^^^^^^^^^^^^^^^^^^^^ can't call foreign function `GetCurrentThreadId` on OS `windows`
    |
    = help: this is likely not a bug in the program; it indicates that the program performed an operation that the interpreter does not support
    = note: BACKTRACE:
    = note: inside `winit::platform_impl::platform::event_loop::EventLoop::<()>::new` at C:\Users\Stefnotch\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\platform_impl\windows\event_loop.rs:191:34: 191:54
    = note: inside `winit::event_loop::EventLoopBuilder::<()>::build` at C:\Users\Stefnotch\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\event_loop.rs:121:25: 121:83
    = note: inside `winit::event_loop::EventLoop::<()>::new` at C:\Users\Stefnotch\.cargo\registry\src\index.crates.io-6f17d22bba15001f\winit-0.28.7\src\event_loop.rs:269:9: 269:40
note: inside `examples::ExampleBase::new`
   --> C:\Users\Stefnotch\Downloads\ash-master\examples\src\lib.rs:213:30
    |
213 |             let event_loop = EventLoop::new();
    |                              ^^^^^^^^^^^^^^^^
note: inside `main`
   --> examples\src\bin\texture.rs:28:20
    |
28  |         let base = ExampleBase::new(1920, 1080);
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to previous error

error: process didn't exit successfully: `C:\Users\Stefnotch\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\bin\cargo-miri.exe runner C:\Users\Stefnotch\Downloads\ash-master\target\miri\x86_64-pc-windows-msvc\debug\texture.exe` (exit code: 1)
~\Downloads\ash-master\examples>
```

What could be done about this issue?

**Comment by RalfJung** [comment]
Yeah, Miri's support for emulating Windows API has a lot of gaps. Adding support for `GetCurrentThreadId` should be fairly easy.

Alternatively, using `--target x86_64-unknown-linux-gnu` should help; Miri can run any target on any host, and Linux targets generally have more API emulation implemented. However, looking at the winit crate, it seems to be made for GUI applications, and Miri does not support GUI applications on any target -- and there are currently no plans to add such support, these APIs are just too big.

**Comment by stefnotch** [comment]
Okay, that makes sense.
Should running Winit's event loop (without creating any windows) be supported? Since the example seems to be failing at `EventLoop::new()`

**Comment by RalfJung** [comment]
I don't know anything about winit, so it's hard to say -- that depends on what kinds of APIs it needs. Event loops often use very complicated OS APIs for polling and so they are often not supported in Miri (e.g., we don't support `epoll`, which is often used for event loops on Linux).

**Comment by bjorn3** [comment]
Creating a winit EventLoop will either directly connect to the native display server (eg X11 or Wayland over a unix socket on Linux) or use the OS provided UI event loop facility to create the event loop (eg NSRunLoop/NSApp on macOS).

**Comment by RalfJung** [comment]
Supporting GUI applications is currently pretty far out, so I will close this issue.
