### ISSUE TITLE
Try out lld, so we can cross-build dependencies for arbitrary targets

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#317]
Here's what we did for an embedded system in another crate: https://github.com/embed-rs/stm32f7-discovery/commit/2b247cfe771b75bc08ba7c35efff8b231c6256c4

**Comment by RalfJung** [comment]
This would also be useful to cross-build libstd: currently, the only reason we need a C toolchain for that is the fact that we build a `dylib`. We could try to avoid building that (see https://github.com/rust-lang/rust/issues/56443) or we could try to use a linker that works for cross-building (this issue, I guess).

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/miri/issues/864 for another way that we could make Miri work for any target architecture (without having the C toolchains for that installed).

**Comment by RalfJung** [comment]
I confirmed locally that with https://github.com/rust-lang/miri/issues/1057 fixed, we don't need lld to cross-compile for other targets. :) With https://github.com/rust-lang/backtrace-rs/pull/297, I was able to cross-build both 64bit and 32bit macOS and Windows libstd on my Linux box, and run a simple file in Miri.

I opened https://github.com/rust-lang/miri/issues/1198 to track testing that on CI.
