### ISSUE TITLE
Manually dropping a variable raises an error

### ISSUE THREAD

**Issue by wyfo** [rust-lang/miri#3186]
In my library, I've a code [example](https://docs.rs/swap-buffer-queue/latest/swap_buffer_queue/struct.Queue.html#examples-9).

I'm focusing on this part:
```rust
{
    let slice = queue.try_dequeue().unwrap();
    // omitted, but no other variable declared
}
```
This example pass Miri check, but if I had a manual drop
```rust
{
    let slice = queue.try_dequeue().unwrap();
    drop(slice);
}
```
I get an error.

Before going into a minimal reproducible example, I just wanted to ask if there is a difference between these two code extracts, so if it's normal that one can pass and the other raise an error.

Also, I suspect this error is a false-positive, because the error is described as a access made in the `Drop::drop` implementation of `slice`, while `slice` is strongly protected (with `Unique`) because it's an argument of `drop(slice)`. But there is nothing wrong to get a mutable access to an object being dropped by calling `drop`, isn't it?

**Comment by RalfJung** [comment]
Yes there is a difference between these two examples. `drop` is just a regular function. When you pass `slice` to `drop`, it must be a valid slice, which in particular means it must be dereferenceable. If `slice` is a shared reference, passing it to *any* function, including `drop`, acts like a read of the contents. If `slice` is a mutable reference, passing it to `*any* function, including `drop`, acts like a write to the contents.

Mixing raw pointers and slices is dicey business and should be avoided if at all possible. If you do it anyway you must be *extremely careful*.

Do you have a self-contained code example that demonstrates your issue?

**Comment by wyfo** [comment]
Thanks for this clarification. However, I still don't really understand why the `Unique` protection of `slice` coming from the `drop(slice)` call is kept when `slice` is dropped.

I will work on a minimal example.

**Comment by RalfJung** [comment]
Without knowing the types involved and the error shown, I can't answer that question. But I don't think it is unique protection from `drop` that causes issue later; the more likely cause is that there is protection established before that is violated by the call to `drop`.

As I said above, assuming `slice` is a mutable reference, `drop(slice)` is equivalent (for the purpose of aliasing violations) to overwriting the entire contents of the slice. This of course then causes issues if there are other parts of the program that are assuming unique access to this memory.

**Comment by wyfo** [comment]
I've crafted a minimal reproducible example [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=db7044fb7a942404af4c4598f35f638c)
```rust
fn main() {
    use std::{
        cell::UnsafeCell,
        sync::atomic::{AtomicBool, Ordering},
    };
    #[derive(Default)]
    struct Struct {
        flag: AtomicBool,
        cell: UnsafeCell<usize>,
    }
    impl Struct {
        fn get(&self) -> Option<Ref<'_>> {
            // Use an atomic flag to ensure safe mutable access
            self.flag
                .compare_exchange(false, true, Ordering::Acquire, Ordering::Relaxed)
                .is_ok()
                .then(|| Ref {
                    struct_: self,
                    _ref: unsafe { &*self.cell.get() },
                })
        }
    }
    struct Ref<'a> {
        struct_: &'a Struct,
        _ref: &'a usize,
    }
    impl<'a> Drop for Ref<'a> {
        fn drop(&mut self) {
            unsafe { (*self.struct_.cell.get()) = 0 };
            self.struct_.flag.store(false, Ordering::Release);
        }
    }
    let my_struct = Struct::default();
    {
        let my_ref = my_struct.get().unwrap();
        drop(my_ref);
    }
}
```
Here is the error:
```
error: Undefined Behavior: not granting access to tag <1735> because that would remove [SharedReadOnly for <1727>] which is strongly protected because it is an argument of call 714
  --> src/main.rs:29:22
   |
29 |             unsafe { (*self.struct_.cell.get()) = 0 };
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not granting access to tag <1735> because that would remove [SharedReadOnly for <1727>] which is strongly protected because it is an argument of call 714
   |
   = help: this indicates a potential bug in the program: it performed an invalid operation, but the Stacked Borrows rules it violated are still experimental
   = help: see https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md for further information
help: <1735> was created by a SharedReadWrite retag at offsets [0x0..0x8]
  --> src/main.rs:29:24
   |
29 |             unsafe { (*self.struct_.cell.get()) = 0 };
   |                        ^^^^^^^^^^^^^^^^^^^^^^^
help: <1727> is this argument
  --> src/main.rs:36:9
   |
36 |         drop(my_ref);
   |         ^^^^^^^^^^^^
   = note: BACKTRACE (of the first span):
   = note: inside `<main::Ref<'_> as std::ops::Drop>::drop` at src/main.rs:29:22: 29:52
   = note: inside `std::ptr::drop_in_place::<main::Ref<'_>> - shim(Some(main::Ref<'_>))` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:498:1: 498:56
   = note: inside `std::mem::drop::<main::Ref<'_>>` at /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:992:24: 992:25
note: inside `main`
  --> src/main.rs:36:9
   |
36 |         drop(my_ref);
   |         ^^^^^^^^^^^^
```
There is no error with `drop(my_ref)` commented. There is also no error without the `Ref::_number` field.

It seems that the reference in `_number` field prevent the destructor to modify the content the cell, even if this field is no more used when the modification occurs. However, it should also be the case without the explicit drop, shouldn't it?
By the way, I've tried to wrap the `_number` reference into an `Option`, and to use `Option::take` in the destructor before modifying the cell, but it still triggers the error when `drop(my_ref)` is called. 

Is there anyway to modify the content of the cell in the destructor of `Ref`, while having a reference to the cell in `Ref`? That's my real need.

> This of course then causes issues if there are other parts of the program that are assuming unique access to this memory.

Actually, the other part of the program assuming unique access to this memory is only the destructor, which is run inside the `drop` function scope because the argument is passed by value. How could it be an issue in this case?

@RalfJung if the real issue is just my misunderstanding, feel free to simply close this issue and I will try reread more carefully your explanations.

**Comment by RalfJung** [comment]
Oh, your references are not references.^^ They are a user-defined type with a custom drop impl. Please don't just omit such absolutely crucial information. Remember we don;t have crystal balls here, we only know about your code what you tell us.

When you pass a reference to a function by-value, such as the references in the fields of `my_ref`, then those references *must not* be invalidated while the function runs. As I said this has nothing to do with `drop`; here is a variant of your code that does not call `drop`: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=68c13a1366354c9c7016c83306292644).

Your `_ref` is a *read-only reference*. It has type `&usize`. It is UB to write to memory behind a shared reference, and you are doing such a write when you are doing `(*self.struct_.cell.get()) = 0`.

**Comment by wyfo** [comment]
> To fix this, you need to change the type of _ref so that the compiler knows that there is mutation happening behind this reference. You might use &UnsafeCell<usize>, or a raw pointer.

Thank you a lot. That's exactly what I need.

> When you pass a reference to a function by-value, such as the references in the fields of my_ref, then those references must not be invalidated while the function runs.

I understand that, but I don't understand why the dropping an argument at the end of the function scope count as `while the function runs. For me, it is quite like saying that in `{ let my_ref = my_struct.get().unwrap(); }` block, `my_ref` must be valid until the end of the block, dropping included, but it should then trigger the same error. 
I mean, if you inline the function into a block, the error disappear, so it seems to me the current behavior is not really consistent.

**Comment by wyfo** [comment]
I'm closing this issue, as my problem seems not to be related to Miri but to Stacked Borrows rules. 

If you think my last interrogation is worth an issue in https://github.com/rust-lang/unsafe-code-guidelines, please tell me and I will open it. Otherwise, if you can enlighten a last time, I would be grateful.

**Comment by RalfJung** [comment]
> why the dropping an argument at the end of the function scope counts as "while the function runs"

The fact that the function is called `drop` plays no role at all. See [my example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=68c13a1366354c9c7016c83306292644) where there's no `drop` being called any more. Do you still find that confusing? It's the exact same as your example, we just renamed `drop` to `myfn`.

> EDIT Actually, I don't really understand too why the protection last for the whole function, instead of being dropped when the protected reference is no more accessible, after a drop for example. Is the reason about optimization and code reordering?

We want LLVM be able to reorder and loop-hoist  accesses to the reference anywhere inside that function. That requires the reference to remain valid for the entire function.

> I'm closing this issue, as my problem seems not to be related to Miri but to Stacked Borrows rules.

Yeah, true. Feel free to ask on the UCG repo on Zulip if you still have further questions.

**Comment by wyfo** [comment]
> The fact that the function is called `drop` plays no role at all. 

I don't talk about manual call to `drop` function here, I talk about the destructor running automatically after the function evaluation for each argument in reverse order, like https://doc.rust-lang.org/reference/destructors.html#scopes-of-function-parameters. As stated in the documentation, destructors are run when the variables go out of scope, so, in my interpretation, the function arguments are dropped out of the function scope, and the protection (maintained in the function scoped for the reasons you wrote) should not be maintained when the destructors are run.

So I understand `my_ref` is protected for the execution of `drop` (or the equivalent `myfn`), but `my_ref` is dropped after (at least in my understanding) the function execution, when it "goes out of [the] scope" of the `drop` function. Do you see what I mean?

**Comment by RalfJung** [comment]
`_ref: &'a usize` gets *invalidated* when anyone writes to the memory it points to. It's a shared reference, it requires the memory it points to to be immutable.

This error has nothing to do with anything getting deallocated.

**Comment by wyfo** [comment]
Yet `Ref` destructor does write to memory pointed by `_ref`, but it's not an issue for Miri when the destructor is run while `my_ref` goes out of its declaration scope (my example without the `drop(my_ref);` line passes without error).
It's only an issue when `my_ref` is passed to a function, because the argument protection is extended while the argument goes out of the function scope when the destructor run.

So contrary to the *out-of-scope destructor run* for a variable declaration in a block, the *out-of-scope destructor run* for a function argument has this additional *function argument protection*, which I find inconsistent (for what my opinion is worth, i.e. not much i know ^^) because the destructor is actually run out of the scope of the function. In my head, function arguments are like variable declarations in a scope enclosing the function scope, so the protection for the enclosed scope should not impact arguments destructor execution.

I will open an issue in UCG, because I have not found an explicit statement about function argument drop in Stacked Borrows reference.

**Comment by RalfJung** [comment]
(I am trying to guess at where the source of the confusion is here, since it's not entirely clear to me.)

Your explicit call to `drop` is *not* equivalent to the implicit drop that the compiler inserts. That works more like `drop_in_place(addr_of_mut!(my_ref))`. This means that the implicit drop does not cause the situation where a `Ref` is passed by-value to a function.
