### ISSUE TITLE
socketpair shim ICEs if passed a slice as the last argument

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#3231]
The crate `socket` gets the ABI of `socketpair` wrong. It contains a binding that looks like this:
```rust
extern "C" {
    fn socketpair(domain: i32, type_: i32, protocol: i32, sv: *mut [i32]) -> i32;
}

fn main() {
    unsafe {
        socketpair(0, 0, 0, &mut [0] as *mut [i32]);
    }
}
```
This ICEs Miri, instead of reporting UB which is what I'd expect. Should it report UB?

**Comment by RalfJung** [comment]
Yeah it shouldn't ICE.

The entire socketpair/epoll implementation currently is basically a stub. Someone started implementing this and then work stopped.

**Comment by saethlin** [comment]
I was able to figure out that the epoll ICEs aren't intentional but I wasn't sure about this one. I guess I need to learn more about epoll, I didn't know socketpair was related 😵

**Comment by RalfJung** [comment]
I think it is related only insofar as socketpair generates FDs, and epoll works on FDs, and tokio uses both of them in some capacity so they both (and their interaction) need to be supported for basic tokio support.

I could also turn epoll support into a student project (I always need more of those ;) but I wasn't sure if @oli-obk and @DebugSteven had any further plans here.

**Comment by DebugSteven** [comment]
I intend to come back to tokio support in the new year. I'll check in with Oli when he's back.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/miri/issues/3442
