### ISSUE TITLE
When reads/writes from the borrow model cause data races, the errors are confusing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3278]
The errors look something like this:
```
error: Undefined Behavior: Data race detected between (1) Read on thread `<unnamed>` and (2) Write on thread `<unnamed>` at ALLOC. (2) just happened here
  --> $DIR/retag_data_race_read.rs:LL:CC
   |
LL |         *p = 5;
   |         ^^^^^^ Data race detected between (1) Read on thread `<unnamed>` and (2) Write on thread `<unnamed>` at ALLOC. (2) just happened here
   |
help: and (1) occurred earlier here
  --> $DIR/retag_data_race_read.rs:LL:CC
   |
LL |         let _r = &*p;
   |                  ^^^
```

People will rightly be confused about this and wonder why Miri thinks there is a read in the second line. So maybe it should say "retag" instead of "read", and then also explain that the retag acts as a read/write for data race purposes.

This affects both Stacked Borrows and Tree Borrows.

**Comment by Vanille-N** [comment]
Related TB message:
https://github.com/rust-lang/miri/blob/580f0b78a94ebd17676f44849239aff9e73d5ba9/src/borrow_tracker/tree_borrows/diagnostics.rs#L41

**Comment by saethlin** [comment]
I think we already have https://github.com/rust-lang/miri/issues/2921 for this?

**Comment by RalfJung** [comment]
Ah. Yes we do. *oops*
