### ISSUE TITLE
CI: Linux test often takes >1h

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3299]
Recently it seems like the test job running on Linux has become quite a bit slower, often taken close to 1h30min and often being the slowest job to complete.

I'm not quite sure when this started; unfortunately it seems like GHA has no good way to track CI time over time. If I go back about a month, I usually see CI times of around 50min for the Linux job, a bit more than 30min for the Windows job, and a bit less than 30min for the macOS job. Now the Linux job is 40min slower and the other two are about 20min slower.

Did GHA get slower or did our CI get slower?
Also, maybe we should split up the Linux job into multiple jobs so that they can run in parallel. However that will increase overall CI resource usage since Miri is then built more often.

**Comment by RalfJung** [comment]
Looking just at the nightly CI, this one was still good:
https://github.com/rust-lang/miri/actions/runs/7839746950
And this one is slow:
https://github.com/rust-lang/miri/actions/runs/7867399849

The ones in between did not pass. Nothing significant changed in Miri in that time, so it can probably only be some rustc change? Looking at the rustup PRs, this is the first slow one:
https://github.com/rust-lang/miri/actions/runs/7852837474
That's this PR:
https://github.com/rust-lang/miri/pull/3293
Corresponding to this rustc range:
https://github.com/rust-lang/rust/compare/384b02c0825cefa59f2e8a99a33d9a5344959079...b5c46dc5426038a49c95398bce30eeb20ec421e2
This includes @saethlin's https://github.com/rust-lang/rust/pull/120594, so I wonder if that is to blame.

**Comment by oli-obk** [comment]
> However that will increase overall CI resource usage since Miri is then built more often.

There are shenanigans we can do where CI builds miri, then sends information to n CI jobs that then run in parallel

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/121114, CI times are back to normal. :)
