### ISSUE TITLE
Miri does not work with a sysroot built without cfg(miri)

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/miri#3311]
This is necessary to be able to use a libstd compiled without `cfg(miri)`, yet still with `-Zalways-encode-mir`. In particular for https://github.com/rust-lang/miri/issues/722#issuecomment-1960262240 I had to use the same standard library as would be linked against for regular programs as `cargo-miri` to build a new standard library with `-Zalways-encode-mir` and `cfg(miri)` doesn't work on wasm. Because the poll syscall is missing, I had to patch the standard library to never try the poll based fast path for detecting if all stdio fds are open.

**Comment by saethlin** [comment]
Can you explain why you need to compile libstd without `cfg(miri)`? I don't think we can realistically support a working libstd in Miri without `cfg(miri)` going forward.

**Comment by bjorn3** [comment]
I need the exact same libstd be used for compiling rustc against and to run miri with. Without `cargo-miri` working, the only way to get a sysroot for miri to use, is to literally reuse the same sysroot used for regular compilation as produced by bootstrap. This worked just fine for hello world at least if I patched bootstrap to pass `-Zalways-encode-mir` when building the stdlib.

**Comment by saethlin** [comment]
> This worked just fine for hello world at least if I patched bootstrap to pass `-Zalways-encode-mir` when building the stdlib.

Yes but it will definitely not work for some programs, and I'm not sure why we'd make any effort to keep it working even for hello-world. For example, panicking and backtraces have Miri-specific code.

**Comment by RalfJung** [comment]
I agree with Ben, we can only reasonably support sysroots built with `cfg(miri)`. 

> I need the exact same libstd be used for compiling rustc against and to run miri with. Without cargo-miri working,

Please open a new issue or a Zulip thread to explain why you need this and why cargo-miri isn't work. But discussing that in this thread about "poll" is off-topic.

**Comment by oli-obk** [comment]
The sysroot that uses cfg(miri) is not the one that can be used to compile miri itself.

**Comment by bjorn3** [comment]
My goal is to have a miri playground run entirely in the browser.

> The sysroot that uses cfg(miri) is not the one that can be used to compile miri itself.

I used one with cfg(miri) disabled both for compiling miri against and to use as sysroot at runtime.

> If you want to run miri in a wasi environment, build a target libstd with cfg miri on a supported host and ship those binaries

Getting that working is non-trivial. It doesn't mesh with bootstrap and outside of that, getting the exact same rustc version to do compilation with isn't easy (the output of the build does contain a rustc compiled to wasm, but cargo doesn't know how to use it) and it no longer has a simple `./x.py install` command to build everything.

**Comment by RalfJung** [comment]
I'm afraid an environment which can't even run cargo is too cursed for us to support.

But as I said above, if it's just about "poll", that can land on its own merits. However you'll run into a bunch of other places in the sysroot that (need to) use `cfg(miri)`.

**Comment by RalfJung** [comment]
Also, `./x.py test miri --stage 0` works, so there's a way to get Miri to work even without completing the bootstrap cycle.

**Comment by RalfJung** [comment]
But anyway, the discussion here now really is part of https://github.com/rust-lang/miri/issues/722#issuecomment-1960262240. It doesn't seem like there's anything being tracked separately? So let's close this.

I guess we could track adding "poll" support, but then there are so many shims missing, it's not worth having an issue for each one of them. I guess that was your intent when you opened the issue, but then it got side-tracked based on the motivation you stated -- sorry for that.
