### ISSUE TITLE
miri fmt failing on Windows

### ISSUE THREAD

**Issue by RossSmyth** [rust-lang/miri#3317]
One issue I am still having is rustfmt isn't working. I had that issue earlier as well. It just says 
```ps
PS C:\Users\Ross\Documents\miri> .\miri fmt -v
$ rustfmt +miri --edition=2021 --config-path C:\Users\Ross\Documents\miri\rustfmt.toml --unstable-features --skip-children -v ...
Error: `rustfmt` failed
```
Adding or removing `-v` doesn't change the output at all.

**Comment by RossSmyth** [comment]
After Saethlin's suggestion of removing the error snuffing, it outputs a giant-ass error of every file passed to rustfmt, but the true error is `The filename or extension is too long. (os error 206)`

**Comment by RossSmyth** [comment]
ChrisD diagnosed it as 
> The windows command line is limited to ~32k characters (assuming ascii). This is a hard limit due to using 16-bit integers https://learn.microsoft.com/en-us/windows/win32/api/ntdef/ns-ntdef-_unicode_string

My guess was https://learn.microsoft.com/en-us/windows/win32/sbscs/application-manifests#longPathAware, but adding a manifest to `miri-script` that made it longPathAware did not fix it. So the above is the issue as the CLI arguments are over 61k character long.

**Comment by RalfJung** [comment]
Yeah we assume that the OS can handle a list of all our files. It's not *that* many.

Looks like for platforms with CLI argument length limits we need to split up the rustfmt invocation into chunks. (We definitely don't want "one rustup per file", that would slow things down considerably.)

**Comment by ChrisDenton** [comment]
You could also try using relative paths to shorten the command line length. Though at >61k this may not be enough on its own.

Another possibility is to get rustfmt to support the `@path` argument (similar to [rustc](https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path)). This would allow dumping the arguments to a file and passing that to rustfmt.

**Comment by RalfJung** [comment]
If relative paths are sufficient that works for me. But then it may only be a matter of time until we hit this limit again.

> Another possibility is to get rustfmt to support the @path argument 

Then we'd have to find a location for that file...

Chunking seems like the easiest approach to me.

**Comment by saethlin** [comment]
Why can't we use `cargo fmt --manifest-path` 3 times?

**Comment by RalfJung** [comment]
We're also formatting all tests and benchmarks.
