### ISSUE TITLE
Execution Traces

### ISSUE THREAD

**Issue by ibraheemdev** [rust-lang/miri#3323]
Using Miri to debug data races is a little tricky currently because adding debug statements to a program run with a failing seed often changes the execution behavior. It would be nice if either 1) Miri had an option to dump a full execution trace, which could be quite a lot of data, but still useful, or 2) Miri exposed an interpreter hook that allowed you to debug values without affecting the execution of the program.

**Comment by RalfJung** [comment]
> 1) Miri had an option to dump a full execution trace, which could be quite a lot of data, 

It does: set `MIRI_LOG=info`.

> 2) Miri exposed an interpreter hook that allowed you to debug values without affecting the execution of the program.

I assume you are referring to the interleaving of concurrent threads. There's a particular chance of switching to a different thread at the end of each basic block. So adding or removing basic blocks will change the execution, that's pretty hard to avoid.

I'm not quite sure what kind of interface you are imagining for this hook. You can add debug statements and then again run Miri with many seeds to find a  new one that fails? That doesn't need a new hook though.

**Comment by ibraheemdev** [comment]
`MRII_LOG=info` looks useful, thanks.

> I'm not quite sure what kind of interface you are imagining for this hook. You can add debug statements and then again run Miri with many seeds to find a new one that fails? That doesn't need a new hook though.

I was thinking of an extern function known to the interpreter that is somehow excluded from affecting the switching behavior. I'm not entirely sure how this works internally so I can't say how feasible this is, but it would be very helpful.

**Comment by RalfJung** [comment]
Function calls introduce new basic blocks in MIR, whether they are magic or not... so we'd have to rely on very specific details of MIR building to make that works. It sounds rather fragile.

**Comment by RalfJung** [comment]
I'll close this issue as we have MIRI_LOG=info and it's not clear what else could be done. The proper solution is probably some proper trace-based debugger, like a combination of priroda and rr or so...
