### ISSUE TITLE
Explore using cargo-hakari to avoid duplicate builds between `miri test` and `miri run`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3372]
`./miri test` and `./miri run` currently each build their own copy of the Miri binary. The reasons for that are described [here](https://github.com/rust-lang/cargo/issues/4463#issuecomment-1987301254). The tool https://crates.io/crates/cargo-hakari is intended to help with cases like that when they arise in a workspace; maybe they also help with the situation of multiple crates within a single package.

**Comment by RalfJung** [comment]
One challenge might be that the crate can't be in a workspace  -- this entire repository is embedded in the rustc repo as a subtree, and rustc makes Miri a workspace member, so Miri's Cargo.toml can't itself be declared a workspace root.

@sunshowers  is that a problem for hakari, or does it also work for non-workspace crates?

**Comment by sunshowers** [comment]
Hmmm, interesting. I've never tried it on single-crate projects, but I wonder if there's a way to make it work with some creativity. For example you could have an outer Cargo.toml that does declare a workspace, and import miri as a subdirectory into the Rust tree.

**Comment by RalfJung** [comment]
The subtree approach we are working doesn't let us do that I think. This repo here is basically just a projection of the `src/tools/miri` subdir in the rustc repo -- the projection is deterministic so each time we extract we get matching git history. But I don't think we can have stuff "around" the projection. Everything in this repo must also exist in the rust repo.

**Comment by RalfJung** [comment]
I managed to get it to work by tweaking the workspace settings:
```
[workspace]
members = ["miri"]
exclude = ["cargo-miri"]
```

And that seems to work indeed. :) No more rebuilds in `./miri run`. :tada: 

However we can't set this up for CI because we can't have this `[workspace]` section permanently in our Cargo.toml.

**Comment by RalfJung** [comment]
In the end I went with https://github.com/rust-lang/miri/pull/3881 -- entirely avoiding the use of `cargo run`, and therefore the need for a workspace-hack crate.
