### ISSUE TITLE
ICE: hir: index out of bounds

### ISSUE THREAD

**Issue by andyleiserson** [rust-lang/miri#3389]
I suspect this is related to https://github.com/rust-lang/rust/issues/122399.

I pushed a minimal test case to https://github.com/andyleiserson/miri/commit/4c9d9ac10667aee405c5cf6be262f772c182e9d7. I'm including the content of the test case below. But to get the issue to reproduce, I had to add it as a crate in test-cargo-miri -- adding it as a regular test was not sufficient. My original repro (from which I distilled this test case) was `git clone -b v0.12.1 https://github.com/rustls/rcgen.git && cd rcgen && cargo +nightly miri test`.

```
const OID_RSA_ENCRYPTION: &[u64] = &[1, 2, 840, 113549, 1, 1, 1];

pub struct SignatureAlgorithm {
    pub oids: &'static [&'static [u64]],
}

pub static PKCS_RSA_SHA256: SignatureAlgorithm = SignatureAlgorithm {
    // Does not repro with this constant inlined.
    oids: &[&OID_RSA_ENCRYPTION],
};
```

The observed behavior is an ICE (reported as stderr mismatch when running run-test.py):
```
thread 'rustc' panicked at /rustc/a615cea3339046c7ab2d75cd253727d1fd42dd0b/compiler/rustc_middle/src/hir/mod.rs:157:84:
index out of bounds: the len is 7 but the index is 7
```

The ICE also includes the following context:
```
query stack during panic:
#0 [local_def_id_to_hir_id] getting HIR ID of `PKCS_RSA_SHA256::{constant#0}`
#1 [exported_symbols] collecting exported symbols for crate `0`
end of query stack
``` 

[rustc-ice-2024-03-18T21_21_30-94784.txt](https://github.com/rust-lang/miri/files/14644584/rustc-ice-2024-03-18T21_21_30-94784.txt)

**Comment by RalfJung** [comment]
Cc @oli-obk
