### ISSUE TITLE
Complete and fix our eventfd implementation

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3445]
`eventfd` is documented reasonably well in its [man page](https://man.netbsd.org/eventfd.2). The current implementation in Miri is incomplete, doesn't have tests (it is only indirect exercised via the tokio MVP test but that's not a good way to test a specific low-level API), and is partially wrong.

It is incomplete in that `read` is not implemented, which means they can't actually be used to do anything.
That's also where EFD_NONBLOCK would come in.

It is partially wrong in that
- `write` panics in all sorts of situations that should be handled gracefully
- ~~`dup` creates a new *independent* event object, rather than a second FD that refers to the same event object~~ (this got fixed in the mean time)

Work on this should IMO follow the [proposed "project" process](https://github.com/rust-lang/miri/issues/3443).

**Comment by RalfJung** [comment]
Also the check here is bogus:

https://github.com/rust-lang/miri/blob/99be2b7c7c4af7dfbfc7447289d1637e633f09e6/src/shims/unix/linux/eventfd.rs#L109-L111

That should be `!= 0`, which then reveals that tokio calls us with unsupported flags.
```
LL |             let fd = syscall!(eventfd(0, flags))?;
   |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ 0x80800 is unsupported
```

**Comment by RalfJung** [comment]
> dup creates a new independent event object, rather than a second FD that refers to the same event object

This should probably be fixed by implementing a proper notion of "file description", and making the file descriptor table a simple indirection for file descriptions. That would fix `dup` for all FDs once and for all, and it will anyway be needed for [epoll](https://github.com/rust-lang/miri/issues/3448).

**Comment by m-rph** [comment]
Hey @RalfJung I would like to give this a shot. May I just `@rustbot claim` it?

**Comment by RalfJung** [comment]
Please coordinate with @oli-obk -- I saw something about a potential GSoC project for epoll support, and I assume this would be part of it.

**Comment by oli-obk** [comment]
cc @tiif 

There's probably some parallel development that can be done, but the file descriptor table refactor is likely gonna block other work, so the earlier it is done the better.

**Comment by m-rph** [comment]
I think it's probably for the best if I pick something simpler and isolated to start with. 
Thank you!

**Comment by tiif** [comment]
This hackmd contains the details for ``eventfd`` implementation: https://hackmd.io/@tiif/rk9hlmP4R
