### ISSUE TITLE
cargo-miri: incorrect behavior when `--target` is given multiple times

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3460]
When `--target` is given multiple times, Miri thinks we are building the first target, but actually cargo will build the last target.

**Comment by bjorn3** [comment]
If you specify `--target` multiple times, cargo will actually build for every specifies target at the same time, except when doing `cargo run` where passing multiple `--target` errors out.

**Comment by RalfJung** [comment]
Ah true, `cargo test` actually runs the tests multiple times.

So yeah Miri should support that as well then.
