### ISSUE TITLE
`ci.yml` uses `deprecated` version of `Node.js`

### ISSUE THREAD

**Issue by hamirmahal** [rust-lang/miri#3518]
![image](https://github.com/rust-lang/miri/assets/43425812/99c316e2-8289-4572-b0b8-3f19c0fb21ca)

That image shows warnings about CI using an action that uses a `deprecated` version of `Node.js`.

**Comment by hamirmahal** [comment]
https://github.com/rust-lang/miri/actions/runs/8853815816

**Comment by hamirmahal** [comment]
![image](https://github.com/rust-lang/miri/assets/43425812/2f034d9a-329b-4bf7-b887-63a65e11e7d6)

**Comment by hamirmahal** [comment]
![image](https://github.com/rust-lang/miri/assets/43425812/99c316e2-8289-4572-b0b8-3f19c0fb21ca)

**Comment by RalfJung** [comment]
Please don't submit issues with an empty description, they are not very... descriptive. Also, images without any text are not great descriptions either -- they cannot be searched and lack context. It's okay to hav an image but it should come with some words in English explaining the problem.

**Comment by hamirmahal** [comment]
> Please don't submit issues with an empty description, they are not very... descriptive. Also, images without any text are not great descriptions either -- they cannot be searched and lack context. It's okay to have an image but it should come with some words in English explaining the problem.

That makes sense. I updated the issue description and added some text to accompany the screenshot I originally posted.

**Comment by hamirmahal** [comment]
That makes sense. I updated the issue description and added some text to accompany the screenshot I originally posted.
