### ISSUE TITLE
Make file descriptors into refcounted references to "file descriptions"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3525]
Currently, every file descriptor has to implement `dup`, and some do that incorrectly. The issue is that file descriptors are more like `Arc` than like `Box`, so all state should be shared among all the duplicates, which typically requires an extra level of indirection -- e.g. in eventfd or epoll, where duplicate file descriptors should reference the same underlying state.

Instead of making each FD type handle that, we should remove `dup` from the `FileDescriptor` trait and handle this ourselves. I see two ways to do that:
- Literally use `Arc<dyn FileDescription>` instead of `Box<dyn FileDescriptor>`, so `Arc` handles the refcounting for us for free. However this will require interior mutability if the file description tracks mutable state (as many of the "special" FDs will).
- Add some sort of `FxHashMap<FileDescriptionId, (usize, Box<dyn FileDescription>)>` (where the `usize` is a refcount) and then make the FD table simply reference `FileDescriptionId`. This means we have to do refcounting ourselves but we can get exclusive access to the data inside a file description.

Interior mutability is annoying, but then there is some chance we'll need to give the `read`/`write` methods access to the machine (even mutable access!) and then it seems hard to avoid some form of interior mutability. So currently my gut feeling is that manual refcounting isn't worth it.

**Comment by RalfJung** [comment]
@ZoeS17 you were looking for some reasonably sized contribution to get your feet wet in the codebase, weren't you?

**Comment by oli-obk** [comment]
We could hide the interior mutability by providing a `FileDescriptor` struct that hides the `Rc<RefCell<dyn Filedescription>>` and provides the right mutability API and forwards it to the inner one

**Comment by RalfJung** [comment]
One downside of the Arc version is that we do not have access to the Machine in drop. So we'd have to carefully align things to make such access unnecessary.

But we can always try Arc first and then migrate to manual refcounting later if it becomes clear that Arc does not work.

**Comment by Luv-Ray** [comment]
Hello! I'm new to miri and I'm eager to contribute. May I take on this issue?

**Comment by RalfJung** [comment]
Let's wait a bit to see if @ZoeS17 wants to take it, as they were already looking for something a good month ago.

We have a bunch of issues labeled ["good first issue"](https://github.com/rust-lang/miri/labels/E-good-first-issue), if you want to take a look. They vary quite a bit in difficulty and our mentoring capacity is limited, but it's always worth asking.

**Comment by RalfJung** [comment]
Actually we already offered ZoeS an issue [here](https://github.com/rust-lang/miri/issues/3454) and they didn't reply, so -- for me it's fine if you take this one, @Luv-Ray. Unfortunately I won't be able to do primary mentoring currently.

**Comment by RalfJung** [comment]
No worries, this is not your job after all :)

**Comment by RalfJung** [comment]
> close get a &mut self as parameter, and check Rc::strong_count(&fd) == 1 before call close

This seems like the best option to me.

**Comment by the8472** [comment]
> The issue is that file descriptors are more like Arc than like Box, so all state should be shared among all the duplicates

Note that there's at least one bit of state that's per file descriptor, not per file description. The O_CLOEXEC flag.
