### ISSUE TITLE
"Install tools" always runs, even when there was a cache hit

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3543]
Looking at https://github.com/rust-lang/miri/actions, all the recent jobs are running this step, even though that should only happen when the cache is cold:
```
      - name: Install tools
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: cargo install -f rustup-toolchain-install-master hyperfine
```

This is likely caused by https://github.com/rust-lang/miri/pull/3519; things worked fine before that PR. There's a reason why I'd prefer if Github didn't subject us to updates like that all the time... they always tend to take time away from actual development...
Cc @hamirmahal

**Comment by hamirmahal** [comment]
Would using something like https://github.com/Swatinem/rust-cache help?

It’s prevented repeated downloading and compiling even when everything’s using the latest version of Node.

**Comment by RalfJung** [comment]
We shouldn't need another action, we just have to get the github native action to behave...

**Comment by RalfJung** [comment]
Ah, in https://github.com/rust-lang/miri/actions it did work properly. Maybe I was just checking the wrong actions, it did take a bit to propagate the updated cache from https://github.com/rust-lang/miri/pull/3537. Sorry for the noise!

**Comment by hamirmahal** [comment]
No worries!
