### ISSUE TITLE
Implement aligned_alloc

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3577]
C11 has a new allocation function: aligned_alloc. We should implement it in Miri. Docs can be found [here](https://en.cppreference.com/w/cpp/memory/c/aligned_alloc).

**Comment by RalfJung** [comment]
Ah, but the function spec is completely terrible of course...

> alignment 	- 	specifies the alignment. Must be a valid alignment supported by the implementation. 

There is no guarantee at all for what is a "valid alignment supported by the implementation". So this can basically always return null, great.

Given the comments in the docs, it seems like a reasonable choice of "valid alignment supported by the implementation" is to require the alignment to be at least the size of a pointer. I have no clue why an implementation would reject smaller alignment, but it is what posix_memalign does so it seems to be common... somehow...

**Comment by workingjubilee** [comment]
indeed, `void*` minimum in practice, it seems: https://www.gnu.org/software/gnulib/manual/html_node/aligned_005falloc.html

**Comment by workingjubilee** [comment]
though asking for too-large alignments is also bad: https://github.com/rust-lang/rust/pull/124788/commits/53bd38b7c5d5dc43feced7cf76904fa5b788de0c

**Comment by RalfJung** [comment]
> indeed, `void*` minimum in practice, it seems: https://www.gnu.org/software/gnulib/manual/html_node/aligned_005falloc.html

That's for that one implementation. But who knows about others...



> though asking for too-large alignments is also bad: [rust-lang/rust@53bd38b](https://github.com/rust-lang/rust/commit/53bd38b7c5d5dc43feced7cf76904fa5b788de0c)

That's "obviously" a platform bug though, I don't think Miri should model that.
(Returning NULL would be fine, but returning an unaligned value is clearly violating the spec.)

**Comment by RalfJung** [comment]
> indeed, `void*` minimum in practice, it seems: https://www.gnu.org/software/gnulib/manual/html_node/aligned_005falloc.html

Looking at the spec again, it says fundamental alignments must be supported. So I think a `void*` minimum is actually non-compliant.

**Comment by RalfJung** [comment]
:joy: turns out libc doesn't have this function yet... https://github.com/rust-lang/libc/issues/3689. That certainly makes testing harder.

**Comment by workingjubilee** [comment]
> Looking at the spec again, it says fundamental alignments must be supported. So I think a void* minimum is actually non-compliant. macOS (and Illumos) implementations of this function are buggy.

And some platforms just don't implement it at all, of course, for legacy reasons.

**Comment by RalfJung** [comment]
According to [my research](https://github.com/rust-lang/libc/issues/3689), at least all the Unixes Miri currently has any support for do all have it. That's good enough for me to say we just provide it on all Unixes.

**Comment by workingjubilee** [comment]
Oh yes, the notable exception is Windows.

**Comment by RalfJung** [comment]
As usual ;)
