### ISSUE TITLE
Revamp "./miri test": parse --target ourselves, pass the rest to the test harness

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3586]
`./miri test <flags>` just sends all the flags to cargo as-is. That's suboptimal for (at least) two reasons:
- `./miri test filter` works, but to filter two things one has to do `./miri test -- filter1 filter2`. This is also how cargo works but it is surprising.
- `./miri test --target foo` interprets `foo` as a *host* target. That's consistent with `./miri build`, but it's basically never what you want. `MIRI_TEST_TARGET=foo ./miri test` is what you want, but that's longer to type, non-standard, and especially inconvenient on Windows.

So I think we should make this command be `./miri test [--target target] <flags>`, where `target` does the same thing as MIRI_TEST_TARGET, and `<flags>` are passed to the test harness -- i.e., the invocation will be `cargo test -- <flags>` (note the extra `--`).

**Comment by RalfJung** [comment]
@RossSmyth  would you like to give this a try? :)

**Comment by RossSmyth** [comment]
#3588

**Comment by RalfJung** [comment]
Fixes by https://github.com/rust-lang/miri/pull/3588
