### ISSUE TITLE
./miri.bat silently exits unconditionally

### ISSUE THREAD

**Issue by cgettys-microsoft** [rust-lang/miri#3714]
#3703 appears to cause ./miri.bat to unconditionally exit even if the stable toolchain is installed.

Not a batch expert, but based on Powershell, `&` would be fork, not "do this after"

&& seems to fix it, PR to follow.

**Comment by RossSmyth** [comment]
Yeah, sorry I didn't check it very carefully.

**Comment by cgettys-microsoft** [comment]
No worries, happens to all of us. Just thought I should bring it up and/or fix it myself 😄
