### ISSUE TITLE
[Question] About option to skip Inline assembly

### ISSUE THREAD

**Issue by bitboom** [rust-lang/miri#3729]
I am currently using Miri to verify the memory safety of the hypervisor project. However, I have encountered limitations when analyzing code that includes inline assembly. These segments prevent Miri from continuing the analysis. So I have to add conditional compilation for every instance of assembly code.

Is there an option in Miri to skip inline assembly code during analysis? If not, is there a recommended approach to handle this issue?

*In the Kani verification tool, there is [a stubbing feature](https://model-checking.github.io/kani/reference/stubbing.html) that allows users to replace certain functions or methods with stubs during verification using the `--enable-stubbing` option. This feature is particularly useful for bypassing unsupported code sections like inline assembly.*

**Comment by saethlin** [comment]
Miri doesn't analyze, Miri executes. That's what it means to be an interpreter.

The only option available currently is what you're already doing. I don't see any reason we couldn't provide exactly the same kind of stubbing that Kani does, someone would just need to implement it.

**Comment by bitboom** [comment]
Thank you for the quick reply!  I understand the current state now.

**Comment by RalfJung** [comment]
Yeah, the way we support stubbing is via `if cfg!(miri) { ... } else { ... }`.
