### ISSUE TITLE
Running `Cargo miri test` on `cargo`, an error occurred

### ISSUE THREAD

**Issue by heisen-li** [rust-lang/miri#3734]
I am using `miri` to run on `cargo` and it shows an error:

```
test util::context::tests::disables_multiplexing ... error: unsupported operation: can't call foreign function `OPENSSL_init_ssl` on OS `linux`
    --> /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/openssl-sys-0.9.92/src/lib.rs:122:13
     |
122  |             OPENSSL_init_ssl(init_options, ptr::null_mut());
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function `OPENSSL_init_ssl` on OS `linux`
     |
     = help: if this is a basic API commonly used on this target, please report an issue with Miri
     = help: however, note that Miri does not aim to support every FFI function out there; for instance, we will not support APIs for things such as GUIs, scripting languages, or databases
     = note: BACKTRACE on thread `util::context::`:
     = note: inside closure at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/openssl-sys-0.9.92/src/lib.rs:122:13: 122:60
     = note: inside closure at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sync/once.rs:149:41: 149:60
     = note: inside `openssl_sys::openssl::init` at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/openssl-sys-0.9.92/src/lib.rs:121:9: 123:11
     = note: inside `libgit2_sys::openssl_init` at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/libgit2-sys-0.17.0+1.8.1/lib.rs:4330:5: 4330:24
     = note: inside closure at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/libgit2-sys-0.17.0+1.8.1/lib.rs:4303:9: 4303:23
     = note: inside closure at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sync/once.rs:149:41: 149:60
     = note: inside `libgit2_sys::init` at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/libgit2-sys-0.17.0+1.8.1/lib.rs:4302:5: 4324:7
     = note: inside `git2::init` at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/git2-0.19.0/src/lib.rs:755:5: 755:16
     = note: inside `git2::Config::open_default` at /root/.cargo/registry/src/szv-open.codehub.huawei.com-f5aae4094eaf2133/git2-0.19.0/src/config.rs:93:9: 93:22
note: inside `util::network::proxy::http_proxy`
    --> src/cargo/util/network/proxy.rs:22:5
     |
22   |     git2::Config::open_default()
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `util::network::proxy::http_proxy_exists`
    --> src/cargo/util/network/proxy.rs:38:5
     |
38   |     http_proxy(http).is_some()
     |     ^^^^^^^^^^^^^^^^
note: inside `util::context::disables_multiplexing_for_bad_curl`
    --> src/cargo/util/context/mod.rs:2955:8
     |
2955 |     if network::proxy::http_proxy_exists(http, gctx) && http.multiplexing.is_none() {
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside `util::context::tests::disables_multiplexing`
    --> src/cargo/util/context/mod.rs:3006:13
     |
3006 |             disables_multiplexing_for_bad_curl(curl_v, &mut http, &gctx);
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: inside closure
    --> src/cargo/util/context/mod.rs:2975:31
     |
2974 |     #[test]
     |     ------- in this procedural macro expansion
2975 |     fn disables_multiplexing() {
     |                               ^
     = note: this error originates in the attribute macro `test` (in Nightly builds, run with -Z macro-backtrace for more info)

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace

error: aborting due to 1 previous error

error: test failed, to rerun pass `--lib`
```

Looking at the error message, `miri` needs to support the common API on Linux? I would like to know what is the progress of `API` support on current `linux`?

**Comment by bjorn3** [comment]
You can't call arbitrary C libraries like OpenSSL or libgit2 from inside miri. Miri has shims for most common libc api's, but for anything else you did either have to remove the usage or patch miri to add your own shims. It seems like you are trying to run cargo inside miri. You could try using gitoxide and rustls for git and tls accesses. Cargo already has support for this, but it is disabled by default. I believe there are a couple of env vars you can set. Also I think miri doesn't have any networking support yet.

**Comment by RalfJung** [comment]
Yeah, Miri does and will not not support calling OpenSSL - sorry. Miri can only check bugs in Rust code, and all C code that you call needs to be re-implemented inside Miri. We do this for some basic platform APIs, but OpenSSL is too big to qualify for that.

**Comment by RalfJung** [comment]
I wonder if we should have a specific error message for "known to be deliberately not supported" functions that says -- sorry but this is out of scope.

> Also I think miri doesn't have any networking support yet.

FWIW that is definitely in scope, I plan for us to have networking support at some point. See https://github.com/rust-lang/miri/issues/3449.

**Comment by heisen-li** [comment]
Sorry, my thoughts are: if the problem is due to unsupported calls to `API`s such as `OpenSSL`, it seems like it should be ignored for now and continue with the program later and give a unified reason later.

Also, I'm just getting started with `miri` and it's not going very well for me (maybe I'm just too dumb), should the user experience be enhanced?

It's just a personal thought, don't take it seriously.

**Comment by bjorn3** [comment]
There is not really a way to ignore it. Miri doesn't know what it could return as dummy value without causing the program to crash immediately or corrupt state in such a way that it will error later in a seemingly unrelated way. Nor does miri know if any of the input pointers will be modified by the call or not.

**Comment by RalfJung** [comment]
If you are just getting started with Miri, why are you trying to run the cargo test suite inside Miri? That is certainly not the normal mode of use.

The normal mode of use is to install Miri, navigate to your own project, and do `cargo miri test` there. Miri is made to test libraries that internally use unsafe code, not fully integrated end-user applications like cargo.
