### ISSUE TITLE
Programs that cast function pointers have escalating memory use

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#3737]
Since https://github.com/rust-lang/rust/pull/123781, this program has unbounded memory use:
```rust
fn main() {
    loop {
        oof as fn(); // oof as usize also works
    }
}

fn oof() {}
```

Currently it looks like the memory use from this is about 1 GB/min, which means that in practice it's likely that this technically-unbounded memory use will go unnoticed.

But in general, I've been trying to make sure that Miri's memory usage is bounded on as many workloads as reasonable so that if we're too slow, users can fall back to just letting Miri run for a long time. If the interpreter's memory grows over that time without bound, that's not an option. So it would be nice if we didn't have this memory growth.

This reminds me a lot of the situation that prompted us to cache our evaluations of consts: https://github.com/rust-lang/rust/pull/118336. Does a similar approach work here?

**Comment by RalfJung** [comment]
> Since https://github.com/rust-lang/rust/pull/123781,

A similar program where `oof` is generic would have had the same kind of escalating memory use already before that PR.

> This reminds me a lot of the situation that prompted us to cache our evaluations of consts: https://github.com/rust-lang/rust/pull/118336. Does a similar approach work here?

Yeah, I think so. We could make `oof as fn()` return one of a finite set of possible addresses for that function.
