### ISSUE TITLE
Support `SystemTime` with enabled isolation

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/miri#3740]
Right now MIRI with enabled isolation fails in code which uses `SystemTime::now()` with the following error:
```
error: unsupported operation: `clock_gettime` with `REALTIME` clocks not available when isolation is enabled
   --> /home/rust/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/time.rs:130:22
    |
130 |         cvt(unsafe { libc::clock_gettime(clock, t.as_mut_ptr()) }).unwrap();
    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `clock_gettime` with `REALTIME` clocks not available when isolation is enabled
    |
```

It means that most loggers will trigger this error. In some cases it's possible to work around this by disabling timestamps, but ideally it would work out of the box.

MIRI already has [emulation](https://github.com/rust-lang/miri/blob/master/src/clock.rs) of monotonic clocks. I think it could be used to emulate sytem time as well by re-interpreting the monotonic clock as UNIX timestamp, i.e. MIRI tests would see timestamps for 1970-01-01.

**Comment by RalfJung** [comment]
We quite deliberately did not do that as it seemed even more confusing than the fake monotonic clock. The intended reaction to a program using `SystemTime` is `-Zmiri-disable-isolation`.

**Comment by RalfJung** [comment]
FWIW if you have a good motivation for why you want this with isolation enabled, we could be persuaded. I just stated our reasoning for not having done this already. :)

**Comment by newpavlov** [comment]
It's just a question of convenience. It would be nice in my opinion to have this feature, but I understand your position above.

>Also, it's Miri, not MIRI.

I always thought it's an abbreviation of  "Mid-level Intermediate Representation Interpreter". :)

**Comment by RalfJung** [comment]
> I always thought it's an abbreviation of "Mid-level Intermediate Representation Interpreter". :)

That is indeed the origin of the name, but we don't write it in all-caps. :)
