### ISSUE TITLE
FFI implementation libc getuid on Linux

### ISSUE THREAD

**Issue by pcwizz** [rust-lang/miri#3753]
I relatively often find code I want to run with Miri that depends on libc getuid when targeting linux. At least to my mind it is a basic operating system API worthy of a miri implementation that would enable more miri code coverage.

**Comment by RalfJung** [comment]
We in fact already support `getuid`, but only when called from inside std... should be easy to change that to allow all code to call it.

The only hard part is a policy decision: currently it always returns 1000. Should we make it return the real ID instead? But what would that even mean when we run on a Windows host?

**Comment by pcwizz** [comment]
Awesome!
I think for my purposes 1000 is sufficient. No need to over complicate it.
-------- Original Message --------On 7/18/24 11:29, Ralf Jung  wrote:
We in fact already support getuid, but only when called from inside std... should be easy to change that to allow all code to call it.
The only hard part is a policy decision: currently it always returns 1000. Should we make it return the real ID instead? But what would that even mean when we run on a Windows host?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/rust-lang/miri/issues/3753#issuecomment-2236050152",
"url": "https://github.com/rust-lang/miri/issues/3753#issuecomment-2236050152",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
