### ISSUE TITLE
epoll does not report EPOLLERR events

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3816]
According to the [man page](https://man7.org/linux/man-pages/man2/epoll_ctl.2.html), epoll will always report EPOLLERR events. However, our implementation never reports them. This is a problem as Miri will silently accept the program but run it in an incorrect way. There's no good way to throw a "not supported" error here, so we should implement this event notification.

Cc @tiif

**Comment by tiif** [comment]
Right now I still haven't understood how to trigger ``EPOLLERR`` yet. I will look into this. 

@rustbot claim

**Comment by RalfJung** [comment]
> It is still unclear to me what will be considered an error condition for socketpair or eventfd.

It seems very plausible that the answer is "nothing". I would have thought closing the FD or the peer FD might do that but that doesn't seem to be the case, right? Those cases are both covered already by existing tests?

In that case I would say the fix is to add the flag to our `EpollReadyEvents` type, and do the plumbing that would forward such events to userspace. Then we are ready for if/when we have an FD type that emits them.

**Comment by tiif** [comment]
Actually right I discovered a test case can trigger ``EPOLLER``, the WIP in #3820 contains the test case. 

But I suspect there should be other test cases that I don't know yet. Would it makes sense to leave this issue up first, wait for bug reports, and fix it on the go?

This bug will be discoverable if the user managed to write a test where our epoll notification differs from real system.

**Comment by RalfJung** [comment]
> Actually right now I discovered a test case can trigger EPOLLER, https://github.com/rust-lang/miri/pull/3820 contains the test case.

Good catch!

If we know about a case, IMO we should implement it.
