### ISSUE TITLE
Missing documentation in provenance_gc.rs? 

### ISSUE THREAD

**Issue by tiif** [rust-lang/miri#3826]
I chanced upon this function while reading about provenance, should there be anything written after "but also"? 
```rust
    fn run_provenance_gc(&mut self) {
        // We collect all tags from various parts of the interpreter, but also
        let this = self.eval_context_mut();

        let mut tags = FxHashSet::default();
        let mut alloc_ids = FxHashSet::default();
        this.visit_provenance(&mut |id, tag| {
            if let Some(id) = id {
                alloc_ids.insert(id);
            }
            if let Some(tag) = tag {
                tags.insert(tag);
            }
        });
        self.remove_unreachable_tags(tags);
        self.remove_unreachable_allocs(alloc_ids);
    }
```
[source url](https://github.com/rust-lang/miri/blob/0665f6e58f27cf91402632733d3128c508959f65/src/provenance_gc.rs#L190)

**Comment by saethlin** [comment]
Definitely.

**Comment by RalfJung** [comment]
Thanks for pointing this out!

Regardless though, Miri's provenance GC is an implementation detail and if you ware looking to understand the impact of provenance of unsafe code, I'd suggest you ignore it. :)   A good starting point for learning about provenance in Rust is [the RFC](https://rust-lang.github.io/rfcs/3559-rust-has-provenance.html).

**Comment by tiif** [comment]
> Thanks for pointing this out!
> 
> Regardless though, Miri's provenance GC is an implementation detail and if you ware looking to understand the impact of provenance of unsafe code, I'd suggest you ignore it. :) A good starting point for learning about provenance in Rust is [the RFC](https://rust-lang.github.io/rfcs/3559-rust-has-provenance.html).

I will take a look at the RFC, thanks!
