### ISSUE TITLE
How to handle/suppress "error: UB: using uninitialized data" correctly 

### ISSUE THREAD

**Issue by kazuyukitanimura** [rust-lang/miri#3861]
I have the following use case
```
unsafe fn read_bytes_to_u64(data: &[u8], offset: usize, count: usize) -> u64 {
    debug_assert!(count <= 8);
    let mut tmp = std::mem::MaybeUninit::<u64>::uninit();
    let src = data.as_ptr().add(offset);
    // SAFETY: the caller must not use the uninitialized `8 - count` bytes in the returned value.
    unsafe {
        std::ptr::copy_nonoverlapping(src, tmp.as_mut_ptr() as *mut u8, count);
        tmp.assume_init()
    }
}
```
from https://github.com/apache/arrow-rs/pull/6288
This method is similar to Rust `read_unaligned` but reads `count <= 8` only. In the above PR, the caller properly masks out the uninitialized part.  Looks like Miri does not understand that the masking makes things safe. 
```
error: Undefined Behavior: using uninitialized data, but this operation requires initialized memory
   --> arrow-buffer/src/util/bit_mask.rs:125:9
    |
125 |         tmp.assume_init()
    |         ^^^^^^^^^^^^^^^^^ using uninitialized data, but this operation requires initialized memory
...
note: inside `util::bit_mask::set_upto_64bits`
   --> arrow-buffer/src/util/bit_mask.rs:101:30
    |
101 |         let chunk = unsafe { read_bytes_to_u64(data, read_byte, bytes) };
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
where the `chunk` gets masked properly later.
```
let chunk = (chunk >> read_shift) & mask;
```

Is there any good way to tell Miri that this is a valid use case? (unless I am overlooking some unexpected behavior...)

For now, I work around the problem by creating Miri and non-Miri methods
```
#[cfg(not(miri))]
unsafe fn read_bytes_to_u64(...

#[cfg(miri)]
unsafe fn read_bytes_to_u64(...
```

**Comment by oli-obk** [comment]
If you need the masking to happen outside your function, you need to return a MaybeUninit<u64> to correctly signal that some bytes of it may be uninit.

Your function as written is UB as uninit bytes end up in a value of type u64

**Comment by saethlin** [comment]
What the caller does is irrelevant. The signature of `read_bytes_to_u64` and indeed the signature of `MaybeUninit::<u64>::assume_init` already promise LLVM that the bytes that they return are initialized. This isn't even Miri being picky; you can see the problem by putting your function into godbolt, the function signature says `define noundef i64`:
https://godbolt.org/z/5avdnqGvv

It would be wrong for Miri to not report UB in this code.

**Comment by RalfJung** [comment]
> Is there any good way to tell Miri that this is a valid use case? (unless I am overlooking some unexpected behavior...)

There isn't because this is not a valid use case. :) There is no valid way to use uninitialized memory outside `MaybeUninit`.

It sounds like you also might be reading out-of-bounds here? I don't see  check for `offset` being in-bounds.

**Comment by kazuyukitanimura** [comment]
Thank you @oli-obk @saethlin @RalfJung 

So, as long as `assume_init()` is called, the value of MaybeUninit::<u64> has to be indeed initialized in advance, sounds like.

**Comment by saethlin** [comment]
That is mentioned in the documentation for `MaybeUninit::assume_init`: 
> Calling this when the content is not yet fully initialized causes immediate undefined behavior. 
If you think this could be more clear, please don't hesitate to make a suggestion on how we could clarify it.
