### ISSUE TITLE
profile-rustflags vs stable in toolchain/miri-script

### ISSUE THREAD

**Issue by DeSevilla** [rust-lang/miri#3863]
I'm building Miri for the first time on Windows according to the instructions [here](https://github.com/rust-lang/miri/blob/master/CONTRIBUTING.md). I've installed [rustup-toolchain-install-master](https://github.com/kennytm/rustup-toolchain-install-master), but by default, running './miri toolchain' in order to install the right version of Rust gives me the following error message:
```quote
The package requires the Cargo feature called `profile-rustflags`, but that feature is not stabilized in this version of Cargo (1.81.0 (2dbb1af80 2024-08-20)).
  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#profile-rustflags-option for more information about the status of this feature.
Failed to build miri-script. Is the 'stable' toolchain installed?
```
The culprit here appears to be this line in miri.bat, which calls "cargo +stable".

https://github.com/rust-lang/miri/blob/7b422febaced2d92d92cd22a011e227846ed5d80/miri.bat#L8

Changing it to "+nightly" lets me build and run Miri successfully. The +stable was introduced in #3402, to fix an inability to build miri-script in case of an error, so just removing "+stable" might not be the best way to solve this in general. Is it possible to build miri-script on stable without requiring profile-rustflags?

**Comment by RalfJung** [comment]
Thanks for the report! None of the core devs use Windows or know the batch file syntax, so the miri.bat file tends to go out-of-date. In this case however the fix is hopefully trivial -- do things work if you apply https://github.com/rust-lang/miri/pull/3864 ?

**Comment by DeSevilla** [comment]
Yep, changing +stable to +nightly makes everything work fine.

**Comment by RalfJung** [comment]
Okay, thanks for testing. :)
