### ISSUE TITLE
Miri doesn't respect `target-feature` in doc tests

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/miri#3869]
When code under miri reaches a function annotated with `#[target_feature(enable = "...")]` in *doc tests* miri throws an error saying "calling a function that requires unavailable target features" despite this being in the `if` block that checks the features using `is_x86_feature_enabled!` and despite having `-C target-feature=...` on the command line. The same issue is not present in non-doc tests and the same code works fine.

**Comment by RalfJung** [comment]
Are you locally using the exact same Miri version as CI?

**Comment by Kixunil** [comment]
I guess e-mail didn't show you my edit, I found it's actually doc tests that have this problem (on both machines).

**Comment by RalfJung** [comment]
How are you setting `-Ctarget-feature`? If you are using RUSTFLAGS, then you need to also set RUSTDOCFLAGS for doctests. MIRIFLAGS should apply everywhere... hopefully...

**Comment by Kixunil** [comment]
> you need to also set RUSTDOCFLAGS

Oh, that helped, thanks!

**Comment by RalfJung** [comment]
FWIW that's a cargo thing, RUSTFLAGS is simply not set on doctests.

**Comment by RalfJung** [comment]
Reading https://github.com/rust-lang/rust/issues/67533 I actually don't understand how setting RUSTDOCFLAGS helps... if rustdoc doesn't pass the flags to the rustc it invokes, then it shouldn't help with `-Ctarget-features` either?

**Comment by RalfJung** [comment]
I guess rustdoc must be forwarding `-C` flags to the rustc it invokes, but not other flags like `--cap-lints`.

**Comment by Kixunil** [comment]
Not sure which flags rustdoc passes but FTR I set both `RUSTFLAGS` and `RUSTDOCFLAGS` in CI to configure `target-features` and it works fine.
