### ISSUE TITLE
Refactor fd.rs ``return_read_bytes_and_count`` and ``return_written_byte_count_or_error``

### ISSUE THREAD

**Issue by tiif** [rust-lang/miri#3904]
It'd be clearer if ``return_read_bytes_and_count`` and ``return_written_byte_count_or_error`` can be combined and separate according to the ``Ok`` and ``Err`` code path. This is mentioned in https://github.com/rust-lang/miri/pull/3852#issuecomment-2355169819. 

(This probably don't need to be an issue, but I am creating this to keep track of what I want to do.)

**Comment by RalfJung** [comment]
I'd phrase this more generally as -- have a nice helper for returning errors in the standard Unix way.

**Comment by RalfJung** [comment]
Yes that one is nice, but I think we want something "lower-level" that takes an `io::Error` rather than an `io::Result`.
