### ISSUE TITLE
Consistently use io error handlers in Unix shims

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3930]
Unix shims return `-1` and set the thread-local "last error" variable to indicate an error occurred.  With https://github.com/rust-lang/miri/pull/3923 and https://github.com/rust-lang/miri/pull/3929, Miri has some nice helpers to help with that, but they are not being used everywhere yet. So this is about refactoring the existing code to use the new helpers.

To help, start by grepping for `-1` and for `this.eval_libc("E` in the `src/shims/unix` folder. You will find a few patterns:

```rust
                    let efault = this.eval_libc("EFAULT");
                    this.set_last_error(efault)?;
                    this.write_int(-1, dest)?;
```
should become `this.set_last_error_and_return(LibcError("EFAULT"), dest)?;`.

```rust
            this.set_last_error(ErrorKind::PermissionDenied)?;
            return Ok(Scalar::from_i32(-1));
```
should become `return this.set_last_error_and_return_i32(ErrorKind::PermissionDenied);`.

Feel free to ask if you encounter other patterns you are unsure about. It's also okay for the first PR to only cover parts of this and leave the harder cases for a second round.

**Comment by noahmbright** [comment]
@rustbot claim

I'll make a PR after a first pass. I can add a second commit or just fixup depending on how that goes. Thanks for the instructions!
