### ISSUE TITLE
`proptest` makes the execution of `miri` extremally slow

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/miri#3933]
Feel free to close if duplicate.

In addition to hard-coded values, I also use `proptest` to exercise private algorithms in unit tests. Unfortunately, it is hardly feasible to use `miri` with `proptest`.

```rust
// MIRIFLAGS="-Zmiri-disable-isolation" cargo miri test

#[cfg(test)]
mod proptest {
    proptest::proptest! {
        #[test]
        fn foo(_bar: u8) {}
    }
}
```

The above snippet that does nothing produces 255 different values of `_bar` but takes ~45 seconds to complete.

Here goes an illustration where the printing to `stdout` doesn't affect the execution time.

https://github.com/user-attachments/assets/cdb77c79-98aa-4990-8126-00a5a99aba8b

I am not aware of the internal details of both projects and I am also not sure if this whole scenario is working as intended.

**Comment by RalfJung** [comment]
Thanks for the report!

Yeah Miri is a lot slower than regular execution. That's hard to avoid, given its architecture.

Unless there is some specific bad interaction with proptest, it's probably not worth keeping this open, I am afraid.

**Comment by c410-f3r** [comment]
So it is working as intended. Thanks for the response.
