### ISSUE TITLE
"Standardize" name for variables of type `InterpCx`

### ISSUE THREAD

**Issue by Mandragorian** [rust-lang/miri#3958]
When I made my first contribution to the main miri code base, I was for a brief moment (slightly) confused about the variables `this` and `ecx`, mostly used to store the result of `eval_context_{ref,mut}`. It would be nice if the name was consistent.

I see that `this` is most commonly used:

```
$ grep -r "this: " | wc -l
62
$ grep -r "let this = " | wc -l
341
```

```
$ grep -r "ecx: " | wc -l
107
$ grep -r "let ecx = " | wc -l
8
```

However, sometimes this is used to refer to other values, for example: 

```
borrow_tracker/tree_borrows/tree.rs:        this: &mut TreeVisitor<'_>,
```

So personally I would propose using `ecx` to store the interpreter context.

Obviously this is not really important, and adds no value to the users, but if you agree that this might improve the code base, I am glad to send a PR.

**Comment by RalfJung** [comment]
We generally use `this` when we'd like to use `self` but cannot.  So that's for all the methods in a `EvalContextExt` impl. You're not confused that `self` has many different types throughout the codebsae, so you shouldn't expect that from `this` either.

However. some of the `ecx` should indeed be `this`, e.g. in `src/alloc_addresses/mod.rs`. Basically all cases of `let ecx = self.eval_context_ref`/`let ecx = self.eval_context_mut` should be changed to `this`. But the `ecx: ...` should stay the way they are, IMO.

**Comment by YohDeadfall** [comment]
Should `this:` be changed to `ecx:`?

**Comment by RalfJung** [comment]
In which context?

**Comment by YohDeadfall** [comment]
I would generalize all found cases into three categories:

* Local functions and closures accepting `InterpCx` as an argument:

https://github.com/rust-lang/miri/blob/052bdcb72dda94f0ac0284304503d25de28acc6b/src/helpers.rs#L1011-L1016

* Shared shim implementations (`futex`, `syscall`, SSE shims, etc.) 
https://github.com/rust-lang/miri/blob/052bdcb72dda94f0ac0284304503d25de28acc6b/src/shims/unix/linux/sync.rs#L6-L10

* Miri internals:

https://github.com/rust-lang/miri/blob/052bdcb72dda94f0ac0284304503d25de28acc6b/src/provenance_gc.rs#L198

**Comment by RalfJung** [comment]
The relevant distinction is whether the code is an InterpCx extension trait or not. In extension trais we use this, everywhere else ecx.

I guess one thing we a team should decide is whether we also want to use ecx in extension traits or stick to "this". @rust-lang/miri any opinion?

**Comment by saethlin** [comment]
Either convention is fine with me, I've never found the current code confusing.

**Comment by RalfJung** [comment]
> I would generalize all found cases into three categories:

Yeah those 3 examples all look to me like they should use `ecx`.

`this` is only intended to be used for cases that morally are `self`, but due to the extension crate technique can't use that. Maybe we should rename to `self_` to make that more clear...?
