### ISSUE TITLE
ICE on invalid thread ID in Linux pthread_getname_np

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#3965]
This program ICEs Miri:
```rust
fn get_thread_name(name: &mut [u8]) -> i32 { unsafe {
    libc::pthread_getname_np(999, name.as_mut_ptr().cast(), name.len())
} }

fn main() {
     get_thread_name(&mut []);
}
```

Thanks to @YohDeadfall for mentioning that. This is definitely a bug, we should never ICE.

**Comment by YohDeadfall** [comment]
@RalfJung, there are a few ways to implement that, so I would like to hear your opinion on that. My current idea is to change the get and set thread name function to return `InterpResult`, but as you said, catching errors isn't something which should happen. Should I use `Result<T, Err>` then?

**Comment by RalfJung** [comment]
Are the various OSes consistent in how they report this error?

`InterpResult<'tcx, Result<(), IoError>>` seems reasonable, if they are consistent.

**Comment by YohDeadfall** [comment]
It's again different error codes or nothing at all, so the set name method should be able to tell whether it's a too long name, or a non-existing thread. Plus other errors that internals of get/set thread name can cause like an invalid pointer.

**Comment by RalfJung** [comment]
> It's again different error codes or nothing at all

Can you elaborate?
Ignoring the error on the caller side is easy. Different error codes is more annoying... maybe we should just have some logic in our `fn pthread_getname_np`/`fn pthread_setname_np` that checks the current target OS and picks a different libc error code name... we usually try to have the platform-specific code in the platform folders, but sometimes that's just more trouble than it is worth.

**Comment by YohDeadfall** [comment]
When I was fixing the behavior of `pthread_{get|set}name_np` shims I had to change the result of the corresponding functions to `bool` because error codes are different. As an example, while for `glibc` it's `ERANGE`, macOS returns `ENAMETOOLONG`. So, there's a mismatch already.

When the specified thread cannot be found, there are differences once again. For macOS it's `ESRCH`, but `glibc` returns `errno` of the `open` syscall.

Therefore, I'm thinking about an enum used for reporting thread name errors like:

```rust
enum ThreadNameError {
    ThreadNotFound,
    NameTooLong,
}
```

Then both `pthread_setname_np` and `pthread_getname_np` can return a `InterpResult<'tcx, ThreadNameError>`, and then it can be converted to the appropriate error code. The thing that concerns me is two underlying functions which perhaps should be changed too, but I'm not sure about that. I better open a pull request where you can see the proposal.

**Comment by RalfJung** [comment]
What I meant was, can you explain what you mean by "different error codes or nothing at all"? Like, give some examples. :)

**Comment by YohDeadfall** [comment]
By nothing at all I meant the FreeBSD implementation that returns `void` for the both methods, but other platforms provide results with incompatible error codes.

**Comment by RalfJung** [comment]
So what does the FreeBSD function do when the thread ID is invalid?

**Comment by YohDeadfall** [comment]
Nothing (:

**Comment by RalfJung** [comment]
Not even write a null termination to return a valid "empty" string?

Do you have docs confirming that?

**Comment by YohDeadfall** [comment]
I have a better thing, there's source code (['pthread_set_name_np'](https://github.com/freebsd/freebsd-src/blob/c2d93a803acef634bd0eede6673aeea59e90c277/lib/libthr/thread/thr_info.c#L99-L104) and [`pthread_get_name_np`](https://github.com/freebsd/freebsd-src/blob/c2d93a803acef634bd0eede6673aeea59e90c277/lib/libthr/thread/thr_info.c#L146-L151):

```rust
__weak_reference(_pthread_set_name_np, pthread_set_name_np);
void
_pthread_set_name_np(pthread_t thread, const char *name)
{
	(void)_pthread_setname_np(thread, name);
}

__weak_reference(_pthread_get_name_np, pthread_get_name_np);
void
_pthread_get_name_np(pthread_t thread, char *buf, size_t len)
{
	(void)_thr_getname_np(thread, buf, len);
}
```

The only thing I haven't understood yet is why `std` uses these versions of the functions returning `void`, but perhaps, I should simply open a pull request a get the reason in it from the owner.

**Comment by RalfJung** [comment]
Docs are better than code. Code can change any time, docs document the intent and long-term properties.

**Comment by RalfJung** [comment]
The _thr_getname_np implementation seems to *sometimes* set `buf[0] = '\0';`, but not in the branch where `_thr_find_thread() == 0` and `thread->state == PS_DEAD`. Very strange...

> The only thing I haven't understood yet is why std uses these versions of the functions returning void, but perhaps, I should simply open a pull request and get the reason in it from the owner.

The more informative ones might not have existed yet when this was added to std.

**Comment by YohDeadfall** [comment]
> Docs are better than code. Code can change any time, docs document the intent and long-term properties.

Not always, and I guess it applies mostly to Rust, Arch Linux and Linux man pages. I might be wrong, but only with thread names I found that:
* Apple gives no documentation at all (old links are broken, and the search gives nothing),
* Windows has documentation, but it's not different from not having it at all (the `HRESULT` I found for the fix came from an experiment and has no name, the function doc tells nothing about errors),
* FreeBSD [man pages](https://man.freebsd.org/cgi/man.cgi?query=pthread_set_name_np&manpath=FreeBSD+14.1-RELEASE+and+Ports) say nothing about all possible error codes except `ESRCH`.
