### ISSUE TITLE
Possibly false negative in leakage detection

### ISSUE THREAD

**Issue by cchanging** [rust-lang/miri#4060]
Hello，

I am using MIRI to perform some memory leak checks, but during the experiment, I found that a certain type of scenario involving global variables seems to lead to false negatives in leak detection. A simplified version of the case is as follows:

```rust
use std::sync::Arc;

static mut GLOBAL_STORE: Vec<Arc<usize>> = Vec::new();

fn main() {
    let item1 = Arc::new(32);
    unsafe {
        GLOBAL_STORE.push(item1.clone());
        let item1_pop = GLOBAL_STORE.pop().unwrap();
        assert_eq!(item1_pop, item1);

        std::mem::forget(item1_pop);
    }
}
// will not report leaks
```

I suspect that the reason for this situation might be that during the leakage check, the internal prov of the global variable is traversed, but the traversal does not take into account the `len` field of the `Vec`, thus still considering `item1` as a static storage, which actually no longer exists. This suspicion is based on the following reason: 

```rust
use std::sync::Arc;

static mut GLOBAL_STORE: Vec<Arc<usize>> = Vec::new();

fn main() {
    // report leak here.
    let item1 = Arc::new(32);
    unsafe {
        GLOBAL_STORE.push(item1.clone());
        let item1_pop = GLOBAL_STORE.pop().unwrap();
        assert_eq!(item1_pop, item1);
        
        // when overwriting the content originally at the position of `item1`, 
        // the leak error is reported normally.
        GLOBAL_STORE.push(Arc::new(12));
        std::mem::forget(item1_pop);
    }
}
```

I am not sure whether this is a bug or a situation that is temporarily unsupported, as I do not have seen any description of this case in the relevant documentation.

Thank you for your time in advance!

**Comment by RalfJung** [comment]
Thanks for the report!

All memory that is still reachable via a `static` is considered "not leaked". That includes pointers in the "dead" part of a `Vec` buffer.

So yeah, this is behaving as intended. Having type-specific logic for the leak check is not really feasible I am afraid.
