### ISSUE TITLE
Support missing for `libsodium`'s `crypto_hash_sha256` C function (through crate `libsodium-sys-stable`)

### ISSUE THREAD

**Issue by vcfxb** [rust-lang/miri#4073]
I got this error while testing a project in miri

```
error: unsupported operation: can't call foreign function `crypto_hash_sha256` on OS `linux`
```

Related docs: https://doc.libsodium.org/advanced/sha-2_hash_function

The project depends on https://crates.io/crates/libsodium-sys-stable btw

**Comment by RalfJung** [comment]
Thanks for the report! However, I'm afraid I don't think we will support cryptographic APIs like that, sorry. Miri can't implement every C library on the planet, and cryptographic APIs require enough care that I don't think we can provide them with reasonable effort.
