### ISSUE TITLE
Unable to install miri

### ISSUE THREAD

**Issue by gretchenfrage** [rust-lang/miri#4078]
Per the README, I run these commands on my system:

```sh
rustup +nightly component add miri
cargo +nightly miri test
```

It outputs this:

> This is a dummy package to make sure nobody malicious registers the cargo-miri crate. This crate was mentioned in a talk but not registered. If you think you deserve to be the owner of this package, please contact Bram Geron.

This looks similar to #2806. However, I have never cloned / developed on / locally built this repository. Moreover, my entire compute was built and its OS installation initialized after that issue was closed.

I am running Linux, NixOS 24.05.6632.c21b77913ea8.

**Comment by saethlin** [comment]
Based on just reading the text you posted, it looks like you tried to run `cargo install cargo-miri`. Remove the rustup component, then `cargo uninstall cargo-miri`, and perhaps the same for miri if you tried to install it that way too, then add the rustup component again.

**Comment by gretchenfrage** [comment]
That worked! Awesome, thanks.
