### ISSUE TITLE
./miri bench runs cargo-miri without a toolchain

### ISSUE THREAD

**Issue by saethlin** [rust-lang/miri#4086]
We are missing a specified toolchain here: https://github.com/rust-lang/miri/blob/f0fe74f2324cfe2114fa47ad558ff72e219debf0/miri-script/src/commands.rs#L419

You can see that we specify `+miri` in other commands, then forget it for the actual running of the benchmarks: https://github.com/rust-lang/miri/actions/runs/12270827404/job/34236690260#step:5:1959

I'm not speculating that this is the cause of that CI failure, but if nothing else it's goofy to have this discrepancy.

**Comment by RalfJung** [comment]
Good catch!
