### ISSUE TITLE
Miri allows transmuting &Cell to &mut Cell

### ISSUE THREAD

**Issue by not-an-aardvark** [rust-lang/miri#4117]
https://doc.rust-lang.org/nomicon/transmutes.html says:

> Transmuting an `&` to `&mut` is *always* Undefined Behavior.

However, Miri allows transmuting `&T` to `&mut T` if all bytes of `T` are part of an `UnsafeCell`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f6d5dba0c70cc63b714941d4b598323c . Based on the documentation, I would expect that Miri reports UB here. (Or if this is actually not considered to be UB due to newly-lenient behavior around `UnsafeCell`, then it seems like the documentation should be loosened.)

I'm unsure if it's caused by the same issue, but Miri also allows constructing a `Box` from a `&Cell` and then dropping the `Box` while the `&Cell` is still alive: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=58875c9849c27fb07df5130eeb2bbe0d (As expected, *reading* from the `&Cell` afterwards is correctly reported as UB. Attempting the same operation with a non-`Cell` causes UB to be reported when constructing the `Box`) IIUC, it's still undecided whether dangling references are instant UB. But it's surprising to me that this would be affected by whether the data that gets pointed to (which has already been freed) is a `Cell`.

**Comment by RalfJung** [comment]
Let me repeat the warning at the top of the Nomicon:

> Warning: This book is incomplete. Documenting everything and rewriting outdated parts take a while. See the [issue tracker](https://github.com/rust-lang/nomicon/issues) to check what's missing/outdated, and if there are any mistakes or ideas that haven't been reported, feel free to open a new issue there.

You are looking at a question where the exact resolution is still undecided. The nomicon takes a very conservative approach to steer people away from an gray areas. Miri needs to be based on a model that can actually be specified and implemented precisely. We currently support two models, [Stacked Borrows](https://github.com/rust-lang/unsafe-code-guidelines/blob/master/wip/stacked-borrows.md) and [Tree Borrows](https://perso.crans.org/vanille/treebor/). Both of those models indeed allow transmuting &Cell to &mut Cell under some conditions, but that does not imply a promise that Rust will allow such transmutes in the future. It will take some more years until "Miri accepts this code" can be understood as a promise that the code indeed is following stable established rules of Rust, and until that is the case, our documentation will continue to be written in a rather conservative style to reduce the risk of people relying on unstable experimental details in the behavior of Miri.
