### ISSUE TITLE
Make cargo-miri not link against librustc (through libmiri)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#418]
Why is cargo-miri so big? 4.4 MiB for what should be a tiny wrapper seems excessive. miri itself is just 2.2 MiB!

**Comment by memoryruins** [comment]
Below are some sizes after compiling cargo-miri with lto, opt-level `s`, and using ``strip`` for debug symbols. All built with --release.
```
    4.3 MiB [##########]  cargo-miri-opt-level-s
    4.3 MiB [######### ]  cargo-miri
    2.7 MiB [######    ]  cargo-miri-lto
    2.7 MiB [######    ]  cargo-miri-lto-opt-level-s
  776.0 KiB [#         ]  cargo-miri-strip
  744.0 KiB [#         ]  cargo-miri-opt-level-s-strip
  692.0 KiB [#         ]  cargo-miri-lto-strip
  640.0 KiB [#         ]  cargo-miri-lto-opt-level-s-strip
```

**Comment by RalfJung** [comment]
Thanks for the analysis!

I think what is happening is that `libmiri` gets linked into `cargo-miri`. Not sure if that can be avoided easily, probably we'd need to use a workspace and make it a separate crate that doesn't depend on all the miri stuff.

**Comment by RalfJung** [comment]
Turns out that even breaking this dependency doesn't actually make the binary any smaller. Looks like the linker does indeed remove almost all of the cruft...

https://github.com/rust-lang/miri/pull/1422 does the workspace porting anyway, but I'll close this size issue as there does not seem to be much we can do.
