### ISSUE TITLE
Add Cargo.lock

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#427]
It would be nice to make use of locking, to make sure CI and me actually test the same stuff.

The problem, if I recall correct what @oli-obk said, is that this lockfile would be picked up by rustc as well through the submodule, and we do not want that. Is that right? How do other tools handle this?

**Comment by RalfJung** [comment]
I am going to close this, as it's not a big deal and I am not even sure if it is worth fixing. (There's also something good about always using the latest version, and with Miri being distributed via rustup soon, this does not affect users.)

**Comment by RalfJung** [comment]
Reopening: in https://github.com/rust-lang/miri/pull/992, CI failed because a bump in a crate, together with not having a lockfile, means Miri doesn't build on CI any more. And until https://github.com/rust-lang/rust/pull/65342 landed we also cannot make it build any more, so Miri development is just halting until that situation is resolved.

That's quite awful, and having a lockfile would avoid this kind of situation.

@ehuss is there any way to have a lockfile here in the Miri repo in a way that when the same file appears in the rustc tree (due to it being a submodule), it does not cause trouble?

**Comment by ehuss** [comment]
I think it should be fine to add a `Cargo.lock`, it should be ignored in the rustc repo.  Was there a specific error you encountered when you tried?

You'll probably need to keep it somewhat in sync with rustc's lock file, which might be a little tedious, but probably better than not working at all.

**Comment by RalfJung** [comment]
Hm, @oli-obk do you remember what the issue was?

**Comment by mati865** [comment]
FWIW both RLS and Rustfmt have Cargo.lock in their repo and it doesn't cause issues for Rust.

**Comment by RalfJung** [comment]
@mati865 ah, that's great!
https://github.com/rust-lang/miri/pull/995 adds a lockfile to Miri, then.
