### ISSUE TITLE
Use bors for merging PRs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#430]
Mostly because I think it would be cool, but also because we sometimes (rarely) do have some kind of queue. ;)

I will look into what it takes, but I assume at some point we need help by @solson.

**Comment by RalfJung** [comment]
I think I am finally frustrated enough by the manual merging that I am ready for this.

@rust-lang/infra what would we have to do to use the bors that rust/cargo/... use? Or would it be preferred for us to use  https://app.bors.tech/ ?

**Comment by pietroalbini** [comment]
@RalfJung see https://github.com/rust-lang/rust-central-station/pull/204 and https://github.com/rust-lang/team/pull/63 to configure bors.

**Comment by RalfJung** [comment]
All right, submitted https://github.com/rust-lang/rust-central-station/pull/265 and https://github.com/rust-lang/team/pull/76.

**Comment by RalfJung** [comment]
@pietroalbini is there a recommended way to set up branch protection and stuff in the Miri repo, to make bors work best? I guess you'll have to do that anyway though, I don't have admin powers.

**Comment by pietroalbini** [comment]
Ok, bors is now fully configured. :tada: -- [Queue page](https://buildbot2.rust-lang.org/homu/queue/miri)

> is there a recommended way to set up branch protection and stuff in the Miri repo, to make bors work best?

I configured branch protection so that only bors can push to the master branch.

**Comment by RalfJung** [comment]
Awesome, thanks a lot!

I guess now we should adjust our CI to do the main testing only in PRs and on the `auto` and `try` branches, but not on `master`?

**Comment by pietroalbini** [comment]
Yeah, that would be ideal.

**Comment by RalfJung** [comment]
I just realized that my central-station PR mentioned Travis but not AppVeyor. Do we have to list that as well there somehow?

**Comment by RalfJung** [comment]
All right, this seems to be working. :)  Thanks a lot @pietroalbini !
