### ISSUE TITLE
Fix TLS dtor + memory leaks on macOS

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#443]
We currently ignore memory leaks on macOS. Likely, this is due to not properly executing TLS destructors in `_tlv_atexit`. Debugging this requires a libstd with full MIR for macOS, which currently we do not know how to do cross-platform -- so, someone who's actually using macOS should take this.

**Comment by mtak-** [comment]
IIUC this was fixed here: https://github.com/rust-lang/rust/issues/57534

**Comment by RalfJung** [comment]
The issue here is about Miri entirely ignoring `_tlv_atexit`. This is a Miri issue, not a rustc issue, and I don't think these PRs fix it.

**Comment by kennethbgoodin** [comment]
I'd like to take a crack at this issue. I have a macOS laptop, just need some guidance on where to get started. 😄

**Comment by RalfJung** [comment]
@kennethbgoodin great! Not knowing the macOS APIs in detail, I can only guess here. The first step is to make sure that you can locally build and run Miri; please let me know if you need any help with that.

Then remove macOS from [this line](https://github.com/rust-lang/miri/blob/22d0546aed2f0c8545f939fe756ababae7a5020b/src/eval.rs#L201) to enable leak checking on macOS. `./miri test` should fail now. Note which test(s) failed so that you can run them directly to check your changes!

My guess for what you will need to implement is [this stub](https://github.com/rust-lang/miri/blob/22d0546aed2f0c8545f939fe756ababae7a5020b/src/shims/foreign_items.rs#L764). Unfortunately I found no docs for `_tlv_atexit`, but it is instructive to see how Rust calls that function, which [happens here](https://doc.rust-lang.org/src/std/sys/unix/fast_thread_local.rs.html#46). You will have to add a new field to Miri's `Machine` to remember the fn ptr that is to be called on exit, and then call that function [around here](https://github.com/rust-lang/miri/blob/22d0546aed2f0c8545f939fe756ababae7a5020b/src/eval.rs#L191).

These are high-level instructions; I can go into more detail once you have concrete questions. :)

**Comment by kennethbgoodin** [comment]
Okay I've done the first steps and have which tests are failing (168!). 

From looking at what rustc does it sounds like our `_tlv_atexit` needs to accept a thread local list of destructors for each thread's globals. I'm not sure how I would go about constructing that list though.

Adding the field to `Machine` and calling that function ptr sounds straightforward enough.

**Comment by RalfJung** [comment]
> From looking at what rustc does it sounds like our _tlv_atexit needs to accept a thread local list of destructors for each thread's globals. I'm not sure how I would go about constructing that list though.

Why that? All I can see is a single function pointer, and a pointer that is passed to that function as an argument.
