### ISSUE TITLE
Teach miri about unsized locals

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#449]
These are just unsized in the typesystem. They are actually just fat pointers

https://play.rust-lang.org/?gist=43d2f8256e22ed27e79b5e58082b3357&version=nightly&mode=debug&edition=2015 is a small example that should work

**Comment by RalfJung** [comment]
Basically I think all we have to do is remove a bunch of asserts, and teach `copy_op` to with with the dynamic, not static, size. Shouldn't be hard.

... famous last words...

**Comment by RalfJung** [comment]
Likely also relevant (at least for tests): https://github.com/rust-lang/rust/pull/54183

**Comment by RalfJung** [comment]
@oli-obk 

> These are just unsized in the typesystem. They are actually just fat pointers

Looking at the MIR, I cannot see this at all.  What makes you say that?

My current impression is that the best way to support this is to actually have proper unsized locals, with the fat-ptr-meta stored in the `Place` that is stored in miri's `locals` table.

**Comment by RalfJung** [comment]
Has been fixed by https://github.com/rust-lang/rust/pull/59780.
