### ISSUE TITLE
Do we need even more agressive validation?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#508]
Currently, we do not catch this:
```rust
#![feature(rustc_attrs)]
#![allow(unused_attributes)]

#[rustc_layout_scalar_valid_range_start(1)]
#[repr(transparent)]
pub(crate) struct NonZero<T>(pub(crate) T);

fn main() {
    let mut x = Some(NonZero(1));
    let xref = match x {
        Some(ref mut c) => c,
        None => panic!(),
    };
    *xref = NonZero(0);
}
```
In the MIR, the `*xref = NonZero(0)` becomes an assignment of the only *field* of this struct, and that field is of type `i32` and hence value `0` is no problem.

I could imagine doing validation of prefixes of the path involved in an assignment, but I see no way to catch the following:
```rust
fn main() {
    let mut x = Some(unsafe { NonZero(1) }); // this one is fine
    let xref = match x {
        Some(NonZero(ref mut c)) => c,
        None => panic!(),
    };
    *xref = 0; // this one is not
}
```
This won't even be caught by @oli-obk's new unsafety check for constructing `NonZero`.

(The last example is not specific to `NonZero` at all; writing `2` into a `&mut bool` after casting it to `*mut u8` is similar.)

**Comment by oli-obk** [comment]
aaand now I'm gonna make taking references to fields of `rustc_layout_scalar_valid_range_start` unsafe, too.

**Comment by oli-obk** [comment]
cc @centril ralf found "the next hole". That didn't take very long

**Comment by Centril** [comment]
Dear lord. =P

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/unsafe-code-guidelines/issues/189: this is first and foremost a question of "what is the spec", not how to implement it.
