### ISSUE TITLE
Make miri easier to install

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#520]
It would be great if we could make miri easier to install.

### miri + cargo miri

One thing is getting miri (and cargo-miri) itself. The ideal solution here would be making this a `component` in rustup so that it comes with a matching nightly. The dev-tools team has said they would support us in getting that done, after the edition.

### libstd

However, miri isn't extremely useful if libstd comes without all the MIR. Right now, I don't think just making it a component is going to do much good, if people still have to then clone our repo to run `xargo/build.sh`.

The best I can think of here is to do this automatically in miri itself: Basically, to move `xargo/*` into the miri library, and have a setup step in the beginning which automatically compiles and then uses an appropriate libstd. Sounds rather hacky, but does anyone have a better idea?

**Comment by oli-obk** [comment]
I'll do it over the holidays. I'll want to deduplicate some work between e.g. clippy and miri distribution instead of just copypasting everything.

**Comment by RalfJung** [comment]
Sounds great :)

**Comment by RalfJung** [comment]
@oli-obk what is the state of making Miri a rustup component?

**Comment by mati865** [comment]
I believe it should be available with next release of rustup (or with git checkout).

**Comment by RalfJung** [comment]
I thought rustup needs patching to hook `cargo-miri`, or so?

**Comment by mati865** [comment]
You mean https://github.com/rust-lang/rustup.rs/pull/1606?

**Comment by RalfJung** [comment]
Ah, I didn't know that already landed!

Whom should we bug for a rustup release?

**Comment by mati865** [comment]
Most of the releases were made by `alexcrichton`, Idk about the preferred way to contact.

**Comment by RalfJung** [comment]
@alexcrichton When do you usually make rustup releases? Would be nice to get one that includes the Miri support.

**Comment by alexcrichton** [comment]
It's just on-demand, there's no schedule currently. There's development happening on rustup right now and presumably when that reaches a good point a release can be made.

**Comment by superriva** [comment]
@alexcrichton , new rustup release needs to testing of the first miri component installation.

**Comment by RalfJung** [comment]
It seems there was a new rustup release. What's next?

**Comment by oli-obk** [comment]
Curious:

```
➜  cargo miri
error: 'cargo-miri' is not installed for the toolchain 'nightly-x86_64-unknown-linux-gnu'
To install, run `rustup component add miri --toolchain nightly-x86_64-unknown-linux-gnu`
➜  rustup component add miri --toolchain nightly-x86_64-unknown-linux-gnu
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'miri' for target 'x86_64-unknown-linux-gnu'
```

**Comment by mati865** [comment]
@oli-obk you didn't add it to https://github.com/rust-lang/rust/blob/88f755f8a84df1d9e6b17cf10c96ae8b93481b2e/src/tools/build-manifest/src/main.rs#L344

**Comment by oli-obk** [comment]
That explains it. I was sure I checked every `clippy` mention, but I might've only looked in bootstrap.

Thanks!

**Comment by mati865** [comment]
https://github.com/rust-lang/rust/pull/58990 was merged, it should work with next nightly.

**Comment by superriva** [comment]
Yes, miri is available in rustup component list now.
```
 rustup component list | grep miri
miri-x86_64-unknown-linux-gnu
```

**Comment by RalfJung** [comment]
Also, shouldn't it be called `miri-preview`?

**Comment by superriva** [comment]
@RalfJung ,
```
rustup component add miri-preview
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'miri-preview' for target 'x86_64-unknown-linux-gnu'
```

**Comment by mati865** [comment]
I debugged `rustup` and there is mismatch  between `miri` and `miri-preview`.
Rust's `dist` crates directory `miri-preview` but but the manifest tells `rustup` to look for `miri`.
Chaning `miri-preview` to `miri` is simple, the other way around requires a bit more work.

I can try to fix it but which name should be used `miri` or `miri-preview`?

**Comment by oli-obk** [comment]
if there's a discrepancy anyway, let's go with `miri-preview` in order to communicate the unstable nature of it

**Comment by mati865** [comment]
Opened https://github.com/rust-lang/rust/pull/59236

**Comment by RalfJung** [comment]
@mati865 awesome, thanks!

But then I assume rustup also needs updating? With https://github.com/rust-lang/rustup.rs/pull/1606/files, it says to install `miri` when the `cargo-miri` binary is missing.

**Comment by mati865** [comment]
IIRC both `miri` and `miri-preview` should work because of rename.

**Comment by superriva** [comment]
```
rustup component list | grep miri
miri-x86_64-unknown-linux-gnu
```
```
rustup component add miri
info: downloading component 'miri'
info: installing component 'miri'
info: rolling back changes
error: component manifest for 'miri' is corrupt

rustup component add miri-preview
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not contain component 'miri-preview' for target 'x86_64-unknown-linux-gnu'
```
Ping. It's still unavailable.

**Comment by mati865** [comment]
@superriva the PR isn't merged yet.

**Comment by orium** [comment]
https://github.com/rust-lang/rust/pull/59236 landed.  Does rustup need to be updated as well?

**Comment by mati865** [comment]
It landed 35 minutes late for the nightly, it should work tomorrow.

sob., 23 mar 2019, 11:45 użytkownik Diogo Sousa <notifications@github.com>
napisał:

**Comment by mati865** [comment]
:confetti_ball: Seems to be finally fixed, running in clear container:
```
root@bc89da8c8ed5:/# rustup component add miri
info: downloading component 'miri'
info: installing component 'miri'
root@bc89da8c8ed5:/# cargo miri
It seems you do not have a recent enough xargo installed. I will run `cargo install xargo -f`. Proceed? [Y/n]
...
```

**Comment by oli-obk** [comment]
cc @shepmaster you can now install miri as a component instead of building it yourself

**Comment by RalfJung** [comment]
Awesome. :)

**Comment by orium** [comment]
The component doesn't seem to be available anymore:

```text
$ rustup component add --toolchain nightly miri-preview
error: component 'miri' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly'
```

**Comment by RalfJung** [comment]
Yeah, that is waiting for https://github.com/rust-lang/rust/pull/59555 to land.

Just like Clippy and RLS, Miri sometimes gets broken by rustc changes and then a fix has to land before it can be installed via rustup again.
