### ISSUE TITLE
Travis macOS cache broken?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#563]
All our Travis macOS builds end in
```
store build cache
0.01s3.45schanges detected, packing new archive
FAILED: tar -Pzcf /Users/travis/.casher/push.tgz 
tar: no files or directories specified
uploading master/cache-osx-e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.tgz
failed to upload cache
curl: Can't open '/Users/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
```
I have no idea why that is or what it means, but it seems wrong.

**Comment by RalfJung** [comment]
With the move to travis-ci.com, the error message went away, but there does not seem to be any caching on macOS at all any more? Linux jobs end with a `store build cache` step, but [macOS jobs don't](https://travis-ci.com/rust-lang/miri/jobs/178407040). 

Cc @pietroalbini

**Comment by RalfJung** [comment]
Oh, I think I know what the problem is... we tell travis to cache `/home/travis/.cargo` but the directory is different on macOS.

Unfortunately, the travis docs contain no guidance for how to do custom caching for cross-platform configurations... can I use `$HOME`? Can I configure per-platform directories?

**Comment by pietroalbini** [comment]
You should be able to use `$HOME`.
