### ISSUE TITLE
Add foreign functions for reconfiguring miri at evaluation time

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/miri#579]
Assume that someone wants function pointers to be equal if they point to the same function, instead of just having identity at creation time. So `f as fn() == f` should be true instead of false like it is right now.

Now we don't want this in general, but someone might desire to have code behave this way. We have three options in the regular curriculum of feature flags:

* command line arguments
* attributes in the code
* environment variables

I propose we add a fourth way: magic extern functions that miri uses to change its internal state.

Users could write

```rust
extern "Rust" {
    fn __miri_function_pointer_identity(b: bool);
}
fn main() {
    assert_ne!(main as fn(), main);
    unsafe { __miri_function_pointer_identity(false); }
    assert_eq!(main as fn(), main);
}
```

The evaluator gets a `bool` flag which it uses for figuring out whether to compare function pointers or whether to compare the functions they point to.

Calling the `__miri_function_pointer_identity` function during interpretation would then invoke the foreign function injection code, where we'd implement it to change that boolean.

**Comment by RalfJung** [comment]
> I propose we add a fourth way: magic extern functions that miri uses to change its internal state.

I'm very much against internal state. State is almost always bad, it's non-composeable and makes debugging horrible. You are reinventing something like the floating point state here.

But what I could imagine is having an intrinsic that in miri performs a somewhat different comparison. `==` is basically "must-be-equal", and we could have a "may-be-equal" intrinsic. This would behave the way you want on function pointers, and it could also treat other pointers differently from `==`.

**Comment by RalfJung** [comment]
@oli-obk I am fine closing this, but what is the reason you do this now, more than half a year after the last comment was made here?

**Comment by oli-obk** [comment]
I talked with @christianpoveda , who linked me to this issue. I reread it and it always was an oddball idea. Not really something I'm behind and you dislike it anyway. In our default mode with intptr we could just go back to the original behaviour where two functions pointers to the same function are equal
