### ISSUE TITLE
miri is too permissive around ZSTs

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#582]
The following code passes, but it probably should not:
```rust
fn main() {
    let b = Box::new(0);
    let ptr = &*b as *const _ as *const ();
    drop(b);
    let _val = unsafe { *ptr }; // UB?
    let _val = unsafe { &*ptr }; // UB!
}
```
I am not 100% sure what the rules are for LLVM here, but it seems safer to not allow ZSTs into dangling allocations (whereas ZSTs with integers pointers are fine). The read might be fine, but certainly we shouldn't consider them valid as references, as `.offset(0)` is considered invalid on dangling non-integer pointers.

**Comment by oli-obk** [comment]
> as .offset(0) is considered invalid on dangling non-integer pointers.

Why is that invalid?

We do have all information (like alignment and bounds) available. So we could in fact check whether reading a zst from a dangling pointer is fine.

**Comment by RalfJung** [comment]
> Why is that invalid?

LLVM says `getelementptr inbounds` must be in-bounds, and it makes no exception for offset 0.

We construct our own exception, so to speak, for integer pointers based on the argument that LLVM cannot exclude the existence of other allocations it doesn't know about, and if these allocations have size 0 then it cannot cannot deduce much from learning about their existence.

**Comment by RalfJung** [comment]
This fails these days. I will try to figure out if we already have a test.
