### ISSUE TITLE
miri can't access foreign statics

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/miri#591]
miri cannot access foreign statics, e.g.,

```rust
pub fn page_size() -> usize {
    unsafe { PAGE_SIZE as _ }
}

extern "C" {
    static PAGE_SIZE: u32;
}
```

**Comment by RalfJung** [comment]
True, but I don't think this bug is possible to fix. I mean, what value should it return?

miri has infrastructure for hard-coding the behavior of some foreign statics, but for user-defined ones that's just as impossible as calling C code via FFI.  So I think this is WONTFIX.

**Comment by gnzlbg** [comment]
Can’t miri perform C FFI calls? I recall hearing that miri could do this
from @oli-obk but I might have misunderstood the claim.

**Comment by RalfJung** [comment]
It cannot. There are some pipe dreams for how one might go about doing that, but that's it.

**Comment by oli-obk** [comment]
Yea, we're just gonna keep hardcoding things or maybe manually implement these to actually read the system value.

Having a full bridge to the system is quite an undertaking that I don't know if it would pay off.

**Comment by gnzlbg** [comment]
I see. I wanted to use miri to test slice-deque since it is very prone to
having undefined behavior but that either requires being able to interface
with system libraries (winapi, mach, Linux sus calls, etc.) or somehow
detecting “miri” as the system and calling some miri APIs.

**Comment by oli-obk** [comment]
can you emulate this via heap allocations?

Depending on the complexity of the APIs we could also just emulate the appropriate c API inside miri. We already do that for e.g. `setenv` and friends and a bunch of `pthread` functions.

**Comment by gnzlbg** [comment]
> can you emulate this via heap allocations?

No, heap allocations are not enough to emulate this. This requires a lower-level API like `mmap` + `memfd_create`, the System V inter-process shared memory APIs, etc.

**Comment by RalfJung** [comment]
Yeah that sounds thoroughly out of scope, for now.

**Comment by RalfJung** [comment]
Is there any point in keeping this bug open? It is about as useful as "miri can't call foreign functions". For *particular* functions/statics, we might want to track implementing them eventually, but such a catch-all bug makes little sense IMO.

**Comment by oli-obk** [comment]
We have the related open PR (#594) for the actionable items.
