### ISSUE TITLE
Apparent mutable aliasing detected in one case but not in another

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/miri#628]
We have two pieces of similar code; one reports a Miri error, the other doesn't. Both seem like they should. 

Is this user error or Miri error?

Using Miri 2019-02-10 ecb8755

# Errors

```rust
fn main() {
    let mut x = [42, 84];
    let x_0: &mut [i32; 2] = unsafe { &mut *(&mut x as *mut [i32; 2]) };
    let x_1: &mut [i32; 2] = &mut x;

    println!("{}, {}", x_0[0], x_1[1]);
}
```

```none
error[E0080]: constant evaluation error: Borrow being dereferenced (Uniq(1772)) does not exist on the stack
 --> src/main.rs:6:24
  |
6 |     println!("{}, {}", x_0[0], x_1[1]);
  |                        ^^^^^^ Borrow being dereferenced (Uniq(1772)) does not exist on the stack
  |
  = note: inside call to `main` at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:64:34
  = note: inside call to closure at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:52:53
  = note: inside call to closure at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:297:40
  = note: inside call to `std::panicking::try::do_call::<[closure@DefId(1/1:1900 ~ std[82ff]::rt[0]::lang_start_internal[0]::{{closure}}[0]) 0:&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe], i32>` at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panicking.rs:293:5
  = note: inside call to `std::panicking::try::<i32, [closure@DefId(1/1:1900 ~ std[82ff]::rt[0]::lang_start_internal[0]::{{closure}}[0]) 0:&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe]>` at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/panic.rs:388:9
  = note: inside call to `std::panic::catch_unwind::<[closure@DefId(1/1:1900 ~ std[82ff]::rt[0]::lang_start_internal[0]::{{closure}}[0]) 0:&dyn std::ops::Fn() -> i32 + std::marker::Sync + std::panic::RefUnwindSafe], i32>` at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:52:25
  = note: inside call to `std::rt::lang_start_internal` at /root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:64:5
  = note: inside call to `std::rt::lang_start::<()>`
```

# No errors

```rust
fn test(x: &mut [i32; 2]) {
    let x_0: &mut [i32; 2] = unsafe { &mut *(x as *mut [i32; 2]) };
    println!("{}, {}", x_0[0], x[1]);
}

fn main() {
    test(&mut [42, 84]);
}
```

**Comment by bjorn3** [comment]
I believe in the second case the `x_0` borrow gets popped once `x[1]` is executed, while in the first case `x_0` gets popped at `let x_1: &mut [i32; 2] = &mut x;`.

**Comment by rodrigorc** [comment]
Actually, these two pieces of code are not the same. In the first one you take the address of `x` twice: one as an unsafe ref and one as a normal reference. In the second one you only take the reference once and then use the unsafe block to duplicate the reference.

Both are undefined, but slightly different.

**Comment by RalfJung** [comment]
The key difference is this line
```rust
let x_1: &mut [i32; 2] = &mut x;
```
This counts as a write access to all of `x`, hence the first code gets rejected.

The second code, IMO, is fine. @rodrigorc why do you say it is undefined? `x_0` gets created as a reborrow from `x`, then `x_0` gets used, then `x` gets used. Now `x_0` may not be used again, but the code does not use it again.

Notice that the following *is* an error:
```rust
fn test(x: &mut [i32; 2]) {
    let x_0: &mut [i32; 2] = unsafe { &mut *(x as *mut [i32; 2]) };
    println!("{}, {}", x_0[0], x[1]);
    println!("{}, {}", x_0[0], x[1]);
}

fn main() {
    test(&mut [42, 84]);
}
```

**Comment by rodrigorc** [comment]
@RalfJung Well, `x_0` is a reborrow of a mutable reference, I assumed that this is undefined, but I may be wrong.

If you suggest that reborrowing a mutable reference is ok as long as the usage of the reborrow does not overlap with the usage of the original reference, then this slightly modified first code:

```
fn main() {
    let mut x = [42, 84];
    let x_1: &mut [i32; 2] = &mut x;
    let x_0: &mut [i32; 2] = unsafe { &mut *(x_1 as *mut [i32; 2]) };
    println!("{}, {}", x_0[0], x_1[1]);
}
```

should also be correct. And indeed Miri accepts it.

**Comment by RalfJung** [comment]
> Well, `x_0` is a reborrow of a mutable reference, I assumed that this is undefined, but I may be wrong.

I do not follow. Reborrows of mutable references are possible in safe code.

Reborrows that "chain though" a raw pointer are also extremely common, consider e.g. [`split_at_mut`](https://doc.rust-lang.org/nightly/src/core/slice/mod.rs.html#991-1001).

**Comment by rodrigorc** [comment]
Oh... I see. That's why this code is safe and valid, just like the second code but without the `unsafe`:

```
fn main() {
    let mut x = [42, 84];
    let x_1: &mut [i32; 2] = &mut x;
    let x_0: &mut [i32; 2] = &mut *x_1;
    println!("{}", x_0[0]);
    println!("{}", x_1[1]);
}
```

The thing with `split_at_mut` is that the returned references do not overlap, so it is totally safe.

So, IIUIC, the first code in the OP is wrong because both mutable borrows overlap, while the second code is ok because the borrows do not overlap in time (although they overlap in memory).

And Miri was right all the time! Is this right?

**Comment by shepmaster** [comment]
> `x_0` gets created as a reborrow from `x`, then `x_0` gets used, then `x` gets used.

Wow, which means that this is OK:

```rust
println!("{}, {}", x_0[0], x[1]);
```

And this is an error:

```rust
println!("{}, {}", x[1], x_0[0]);
```

That's *incredibly* subtle.

**Comment by RalfJung** [comment]
> That's _incredibly_ subtle.

I guess it is. Notice, however, that this is exactly the same principle according to which this code is accepted by NLL
```rust
let x = &mut 0;
let y = &mut *x;
*y = 3;
*x = 4;
```
and this code is not
```rust
let x = &mut 0;
let y = &mut *x;
*x = 4;
*y = 3;
```
The order of accesses matters for the lifetime discipline. Stacked Borrows just extrapolates this to unsafe code.

**Comment by shepmaster** [comment]
What would be the safe equivalent inside of a single function (well, macro...) call? Both orderings in the `println!` here report compile errors:

```rust
fn main() {
    let mut x = 42;
    let x_0 = &mut x;
    let x_1 = &mut x;
    // Both of these cause errors
    // println!("{}, {}", x_0, x_1);
    // println!("{}, {}", x_1, x_0);
}
```

**Comment by RalfJung** [comment]
Seems like NLL considers all accesses in a statement to kind-of happen "together".  But of course that does not make much sense for an operational (dynamic) model -- the syntax is long gone at this point, all we see are the primitive operations and in which order they happen.

**Comment by RalfJung** [comment]
Closing as not-a-bug.
