### ISSUE TITLE
Is it possible to use miri as standalone interpreter for independent *.rs files? If yes, how?

### ISSUE THREAD

**Issue by superriva** [rust-lang/miri#639]
Is it possible to use miri as standalone interpreter for independent *.rs files? If yes, how?
I did:
[1]
`cargo +nightly install --force --git https://github.com/solson/miri miri`
[2]
`cargo +nightly miri setup`
[3]
I would like to run independent rs file:
`miri simple.rs`
```
// simple.rs
fn main() {
    let x = 13;
    let _y = 3*x + 3;
}
```
And I get the error:
```
error[E0080]: constant evaluation error: no mir for `std::rt::lang_start_internal`
   |
   = note: inside call to `std::rt::lang_start::<()>`
error: aborting due to previous error
For more information about this error, try `rustc --explain E0080`.
```
Excuse me, where am I wrong? Thx.

**Comment by oli-obk** [comment]
When the setup finishes, it tells you about an environment flag that you need to set. Without that flag we can't find the built `libstd` with the MIR. This is documented in https://github.com/rust-lang/miri#using-a-nightly-rustc and most likely `export MIRI_SYSROOT=~/.cache/miri/HOST` will work for you

**Comment by superriva** [comment]
Yes, that works. Thx!

**Comment by RalfJung** [comment]
I am actually quite surprised that you are not getting an error saying it couldn't find some `.so` file. That's what I would expect when you directly run `miri`.

Also notice that Miri is not meant as the kind of interpreter that you'd actually want to run programs in "for real". If you want a quick and easy way to run a `.rs` file, look for "cargo-script".

**Comment by superriva** [comment]
@RalfJung , do you think about to put miri's libs into cargo home directory? I think it looks like naturally:
```
.../cargo/bin/cargo
.../cargo/git/...
.../cargo/registry/...
.../cargo/bin/miri
.../cargo/bin/cargo-miri
.../cargo/lib/miri/HOST...
```

**Comment by RalfJung** [comment]
*shrug* I am not really attached to any particular location, but I also don't see what changing the location would buy us.
