### ISSUE TITLE
Should be able to change stack limit

### ISSUE THREAD

**Issue by orium** [rust-lang/miri#643]
It is currently not possible to change the stack limit. It would be great to get that functionality back!

# Original report

Maybe I'm doing something wrong, but I'm unable to set the stack limit for miri.

If I call `cargo miri test --help` it says:

```text
The config flag `miri` is automatically defined for convenience. You can use
it to configure the resource limits

    #![cfg_attr(miri, memory_size = 42)]

available resource limits are `memory_size`, `step_limit`, `stack_limit`
```

After adding

```rust 
#![cfg_attr(miri, stack_limit = 100000)]
```

to my `lib.rs` I get "stack limit reached error" at the same depth.

**Comment by RalfJung** [comment]
@oli-obk did that get lost in the move to rustc?

**Comment by orium** [comment]
I think it was.  For quickly grepping rustc's repository it looks like this value is hardcoded to 100:

https://github.com/rust-lang/rust/blob/f47ec2ad5b6887b3d400aee49e2294bd27733d18/src/librustc/session/mod.rs#L1188

I didn't find any place where this field gets changed (https://github.com/rust-lang/rust/search?q=const_eval_stack_frame_limit).

Not sure about the other configurations (`memory_size`, `step_limit`).

**Comment by oli-obk** [comment]
Hm. yes, they seem to have gotten lost. We should probably just remove that limitation entirely, just like we got rid of the memory limit.

**Comment by orium** [comment]
Currently rustc uses this `stack_limit = 100` when [evaluating const fn](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b36cfea0a3d54ae6a040a488f129e185).

Do we want to keep this limit for compilation?

**Comment by oli-obk** [comment]
For const eval we can just use the recursion limit, which is already configurable by users

**Comment by RalfJung** [comment]
The bug part of this is now "fixed" by removing this text from `--help`.

I am turning this into a ticket to track the enhancement request that the stack limit should be changeable.

**Comment by CAD97** [comment]
I think https://github.com/rust-lang/rust/pull/66726 should address this?

I would just like to note that I hit the stack frame limit exactly, which prompted me to check how difficult it'd be to change this:

```
>cargo miri test
[...]
error: Miri evaluation error: reached the configured maximum number of stack frames
   --> D:\usr\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\src\libcore\mem\mod.rs:245:5
    |
245 |     intrinsics::size_of::<T>()
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri evaluation error: reached the configured maximum number of stack frames
    |
```
