### ISSUE TITLE
Miri is very slow

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/miri#654]
Hashbrown's unit test `test_lots_of_insertions` takes too long to run under miri. 
Maybe it might be worth to investigate what this test does and see if there are any low hanging fruit optimizations that can be applied to miri to make it run faster.

**Comment by RalfJung** [comment]
Yeah, Miri is pretty slow -- not sure how useful it is to keep a bug about that open, but whatever.

**Comment by elichai** [comment]
So Miri just took all my 32GB of RAM + 4GB of swap. I'll try to see if I can pinpoint where/what takes so much memory, but it did seem like there's not a lot of cleanup after each test is finished

**Comment by RalfJung** [comment]
Do we want to keep some kind of general tracking issue open for the perf problems or does that not make sense?

**Comment by oli-obk** [comment]
If we have specific slow examples, we can open issues for those, but a tracking issue (that hasn't seen a comment in 3 years and no cross reference in 2) is probably not too useful
