### ISSUE TITLE
Installation instructions in the readme "incomplete"

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/miri#656]
The installation instructions should include

```
rustup component add rust-src
cargo install xargo
```

or at least mention that these are required. Ideally the code provided should just work on a clean Rust install.

**Comment by bjorn3** [comment]
`cargo miri setup` will install both when they are not yet installed.

**Comment by RalfJung** [comment]
And moreover `cargo miri run` will do the same. So the following

> Ideally the code provided should just work on a clean Rust install.

is the case, I think. Could you provide reproducible instructions for when Miri does not work on a clean install?

**Comment by gnzlbg** [comment]
@RalfJung so I've set up miri in hashbrown CI. Locally, I followed the readme, and it worked. However, on Travis-CI, `rust-src` and `xargo` were not installed. The `cargo miri test` did report that, and also asked whether these should be installed, but CI hanged on a `Y/n` input prompt. So I installed `xargo`, repeat, got error about rust-src, install that, repeat. 

Ideally, the readme should contain something like:

> To install miri:
> 
> ```
> cargo install ... miri
> cargo miri setup
> ```
> 
> and to run all tests under miri: `cargo miri test`. 

If everything is set up, `cargo miri setup` should return success independently of whether anything had to be installed or not. 

For a big bonus, maybe add a section about how to set up miri robustly on CI. This is not what `hashbrown` is using, but this is what I'd like to use:

```yml
- name: "miri"
   rust: nightly
   script: |
       if [ travis_retry cargo +nightly install --force --git https://github.com/rust-lang/miri miri ]; then
           travis_retry cargo miri setup
           cargo miri test
       fi 
```

Robust here means that, if miri does not build on nightly, the job should pass. And if something fails to download, that download should be retried to reduce spurious build job failures due to VM network issues.

**Comment by RalfJung** [comment]
Won't the `travis_retry` retry building Miri three times if the nightly is broken? That seems annoying.

**Comment by gnzlbg** [comment]
> Won't the travis_retry retry building Miri three times if the nightly is broken? That seems annoying.

Yes, I think one might be able to use a `CARGO_NET_RETRY=N CARGO_NET_TIMEOUT=M cargo +nightly install ....` to retry downloads N times and waiting M seconds between each retry, but I'm not sure. cc @ehuss

**Comment by RalfJung** [comment]
@gnzlbg once you have actually used this CI snippet somewhere (so we know it works), could you open a PR to add a CI section to the README?

**Comment by gnzlbg** [comment]
I'll do that.

**Comment by ehuss** [comment]
> CARGO_NET_RETRY=N CARGO_NET_TIMEOUT=M

I think it is `CARGO_HTTP_TIMEOUT`.  Retry defaults to 2 (for a total of 3 attempts), and timeout defaults to 30 seconds.
