### ISSUE TITLE
type validation failed: encountered undefined address

### ISSUE THREAD

**Issue by flagello** [rust-lang/miri#661]
Valid use of `core::mem::uninitialized` triggers type validation failure ([minimal playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=806abc8b816672c9ac6585e5d1a25754)). Is it supposed to be a gateway to `MaybeUninit`?

**Comment by RalfJung** [comment]
This is not a valid use of `mem::uninitialized`. References must be non-NULL, and `mem::uninitialized` could result in a NULL value.

**Comment by flagello** [comment]
Of course they must be, but as far as safe Rust is concerned then so should any other value that is not a raw pointer. That is, since reading any uninitialized value is UB, and since the above adjusted to `let mut a: N;` in place of `let mut a: N = unsafe { std::mem::uninitialized() };` works fine and is uninitialized memory as well, then shouldn‘t Miri allow uninitialized references as well and then check for reads on uninitialized memory as it normally does for values?

The use case is a giant struct constructor where using raw pointers or `Optional` is way more trouble than it‘s worth.

**Comment by RalfJung** [comment]
The invariant about references being non-NULL kicks in for all variables that Rust considers initialized. `let x: N;` is not subject to any optimizations as it is statically not initialized. `let x: N = mem::uninitialized()` is fully initialized as far as rustc is concerned (you got some value from some function and used it to initialize `x`), and thus must satisfy the invariant.

> The use case is a giant struct constructor where using raw pointers or Optional is way more trouble than it‘s worth.

`Option` won't help here, uninitialized memory is never good for an enum. You can, however, use `mem::zeroed` with `Option<&[mut T]>`, that will work.

If you have references in your struct, you need to initialize them, period. No exceptions. Sometimes you want to initialize things field by field, that is what `MaybeUninit` is meant for. But the moment you go from `MaybeUninit<MyStruct>` to `MyStruct`, all fields must have been initialized.

(The discussion whether uninitialized raw pointers are okay is still ongoing. Miri allows them for now, but that might change.)
