### ISSUE TITLE
can't call foreign functions from cmath (libm)

### ISSUE THREAD

**Issue by cuviper** [rust-lang/miri#667]
I just tried `cargo miri test` on the various [num](https://github.com/rust-num) crates. I got pretty far, but I was stopped by errors on foreign function calls from `std::sys::cmath`, which come from `libm` on `unix` platforms. For example:

num-complex:
```
error[E0080]: constant evaluation error: can't call foreign function: hypot
   --> /home/jistone/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/f64.rs:533:18
    |
533 |         unsafe { cmath::hypot(self, other) }
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^ can't call foreign function: hypot
    |
```

num-integer:
```
   --> /home/jistone/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/f64.rs:513:18
    |
513 |         unsafe { cmath::cbrt(self) }
    |                  ^^^^^^^^^^^^^^^^^ can't call foreign function: cbrt
    |
```

**Comment by oli-obk** [comment]
These should be fairly easy to do by adding new match arms to https://github.com/rust-lang/miri/blob/95a842ba40f39edf119cd2623de80a90a2bcab39/src/fn_call.rs#L464 and following the implementation strategies of the intrinsics

**Comment by kennethbgoodin** [comment]
Hi, I'm interested in attempting this issue. Can you @oli-obk  expand on what implementing the match arms would entail? I'm guessing I'd just find what the two functions causing issues (cbrt, hypot) are meant to do and implement that functionality?

**Comment by oli-obk** [comment]
@kennethbgoodin 	after implementing `cbrt` and `hypot` you may hit more such errors when running Miri on `num`. But starting with those two is a good plan.

Yes, essentially reimplement that functionality. Since we don't care *too* much about floating point correctness, you can actually just read a float and run the appropriate function by making Miri depend on the `cmath` crate and calling the function from the `cmath` crate.

**Comment by cuviper** [comment]
FWIW, `cmath` is not a crate here, just a [`std` module](https://github.com/rust-lang/rust/blob/61d286e9d0530bea8fb1ae24be3989baa9ea08eb/src/libstd/sys/unix/cmath.rs) of extern declarations. Can Miri just call that natively itself? (Or perhaps call `f64::cbrt` to end up there.)

**Comment by kennethbgoodin** [comment]
It doesn't look like I can access `f64::cbrt` from within miri, failing to compile trying to use that.

**Comment by cuviper** [comment]
It would be a method of the `f64` primitive type, not the `std::f64` module.

**Comment by kennethbgoodin** [comment]
oh, doi. Thanks!

**Comment by kennethbgoodin** [comment]
What would be the best way to test? Should I build the compiler, add it to my toolchain. and then do `cargo miri test` on the num crates?

**Comment by RalfJung** [comment]
Yeah, I have a toolchain `stage2` pointing to `build/x86_64-unknown-linux-gnu/stage2`. Then I `./x.py build src/rustc` in the rustc dir, switch to the Miri dir, `rustup override set stage2` and finally `./miri install`.

**Comment by RalfJung** [comment]
I'd also recomment writing a testcase that does not depend on `num` but calls these methods directly. We'll want that for Miri's test suite anyway, and then you can just `./miri run <file>.rs`, which is easier than dealing with `cargo miri`. (Do `./miri run-debug` if you want compilation to be faster.)

**Comment by oli-obk** [comment]
maybe we can convice the `num` authors to run miri from rustup in their CI?

**Comment by cuviper** [comment]
I am a `num` author, so yes, this is something I would like in CI.

**Comment by RalfJung** [comment]
@kennethbgoodin has implemented some math functions. @cuviper are there any left that you are missing or can we close this?

**Comment by cuviper** [comment]
I think that's it for float functions, thanks!

(I had to exclude `hash` tests for `getrandom` calls, even after using a seed, but I'll try to investigate that later and file separately...)

**Comment by RalfJung** [comment]
@cuviper great. :)
Do you have a link for your Miri tests, or are they not on CI yet? Did anything come up?

I have to admit nums was not high up on my list of candidate crates as I did not expect much raw pointer stuff in there.^^

**Comment by cuviper** [comment]
I didn't add it to CI yet -- part "didn't get around to it" and part "`hash` doesn't work".

FWIW, here's the error I get with `num-complex` when I try to add a seed for hashing:

```
$ cargo +nightly-2019-07-04 miri test  -- -Zmiri-seed=42 -- -Zunstable-options --exclude-should-panic
   Compiling num-complex v0.2.3 (/home/jistone/rust/num/complex)

running 72 tests
error[E0080]: Miri evaluation error: a memory access tried to interpret some bytes as a pointer
  --> /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/mpsc/mpsc_queue.rs:98:25
   |
98 |                 assert!((*next).value.is_some());
   |                         ^^^^^^^^^^^^^ Miri evaluation error: a memory access tried to interpret some bytes as a pointer
   |
   = note: inside call to `std::sync::mpsc::mpsc_queue::Queue::<(test::test::TestDesc, test::test::TestResult, std::vec::Vec<u8>)>::pop` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/mpsc/shared.rs:271:25
   = note: inside call to `std::sync::mpsc::shared::Packet::<(test::test::TestDesc, test::test::TestResult, std::vec::Vec<u8>)>::try_recv` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/mpsc/shared.rs:221:15
   = note: inside call to `std::sync::mpsc::shared::Packet::<(test::test::TestDesc, test::test::TestResult, std::vec::Vec<u8>)>::recv` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sync/mpsc/mod.rs:1205:27
   = note: inside call to `std::sync::mpsc::Receiver::<(test::test::TestDesc, test::test::TestResult, std::vec::Vec<u8>)>::recv` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libtest/lib.rs:1167:42
   = note: inside call to `test::test::run_tests::<[closure@DefId(13:316 ~ test[1ece]::run_tests_console[0]::{{closure}}[2]) 0:&mut test::test::ConsoleTestState, 1:&mut std::boxed::Box<dyn test::test::formatters::OutputFormatter>]>` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libtest/lib.rs:971:5
   = note: inside call to `test::test::run_tests_console` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libtest/lib.rs:292:15
   = note: inside call to `test::test::test_main` at /home/jistone/.rustup/toolchains/nightly-2019-07-04-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libtest/lib.rs:326:5
```

But without the seed, it does start running some tests, so I'm not sure why this is broken...

> I have to admit nums was not high up on my list of candidate crates as I did not expect much raw pointer stuff in there.^^

Totally fair -- I don't think there's any pointer stuff in `num` crates at all! There are a few `unsafe` blocks, but it's pretty innocuous.

I'd love to give Rayon a spin, but AIUI you're a bit farther from supporting that.

**Comment by RalfJung** [comment]
> FWIW, here's the error I get with num-complex when I try to add a seed for hashing:

Ah, I've seen that before. Please wait until https://github.com/rust-lang/miri/pull/830 lands, Miri currently does not fully work. That PR should fix your problem, in fact it [adds it specifically as a test case](https://github.com/rust-lang/miri/pull/830/files#diff-c580e8c54d67c1a5f781990424adb178).
