### ISSUE TITLE
Support for accessing host environment variables

### ISSUE THREAD

**Issue by cuviper** [rust-lang/miri#670]
Miri currently starts with an empty environment, as noted on `Evaluator::env_vars`:

```rust
/// Miri does not expose env vars from the host to the emulated program.
```

It would be nice to have some control over this from the command line, as suggested on reddit
by [/u/0b_0101_001_1010](https://www.reddit.com/r/rust/comments/b5um0v/miri_available_as_rustup_component/ejkderz/).

Possible inspirations:
- `docker run -e` / `--env` / `--env-file` ([ref](https://docs.docker.com/engine/reference/commandline/run/#set-environment-variables--e---env---env-file))
- `sudo -E` / `--preserve-env` ([ref](https://www.sudo.ws/man/sudo.man.html))

**Comment by RalfJung** [comment]
Related to https://github.com/rust-lang/miri/issues/800.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/miri/pull/894, you can pass `-Zmiri-enable-communication` to let the interpreted program access host environment variables.

The name of that flag is still up for debate; let's discuss that in https://github.com/rust-lang/miri/issues/800 though.
