### ISSUE TITLE
tests fail without MIRI_SYSROOT

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/miri#684]
rustc master 3750348daff89741e3153e0e120aa70a45ff5b68
miri 28f2e5b17a9a4c33a810dffda8eaaf55a1b8b70d
`cargo +master test` fails with multiple errors like

````

thread '[ui] run-pass/vecs.rs' panicked at 'explicit panic', /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/compiletest_rs-0.3.21/src/runtest.rs:2632:9
test [ui] run-pass/vecs.rs ... FAILED
normalized stderr:
error[E0080]: constant evaluation error: no mir for `std::rt::lang_start_internal`
   |
   = note: inside call to `std::rt::lang_start::<()>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0080`.


expected stderr:


diff of stderr:

+error[E0080]: constant evaluation error: no mir for `std::rt::lang_start_internal`
+   |
+   = note: inside call to `std::rt::lang_start::<()>`
+
+error: aborting due to previous error
+
+For more information about this error, try `rustc --explain E0080`.
+
````

there are PRs in rustc repo that try to update miri but I don't see how they are supposed to pass ci. :/

**Comment by matthiaskrgr** [comment]
Ah, the pr does not include 28f2e5b17a9a4c33a810dffda8eaaf55a1b8b70d which probably might have broken it in the meantime.

**Comment by RalfJung** [comment]
No, this is just the lack of `MIRI_SYSROOT`. Tests run the `miri` engine directly, which has less convenience wrappers than `cargo miri` does.

Try
```
cargo miri setup
# should print where the libsts was built, on Linux ~/.cache/miri/HOST
MIRI_SYSROOT=~/.cache/miri/HOST cargo test
```

**Comment by RalfJung** [comment]
It would be nice to make `cargo test` just work out-of-the-box, but I am not a fan of making it integrate with `cargo miri`.

Locally, I just a shellscript like this to run tests:
```
#!/bin/bash
set -e
export RUSTFLAGS="-C link-args=-Wl,-rpath,$(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib"
cargo build --release

# Find sysroot
if rustc --print sysroot | fgrep -q build/x86_64-unknown-linux-gnu/stage; then
	# a local build, we have a proper libstd
	true
else
	# Get a sysroot
	cargo run --release --bin cargo-miri -- miri setup
	export MIRI_SYSROOT=~/.cache/miri/HOST
fi
# Run tests
exec cargo test --release "$@"
```
Maybe we should include something like this in the repo? It is Linux-86-specific, though.

**Comment by RalfJung** [comment]
Hm, something we really could do though is to mention setting MIRI_SYSROOT when MIR is missing.

**Comment by matthiaskrgr** [comment]
Hm, put `export MIRI_SYSROOT=~/.cache/miri/HOST` into `~/.zshrc` now, ran
````
rm -rf ~/.cache/miri
rustup component remove miri
rustup component add miri
RUSTC_WRAPPER="" ~/.cargo/bin/cargo miri setup
cargo miri test
````
but I got the failure
````
   Compiling libc v0.2.51
error[E0463]: can't find crate for `std`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `libc`.
````

It seems that `~/.cache/miri/` is not regenerated by `cargo miri setup` or there is some silent failure :/

**Comment by bjorn3** [comment]
Could you please set `RUST_LOG=warn`? There is a change it will show why it couldn't find `std`.

**Comment by RalfJung** [comment]
> It seems that ~/.cache/miri/ is not regenerated by cargo miri setup

Yeah, if you have the env var set then `cargo miri` thinks you already took care of the setup and doesn't do anything.

I suppose it'd make sense to make `cargo miri setup` do something even even if the env var is set.

**Comment by RalfJung** [comment]
That's not entirely easy though... xargo automatically adds a `/HOST` to the end of the path.

Really, the intended way to run this is
```
cargo run --release --bin cargo-miri -- miri setup
MIRI_SYSROOT=~/.cache/miri/HOST cargo test --release
```

I suggest to unset `MIRI_SYSROOT` in your `~/.zshrc`.

**Comment by matthiaskrgr** [comment]
Would something like this in `miri setup` help?

````diff
diff --git a/src/bin/cargo-miri.rs b/src/bin/cargo-miri.rs
index b6c448c..9b1c86d 100644
--- a/src/bin/cargo-miri.rs
+++ b/src/bin/cargo-miri.rs
@@ -171,8 +171,15 @@ fn ask(question: &str) {
 /// `MIRI_SYSROOT`. Skipped if `MIRI_SYSROOT` is already set, in which case we expect the user has
 /// done all this already.
 fn setup(ask_user: bool) {
-    if std::env::var("MIRI_SYSROOT").is_ok() {
-        return;
+    let env_var = std::env::var("MIRI_SYSROOT");
+    if env_var.is_ok() {
+        let miri_sysroot = env_var.unwrap();
+
+        if PathBuf::from(&miri_sysroot).exists() {
+            return;
+        } else {
+            println!("MIRI_SYSROOT points to {} which does not exist. Running setup...", &miri_sysroot);
+        }
     }

     // First, we need xargo.
````

**Comment by RalfJung** [comment]
@matthiaskrgr that would however ignore the value `MIRI_SYSROOT` is set to... like, you could do `MIRI_SYSROOT=~/my/other/dir` but the sysroot would still be built in `~/.cache/miri/HOST`.

**Comment by matthiaskrgr** [comment]
ah :/

**Comment by RalfJung** [comment]
Honoring `MIRI_SYSROOT` in `cargo miri setup` is far from trivial. In https://github.com/rust-lang/miri/pull/704 I instead make `cargo miri setup` warn when it does not do anything, which I hope is a start.  Also I hope that PR makes the docs more clear. Please let me know if it helps.

**Comment by RalfJung** [comment]
This just got much easier: you can now do `./miri test`.
