### ISSUE TITLE
ManuallyDrop isn't inheriting validity invariant

### ISSUE THREAD

**Issue by CAD97** [rust-lang/miri#733]
[proof ManuallyDrop inherits validity invariant](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=66c890383ec86d81d58322e5cae85fde)

[Creation of invalid value that miri allows](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2ba8733dd6036ca4384725fa4bc1469f)

**Comment by RalfJung** [comment]
So you are saying that Miri makes it not inherit the validity invariant, but it should?

Your example has nothing to do with `ManuallyDrop` though, [removing it does not change anything](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2c276228b8fe3592376e078e99d9161f).

The real "bug" here, if any, is that Miri currently does not enforce validity behind references. That would be extremely expensive, and we haven't decided what is the actual invariant. (In fact, one of the main reason why I am against recursive validity for references is that it is very costly to check. But that's just my opinion.) To be able to run with existing code in libstd, Miri checks essentially a "lower bound" of validity invariants (it allows integers to be uninitialized and does not recursive checking for references).

We should maybe document that better, but I see no bug here.

**Comment by CAD97** [comment]
Would it make sense to check recursively _just_ on `mem::transmute`? That'd help catch some simple problems without being much overhead in theory.

Otherwise, I agree; I forgot about that quality of Miri's checks. (Feel free to close this.)

**Comment by RalfJung** [comment]
> Would it make sense to check recursively just on mem::transmute? That'd help catch some simple problems without being much overhead in theory.

I think it'd be weird to make transmute special in any way -- that only makes things harder to explain.
