### ISSUE TITLE
Use directories crate to compute config/cache directories

### ISSUE THREAD

**Issue by soc** [rust-lang/miri#737]
Hey @oli-obk,

long time no see! :-)

As discussed, here is the reminder for using https://github.com/soc/directories-rs.

Cheers,

Simon

**Comment by oli-obk** [comment]
We're using 2.0 since a week ago or so: 724a9276b1f382a000ceed27ba52bcb04ed436f4 and have been using directories since https://github.com/rust-lang/miri/pull/543

So I guess we're all good here.

**Comment by soc** [comment]
@oli-obk Ok, great!

Though this doesn't look intended: https://github.com/rust-lang/miri/blob/master/src/bin/cargo-miri.rs#L250

I'll create a separate PR for it.

**Comment by soc** [comment]
See https://github.com/rust-lang/miri/pull/774.
