### ISSUE TITLE
ICE with validation disabled

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#754]
The following test passes normally but ICEs when validation gets disabled:
```rust
use std::cell::*;

fn main() {
    let cell: RefCell<[i32; 3]> = RefCell::new([1, 2, 3]);
    {
        let mut cellref: RefMut<'_, [i32; 3]> = cell.borrow_mut();
        cellref[0] = 4;
        let mut coerced: RefMut<'_, [i32]> = cellref;
        coerced[2] = 5;
    }
    {
        let comp: &mut [i32] = &mut [4, 2, 5];
        let cellref: Ref<'_, [i32; 3]> = cell.borrow();
        assert_eq!(&*cellref, comp);
        let coerced: Ref<'_, [i32]> = cellref;
        assert_eq!(&*coerced, comp);
    }
}
```

We don't test `-Zmiri-disable-validation` very much. But we also cannot test every flag...

**Comment by oli-obk** [comment]
We could setup a weekly cronjob for all flags On 31 May 2019 15:59, Ralf Jung <notifications@github.com> wrote:The following test passes normally but ICEs when validation gets disabled:
use std::cell::*;

fn main() {
    let cell: RefCell<[i32; 3]> = RefCell::new([1, 2, 3]);
    {
        let mut cellref: RefMut<'_, [i32; 3]> = cell.borrow_mut();
        cellref[0] = 4;
        let mut coerced: RefMut<'_, [i32]> = cellref;
        coerced[2] = 5;
    }
    {
        let comp: &mut [i32] = &mut [4, 2, 5];
        let cellref: Ref<'_, [i32; 3]> = cell.borrow();
        assert_eq!(&*cellref, comp);
        let coerced: Ref<'_, [i32]> = cellref;
        assert_eq!(&*coerced, comp);
    }
}

We don't test -Zmiri-disable-validation very much. But we also cannot test every flag...

**Comment by RalfJung** [comment]
I might have CI time budget to run at least some of the libstd test suites without validation on https://github.com/rust-lang/miri/issues/754.
