### ISSUE TITLE
Addresses are unintentionally aligned

### ISSUE THREAD

**Issue by christianpoveda** [rust-lang/miri#791]
During the [implementation](https://github.com/rust-lang/miri/pull/779) of the intptrcast model we discovered that memory addresses are aligned even when `miri::intptrcast::GlobalState::align_addr` is not used. 

Relevant code:

```rust
let x = (&5u8 as *const u8 as usize) * 2;
let y = (&6u16 as *const u16 as usize) * 2 / 2;
assert!(y % 2 == 1);
```

**Comment by RalfJung** [comment]
`%` should also cause `force_bits`, so you shouldn't need the `* 2` stuff.

But also it is impossible to entirely avoid this. So maybe we *should* keep the "no int base addresses" mode... or have a mode where the base address is *only* used for ptr comparison, not anything else? That seems neat actually.

**Comment by oli-obk** [comment]
wait how is `assert!(x % 2 == 1);` passing if its value was multiplied by `2` before?

**Comment by christianpoveda** [comment]
> wait how is `assert!(x % 2 == 1);` passing if its value was multiplied by `2` before?
Oh I should had left a comment/remove it. I left it when I copied and pasted just after finishing doodling with it.

**Comment by christianpoveda** [comment]
Adding @oli-obk's comment: We should stop wasting align bytes if we were already aligned
