### ISSUE TITLE
Miri should support concurrency

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#811]
Miri currently does not support spawning threads. Would be nice if it did! This seems like a big project though.

Notice that this is about *concurrency*, not *parallelism*. So the Miri interpreter can remain single-threaded for this, it "just" has to support multiple interpreted threads each with their own stack, and then have a scheduler to pick which one to choose next.

Beyond the implementation effort, other issues that arise is: can we sometimes or even reliably detect UB due to data races? And how does Stacked Borrows fare with concurrency?

**Comment by RalfJung** [comment]
@christianpoveda @vakaras you both privately told me you were working on this. I figured I'd probably tell you both before too much work gets duplicated. ;)

**Comment by Aaron1011** [comment]
Can this issue be closed, or is there still more work to do?

**Comment by RalfJung** [comment]
We have https://github.com/rust-lang/miri/labels/A-concurrency for the remaining open issues around concurrency, so this one can likely be closed -- thanks.
