### ISSUE TITLE
Missing cmath function: ldexp

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#821]
The libcore test suites calls `ldexp` via FFI. Unfortunately, libstd does not expose this function in any way. What would be the best way for us to implement this shim?

I found [this crate](https://crates.io/crates/float_extras). Alternatively we could try to just define the `extern` symbol ourselves and see if that works on all our host platforms?^^

**Comment by christianpoveda** [comment]
I am taking care of this one

**Comment by RalfJung** [comment]
Awesome!

Do you need mentoring? The file to edit is [this one](https://github.com/rust-lang/miri/blob/master/src/shims/foreign_items.rs).

**Comment by christianpoveda** [comment]
Thank you Ralf. It seems my gut feeling was right this time :D that's the file I modified. I just  added a new match under `// math functions` based on the [description] (http://www.cplusplus.com/reference/cmath/ldexp/) for `ldexp`:
```rust
        "ldexp" => {
            let x = f32::from_bits(this.read_scalar(args[0])?.to_u32()?);
            let exp = f32::from_bits(this.read_scalar(args[1])?.to_u32()?);
            this.write_scalar(Scalar::from_u32((x * 2.0f32.powf(exp)).to_bits()), dest)?;
        }
```
Should that be enough? Or should I use the crate you mentioned?

I also suppose we should remove https://github.com/rust-lang/rust/blob/0f11354a9c1bf0c5ac250c7fa2bafc289a662f42/src/libcore/tests/num/flt2dec/mod.rs#L1, is that right?

**Comment by RalfJung** [comment]
>  I just added a new match under // math functions based on the description for ldexp

Hm. I guess it is a reasonable start. Maybe add a FIXME saying that if we see imprecise results, we should try to use the C math lib `ldexp` instead.

Your code should also, like the other math functions, have a FIXME because it uses host floats.

And finally, find an appropriate test case to extend and call the function there.

> I also suppose we should remove

Once this lands in Miri and Miri has been updated in rustc, that can be removed, yes. One step after the other. :)

**Comment by christianpoveda** [comment]
> > I just added a new match under // math functions based on the description for ldexp
> 
> Hm. I guess it is a reasonable start. Maybe add a FIXME saying that if we see imprecise results, we should try to use the C math lib `ldexp` instead.

I can use the C math library directly if you think that's a more definitive solution.
> > I also suppose we should remove
> 
> Once this lands in Miri and Miri has been updated in rustc, that can be removed, yes. One step after the other. :)
Ok then I will do the miri PR first and wait :)

**Comment by RalfJung** [comment]
> I can use the C math library directly if you think that's a more definitive solution.

That is more in line with what we do with the other functions. I just don't know if it will work on all platforms.

**Comment by RalfJung** [comment]
Seems like `ldexp` is part of the normal C math lib so we can rely on it being present in Miri. So @christianpoveda if you want to switch it to import the function via `extern` instead, be my guest. :)

**Comment by RalfJung** [comment]
I am seeing test failures when turning on the libcore tests that use `ldexp`, so maybe we actually need the higher precision.

**Comment by christianpoveda** [comment]
I'll fix this ASAP :)
