### ISSUE TITLE
CI: Change back to stable toolchain

### ISSUE THREAD

**Issue by lzutao** [rust-lang/miri#828]
PR #827 changed default CI toolchain to beta to sort out cargo warning
for cargo feature `default-run`. We should revert it back when we done 
dealing with latest rustc.

**Comment by RalfJung** [comment]
> We should revert it back when we done dealing with latest rustc.

Correction: we can only revert it back once Rust 1.37 hits stable.

**Comment by RalfJung** [comment]
Actually, thinking about it, using the beta compiler seems like a nice idea. That's very close to the version rustc uses for bootstrapping, which is good -- that's the cargo version used in rustc CI.

**Comment by lzutao** [comment]
This could be closed now.
