### ISSUE TITLE
Pre-commit githook for enforcing coding style

### ISSUE THREAD

**Issue by oxr463** [rust-lang/miri#846]
Please keep `std` imports separately. This new import should be below the `rustc` imports, in fact.

_Originally posted by @RalfJung in https://github.com/rust-lang/miri/pull/834_

**Comment by RalfJung** [comment]
Seems like our import order is "std, other, rustc".

**Comment by RalfJung** [comment]
We now have `./miri fmt` to check the parts of the coding style that can be checked automatically. I don't think there is a good way to enforce import groups (which I prefer to have "global to local", as in separately grouped imports for std, other crates, rustc, local crate, in that order), so this is not really actionable.
