### ISSUE TITLE
Consider doing only a "check" build of libstd

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#864]
Somewhere (I forgot) I got the recommendation to try and make Miri only do a "check" build of libstd, instead of doing a full "build". That could help circumventing https://github.com/rust-lang/rust/issues/56443, which in turn would hopefully enable Miri to cross-interpret programs for any target.

I am unsure whether we should do this by extending `xargo` with support for "check" builds, or whether we should just copy the relevant parts of `xargo` and thus kill that dependency. I am not sure how much would have to be copied.

Cc @oli-obk

**Comment by oli-obk** [comment]
No clue what the right way would be here. I'm not even sure what "all the things that `xargo` does" are. Maybe we can just call `cargo check` on a checkout of `libstd`?

**Comment by RalfJung** [comment]
> I'm not even sure what "all the things that xargo does" are

Same. I think it boils down to preparing a `Cargo.toml` in a tmpdir and calling `cargo` with the right flags and env vars.

> Maybe we can just call cargo check on a checkout of libstd?

It should work with what is in the `rust-src` component, which is not a complete workspace.

**Comment by bjorn3** [comment]
And it then copies the right files into the correct sysroot layout and then builds libtest in a way I dont yet understand.

**Comment by RalfJung** [comment]
Ah good point, we need libtest as well.

**Comment by RalfJung** [comment]
@Aaron1011 is working on the basics for this in xargo, with the goal of resolving https://github.com/rust-lang/rust/issues/66247.

**Comment by RalfJung** [comment]
Closing in favor of https://github.com/rust-lang/miri/issues/1057.
