### ISSUE TITLE
Does Miri install into the correct rustup toolchain if it's not the default?

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/miri#892]
The current nightly doesn't have Miri, so I installed a nightly from a few days back to run nightly. I forgot to install `rust-src`, which Miri thoughtfully prompted me:

```
cargo +nightly-2019-08-01 miri --bin hash_file src/lib.rs
It seems you do not have the rust-src component installed. I will run `rustup component add rust-src`. Proceed? [Y/n]
```

Since it says what it would run, I assumed that it would not secretly run  `rustup component add rust-src --toolchain nightly-2019-08-01` and canceled it. Would it have installed the component in the right toolchain for me?

**Comment by RalfJung** [comment]
It definitely would have run what it says.

But in an ideal world, `rustup` would set the right env var inside the commands it executes so that nested `rustup` invocations also apply to that toolchain. I will do some digging.

**Comment by RalfJung** [comment]
I tested this, and it seems to work fine. Looks like `rustup` is doing the right thing.

**Comment by shepmaster** [comment]
That's a good rustup.
