### ISSUE TITLE
Report null fat raw pointers

### ISSUE THREAD

**Issue by nico-abram** [rust-lang/miri#918]
https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=37f152716318de72dd678cb4b8906257
As far as I know, this example is ub. I doubt 
detecting this is very important since either zeroed or transmute are probably the only way to do this, and it seems to be as insta ub as setting a reference to null (since the vtable ptr Is NonNull iirc) so i doubt any working code does it.

**Comment by RalfJung** [comment]
Thanks for the report!

This is deliberately not warned against until https://github.com/rust-lang/unsafe-code-guidelines/issues/166 is resolved. I think the likely conclusion of that discussion will be that wide raw pointers are like `(usize, usize)` can have no non-NULL requirements or so -- so I don't want to cause tons of errors in existing code.

Being able to zero-initialize raw pointers is actually a key motivation for *not* making this UB, IMO.

**Comment by RalfJung** [comment]
> since the vtable ptr Is NonNull iirc

I don't think it is, do you have a source for this?

**Comment by nico-abram** [comment]
The example playground i linked crashes on release. Theres also this (somewhat old) comment https://github.com/rust-lang/rfcs/issues/433#issuecomment-345497470

**Comment by RalfJung** [comment]
> The example playground i linked crashes on release.

Ouch. That seems like a bug to me, probably a bad `Debug` impl for raw pointers? Could you report this against rustc, Cc me?

Reopening until we figured out if this is a Miri or rustc bug. Definitely it shouldn't crash on rustc but work fine in Miri.

**Comment by nico-abram** [comment]
The same thing happens without the debug impl: https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=7c69493026add62256996d204e1278c0

Sure, will open issue in rust-lang/Rust.
