### ISSUE TITLE
Miri does not support file system access

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#923]
This issue tracks Miri not supporting all sorts of file system access APIs, from working directories to directory listing to actual read/writes. Such access should be possible when `-Zmiri-disable-isolation` is set. But it will be quite some work to implement dozens of shims for our 3 supported platforms.

If you are running into this, I suggest trying to carve out a part of your library does can run on "pure data", without accessing the file system. That part you should then be able to test in Miri.

**Comment by christianpoveda** [comment]
When https://github.com/rust-lang/miri/pull/962 lands, miri will have some basic file access capabilities (do `File::read` on linux).

**Comment by RalfJung** [comment]
That sounds like a good start, let's use more targeted issues when more APIs get requested.

Thanks a lot @christianpoveda for helming this. :)
