### ISSUE TITLE
`cargo miri test -- -Zmiri-disable-isolation` fails

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#933]
Ever since we got full env var forwarding (Cc @christianpoveda), running `cargo miri test -- -Zmiri-disable-isolation` fails with something like:

```
error[E0080]: Miri evaluation error: can't call foreign function: stat64
   --> /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/sys/unix/fs.rs:803:9
    |
803 |         stat64(p.as_ptr(), &mut stat)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri evaluation error: can't call foreign function: stat64
    |
    = note: inside call to `std::sys::unix::fs::stat` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/fs.rs:1516:5
    = note: inside call to `std::fs::metadata::<&std::path::PathBuf>` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libterm/terminfo/searcher.rs:50:12
    = note: inside call to `term::terminfo::searcher::get_dbpath_for_term` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libterm/terminfo/mod.rs:87:9
    = note: inside call to `term::terminfo::TermInfo::from_name` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libterm/terminfo/mod.rs:73:25
    = note: inside call to `term::terminfo::TermInfo::from_env` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libterm/terminfo/mod.rs:232:9
    = note: inside call to `term::terminfo::TerminfoTerminal::<std::io::Stdout>::new` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libterm/lib.rs:61:5
    = note: inside call to `term::stdout` at /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libtest/lib.rs:921:24
```

Looks like the presence of some env vars makes `terminfo` do something that we don't support yet.

Thanks @elichai for the original report!

**Comment by RalfJung** [comment]
Specifically, if `TERM` is set, it starts to traverse the file system for information about that kind of terminal. That code looks like it needs a significant fraction of https://github.com/rust-lang/miri/issues/923 to work.

As a hack, we could blacklist `TERM` from the env var import that we do when isolation is disabled...

**Comment by RalfJung** [comment]
> I could add an arguments with the blacklisted vars to EnvVars::init

I'd just hard-code the blacklist in `env.rs`.

> We could add a -Zmiri-blacklisted-env-vars=<names> flag so we don't have to do a commit for every single variable.

Well, we still want a default that "makes stuff work". So that doesn't really save us from maintaining a list.
But indeed having a user-controlled whitelist or blacklist for the "exposed environment" is a feature that got requested before.

**Comment by RalfJung** [comment]
`-Zmiri-env-exclude`? Not sure what it should use as separator though. Maybe just passing the flag multiple times.

**Comment by RalfJung** [comment]
@christianpoveda did the first step, thanks. :)

But I think we will want to add a test to `test-cargo-miri/run-test.py`:
```
def test_cargo_miri_test():
    test("cargo miri test",
        cargo_miri("test") + ["--", "-Zmiri-seed=feed"],
        "test.stdout.ref", "test.stderr.ref"
    )
    test("cargo miri test (with filter)",
        cargo_miri("test") + ["--", "--", "le1"],
        "test.stdout.ref2", "test.stderr.ref"
    )
    test("cargo miri test (without isolation)",
        cargo_miri("test") + ["--", "-Zmiri-disable-isolation", "--", "num_cpus"],
        "test.stdout.ref2", "test.stderr.ref"
    )
```
And this will still currently fail.
Basically, id the exclusion list is empty, `TERM` should be added to it.

**Comment by christianpoveda** [comment]
Hopefully https://github.com/rust-lang/miri/pull/937 should fix this :)

**Comment by RalfJung** [comment]
And with https://github.com/rust-lang/rust/pull/64001 that PR will be in a rustup component near you soon. :)

**Comment by RalfJung** [comment]
Looks like we forgot to close this.
