### ISSUE TITLE
don't report memory leaks for static data

### ISSUE THREAD

**Issue by matklad** [rust-lang/miri#940]
Currently, miri reports a memory leak for a `static` with heap allocated data. This is somewhat expected, as statics don't run destructors and indeed leak memory. However, this is not error, and ideally shouldn't be reported by miri as such.

See https://github.com/matklad/once_cell/pull/45/commits/327f4e24678b5930d129e79b61023a33499961be for an example.

**Comment by oli-obk** [comment]
Oh, heh. I never thought about heap pointers being leaked into statics. Also calls to `Box::leak` should probably not trigger the leak errors.

Maybe we should, before running the check, recursively mark anything reachable by a static as static itself.

And we should add a hook to `Box::leak` to make it mark its memory as static (we can use `rustc_diagnostic_item` to get the `DefId` of `Box::leak`

**Comment by RalfJung** [comment]
We probably also should make the leak check optional. A quick solution would be `-Zmiri-allow-leaks`; or we could make the leak error a "deny-by-default lint" and then use `-Aleak` or so.

> And we should add a hook to Box::leak to make it mark its memory as static

Why that? I think our leak check should trigger for `Box::leak` memory that is actually leaked.

**Comment by oli-obk** [comment]
> Why that? I think our leak check should trigger for Box::leak memory that is actually leaked.

I assumed that `Box::leak` could never be undone, but even stacked borrows is fine with it: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cae54e950dfd613b3c255263f352795f

I'm assuming `&'static mut T` and `*mut T` are equal in the eyes of stacked borrows

My statement came from assuming that people don't use `Box::leak` and expect to ever take back ownership of that. If you ever stored it in a global it seems impossible to ever safely undo the leak because any other code may have an immutable reference to the thing.

Nixing the entire leak check, just because some code found it ok to leak a single value out of lazy static like reasons, seems a bit extreme.

**Comment by RalfJung** [comment]
I just ran into another instance of this. The following program is considered leaking:
```
fn main() {
    let _val = 0;
    // Capture something to make closure a non-ZST
    std::panic::set_hook(Box::new(move |_info| { _val; }));
}
```

**Comment by RalfJung** [comment]
On Windows, we need this even to get an empty `fn main() {}` working with the leak checker enabled: there are some statics in libstd that are otherwise considered leaking.

**Comment by jonhoo** [comment]
Hmm, I still get [a reported leak](https://dev.azure.com/jonhoo/jonhoo/_build/results?buildId=1071&view=logs&j=51a00aa1-06f5-5fab-feeb-339bdc13aef3&t=79951b30-7f39-53ec-11c6-4eb34331b41a&l=121) through `crossbeam-epoch` when using statics. I don't know enough about the crossbeam internals to say whether it is legitimate or not, but I know they run a leak sanitizer which hasn't caught anything? I haven't tried running the [crossbeam tests themselves on miri](https://github.com/crossbeam-rs/crossbeam/issues/464#issuecomment-612010579) yet, but maybe that'd be worth doing?

**Comment by RalfJung** [comment]
@jonhoo could that be the same problem as https://github.com/rust-lang/miri/issues/1302, i.e., the pointer is cast to an integer before being stored and thus Miri cannot "see" it and cannot figure out that the allocation is reachable?

**Comment by jonhoo** [comment]
Ah, quite possible! I know `crossbeam-utils` does that in a few places from skimming the code. Sounds like maybe it'd be worthwhile to change those to use raw pointers instead. I don't know why they are using `usize` in the first place..

**Comment by RalfJung** [comment]
They might also be using `AtomicPtr` which under the hood does a cast to `usize` -- see https://github.com/rust-lang/rust/pull/70765.

**Comment by jonhoo** [comment]
I suspect the offender here might be
https://github.com/crossbeam-rs/crossbeam/blob/0599b8e88cccc88525cd430c806b057cc4be2829/crossbeam-epoch/src/atomic.rs#L128
I suspect it was stored as a `usize` due to using alignment bits to store a tag:
https://github.com/crossbeam-rs/crossbeam/blob/0599b8e88cccc88525cd430c806b057cc4be2829/crossbeam-epoch/src/atomic.rs#L120-L122
Is that also legal for `*` pointers?

`crossbeam-channel` and `crossbeam-deque` both use `AtomicPtr`, though none of that is used in the code that reports the leak I linked to.

**Comment by RalfJung** [comment]
> Is that also legal for * pointers?

It is *only* legal for raw pointers -- references must be aligned, so their last bits *must* be 0.

**Comment by jonhoo** [comment]
Sorry, yes, I meant the "also" in comparison to `usize`, not in comparison to references which I know must be aligned :)

**Comment by RalfJung** [comment]
Ah, yes raw pointers may be NULL, dangling and unaligned, that is fine.

**Comment by jonhoo** [comment]
Digging some more into this, it's actually tricky to make `crossbeam` use `AtomicPtr` since it relies on operations like `AtomicUsize::fetch_xor`, which do not exist for `AtomicPtr` :/

**Comment by RalfJung** [comment]
Yeah, that sounds tricky indeed. Hm.

**Comment by jonhoo** [comment]
Especially since it seems these were once supported, and then removed: https://github.com/rust-lang/rust/pull/10154

**Comment by RalfJung** [comment]
Honestly I am not sure any of this will suffice. XOR is fundamentally an integer operation that loses provenance, and while we could re-introduce awful hacks in Miri that enable provenance tracking over XOR, I do not think that is a good idea.

**Comment by RalfJung** [comment]
See `ptr_int_arithmetic` removed [in this commit](https://github.com/rust-lang/miri/commit/82da68c5caca6b534d77c01cbcf9d1ed0a6ef496) for the awful things we used to do.

**Comment by jonhoo** [comment]
crossbeam only specifically does xor of the alignment bits though, not of the "real" part of the pointer. Though I recognize that that might not really help :sweat_smile: It would be really sad if miri simply could not support checking `crossbeam-epoch`, or anything that depends on it.

**Comment by RalfJung** [comment]
> It would be really sad if miri simply could not support checking crossbeam-epoch, or anything that depends on it.

Yeah, I agree that would be sad.
However, re-adding that code might be even more sad.^^

**Comment by RalfJung** [comment]
To avoid continuing this discussion in a closed issue, I opened https://github.com/rust-lang/miri/issues/1318.
