### ISSUE TITLE
Support atomic_fence instrinstic

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/miri#972]
I'd love to try `miri` on [`evmap`](https://github.com/jonhoo/rust-evmap), but sadly I get the following error:

```
error[E0080]: Miri evaluation error: unimplemented intrinsic: atomic_fence
    --> /home/jon/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/sync/atomic.rs:2412:23
     |
2412 |             SeqCst => intrinsics::atomic_fence(),
     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^ Miri evaluation error: unimplemented intrinsic: atomic_fence
     |
note: inside call to `std::sync::atomic::fence` at src/write.rs:306:9
    --> src/write.rs:306:9
     |
306  |         atomic::fence(atomic::Ordering::SeqCst);
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Is this a known issue? Some cursory searching did not yield anything that seemed relevant.

**Comment by RalfJung** [comment]
This is just a missing shim. The shim should not do anything so this should be easy to fix.

**Comment by jonhoo** [comment]
I'm guess we also need to do something special to get the `miri` installed by `rustup` to pick this up?

**Comment by RalfJung** [comment]
Yeah, the miri submodule in rustc (at `src/tools/miri`) needs to be updated. Do you want to make a PR?

**Comment by jonhoo** [comment]
Sure, I'll do that, thanks!

**Comment by RalfJung** [comment]
Remember to run `./x.py` to make sure your `Cargo.lock` is up-to-date.

**Comment by jonhoo** [comment]
https://github.com/rust-lang/rust/pull/65278
