### ISSUE TITLE
Need to fix 'miri' bash script for Windows powershell users

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/miri#978]
![image](https://user-images.githubusercontent.com/10286488/66246031-8bdb2080-e6df-11e9-9dd0-84d1f3dcbc49.png)

While trying to work on Issue #707 locally, I got stuck with **'Testing the Miri driver'** step. I used Powershell to confront the above error. The current issue is that **$MIRI_SYSROOT** fed to the miri executable is stripped off of its backslashes, resulting in an error **"can't find crate for std"**

Maybe the 'miri' bash script should be fixed to escape backslashes for windows users?
Or it could also be an issue with **cargo**

**Comment by RalfJung** [comment]
Unfortunately I have no experience with bash scripts on Windows, nor with power shell. But I'd happily review a PR trying to fix this. :)

I am surprised the bash script does *anything* on Windows. I didn't even know PowerShell can run bash...

**Comment by RalfJung** [comment]
@JOE1994 so now that this works, do you think we could somehow use the `miri` script for our AppVeyor CI (configured at https://github.com/rust-lang/miri/blob/master/.appveyor.yml ) ?

**Comment by JOE1994** [comment]
@RalfJung I currently have zero knowledge of AppVeyor CI. I'll need some time to learn about it before I can say something about it 😢 
https://github.com/rust-lang/miri/blob/0d01c306fe032de4f2c4722ae235caa021ad37db/.appveyor.yml#L1-L6

Is the AppVeyor script solely for Windows ?? 
(I assume not, but don't see any `TARGET`s in the script other than Windows)

**Comment by RalfJung** [comment]
Yes AppVeyor is for Windows only. So really the main question is: how do I get bash onto Windows? Is that a normal thing for Rust devs to do on Windows?

**Comment by JOE1994** [comment]
In either Powershell or the Batch shell (2 shells that come with Windows), it is possible to run bash scripts or enter bash shell by using the `sh` command. 

![image](https://user-images.githubusercontent.com/10286488/66841847-4537c280-ef38-11e9-8535-a10e3ac859c6.png)

> how do I get bash onto Windows? Is that a normal thing for Rust devs to do on Windows?

Maybe I should ask this question to the Rust language forum or the Rust subreddit to find out..
Personally, I try to use bash on Windows when projects only provide bash scripts for building it.

https://users.rust-lang.org/t/is-it-normal-to-use-bash-on-windows-to-build-rust-projects/33628

**Comment by RalfJung** [comment]
Hm, but `sh` is not shipped with Windows, right? Don't we need to install it?

**Comment by JOE1994** [comment]
It is shipped with Windows by default.

**Comment by JOE1994** [comment]
Oh.. I just realized that it is not shipped with Windows by default.
One needs to have WSL(Windows Subsystem for Linux) installed and enabled in order to use bash shell in Windows.

**Comment by RalfJung** [comment]
That still seems to be rather experimental on the AppVeyor side: https://github.com/appveyor/ci/issues/1295.

So, probably best to stick to our current scheme for now. Thanks for testing the script on WSL though, good to know it works now!

**Comment by mati865** [comment]
Git for Windows ships with bash (`bash` and `sh` executables) so anybody who have git will have sh available.
