### ISSUE TITLE
Factor "X not available when isolation disabled" into common function

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/miri#986]
@christianpoveda added that same check half a dozen times or so. I think it would make sense to factor that into a small helper function that's called everywhere to avoid duplication.

The error message should also mention `-Zmiri-disable-isolation` so that people know how to make the error go away.

**Comment by christianpoveda** [comment]
Should this go in `src/helpers.rs` as an standalone function? this doesn't need anything from `ecx` to be inside the extension trait

**Comment by RalfJung** [comment]
Well it needs to access the "are we in isolation" flag, right?

**Comment by christianpoveda** [comment]
Oh yeah I was thinking in just factoring the error, not the isolation check. Time to work

**Comment by RalfJung** [comment]
Ah I see. I meant all the common code, including the check.
