### ISSUE TITLE
Implement `GetSystemTimeAsFileTime` shim for Windows

### ISSUE THREAD

**Issue by christianpoveda** [rust-lang/miri#997]
`SystemTime::now` is [implemented](https://github.com/rust-lang/rust/blob/e413dc36a83a5aad3ab6270373000693a917e92b/src/libstd/sys/windows/time.rs#L82) in windows using the `GetSystemTimeAsFileTime` foreign function, which currently doesn't have a shim in miri.

**Some instructions:**

Implementing the shim for `GetSystemTimeAsFileTime` its pretty similar to the linux (`clock_gettime`) and macOS (`gettimeofday`) shims (those can already be found in `src/shims/time.rs`). Its functionality is described in detail [here](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemtimeasfiletime).

The main difference is that this shim only has one argument: a pointer to a [`FILETIME` structure](https://docs.microsoft.com/en-us/windows/win32/api/minwinbase/ns-minwinbase-filetime), which has two integer fields `dwLowDateTime` and `dwHighDateTime`. These fields correspond to the first and last 32 bits of the 64 bits number counting the 100-nanosecond intervals (so its basically an `u64` represented as two `u32`).

It is also important to take into account that windows counts time since January 1, 1601 instead of January 1, 1970.

The testcase for this issue is:
```rust
use std::time::SystemTime;

fn main() {
   let _now = SystemTime::now();
}
```
Which can be found in `miri/tests/run-pass/time.rs`.

**Comment by christianpoveda** [comment]
@JOE1994 some tips:

The signature of this function is: 
```c++
DWORD GetEnvironmentVariableW(LPCWSTR lpName, LPWSTR lpBuffer, DWORD nSize);
```
A brief description of the arguments:
   - `lpName` is a pointer to `wchar_t` (those are wide chars, because windows use 2 bytes to encode characters instead of just 1). This points to the name of the variable
   - `lpBuffer` is a pointer to `char_t` (regular 1 byte chars). This is the buffer I mentioned before, where the value of the variable is supposed to be written.
   - `nSize` is a 32-bit unsigned integer. It represents the size of `lpBuffer`.

Instructions:
- The `args` variable contains a bunch of `OpTy` representing the arguments of the foreign function in the same order as stated above (`lpName` is `args[0]` and so on). Take each one of these `OpTy` and transform it to a more proper representation:
    - `lpName` and `lpBuffer` are both pointers so they need to be transformed from `OpTy`s to `Scalar`s to be able to read to what they are pointing to. This is done in the same way as with the only argument of `getenv` using `InterpCx::read_scalar` and then `ScalarMaybeUndef::not_undef`.
    - `nSize` can be transformed into an integer by turning it first into an scalar using `InterpCx::read_scalar`, this return an `ScalarMaybeUndef`, then you can use `ScalarMaybeUndef::.to_u32` to turn it into a proper integer.
-  Then after you have `lpName` as a `Pointer` you can read from it using `Memory::read_c_str`. I'm not sure if this will misbehave somehow because `lpName` is a pointer to wide chars and not just chars, this will return a `Vec<u8>` which is the actual name of the variable.
- With the name of the variable, you can recover the `Pointer` to the value of the variable that is stored in the `EnvVars` struct. Then you can read from this pointer in the same way as with `lpName` to recover the value of the variable, except for one detail: Right now all variables are stored as `NAME=VALUE` so you need to offset this pointer to not include the `NAME=` part. You can check `getenv` to see how to do it.

After this we "just" need to write the actual value to `lpBuffer`, we can get into that later. Until this point just be sure that the value of a variable actually has what it is supposed to.

**Comment by JOE1994** [comment]
I'm currently working on this issue, and will try to make a PR soon.
